<?php
// Specify our wmf custom groups.
// Note this is not going through the civicrm_managed system
// ie no mgd in the file prefix
// as we want to use the bulkSave action for efficiency.
// however we are keeping the declaration similar as it is conceptually similar.
// ** To sync the database with fields defined in this file use `drush update-custom-fields` **
use Civi\WMFHooks\CalculatedData;

$calculatedData = new CalculatedData();

return [
  'wmf_donor' => [
    'group' => [
      'extends' => 'Contact',
      'name' => 'wmf_donor',
      'table_name' => 'wmf_donor',
      'title' => ts('WMF Donor'),
      'is_active' => 1,
      'style' => 'inline',
    ],
    'fields' => $calculatedData->getWMFDonorFields(),
  ],
  'contribution_extra' => [
    'group' => [
      'extends' => 'Contribution',
      'name' => 'contribution_extra',
      'table_name' => 'wmf_contribution_extra',
      'title' => ts('Contribution Extra'),
      'is_active' => 1,
    ],
    'fields' => _wmf_civicrm_get_wmf_contribution_extra_fields(),
  ],
  'Communication' => [
    'group' => [
      'name' => 'Communication',
      'extends' => 'Contact',
      'style' => 'Inline',
      'collapse_display' => 0,
      'title' => 'Communication',
      'table_name' => 'civicrm_value_1_communication_4',
    ],
    'fields' => _wmf_civicrm_get_communication_fields(),
  ],
  'Gift_Data' => [
    'group' => [
      'name' => 'Gift_Data',
      'title' => ts('Gift Data'),
      'extends' => 'Contribution',
      'style' => 'inline',
      'is_active' => 1,
    ],
    'fields' => _wmf_civicrm_get_gift_data_fields(),
  ],
  'Prospect' => [
    'group' => [
      'name' => 'Prospect',
      'title' => 'Prospect',
      'extends' => 'Contact',
      'style' => 'tab',
      'is_active' => 1,
      'table_name' => 'civicrm_value_1_prospect_5',
    ],
    'fields' => _wmf_civicrm_get_prospect_fields(),
  ],
  'Anonymous' => [
    'group' => [
      'name' => 'Anonymous',
      'title' => 'Benefactor Page Listing',
      'extends' => 'Contact',
      'style' => 'Inline',
      'is_active' => 1,
    ],
    'fields' => _wmf_civicrm_get_benefactor_fields(),
  ],
  'Partner' => [
    'group' => [
      'name' => 'Partner',
      'title' => 'Partner',
      'extends' => 'Contact',
      'style' => 'Inline',
      'is_active' => 1,
      // Setting weight here is a bit hit & miss but one day the api
      // will do the right thing...
      'weight' => 1,
    ],
    'fields' => _wmf_civicrm_get_partner_fields(),
  ],
  'Stock_Information' => [
    'group' => [
      'name' => 'Stock_Information',
      'title' => 'Stock Information',
      'extends' => 'Contribution',
      'style' => 'Inline',
      'is_active' => 1,
      // Setting weight here is a bit hit & miss but one day the api
      // will do the right thing...
      'weight' => 1,
    ],
    'fields' => _wmf_civicrm_get_stock_fields(),
  ],
  'Organization_Contact' => [
    'group' => [
      'name' => 'Organization_Contact',
      'title' => 'Organization Contact',
      'extends' => 'Organization',
      'is_active' => 1,
    ],
    'fields' => _wmf_civicrm_get_organization_contact_fields(),
  ],
  'Relationship_Metadata' => [
    'group' => [
      'name' => 'Relationship_Metadata',
      'title' => 'Relationship Metadata',
      'extends' => 'Relationship',
      'style' => 'Inline',
      'is_active' => 1,
      'table_name' => 'civicrm_value_relationship_metadata',
    ],
    'fields' => _wmf_civicrm_get_relationship_metadata_fields(),
  ]
];


/**
 * Get fields for gift data custom group.
 *
 * @return array
 */
function _wmf_civicrm_get_gift_data_fields() {
  return [
    'Fund' => [
      'name' => 'Fund',
      'column_name' => 'fund',
      'label' => ts('Restrictions'),
      'data_type' => 'String',
      'html_type' => 'Select',
      'default_value' => 'Unrestricted - General',
      'is_active' => 1,
      'is_required' => 1,
      'is_searchable' => 1,
      'option_values' => [
        'Unrestricted - General' => 'Unrestricted - General',
        'Restricted - Foundation' => 'Restricted - Foundation',
        'Restricted - Program' => 'Restricted - Program',
        'Restricted - Fiscal Sponsorship' => 'Restricted - Fiscal Sponsorship',
      ],
    ],
    'Campaign' => [
      'name' => 'Campaign',
      'column_name' => 'campaign',
      'label' => ts('Gift Source'),
      'data_type' => 'String',
      'html_type' => 'Select',
      'default_value' => 'Community Gift',
      'is_active' => 1,
      'is_required' => 1,
      'is_searchable' => 1,
      'option_values' => [
        'Alternative Gifts' => 'Alternative Gifts',
        'Benefactor Gift' => 'Benefactor Gift',
        'BusDev' => 'BusDev',
        'Chapter Gift' => 'Chapter Gift',
        'Combined Federal Campaign' => 'Combined Federal Campaign',
        'Community Gift' => 'Community Gift',
        'Corporate Gift' => 'Corporate Gift',
        'Donor Advised Fund' => 'Donor Advised Fund',
        'Endowment Gift' => 'Endowment Gift',
        'Fund-to-Fund Transfer' => 'Fund-to-Fund Transfer',
        'Foundation Gift' => 'Foundation Gift',
        'Legacy Gift' => 'Legacy Gift',
        'Major Gift' => 'Major Gift',
        'Matching Gift' => 'Matching Gift',
        'Partnerships Gift' => 'Partnerships Gift',
        'Payroll Deduction' => 'Payroll Deduction',
        'Realized PG Gift ' => 'Realized PG Gift',
        'Realized PG Gift - Endowment Specified' => 'Realized PG Gift - Endowment Specified',
        'Retirement Fund' => 'Retirement Fund',
        'Retirement Fund - Endowment Specified' => 'Retirement Fund - Endowment Specified',
        'Retirement Fund - Annual Fund Specified' => 'Retirement Fund - Annual Fund Specified',
      ],
    ],
    'Appeal' => [
      'name' => 'Appeal',
      'column_name' => 'appeal',
      'label' => ts('Direct Mail Appeal'),
      'data_type' => 'String',
      'html_type' => 'Select',
      'default_value' => 'Spontaneous Donation',
      'is_active' => 1,
      'is_required' => 1,
      'is_searchable' => 1,
      'option_values' => [
        'White Mail' => 'White Mail',
        'Spontaneous Donation' => 'Spontaneous Donation',
        'Facebook' => 'Facebook',
        'Event' => 'Event',
        'Mobile Giving' => 'Mobile Giving',
        'Corp Matching Gift' => 'Corp Matching Gift',
      ],
    ],
  ];
}

/**
 * Get fields from prospect custom group.
 *
 * @return array
 */
function _wmf_civicrm_get_prospect_fields(): array {
  return [
    'Origin' => [
      'name' => 'Origin',
      'label' => 'Origin',
      'data_type' => 'String',
      'html_type' => 'Select',
      'help_post' => 'How do we know about the prospect?',
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
      //"option_group_id":"65",
    ],
    'Steward' => [
      'name' => 'Steward',
      'label' => 'Steward',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => 1,
      'default_value' => 5,
      'note_columns' => 60,
      'note_rows' => 4,
      //"option_group_id":"44",
    ],
    'Solicitor' => [
      'name' => 'Solicitor',
      'label' => 'Solicitor',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => 1,
      'note_columns' => 60,
      'note_rows' => 4,
      //"option_group_id":"45",
    ],
    'Biography' => [
      'name' => 'Biography',
      'label' => 'Biography',
      "data_type" => 'Memo',
      'html_type' => 'RichTextEditor',
      'is_searchable' => 1,
      'help_post' => 'Who they are, what they do.',
      'attributes' => 'rows=4, cols=60',
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
    ],
    'Estimated_Net_Worth' => [
      'name' => 'Estimated_Net_Worth',
      'label' => 'Estimated Net Worth',
      'column_name' => 'estimated_net_worth_144',
      'data_type' => 'String',
      'html_type' => 'Select',
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
      'option_values' => [
        1 => '$20 Million +',
        2 => '$10 Million - $19.99 Million',
        3 => '$5 Million - $9.99 Million',
        4 => '$2 Million - $4.99 Million',
        5 => '$1 Million - $1.99 Million',
        6 => '$500,000 - $999,999',
        7 => '>$5B',
        8 => '>$1B',
        9 => '>$10B',
        10 => '$100 Million +',
        'A' => 'Below $25,000',
        'B' => '$25,000 - $49,999',
        'C' => '$50,000 - $74,999',
        'D' => '$75,000 - $99,999',
        'E' => '$150,000 - $199,999',
        'F' => '$150,000 - $199,999',
        'G' => '$200,000 - $249,999',
        'H' => '$250,000 - $499,999',
        'I' => '$500,000 - $749,999',
        'J' => '$750,000 - $999,999',
        'K' => '$1,000,000 - $2,499,999',
        'L' => '$2,500,000 - $4,999,999',
        'M' => '$5,000,000 - $9,999,999',
        'N' => 'Above $10,000,000',
      ],
    ],
    'Philanthropic_History' => [
      'name' => 'Philanthropic_History',
      'label' => 'Philanthropic History',
      'data_type' => 'Memo',
      'html_type' => 'RichTextEditor',
      'is_searchable' => 1,
      'attributes' => 'rows=4, cols=60',
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
    ],
    'Philanthropic_Interests' => [
      'name' => 'Philanthropic_Interests',
      'label' => 'Philanthropic Interests',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => 1,
      'note_columns' => 60,
      'note_rows' => 4,
      'option_values' => [
        1 => 'Technology',
        2 => 'Education',
        3 => 'Political Campaign',
        4 => 'Cultural Arts',
        5 => 'Poverty',
        6 => 'Environment',
      ],
    ],
    'Subject_Area_Interest' => [
      'name' => 'Subject_Area_Interest',
      'label' => 'Subject Area Interest',
      'data_type' => 'String',
      'html_type' => 'Multi-Select',
      'is_searchable' => 1,
      'help_post' => 'Subject Area, Interests',
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
      //"option_group_id":"115",
    ],
    'Interests' => [
      'name' => 'Interests',
      'label' => 'Interests',
      'data_type' => 'Memo',
      'html_type' => 'RichTextEditor',
      'is_searchable' => 1,
      'help_post' => 'Pet projects, hobbies, other conversation worthy interests',
      'attributes' => 'rows=4, cols=60',
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
    ],
    'University_Affiliation' => [
      'name' => 'University_Affiliation',
      'label' => 'University Affiliation',
      'data_type' => 'String',
      'html_type' => 'Multi-Select',
      'is_searchable' => 1,
      'help_post' => 'University Attended, Taught At, Employed By',
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
      'option_values' => [
        'Stanford' => 'Stanford',
        'CAL - Berkeley' => 'CAL__Berkeley',
        'MIT' => 'MIT',
        'Carnegie Mellon' => 'Carnegie Mellon',
        'Harvard' => 'Harvard',
        1 => 'University of Chicago',
        2 => 'Yale',
      ],
    ],
    'Board_Affiliations' => [
      'name' => 'Board_Affiliations',
      'label' => 'Board Affiliations',
      'data_type' => 'Memo',
      'html_type' => 'RichTextEditor',
      'is_searchable' => 1,
      'note_columns' => 60,
      'note_rows' => 4,
    ],
    'Notes' => [
      'name' => 'Notes',
      'label' => 'Notes',
      'data_type' => 'Memo',
      'html_type' => 'RichTextEditor',
      'is_searchable' => 1,
      'note_columns' => 60,
      'note_rows' => 4,
    ],
    'Stage' => [
      'name' => 'Stage',
      'label' => 'MG Stage',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => 1,
      'note_columns' => 60,
      'note_rows' => 4,
      // "option_group_id":"32",
    ],
    'Endowment_Stage' => [
      'name' => 'Endowment_Stage',
      'label' => 'Endowment Stage',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => 1,
      'note_columns' => 60,
      'note_rows' => 4,
    ],
    'On Hold' => [
      'name' => 'On_Hold',
      'label' => 'On Hold',
      'data_type' => 'Boolean',
      'html_type' => 'Radio',
      'default_value' => 0,
      'is_searchable' => 1,
      'help_post' => 'Prospects archived from being stewarded',
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
    ],
    'Affinity' => [
      'name' => 'Affinity',
      'label' => 'Affinity',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => 1,
      'default_value' => 'Unknown',
      'note_columns' => 60,
      'note_rows' => 4,
      'option_values' => [
        1 => '(0) Neutral ',
        2 => '(+) Positive',
        3 => '(-) Negative',
        'On Hold' => 'On Hold',
        'Unknown' => 'Unknown',
      ],
    ],

    'Capacity' => [
      'name' => 'Capacity',
      'label' => 'Capacity',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => 1,
      'help_post' => 'Low = <$5k\r\nMedium = $5k to $99,999\r\nHigh = >$100k and over',
      'note_columns' => 60,
      'note_rows' => 4,
      'option_values' => [
        1 => '$0 - $999',
        2 => '$1,000 - $4,999',
        3 => '$5,000 - $9,999',
        4 => '$10,000 - $49,000',
        5 => '$50,000 - $99,999',
        6 => '$100,000 - $250,000',
        7 => '$250,000 to $500,000',
        8 => '$500,000 +',
        'Connector' => 'Connector ',
        'Low' => 'Low',
        'Medium' => 'Medium',
        'High  ' => 'High',
      ],
    ],
    'Reviewed' => [
      'name' => 'Reviewed',
      'label' => 'Reviewed',
      'data_type' => 'Date',
      'html_type' => 'Select Date',
      'is_searchable' => 1,
      'is_search_range' => 1,
      'start_date_years' => 10,
      'end_date_years' => 1,
      'date_format' => 'mm/dd/yy',
      'note_columns' => 60,
      'note_rows' => 4,
    ],
    'Income_Range' => [
      'name' => 'Income_Range',
      'label' => 'Income Range',
      'column_name' => 'income_range',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => 1,
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
      'option_values' => [
        'a' => 'Below $30,000',
        'b ' => '$30,000 - $39,999',
        'c' => '$40,000 - $49,999',
        'd' => '$50,000 - $59,999',
        'e' => '$60,000 - $74,999',
        'f' => '$75,000 - $99,999',
        'g' => '$100,000 - $124,999',
        'h' => '$125,000 - $149,999',
        'i' => '$150,000 - $199,999',
        'j' => '$200,000 - $249,999',
        'k' => '$250,000 - $299,999',
        'l' => '$300,000 - $499,999',
        'm' => 'Above $500,000',
      ],
    ],
    'Charitable_Contributions_Decile' => [
      'name' => 'Charitable_Contributions_Decile',
      'column_name' => 'charitable_contributions_decile',
      'label' => 'Charitable Contributions Decile',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => 1,
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
      'option_values' => [
        '1' => '1',
        '2' => '2',
        '3' => '3',
        '4' => '4',
        '5 ' => '5',
        '6' => '6',
        '7' => '7',
        '8' => '8',
        '9' => '9',
        '10' => '10',
        '11' => '11',
      ],
    ],
    'Disc_Income_Decile' => [
      'name' => 'Disc_Income_Decile',
      'label' => 'Disc Income Decile',
      'column_name' => 'disc_income_decile',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => 1,
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
      'option_values' => [
        '1' => '1',
        '2' => '2',
        '3' => '3',
        '4' => '4',
        '5' => '5',
        '6' => '6',
        '7' => '7',
        '8' => '8',
        '9' => '9',
        '10' => '10',
        '11' => '11',
      ],
    ],
    'Voter_Party' => [
      'name' => 'Voter_Party',
      'label' => 'Voter Party',
      'column_name' => 'voter_party',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => 1,
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
      'option_values' => [
        'democrat ' => 'Democrat',
        'republican' => 'Republican',
        'green' => 'Green',
        'independent' => 'Independent',
        'libertarian' => 'Libertarian',
        'no_party' => 'No Party',
        'other' => 'Other',
        'unaffiliated' => 'Unaffiliated',
        'unregistered' => 'Unregistered',
        'working_fam' => 'Working Fam',
        'conservative' => 'Conservative',
      ],
    ],
    'ask_amount' => [
      'name' => 'ask_amount',
      'label' => 'Ask Amount',
      'data_type' => 'Money',
      'html_type' => 'Text',
      'is_searchable' => 1,
      'is_search_range' => 1,
    ],
    'expected_amount' => [
      'name' => 'expected_amount',
      'label' => 'Expected Amount',
      'data_type' => 'Money',
      'html_type' => 'Text',
      'is_searchable' => 1,
      'is_search_range' => 1,
    ],
    'likelihood' => [
      'name' => 'likelihood',
      'label' => 'Likelihood (%)',
      'data_type' => 'Int',
      'html_type' => 'Text',
      'is_searchable' => 1,
      'is_search_range' => 1,
    ],
    'expected_close_date' => [
      'name' => 'expected_close_date',
      'label' => 'Expected Close Date',
      'data_type' => 'Date',
      'html_type' => 'Select Date',
      'is_searchable' => 1,
      'is_search_range' => 1,
    ],
    'close_date' => [
      'name' => 'close_date',
      'label' => 'Close Date',
      'data_type' => 'Date',
      'html_type' => 'Select Date',
      'is_searchable' => 1,
      'is_search_range' => 1,
    ],
    'next_step' => [
      'name' => 'next_step',
      'label' => 'Next Step',
      'data_type' => 'Memo',
      'html_type' => 'RichTextEditor',
      'note_columns' => 60,
      'note_rows' => 4,
    ],
    'PG_Stage' => [
      'name' => 'PG_Stage',
      'label' => 'PG Stage',
      'data_type' => 'String',
      'html_type' => 'Select',
      'note_columns' => 60,
      'note_rows' => 4,
      'is_searchable' => 1,
      'option_values' => [
        '1' => 'Cultivation',
        '2' => "Cont'd Cultivation",
      ],
    ],
    'Survey_Responses' => [
      'name' => 'Survey_Responses',
      'label' => 'Survey Responses',
      'data_type' => 'String',
      'html_type' => 'Text',
      'note_columns' => 60,
      'note_rows' => 4,
      'help_pre' => 'Data field to store any MGF survey related data for future reference.  Please date appropriately and do not overwrite previous responses.',
    ],
    'Family_Composition' => [
      'name' => 'Family_Composition',
      'label' => 'Family Composition',
      'data_type' => 'String',
      'html_type' => 'Select',
      'column_name' => 'family_composition_173',
      'is_searchable' => 1,
      'option_values' => [
        1  => 'Single',
        2 => 'Single with Children',
        3 => 'Couple',
        4 => 'Couple with children',
        5 => 'Multiple Generations',
        6 => 'Multiple Surnames (3+)',
        7 => 'Other',
      ],
    ],
    'Occupation' => [
      'name' => 'Occupation',
      'label' => 'Occupation',
      'column_name' => 'occupation_175',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => 1,
      'option_values' => [
        1 => 'Professional/Technical',
        2 => 'Upper Management/Executive',
        3 => 'Sales/Service',
        4  => 'Office/Clerical',
        5 => 'Skilled Trade',
        6 => 'Retired',
        7 => 'Administrative/Management',
        8 => 'Self Employed',
        9 => 'Military',
        10 => 'Farming/Agriculture',
        11 => 'Medical/Health Services',
        12 => 'Financial Services',
        13 => 'Teacher/Educator',
        14 => 'Legal Services',
        15 => 'Religious',
      ],
    ],
    'IRA and 401K Decile' => [
      'label' => 'IRA and 401K Decile',
      'name' => 'IRA_and_401K_Decile',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => 1,
      'option_values' => [
        '1' => '1',
        '2' => '2',
        '3' => '3',
        '4' => '4',
        '5' => '5',
        '6' => '6',
        '7' => '7',
        '8' => '8',
        '9' => '9',
        '10' => '10',
      ],
    ]
  ];
}

/**
 * Get fields for partner custom group.
 *
 * @return array
 */
function _wmf_civicrm_get_partner_fields() {
  return [
    'Partner' => [
      'name' => 'Partner',
      'label' => 'Partner',
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_searchable' => 1,
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
    ],
  ];
}

/**
 * Get fields for _wmf_contribution_extra.
 *
 * @return array
 */
function _wmf_civicrm_get_wmf_contribution_extra_fields() {
  return [
    'settlement_date' => [
      'name' => 'settlement_date',
      'column_name' => 'settlement_date',
      'label' => ts('Settlement Date'),
      'data_type' => 'Date',
      'html_type' => 'Select Date',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_search_range' => 1,
      'is_view' => 1,
      'date_format' => 'M d, yy',
      'time_format' => 2,
    ],
    'no_thank_you' => [
      'name' => 'no_thank_you',
      'column_name' => 'no_thank_you',
      'label' => ts('No Thank-you Reason'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 0,
    ],
    'total_usd' => [
      'name' => 'total_usd',
      'column_name' => 'total_usd',
      'label' => ts('Total in USD (approx)'),
      'data_type' => 'Money',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_search_range' => 1,
      'is_view' => 1,
    ],
    'gateway_account' => [
      'name' => 'gateway_account',
      'column_name' => 'gateway_account',
      'label' => ts('Gateway Account Name'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'gateway' => [
      'name' => 'gateway',
      'column_name' => 'gateway',
      'label' => ts('Gateway'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'gateway_txn_id' => [
      'name' => 'gateway_txn_id',
      'column_name' => 'gateway_txn_id',
      'label' => ts('Gateway Transaction ID'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'gateway_status_raw' => [
      'name' => 'gateway_status_raw',
      'column_name' => 'gateway_status_raw',
      'label' => ts('Gateway Status (raw)'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'gateway_date' => [
      'name' => 'gateway_date',
      'column_name' => 'gateway_date',
      'label' => ts('Gateway Last Update Timestamp'),
      'data_type' => 'Date',
      'html_type' => 'Select Date',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_search_range' => 1,
      'is_view' => 1,
      'date_format' => 'M d, yy',
      'time_format' => 2,
    ],
    'original_amount' => [
      'name' => 'original_amount',
      'column_name' => 'original_amount',
      'label' => ts('Original Amount Received (unconverted)'),
      'data_type' => 'Money',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_search_range' => 1,
      'is_view' => 1,
    ],
    'original_currency' => [
      'name' => 'original_currency',
      'column_name' => 'original_currency',
      'label' => ts('Original Currency Received'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'settlement_usd' => [
      'name' => 'settlement_usd',
      'column_name' => 'settlement_usd',
      'label' => ts('Settlement Total (USD)'),
      'data_type' => 'Money',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_search_range' => 1,
      'is_view' => 1,
    ],
    'settlement_currency' => [
      'name' => 'settlement_currency',
      'column_name' => 'settlement_currency',
      'label' => ts('Settlement Currency'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'deposit_date' => [
      'name' => 'deposit_date',
      'column_name' => 'deposit_date',
      'label' => ts('Deposit Received Date'),
      'data_type' => 'Date',
      'html_type' => 'Select Date',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_search_range' => 1,
      'is_view' => 1,
      'date_format' => 'M d, yy',
      'time_format' => 2,
    ],
    'deposit_usd' => [
      'name' => 'deposit_usd',
      'column_name' => 'deposit_usd',
      'label' => ts('Deposit Total (USD)'),
      'data_type' => 'Money',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_search_range' => 1,
      'is_view' => 1,
    ],
    'deposit_currency' => [
      'name' => 'deposit_currency',
      'column_name' => 'deposit_currency',
      'label' => ts('Deposit Currency'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'parent_contribution_id' => [
      'name' => 'parent_contribution_id',
      'column_name' => 'parent_contribution_id',
      'label' => ts('Parent Contribution ID'),
      'data_type' => 'Int',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'finance_only' => [
      'name' => 'finance_only',
      'column_name' => 'finance_only',
      'label' => ts('Finance Auditing Only'),
      'data_type' => 'Boolean',
      'html_type' => 'Radio',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'source_name' => [
      'name' => 'source_name',
      'column_name' => 'source_name',
      'label' => ts('Source Name'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'source_type' => [
      'name' => 'source_type',
      'column_name' => 'source_type',
      'label' => ts('Source Type'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'source_host' => [
      'name' => 'source_host',
      'column_name' => 'source_host',
      'label' => ts('Source Host'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'source_run_id' => [
      'name' => 'source_run_id',
      'column_name' => 'source_run_id',
      'label' => ts('Source Run ID'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'source_version' => [
      'name' => 'source_version',
      'column_name' => 'source_version',
      'label' => ts('Source Version'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'source_enqueued_time' => [
      'name' => 'source_enqueued_time',
      'column_name' => 'source_enqueued_time',
      'label' => ts('Enqueued At Timestamp'),
      'data_type' => 'Date',
      'html_type' => 'Select Date',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_search_range' => 1,
      'is_view' => 1,
      'date_format' => 'M d, yy',
      'time_format' => 2,
    ],
    'Postmark_Date' => [
      'name' => 'Postmark_Date',
      'column_name' => 'postmark_date',
      'label' => ts('Postmark Date'),
      'data_type' => 'Date',
      'html_type' => 'Select Date',
      'is_active' => 1,
      'is_searchable' => 0,
      'is_view' => 0,
    ],
  ];
}

/**
 * Get fields for communication custom group.
 *
 * @return array
 */
function _wmf_civicrm_get_communication_fields() {
  return [
    'opt_in' => [
      'name' => 'opt_in',
      'column_name' => 'opt_in',
      'label' => ts('Opt In'),
      'data_type' => 'Boolean',
      'html_type' => 'Radio',
      'is_active' => 1,
      'is_searchable' => 0,
    ],
    'do_not_solicit' => [
      'name' => 'do_not_solicit',
      'column_name' => 'do_not_solicit',
      'label' => ts('Do not solicit'),
      'data_type' => 'Boolean',
      'html_type' => 'Radio',
      'is_active' => 1,
      'is_required' => 0,
      'is_searchable' => 1,
      'default_value' => 0,
    ],
    'Employer_Name' => [
      'name' => 'Employer_Name',
      'label' => ts('Employer Name'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
    ],
    'optin_source' => [
      'name' => 'optin_source',
      'label' => ts('Opt-in Source'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
    ],
    'optin_medium' => [
      'name' => 'optin_medium',
      'label' => ts('Opt-in Medium'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
    ],
    'optin_campaign' => [
      'name' => 'optin_campaign',
      'label' => ts('Opt-in Campaign'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
    ],
  ];
}

/**
 * Get fields for stock info
 *
 * @return array[]
 */
function _wmf_civicrm_get_stock_fields() {
  return [
    'description_of_stock' => [
      'name' => 'Description_of_Stock',
      'column_name' => 'description_of_stock',
      'label' => ts('Description of Stock'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 0,
    ],
    'stock_value' => [
      'name' => 'Stock Value',
      'column_name' => 'stock_value',
      'label' => ts('Stock Value'),
      'data_type' => 'Money',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 0,
    ]
  ];
}

/**
 * Get fields for organization_contact info
 *
 * @return array[]
 */
function _wmf_civicrm_get_organization_contact_fields(): array {
  return [
    'Name' => [
      'name' => 'Name',
      'label' => ts('Org contact Name'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_required' => 0,
      'is_searchable' => 1,
      'is_view' => 0,
    ],
    'Title' => [
      'name' => 'Title',
      'label' => ts('Org contact Title'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_required' => 0,
      'is_searchable' => 0,
      'is_view' => 0,
    ],
    'Email' => [
      'name' => 'Email',
      'label' => ts('Org contact Email'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_required' => 0,
      'is_searchable' => 1,
      'is_view' => 0,
    ],
    'Phone' => [
      'name' => 'Phone',
      'label' => ts('Org contact Phone'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_required' => 0,
      'is_searchable' => 0,
      'is_view' => 0,
    ],
  ];
}

/**
 * Get fields from prospect custom group.
 *
 * @return array
 */
function _wmf_civicrm_get_benefactor_fields(): array {
  return [
    'Listed_as_Anonymous' => [
      'name' => 'Listed_as_Anonymous',
      'label' => 'Listed as',
      'data_type' => 'String',
      'html_type' => 'Select',
      'default_value' => 'not_replied',
      'is_searchable' => 1,
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
      'option_values' => [
        'anonymous' => 'Anonymous',
        'not_replied' => 'Not replied',
        'public' => 'Public',
      ],
    ],
    'Listed_on_Benefactor_Page_as' => [
      'name' => 'Listed_on_Benefactor_Page_as',
      'label' => 'Listed on Benefactor Page as',
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_searchable' => 1,
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
    ],
    'Benefactor_order_as' => [
      'name' => 'Benefactor_order_as',
      'label' => 'Benefactor order as',
      'data_type' =>  'String',
      'html_type' => 'Text',
      'is_searchable' => 1,
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
    ],
    'Endowment_Site_Listed_as' => [
      'name' => 'Endowment_Site_Listed_as',
      'label' => 'Endowment Site Listed as',
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_searchable' => 1,
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
    ],
    'WLS_Listed_as' => [
      'name' => 'WLS_Listed_as',
      'label' =>  'WLS Listed as',
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_searchable' => 1,
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
      'help_pre' => "How donor has chosen to be listed publicly anywhere there is a Legacy listing.",
      'help_post' => "How donor has chosen to be listed publicly anywhere there is a Legacy listing.",
    ],
    'Benefactor_Page_Last_Updated' => [
      'name' => 'Benefactor_Page_Last_Updated',
      'label' => 'Benefactor Page Last Updated',
      'data_type' => 'Date',
      'html_type' => 'Select Date',
      'text_length' => 255,
      'date_format' => 'mm/dd/yy',
    ],
    'WLS_Listing_Last_Updated' => [
      'name' => 'wls_listing_last_updated',
      'column_name' => 'wls_listing_last_updated',
      'label' => 'WLS Listing Last Updated',
      'data_type' => 'Date',
      'html_type' => 'Select Date',
      'text_length' => 255,
      'date_format' => 'mm/dd/yy',
    ],
    'Endowment_Listing_Last_Updated' => [
      'name' => 'endowment_listing_last_updated',
      'column_name' => 'endowment_listing_last_updated',
      'label' => 'Endowment Listing Last Updated',
      'data_type' => 'Date',
      'html_type' => 'Select Date',
      'text_length' => 255,
      'date_format' => 'mm/dd/yy',
    ],
  ];
}

function _wmf_civicrm_get_relationship_metadata_fields(): array {
  return [
    'Provided_By_Donor' => [
      'name' => 'provided_by_donor',
      'column_name' => 'provided_by_donor',
      'label' => 'Provided by donor',
      'help_pre' => '"Yes" means the donor provided this information to us (usually on the donation form)',
      'help_post' => 'For employer relationships, "Yes" will trigger automatic matching gifts emails',
      'data_type' => 'Boolean',
      'html_type' => 'Radio',
      'default_value' => 0,
    ],
  ];
}
