<?php
// Specify our wmf custom groups.
// Note this is not going through the civicrm_managed system
// ie no mgd in the file prefix
// for historical reasons - ie in the past the managed system did not
// use the move efficient BulkSave. In addition it used to be poor at
// matching existing fields. For new custom fields the CustomGroupMatchingGiftInformation.mgd.php
// is the model to follow.
// The fields in here could be converted but for now follow our old system - which
// keeps the declaration similar as it is conceptually similar.
// ******
// To sync the database with fields defined in this file use:
// drush @wmff cvapi WMFConfig.SyncCustomFields version=4
// ******
use Civi\WMFHook\CalculatedData;

$calculatedData = new CalculatedData();
// The option value for relationship is also ensured in the relationship
// block extension but we do it here as well in case that is not enabled
// in future for any reason.
CRM_Core_BAO_OptionValue::ensureOptionValueExists([
  'option_group_id' => 'cg_extend_objects',
  'name' => 'civicrm_relationship',
  'label' => ts('Relationship'),
  'value' => 'Relationship',
]);
// FIXME: Should we do these in an ActivityType.mgd.php?
$mg_year_end_appeal_activity_type = CRM_Core_BAO_OptionValue::ensureOptionValueExists([
  'option_group_id' => 'activity_type',
  'name' => 'Major Gifts Year End Appeal',
  'label' => ts('Major Gifts Year End Appeal'),
]);
$endowment_year_end_appeal_activity_type = CRM_Core_BAO_OptionValue::ensureOptionValueExists([
  'option_group_id' => 'activity_type',
  'name' => 'Endowment Year End Appeal',
  'label' => ts('Endowment Year End Appeal'),
]);
CRM_Core_BAO_OptionValue::ensureOptionValueExists([
  'option_group_id' => 'activity_type',
  'label' => 'Recurring Upgrade',
  'value' => 165,
  'name' => 'Recurring Upgrade',
  'grouping' => NULL,
  'filter' => 1,
  'is_default' => FALSE,
  'description' => 'Donor agreed to increase their recurring donation amount',
  'is_optgroup' => FALSE,
  'is_reserved' => TRUE,
  'is_active' => TRUE,
  'component_id' => NULL,
  'domain_id' => NULL,
  'visibility_id' => NULL,
  'icon' => 'fa-thumbs-o-up',
  'color' => NULL,
]);
CRM_Core_BAO_OptionValue::ensureOptionValueExists([
  'option_group_id' => 'activity_type',
  'label' => 'Recurring Downgrade',
  'value' => 168,
  'name' => 'Recurring Downgrade',
  'grouping' => NULL,
  'filter' => 1,
  'is_default' => FALSE,
  'description' => 'Donor reduced their recurring donation amount',
  'is_optgroup' => FALSE,
  'is_reserved' => TRUE,
  'is_active' => TRUE,
  'component_id' => NULL,
  'domain_id' => NULL,
  'visibility_id' => NULL,
  'icon' => 'fa-arrow-down',
  'color' => NULL,
]);
CRM_Core_BAO_OptionValue::ensureOptionValueExists([
  'option_group_id' => 'activity_type',
  'label' => 'Recurring Upgrade Decline',
  'value' => 166,
  'name' => 'Recurring Upgrade Decline',
  'grouping' => NULL,
  'filter' => 0,
  'is_default' => FALSE,
  'description' => 'Donor declined to increase their recurring donation amount',
  'is_optgroup' => FALSE,
  'is_reserved' => FALSE,
  'is_active' => TRUE,
  'component_id' => NULL,
  'domain_id' => NULL,
  'visibility_id' => NULL,
  'icon' => 'fa-thumbs-o-down',
  'color' => NULL,
]);

return [
  'wmf_donor' => [
    'group' => [
      'extends' => 'Contact',
      'name' => 'wmf_donor',
      'table_name' => 'wmf_donor',
      'title' => ts('WMF Donor'),
      'is_active' => 1,
      'style' => 'inline',
    ],
    'fields' => $calculatedData->getWMFDonorFields(),
  ],
  'External_Identifiers' => [
    'group' => [
      'extends' => 'Contact',
      'name' => 'External_Identifiers',
      'table_name' => 'wmf_external_contact_identifiers',
      'title' => ts('External Identifiers'),
      'is_active' => 1,
      'style' => 'inline',
    ],
    'fields' => _wmf_civicrm_get_external_identifiers_fields(),
  ],
  'contribution_extra' => [
    'group' => [
      'extends' => 'Contribution',
      'name' => 'contribution_extra',
      'table_name' => 'wmf_contribution_extra',
      'title' => ts('Contribution Extra'),
      'is_active' => 1,
    ],
    'fields' => _wmf_civicrm_get_wmf_contribution_extra_fields(),
  ],
  'Communication' => [
    'group' => [
      'name' => 'Communication',
      'extends' => 'Contact',
      'style' => 'Inline',
      'collapse_display' => 0,
      'title' => 'Communication',
      'table_name' => 'civicrm_value_1_communication_4',
    ],
    'fields' => _wmf_civicrm_get_communication_fields(),
  ],
  'Adjustment' => [
    'group' => [
      'name' => 'Adjustment',
      'table_name' => 'civicrm_value_adjustment_31',
      'title' => ts('Adjustment'),
      'extends' => 'Contribution',
      'style' => 'inline',
      'is_active' => 1,
    ],
    'fields' => _wmf_civicrm_get_gift_adjustment_fields(),
  ],
  'Gift_Data' => [
    'group' => [
      'name' => 'Gift_Data',
      'table_name' => 'civicrm_value_1_gift_data_7',
      'title' => ts('Gift Data'),
      'extends' => 'Contribution',
      'style' => 'inline',
      'is_active' => 1,
    ],
    'fields' => _wmf_civicrm_get_gift_data_fields(),
  ],
  'Prospect' => [
    'group' => [
      'name' => 'Prospect',
      'title' => 'Prospect',
      'extends' => 'Contact',
      'style' => 'tab',
      'is_active' => 1,
      'table_name' => 'civicrm_value_1_prospect_5',
    ],
    'fields' => _wmf_civicrm_get_prospect_fields() + _wmf_civicrm_get_data_axle_fields(),
  ],
  'Anonymous' => [
    'group' => [
      'name' => 'Anonymous',
      'title' => 'Benefactor Page Listing',
      'extends' => 'Contact',
      'style' => 'Inline',
      'is_active' => 1,
    ],
    'fields' => _wmf_civicrm_get_benefactor_fields(),
  ],
  'Partner' => [
    'group' => [
      'name' => 'Partner',
      'title' => 'Partner',
      'extends' => 'Contact',
      'style' => 'Inline',
      'is_active' => 1,
      // Setting weight here is a bit hit & miss but one day the api
      // will do the right thing...
      'weight' => 1,
    ],
    'fields' => _wmf_civicrm_get_partner_fields(),
  ],
  'Stock_Information' => [
    'group' => [
      'name' => 'Stock_Information',
      'title' => 'Stock Information',
      'extends' => 'Contribution',
      'style' => 'Inline',
      'is_active' => 1,
      // Setting weight here is a bit hit & miss but one day the api
      // will do the right thing...
      'weight' => 1,
    ],
    'fields' => _wmf_civicrm_get_stock_fields(),
  ],
  'Organization_Contact' => [
    'group' => [
      'name' => 'Organization_Contact',
      'title' => 'Organization Contact',
      'extends' => 'Organization',
      'is_active' => 1,
    ],
    'fields' => _wmf_civicrm_get_organization_contact_fields(),
  ],
  'Relationship_Metadata' => [
    'group' => [
      'name' => 'Relationship_Metadata',
      'title' => 'Relationship Metadata',
      'extends' => 'Relationship',
      'style' => 'Inline',
      'is_active' => 1,
      'table_name' => 'civicrm_value_relationship_metadata',
    ],
    'fields' => _wmf_civicrm_get_relationship_metadata_fields(),
  ],
  'Assistant' => [
    'group' => [
      'name' => 'Assistant',
      'title' => 'Assistant',
      'extends' => 'Individual',
      'style' => 'Inline',
      'is_active' => 1,
      'table_name' => 'civicrm_value_assistant_15',
    ],
    'fields' => _wmf_civicrm_get_assistant_fields(),
  ],
  'Major_Gifts_Year_End_Appeal' => [
    'group' => [
      'name' => 'Major_Gifts_Year_End_Appeal',
      'title' => 'Major Gifts Year End Appeal',
      'extends' => 'Activity',
      'extends_entity_column_value' => $mg_year_end_appeal_activity_type['value'],
      'style' => 'Inline',
      'weight' => 31,
      'is_active' => 1,
      'table_name' => 'civicrm_value_major_gifts_y_27',
    ],
    'fields' => _wmf_civicrm_get_mg_year_end_appeal_fields(),
  ],
  'Endowment_Year_End_Appeal' => [
    'group' => [
      'name' => 'Endowment_Year_End_Appeal',
      'title' => 'Endowment Year End Appeal',
      'extends' => 'Activity',
      'extends_entity_column_value' => $endowment_year_end_appeal_activity_type['value'],
      'style' => 'Inline',
      'weight' => 32,
      'is_active' => TRUE,
      'table_name' => 'civicrm_value_endowment_yea_28',
    ],
    'fields' => _wmf_civicrm_get_endowment_year_end_appeal_fields(),
  ],
  'activity_tracking' => [
    'group' => [
      'name' => 'activity_tracking',
      'title' => 'Activity Tracking',
      'extends' => 'Activity',
  // Values hardcoded above
      'extends_entity_column_value' => [165, 166, 168],
      'style' => 'Inline',
      'is_active' => TRUE,
      'table_name' => 'civicrm_activity_tracking',
      'weight' => 3,
    ],
    'fields' => _wmf_civicrm_get_activity_tracking_fields(),
  ],

  'address_data' => [
    'group' => [
      'name' => 'address_data',
      'title' => 'Address Data',
      'extends' => 'Address',
      'style' => 'Inline',
      'is_active' => TRUE,
      'table_name' => 'civicrm_value_address_data',
    ],
    'fields' => _wmf_civicrm_get_address_data_fields(),
  ],
  'donor_advised_fund' => [
    'group' => [
      'name' => 'donor_advised_fund',
      'title' => 'Donor Advised Fund',
      'extends' => 'Contribution',
      'style' => 'Inline',
      'is_active' => TRUE,
      'table_name' => 'civicrm_relationship_donor_advised',
    ],
    'fields' => _wmf_civicrm_get_donor_advised_fields(),
  ],
];

/**
 * Get fields for gift data custom group.
 *
 * @return array
 */
function _wmf_civicrm_get_gift_data_fields(): array {
  return [
    'Fund' => [
      'name' => 'Fund',
      'column_name' => 'fund',
      'label' => ts('Fund'),
      'data_type' => 'String',
      'html_type' => 'Select',
      'default_value' => 'Unrestricted - General',
      'is_active' => 1,
      'is_required' => 1,
      'is_searchable' => 1,
      'option_values' => [
        'Unrestricted - General' => 'Unrestricted - General',
        'Restricted - Foundation' => 'Restricted - Foundation',
        'Restricted - Program' => 'Restricted - Program',
        'Restricted - Fiscal Sponsorship' => 'Restricted - Fiscal Sponsorship',
        'Endowment Fund' => 'Endowment Fund',
        'Major Gifts - CC104' => 'Major Gifts - CC104',
      ],
    ],
    'Campaign' => [
      'name' => 'Campaign',
      'column_name' => 'campaign',
      'label' => ts('Gift Type'),
      'data_type' => 'String',
      'html_type' => 'Select',
      'default_value' => 'Individual Gift',
      'is_active' => 1,
      'is_required' => 1,
      'is_searchable' => 1,
      'option_values' => [
        'Individual Gift' => 'Individual Gift',
        'Online Gift' => 'Online Gift',
        'Alternative Gifts' => 'Alternative Gifts',
        'Benefactor Gift' => 'Benefactor Gift',
        'BusDev' => 'BusDev',
        'Chapter Gift' => 'Chapter Gift',
        'Combined Federal Campaign' => 'Combined Federal Campaign',
        'Community Gift' => 'Community Gift',
        'Corporate Gift' => 'Corporate Gift',
        'Donor Advised Fund' => 'Donor Advised Fund',
        'Endowment Gift' => 'Endowment Gift',
        'Employee Giving' => 'Employee Giving',
        'Fund-to-Fund Transfer' => 'Fund-to-Fund Transfer',
        'Foundation Gift' => 'Foundation Gift',
        'Legacy Gift' => 'Legacy Gift',
        'Major Gift' => 'Major Gift',
        'Matching Gift' => 'Matching Gift',
        'Partnerships Gift' => 'Partnerships Gift',
        'Payroll Deduction' => 'Payroll Deduction',
        'Realized PG Gift ' => 'Realized PG Gift',
        'Realized PG Gift - Endowment Specified' => 'Realized PG Gift - Endowment Specified',
        'Retirement Fund' => 'Retirement Fund',
        'Retirement Fund - Endowment Specified' => 'Retirement Fund - Endowment Specified',
        'Retirement Fund - Annual Fund Specified' => 'Retirement Fund - Annual Fund Specified',
        'Volunteer Match' => 'Volunteer Match',
      ],
    ],
    'Appeal' => [
      'name' => 'Appeal',
      'column_name' => 'appeal',
      'label' => ts('Direct Mail Appeal'),
      'data_type' => 'String',
      'html_type' => 'Select',
      'default_value' => 'Spontaneous Donation',
      'is_active' => 1,
      'is_required' => 1,
      'is_searchable' => 1,
      'option_values' => [
        'White Mail' => 'White Mail',
        'Spontaneous Donation' => 'Spontaneous Donation',
        'Facebook' => 'Facebook',
        'Event' => 'Event',
        'Mobile Giving' => 'Mobile Giving',
        'Corp Matching Gift' => 'Corp Matching Gift',
      ],
    ],
    'Donor Specified' => [
      'name' => 'Donor_Specified',
      'column_name' => 'donor_specified_340',
      'label' => ts('Donor Specified'),
      'data_type' => 'String',
      'html_type' => 'CheckBox',
      'default_value' => NULL,
      'is_required' => FALSE,
      'is_searchable' => TRUE,
      'is_search_range' => FALSE,
      'option_values' => [
        'Endowment Fund' => 'Endowment Fund',
        'Unrestricted - Fund' => 'Unrestricted - Fund',
      ],
    ],
    'Package' => [
      'name' => 'Package',
      'label' => 'Package',
      'column_name' => 'package',
      'html_type' => 'Autocomplete-Select',
      'is_searchable' => TRUE,
      'weight' => 326,
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
      'option_values' => [
        'OCT1B3ES' => 'OCT1B3ES',
        'OCT1B2ES' => 'OCT1B2ES',
      ],
    ],
    'Channel' => [
      'name' => 'Channel',
      'label' => 'Channel',
      'column_name' => 'channel',
      'html_type' => 'Select',
      'is_searchable' => TRUE,
      'weight' => 310,
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
      'option_values' => [
        'Banner' => 'Banner',
        'Email' => 'Email',
        'Direct_Mail' => 'Direct Mail',
        'Workplace_Giving' => 'Workplace Giving',
        'Direct_Solicitation' => 'Direct Solicitation',
        'Planned_Giving' => 'Planned Giving',
        'Events' => 'Events',
        'SMS' => 'SMS',
        'Recurring_Gift' => 'Recurring Gift',
        'Chapter_Gifts' => 'Chapter Gifts',
        'Other Offline' => 'Other Offline',
      ],
    ],
  ];
}

/**
 * Get fields for gift adjustment custom group.
 *
 * @return array
 */
function _wmf_civicrm_get_gift_adjustment_fields(): array {
  return [
    'Date' => [
      'name' => 'Date',
      'column_name' => 'date',
      'label' => ts('Date'),
      'data_type' => 'Date',
      'html_type' => 'Select Date',
      'default_value' => NULL,
      'is_active' => 1,
      'is_required' => 0,
      'is_searchable' => 1,
      'help_pre' => 'Enter the date of the adjustment',
      'date_format' => 'mm/dd/yy',
      'weight' => 4,
      'note_columns' => 60,
      'note_rows' => 4,
    ],
    'Reason' => [
      'name' => 'Reason',
      'column_name' => 'reason',
      'label' => ts('Reason'),
      'data_type' => 'String',
      'html_type' => 'Select',
      'default_value' => NULL,
      'is_active' => 1,
      'is_required' => 0,
      'is_searchable' => 1,
      'weight' => 8,
      'option_values' => [
        'Direct Mail Appeal' => 'Direct Mail Appeal',
        'Change Restriction to Unrestricted - General' => 'Change Restriction to Unrestricted - General',
        'Change Restriction to Endowment Fund' => 'Change Restriction to Endowment Fund',
      ],
    ],
    'Notes' => [
      'name' => 'Notes',
      'column_name' => 'notes',
      'label' => ts('Notes'),
      'data_type' => 'Memo',
      'html_type' => 'TextArea',
      'default_value' => NULL,
      'is_active' => 1,
      'is_required' => 0,
      'is_searchable' => 1,
      'weight' => 9,
      'help_pre' => 'Record information about the adjustment',
      'attributes' => 'rows=4, cols=60',
      'note_columns' => 60,
      'note_rows' => 4,
    ],
  ];
}

/**
 * Get fields from prospect custom group.
 *
 * @return array
 */
function _wmf_civicrm_get_prospect_fields(): array {
  return [
    'Origin' => [
      'name' => 'Origin',
      'label' => 'Origin',
      'data_type' => 'String',
      'html_type' => 'Select',
      'help_post' => 'How do we know about the prospect?',
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
      //"option_group_id":"65",
    ],
    'Steward' => [
      'name' => 'Steward',
      'label' => 'Steward',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => 1,
      'default_value' => 5,
      'note_columns' => 60,
      'note_rows' => 4,
      //"option_group_id":"44",
    ],
    'Solicitor' => [
      'name' => 'Solicitor',
      'label' => 'Solicitor',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => 1,
      'note_columns' => 60,
      'note_rows' => 4,
      //"option_group_id":"45",
    ],
    'Biography' => [
      'name' => 'Biography',
      'label' => 'Biography',
      "data_type" => 'Memo',
      'html_type' => 'RichTextEditor',
      'is_searchable' => 1,
      'help_post' => 'Who they are, what they do.',
      'attributes' => 'rows=4, cols=60',
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
    ],
    'Estimated_Net_Worth' => [
      'name' => 'Estimated_Net_Worth',
      'label' => '(TS) Estimated Net Worth',
      'column_name' => 'estimated_net_worth_144',
      'data_type' => 'String',
      'html_type' => 'Select',
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
      'option_values' => [
        1 => '$20 Million +',
        2 => '$10 Million - $19.99 Million',
        3 => '$5 Million - $9.99 Million',
        4 => '$2 Million - $4.99 Million',
        5 => '$1 Million - $1.99 Million',
        6 => '$500,000 - $999,999',
        7 => '>$5B',
        8 => '>$1B',
        9 => '>$10B',
        10 => '$100 Million +',
        'A' => 'Below $25,000',
        'B' => '$25,000 - $49,999',
        'C' => '$50,000 - $74,999',
        'D' => '$75,000 - $99,999',
        'E' => '$150,000 - $199,999',
        'F' => '$150,000 - $199,999',
        'G' => '$200,000 - $249,999',
        'H' => '$250,000 - $499,999',
        'I' => '$500,000 - $749,999',
        'J' => '$750,000 - $999,999',
        'K' => '$1,000,000 - $2,499,999',
        'L' => '$2,500,000 - $4,999,999',
        'M' => '$5,000,000 - $9,999,999',
        'N' => 'Above $10,000,000',
      ],
    ],
    'Philanthropic_History' => [
      'name' => 'Philanthropic_History',
      'label' => 'Philanthropic History',
      'data_type' => 'Memo',
      'html_type' => 'RichTextEditor',
      'is_searchable' => 1,
      'attributes' => 'rows=4, cols=60',
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
    ],
    'Philanthropic_Interests' => [
      'name' => 'Philanthropic_Interests',
      'label' => 'Philanthropic Interests',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => 1,
      'note_columns' => 60,
      'note_rows' => 4,
      'option_values' => [
        1 => 'Technology',
        2 => 'Education',
        3 => 'Political Campaign',
        4 => 'Cultural Arts',
        5 => 'Poverty',
        6 => 'Environment',
      ],
    ],
    'Subject_Area_Interest' => [
      'name' => 'Subject_Area_Interest',
      'label' => 'Subject Area Interest',
      'data_type' => 'String',
      'html_type' => 'Multi-Select',
      'is_searchable' => 1,
      'help_post' => 'Subject Area, Interests',
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
      //"option_group_id":"115",
    ],
    'Interests' => [
      'name' => 'Interests',
      'label' => 'Interests',
      'data_type' => 'Memo',
      'html_type' => 'RichTextEditor',
      'is_searchable' => 1,
      'help_post' => 'Pet projects, hobbies, other conversation worthy interests',
      'attributes' => 'rows=4, cols=60',
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
    ],
    'University_Affiliation' => [
      'name' => 'University_Affiliation',
      'label' => 'University Affiliation',
      'data_type' => 'String',
      'html_type' => 'Multi-Select',
      'is_searchable' => 1,
      'help_post' => 'University Attended, Taught At, Employed By',
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
      'option_values' => [
        'Stanford' => 'Stanford',
        'CAL - Berkeley' => 'CAL__Berkeley',
        'MIT' => 'MIT',
        'Carnegie Mellon' => 'Carnegie Mellon',
        'Harvard' => 'Harvard',
        1 => 'University of Chicago',
        2 => 'Yale',
      ],
    ],
    'Board_Affiliations' => [
      'name' => 'Board_Affiliations',
      'label' => 'Board Affiliations',
      'data_type' => 'Memo',
      'html_type' => 'RichTextEditor',
      'is_searchable' => 1,
      'note_columns' => 60,
      'note_rows' => 4,
    ],
    'Notes' => [
      'name' => 'Notes',
      'label' => 'Notes',
      'data_type' => 'Memo',
      'html_type' => 'RichTextEditor',
      'is_searchable' => 1,
      'note_columns' => 60,
      'note_rows' => 4,
    ],
    'Stage' => [
      'name' => 'Stage',
      'label' => 'MG Stage',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => 1,
      'note_columns' => 60,
      'note_rows' => 4,
      // "option_group_id":"32",
    ],
    'Endowment_Stage' => [
      'name' => 'Endowment_Stage',
      'label' => 'Endowment Stage',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => 1,
      'note_columns' => 60,
      'note_rows' => 4,
    ],
    'On Hold' => [
      'name' => 'On_Hold',
      'label' => 'On Hold',
      'data_type' => 'Boolean',
      'html_type' => 'Radio',
      'default_value' => 0,
      'is_searchable' => 1,
      'help_post' => 'Prospects archived from being stewarded',
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
    ],
    'Affinity' => [
      'name' => 'Affinity',
      'label' => 'Affinity',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => 1,
      'default_value' => 'Unknown',
      'note_columns' => 60,
      'note_rows' => 4,
      'option_values' => [
        1 => '(0) Neutral ',
        2 => '(+) Positive',
        3 => '(-) Negative',
        'On Hold' => 'On Hold',
        'Unknown' => 'Unknown',
      ],
    ],

    'Capacity' => [
      'name' => 'Capacity',
      'label' => '(TS) Capacity',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => 1,
      'help_post' => 'Low = <$5k\r\nMedium = $5k to $99,999\r\nHigh = >$100k and over',
      'note_columns' => 60,
      'note_rows' => 4,
      'option_values' => [
        1 => '$0 - $999',
        2 => '$1,000 - $4,999',
        3 => '$5,000 - $9,999',
        4 => '$10,000 - $49,000',
        5 => '$50,000 - $99,999',
        6 => '$100,000 - $250,000',
        7 => '$250,000 to $500,000',
        8 => '$500,000 +',
        'Connector' => 'Connector ',
        'Low' => 'Low',
        'Medium' => 'Medium',
        'High  ' => 'High',
      ],
    ],
    'Reviewed' => [
      'name' => 'Reviewed',
      'label' => 'Reviewed',
      'data_type' => 'Date',
      'html_type' => 'Select Date',
      'is_searchable' => 1,
      'is_search_range' => 1,
      'start_date_years' => 10,
      'end_date_years' => 1,
      'date_format' => 'mm/dd/yy',
      'note_columns' => 60,
      'note_rows' => 4,
    ],
    'Income_Range' => [
      'name' => 'Income_Range',
      'label' => '(TS) Income Range',
      'column_name' => 'income_range',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => 1,
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
      'option_values' => [
        'a' => 'Below $30,000',
        'b ' => '$30,000 - $39,999',
        'c' => '$40,000 - $49,999',
        'd' => '$50,000 - $59,999',
        'e' => '$60,000 - $74,999',
        'f' => '$75,000 - $99,999',
        'g' => '$100,000 - $124,999',
        'h' => '$125,000 - $149,999',
        'i' => '$150,000 - $199,999',
        'j' => '$200,000 - $249,999',
        'k' => '$250,000 - $299,999',
        'l' => '$300,000 - $499,999',
        'm' => 'Above $500,000',
      ],
    ],
    'Charitable_Contributions_Decile' => [
      'name' => 'Charitable_Contributions_Decile',
      'column_name' => 'charitable_contributions_decile',
      'label' => '(TS) Charitable Contributions Decile',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => 1,
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
      'option_values' => [
        '1' => '1',
        '2' => '2',
        '3' => '3',
        '4' => '4',
        '5 ' => '5',
        '6' => '6',
        '7' => '7',
        '8' => '8',
        '9' => '9',
        '10' => '10',
        '11' => '11',
      ],
    ],
    'Disc_Income_Decile' => [
      'name' => 'Disc_Income_Decile',
      'label' => '(TS) Disc Income Decile',
      'column_name' => 'disc_income_decile',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => 1,
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
      'option_values' => [
        '1' => '1',
        '2' => '2',
        '3' => '3',
        '4' => '4',
        '5' => '5',
        '6' => '6',
        '7' => '7',
        '8' => '8',
        '9' => '9',
        '10' => '10',
        '11' => '11',
      ],
    ],
    'ask_amount' => [
      'name' => 'ask_amount',
      'label' => 'Ask Amount',
      'data_type' => 'Money',
      'html_type' => 'Text',
      'is_searchable' => 1,
      'is_search_range' => 1,
    ],
    'expected_amount' => [
      'name' => 'expected_amount',
      'label' => 'Expected Amount',
      'data_type' => 'Money',
      'html_type' => 'Text',
      'is_searchable' => 1,
      'is_search_range' => 1,
    ],
    'likelihood' => [
      'name' => 'likelihood',
      'label' => 'Likelihood (%)',
      'data_type' => 'Int',
      'html_type' => 'Text',
      'is_searchable' => 1,
      'is_search_range' => 1,
    ],
    'expected_close_date' => [
      'name' => 'expected_close_date',
      'label' => 'Expected Close Date',
      'data_type' => 'Date',
      'html_type' => 'Select Date',
      'is_searchable' => 1,
      'is_search_range' => 1,
    ],
    'close_date' => [
      'name' => 'close_date',
      'label' => 'Close Date',
      'data_type' => 'Date',
      'html_type' => 'Select Date',
      'is_searchable' => 1,
      'is_search_range' => 1,
    ],
    'next_step' => [
      'name' => 'next_step',
      'label' => 'Next Step',
      'data_type' => 'Memo',
      'html_type' => 'RichTextEditor',
      'note_columns' => 60,
      'note_rows' => 4,
    ],
    'PG_Stage' => [
      'name' => 'PG_Stage',
      'label' => 'PG Stage',
      'data_type' => 'String',
      'html_type' => 'Select',
      'note_columns' => 60,
      'note_rows' => 4,
      'is_searchable' => 1,
      'option_values' => [
        '1' => 'Cultivation',
        '2' => "Cont'd Cultivation",
      ],
    ],
    'Survey_Responses' => [
      'name' => 'Survey_Responses',
      'label' => 'Survey Responses',
      'data_type' => 'String',
      'html_type' => 'Text',
      'note_columns' => 60,
      'note_rows' => 4,
      'help_pre' => 'Data field to store any MGF survey related data for future reference.  Please date appropriately and do not overwrite previous responses.',
    ],
    'Family_Composition' => [
      'name' => 'Family_Composition',
      'label' => '(TS) Family Composition',
      'data_type' => 'String',
      'html_type' => 'Select',
      'column_name' => 'family_composition_173',
      'is_searchable' => 1,
      'option_values' => [
        1 => 'Single',
        2 => 'Single with Children',
        3 => 'Couple',
        4 => 'Couple with children',
        5 => 'Multiple Generations',
        6 => 'Multiple Surnames (3+)',
        7 => 'Other',
      ],
    ],
    'Occupation' => [
      'name' => 'Occupation',
      'label' => '(TS) Occupation',
      'column_name' => 'occupation_175',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => 1,
      'option_values' => [
        1 => 'Professional/Technical',
        2 => 'Upper Management/Executive',
        3 => 'Sales/Service',
        4 => 'Office/Clerical',
        5 => 'Skilled Trade',
        6 => 'Retired',
        7 => 'Administrative/Management',
        8 => 'Self Employed',
        9 => 'Military',
        10 => 'Farming/Agriculture',
        11 => 'Medical/Health Services',
        12 => 'Financial Services',
        13 => 'Teacher/Educator',
        14 => 'Legal Services',
        15 => 'Religious',
      ],
    ],
    'IRA and 401K Decile' => [
      'label' => '(TS) IRA and 401K Decile',
      'name' => 'IRA_and_401K_Decile',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => 1,
      'option_values' => [
        '1' => '1',
        '2' => '2',
        '3' => '3',
        '4' => '4',
        '5' => '5',
        '6' => '6',
        '7' => '7',
        '8' => '8',
        '9' => '9',
        '10' => '10',
      ],
    ],
    'Prospect_Insight' => [
      'name' => 'Prospect_Insight',
      'label' => 'Prospect Insight',
      'data_type' => 'String',
      'html_type' => 'Select',
      'help_pre' => 'iWave determined prospect insight',
      'column_name' => 'prospect_insight_280',
      'option_values' => [
        '1' => 'Hidden Gem',
        '2' => 'Your Champion',
        'Distinguished Philanthropist' => 'Distinguished Philanthropist',
        'Not Now Prospect' => 'Not Now Prospect',
      ],
    ],
    'Estimated_Capacity' => [
      'name' => 'Estimated_Capacity',
      'label' => '(TS) Estimated Capacity',
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_searchable' => TRUE,
      'is_search_range' => FALSE,
      'weight' => 295,
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
      'column_name' => 'estimated_capacity_281',
    ],
    'Planned_Giving_Score' => [
      'name' => 'Planned_Giving_Score',
      'label' => 'Planned Giving Score',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => TRUE,
      'is_search_range' => FALSE,
      'weight' => 312,
      'is_active' => TRUE,
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
      'column_name' => 'planned_giving_score_282',
      'option_values' => [
        '1' => '1',
        '2' => '2',
        '3' => '3',
        '4' => '4',
      ],
    ],
    'Planned_Giving_Segment' => [
      'name' => 'Planned_Giving_Segment',
      'label' => 'Planned Giving Segment',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => TRUE,
      'is_search_range' => FALSE,
      'weight' => 313,
      'is_active' => TRUE,
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
      'column_name' => 'planned_giving_segment_283',
      'option_values' => [
        '1' => 'Potential Planned Giver',
        '2' => 'Ideal Planned Giver',
        'Not a Planned Giver' => 'Not a Planned Giver',
        'Strong Planned Giving Prospect' => 'Strong Planned Giving Prospect',
      ],
    ],
  ];
}

/**
 * Get fields from prospect custom group.
 *
 * @return array
 */
function _wmf_civicrm_get_data_axle_fields(): array {
  return [
    'data_axle_net_worth' => [
      'name' => 'data_axle_net_worth',
      'label' => '(DA) Net Worth',
      'column_name' => 'data_axle_net_worth',
      'help_pre' => 'CE Wealth-finder Code (Net Worth)',
      'data_type' => 'String',
      'html_type' => 'Select',
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
      'option_values' => [
        'A' => '99+ Percentile - Net Worth Range: $13,693,440+',
        'B' => '98-99 Percentile - Net Worth Range: $8,693,520 - $13,693,439',
        'C' => '97-98 Percentile - Net Worth Range: $3,693,600 - $8,693,519',
        'D' => '96-97 Percentile - Net Worth Range: $3,218,667 - $3,693,599',
        'E' => '95-96 Percentile - Net Worth Range: $2,743,733 - $3,218,666',
        'F' => '90-95 Percentile - Net Worth Range: $1,186,300 - $2,743,732',
        'G' => '85-90 Percentile - Net Worth Range: $739,000 - $1,186,299',
        'H' => '80-85 Percentile - Net Worth Range: $554,050 - $738,999',
        'I' => '75-80 Percentile - Net Worth Range: $363,100 - $554,049',
        'J' => '70-75 Percentile - Net Worth Range: $295,000 - $369,099',
        'K' => '65-70 Percentile - Net Worth Range: $220,990 - $294,999',
        'L' => '60-65 Percentile - Net Worth Range: $173,850 - $220,899',
        'M' => '55-60 Percentile - Net Worth Range: $126,800 - $173,849',
        'N' => '50-55 Percentile - Net Worth Range: $97,300 - $126,799',
        'O' => '45-50 Percentile - Net Worth Range: $71,501 - $97,299',
        'P' => '40-45 Percentile - Net Worth Range: $51,303 - $71,500',
        'Q' => '30-40 Percentile - Net Worth Range: $20,703 - $51,302',
        'R' => '20-30 Percentile - Net Worth Range: $5,700 - $20,702',
        'S' => '10-20 Percentile - Net Worth Range: $550 - $5,699',
        'T' => '0-10 Percentile - Net Worth Range: $0 - $549',
      ],
    ],
    'data_axle_expendable_income' => [
      'name' => 'data_axle_expendable_income',
      'label' => '(DA) Expendable Income',
      'column_name' => 'data_axle_expendable_income',
      'help_pre' => 'CE Expendable Income Rank Code (Model Predicts HH Monthly Expendable Income (Estimated Household Income/12) By Subtracting The Monthly Mortgage Payment Or Estimated Rent Value.)',
      'data_type' => 'String',
      'html_type' => 'Select',
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
      'option_values' => [
        'A' => 'Top 6.6%',
        'B' => 'Second Best 6.6%',
        'C' => 'Third Best 6.6%',
        'D' => 'Fourth Best 6.6%',
        'E' => 'Fifth Best 6.6%',
        'F' => 'Sixth Best 6.6%',
        'G' => 'Seventh Best 6.6%',
        'H' => 'Eighth Best 6.6%',
        'I' => 'Ninth Best 6.6%',
        'J' => 'Tenth Best 6.6%',
        'K' => 'Eleventh Best 6.6%',
        'L' => 'Twelfth Best 6.6%',
        'M' => 'Thirteenth Best 6.6%',
        'N' => 'Next to Bottom 6.6%',
        'O' => 'Bottom 6.6%',
      ],
    ],
    'data_axle_donation_interest' => [
      'name' => 'data_axle_donation_interest',
      'label' => '(DA) Donation Interest',
      'column_name' => 'data_axle_donation_interest',
      'help_pre' => 'CE Household Charitable Donor (Interest In Donating To Charities.)',
      'data_type' => 'Int',
      'html_type' => 'Text',
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
    ],
    'data_axle_marital_status' => [
      'name' => 'data_axle_marital_status',
      'label' => '(DA) Marital Status',
      'column_name' => 'data_axle_marital_status',
      'help_pre' => 'CE Selected Individual Marital Status',
      'data_type' => 'String',
      'html_type' => 'Select',
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
      'option_values' => [
        'S' => 'Single',
        'M' => 'Married',
        'U' => 'Unknown',
      ],
    ],
    'data_axle_is_grandparent' => [
      'name' => 'data_axle_is_grandparent',
      'label' => '(DA) Is GrandParent',
      'column_name' => 'data_axle_is_grandparent',
      'help_pre' => 'CE Selected Individual Grandparent Flag (Indicates Household Member Is Considered A Grandparent.)',
      'data_type' => 'Boolean',
      'html_type' => 'YesNo',
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
    ],
    'data_axle_is_parent' => [
      'name' => 'data_axle_is_parent',
      'label' => '(DA) Is Parent',
      'column_name' => 'data_axle_is_parent',
      'help_pre' => 'CE Selected Individual Parent Flag (Indicates Household Member Is Considered A Parent.)',
      'data_type' => 'Boolean',
      'html_type' => 'YesNo',
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
    ],
    'data_axle_number_children' => [
      'name' => 'data_axle_number_children',
      'label' => '(DA) Number of Children',
      'column_name' => 'data_axle_number_children',
      'help_pre' => 'CE Number of Children (Indicates The Number Of Household Members Determined To Be Children. Not The Same As Number Of Children Names.)',
      'data_type' => 'Int',
      'html_type' => 'Text',
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
    ],
    'data_axle_security_investor_likelihood' => [
      'name' => 'data_axle_security_investor_likelihood',
      'label' => '(DA) High Value Security Investor',
      'column_name' => 'data_axle_security_investor_likelihood',
      'help_pre' => 'CE High Value Security Investor Model (The High-Value Security Investors Model (SEC) Predicts The Likelihood That A Household Has Securities With A Total Value Of At Least $150,000)',
      'help_post' => 'Highest is 9, 0 is unknown',
      'data_type' => 'Int',
      'html_type' => 'Text',
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
    ],
    'data_axle_stock_investor_likelihood' => [
      'name' => 'data_axle_stock_investor_likelihood',
      'label' => '(DA) High Value Stock Investor',
      'column_name' => 'data_axle_stock_investor_likelihood',
      'help_pre' => 'CE High Value Stock Investor Model (The High-Value Stock Investors Model (STK) Predicts The Likelihood That A Household Has Stocks With A Total Value Of At Least $100,000)',
      'help_post' => 'Highest is 9, 0 is unknown',
      'data_type' => 'Int',
      'html_type' => 'Text',
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
    ],
    'data_axle_is_likely_homeowner' => [
      'name' => 'data_axle_homeowner_investor_likelihood',
      'label' => '(DA) Is probably home owner',
      'column_name' => 'data_axle_is_likely_homeowner',
      'help_pre' => 'CE Home Owner Flag (Derived From The Home Owner/Renter Model Values Of 7 Or Above Reported Or Most Likely Home Owners.)',
      'data_type' => 'Boolean',
      'html_type' => 'YesNo',
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
    ],

  ];
}

/**
 * Get fields for partner custom group.
 *
 * @return array
 */
function _wmf_civicrm_get_partner_fields(): array {
  return [
    'Partner' => [
      'name' => 'Partner',
      'label' => 'Partner',
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_searchable' => 1,
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
    ],
  ];
}

/**
 * These are donor identifiers in external systems, like the
 * Fundraise Up Supporter ID. In WmfContact\Save, the external_identifier
 * field will be mapped to a custom field whose name is the gateway name
 * with '_id' appended. So for example if we start storing the PayPal
 * PAYERID we would add a field here called paypal_id.
 *
 * @return array
 */
function _wmf_civicrm_get_external_identifiers_fields(): array {
  return [
    'fundraiseup_id' => [
      'name' => 'fundraiseup_id',
      'column_name' => 'fundraiseup_id',
      'label' => ts('Fundraise Up Supporter ID'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 0,
    ],
    'venmo_user_name' => [
      'name' => 'venmo_user_name',
      'column_name' => 'venmo_user_name',
      'label' => ts('Venmo user name'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 0,
    ],
    'gravy_id' => [
      'name' => 'gravy_id',
      'column_name' => 'gravy_id',
      'label' => ts('Gravy Buyer ID'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 0,
    ],
  ];
}

/**
 * Get fields for _wmf_contribution_extra.
 *
 * @return array
 */
function _wmf_civicrm_get_wmf_contribution_extra_fields(): array {
  return [
    'settlement_date' => [
      'name' => 'settlement_date',
      'column_name' => 'settlement_date',
      'label' => ts('Settlement Date'),
      'data_type' => 'Date',
      'html_type' => 'Select Date',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_search_range' => 1,
      'is_view' => 1,
      'date_format' => 'M d, yy',
      'time_format' => 2,
    ],
    'no_thank_you' => [
      'name' => 'no_thank_you',
      'column_name' => 'no_thank_you',
      'label' => ts('No Thank-you Reason'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 0,
    ],
    'total_usd' => [
      'name' => 'total_usd',
      'column_name' => 'total_usd',
      'label' => ts('Total in USD (approx)'),
      'data_type' => 'Money',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_search_range' => 1,
      'is_view' => 1,
    ],
    'gateway_account' => [
      'name' => 'gateway_account',
      'column_name' => 'gateway_account',
      'label' => ts('Gateway Account Name'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'gateway' => [
      'name' => 'gateway',
      'column_name' => 'gateway',
      'label' => ts('Gateway'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'backend_processor' => [
      'name' => 'backend_processor',
      'column_name' => 'backend_processor',
      'label' => ts('Backend Processor'),
      'description' => 'Underlying payment processor, when gateway is a payment orchestrator',
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'gateway_txn_id' => [
      'name' => 'gateway_txn_id',
      'column_name' => 'gateway_txn_id',
      'label' => ts('Gateway Transaction ID'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'backend_processor_txn_id' => [
      'name' => 'backend_processor_txn_id',
      'column_name' => 'backend_processor_txn_id',
      'label' => ts('Backend Processor Transaction ID'),
      'description' => 'ID of transaction at the underlying payment processor, when gateway is a payment orchestrator',
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'payment_orchestrator_reconciliation_id' => [
      'name' => 'payment_orchestrator_reconciliation_id',
      'column_name' => 'payment_orchestrator_reconciliation_id',
      'label' => ts('Payment Orchestrator Reconciliation ID'),
      'description' => 'cross-system reconciliation/shared ID of transaction at the payment orchestrator and underlying payment processor',
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'gateway_status_raw' => [
      'name' => 'gateway_status_raw',
      'column_name' => 'gateway_status_raw',
      'label' => ts('Gateway Status (raw)'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'gateway_date' => [
      'name' => 'gateway_date',
      'column_name' => 'gateway_date',
      'label' => ts('Gateway Last Update Timestamp'),
      'data_type' => 'Date',
      'html_type' => 'Select Date',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_search_range' => 1,
      'is_view' => 1,
      'date_format' => 'M d, yy',
      'time_format' => 2,
    ],
    'original_amount' => [
      'name' => 'original_amount',
      'column_name' => 'original_amount',
      'label' => ts('Original Amount Received (unconverted)'),
      'data_type' => 'Money',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_search_range' => 1,
      'is_view' => 1,
    ],
    'original_currency' => [
      'name' => 'original_currency',
      'column_name' => 'original_currency',
      'label' => ts('Original Currency Received'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'settlement_usd' => [
      'name' => 'settlement_usd',
      'column_name' => 'settlement_usd',
      'label' => ts('Settlement Total (USD)'),
      'data_type' => 'Money',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_search_range' => 1,
      'is_view' => 1,
    ],
    'settlement_currency' => [
      'name' => 'settlement_currency',
      'column_name' => 'settlement_currency',
      'label' => ts('Settlement Currency'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'settlement_batch_number' => [
      'name' => 'settlement_batch_number',
      'column_name' => 'settlement_batch_number',
      'label' => ts('Settlement Batch Number'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'deposit_date' => [
      'name' => 'deposit_date',
      'column_name' => 'deposit_date',
      'label' => ts('Deposit Received Date'),
      'data_type' => 'Date',
      'html_type' => 'Select Date',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_search_range' => 1,
      'is_view' => 1,
      'date_format' => 'M d, yy',
      'time_format' => 2,
    ],
    'deposit_usd' => [
      'name' => 'deposit_usd',
      'column_name' => 'deposit_usd',
      'label' => ts('Deposit Total (USD)'),
      'data_type' => 'Money',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_search_range' => 1,
      'is_view' => 1,
    ],
    'deposit_currency' => [
      'name' => 'deposit_currency',
      'column_name' => 'deposit_currency',
      'label' => ts('Deposit Currency'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'parent_contribution_id' => [
      'name' => 'parent_contribution_id',
      'column_name' => 'parent_contribution_id',
      'label' => ts('Parent Contribution ID'),
      'data_type' => 'Int',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'finance_only' => [
      'name' => 'finance_only',
      'column_name' => 'finance_only',
      'label' => ts('Finance Auditing Only'),
      'data_type' => 'Boolean',
      'html_type' => 'Radio',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'markup_fee' => [
      'name' => 'markup_fee',
      'column_name' => 'markup_fee',
      'label' => ts('Markup Fee (in settlement currency)'),
      'data_type' => 'Money',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_view' => 1,
    ],
    'interchange_fee' => [
      'name' => 'interchange_fee',
      'column_name' => 'interchange_fee',
      'label' => ts('Interchange Fee (in settlement currency)'),
      'data_type' => 'Money',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_view' => 1,
    ],
    'scheme_fee' => [
      'name' => 'scheme_fee',
      'column_name' => 'scheme_fee',
      'label' => ts('Scheme Fee (in settlement currency)'),
      'data_type' => 'Money',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_view' => 1,
    ],
    'source_name' => [
      'name' => 'source_name',
      'column_name' => 'source_name',
      'label' => ts('Source Name'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'source_type' => [
      'name' => 'source_type',
      'column_name' => 'source_type',
      'label' => ts('Source Type'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'source_host' => [
      'name' => 'source_host',
      'column_name' => 'source_host',
      'label' => ts('Source Host'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'source_run_id' => [
      'name' => 'source_run_id',
      'column_name' => 'source_run_id',
      'label' => ts('Source Run ID'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'source_version' => [
      'name' => 'source_version',
      'column_name' => 'source_version',
      'label' => ts('Source Version'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'source_enqueued_time' => [
      'name' => 'source_enqueued_time',
      'column_name' => 'source_enqueued_time',
      'label' => ts('Enqueued At Timestamp'),
      'data_type' => 'Date',
      'html_type' => 'Select Date',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_search_range' => 1,
      'is_view' => 1,
      'date_format' => 'M d, yy',
      'time_format' => 2,
    ],
    'Postmark_Date' => [
      'name' => 'Postmark_Date',
      'column_name' => 'postmark_date',
      'label' => ts('Postmark Date'),
      'data_type' => 'Date',
      'html_type' => 'Select Date',
      'is_active' => 1,
      'is_searchable' => 0,
      'is_view' => 0,
    ],
  ];
}

/**
 * Get fields for communication custom group.
 *
 * @return array
 */
function _wmf_civicrm_get_communication_fields(): array {
  return [
    'opt_in' => [
      'name' => 'opt_in',
      'column_name' => 'opt_in',
      'label' => ts('Opt In'),
      'data_type' => 'Boolean',
      'html_type' => 'Radio',
      'is_active' => 1,
      'is_searchable' => 0,
    ],
    'do_not_solicit' => [
      'name' => 'do_not_solicit',
      'column_name' => 'do_not_solicit',
      'label' => ts('Do not solicit'),
      'data_type' => 'Boolean',
      'html_type' => 'Radio',
      'is_active' => 1,
      'is_required' => 0,
      'is_searchable' => 1,
      'default_value' => 0,
    ],
    'no_direct_mail' => [
      'name' => 'no_direct_mail',
      'column_name' => 'no_direct_mail',
      'label' => ts('No Direct Mail'),
      'data_type' => 'Boolean',
      'html_type' => 'Radio',
      'is_active' => 1,
      'is_required' => 0,
      'is_searchable' => 1,
      'default_value' => 0,
    ],
    'no_paper_ty' => [
      'name' => 'no_paper_ty',
      'column_name' => 'no_paper_ty',
      'label' => ts('No Paper TY'),
      'help_pre' => 'No Paper Thank You',
      'data_type' => 'Boolean',
      'html_type' => 'Radio',
      'is_active' => 1,
      'is_required' => 0,
      'is_searchable' => 1,
      'default_value' => 0,
    ],
    'Employer_Name' => [
      'name' => 'Employer_Name',
      'label' => ts('Employer Name'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
    ],
    'optin_source' => [
      'name' => 'optin_source',
      'label' => ts('Opt-in Source'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
    ],
    'optin_medium' => [
      'name' => 'optin_medium',
      'label' => ts('Opt-in Medium'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
    ],
    'optin_campaign' => [
      'name' => 'optin_campaign',
      'label' => ts('Opt-in Campaign'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
    ],
    'first_name_phonetic' => [
      'name' => 'first_name_phonetic',
      'label' => 'First name phonetic',
      'data_type' => 'String',
      'html_type' => 'Text',
      'help_pre' => 'Phonetic version of first name field',
      'column_name' => 'first_name_phonetic',
      'is_active' => 1,
      'is_searchable' => 1,
    ],
    'last_name_phonetic' => [
      'name' => 'last_name_phonetic',
      'label' => 'Last name phonetic',
      'data_type' => 'String',
      'html_type' => 'Text',
      'help_pre' => 'Phonetic version of last name field',
      'column_name' => 'last_name_phonetic',
      'is_active' => 1,
      'is_searchable' => 1,
    ],
  ];
}

/**
 * Get fields for stock info
 *
 * @return array[]
 */
function _wmf_civicrm_get_stock_fields(): array {
  return [
    'stock_qty' => [
      'name' => 'Stock Quantity',
      'column_name' => 'stock_qty',
      'label' => ts('Stock Quantity'),
      'data_type' => 'Int',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 0,
    ],
    'stock_ticker' => [
      'name' => 'Stock Ticker',
      'column_name' => 'stock_ticker',
      'label' => ts('Stock Ticker'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 0,
    ],
    'description_of_stock' => [
      'name' => 'Description_of_Stock',
      'column_name' => 'description_of_stock',
      'label' => ts('Description of Stock'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 0,
    ],
    'stock_value' => [
      'name' => 'Stock Value',
      'column_name' => 'stock_value',
      'label' => ts('Stock Value'),
      'data_type' => 'Money',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 0,
    ],
  ];
}

/**
 * Get fields for organization_contact info
 *
 * @return array[]
 */
function _wmf_civicrm_get_organization_contact_fields(): array {
  return [
    'Name' => [
      'name' => 'Name',
      'label' => ts('Org contact Name'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_required' => 0,
      'is_searchable' => 1,
      'is_view' => 0,
    ],
    'Title' => [
      'name' => 'Title',
      'label' => ts('Org contact Title'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_required' => 0,
      'is_searchable' => 0,
      'is_view' => 0,
    ],
    'Email' => [
      'name' => 'Email',
      'label' => ts('Org contact Email'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_required' => 0,
      'is_searchable' => 1,
      'is_view' => 0,
    ],
    'Phone' => [
      'name' => 'Phone',
      'label' => ts('Org contact Phone'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_required' => 0,
      'is_searchable' => 0,
      'is_view' => 0,
    ],
  ];
}

/**
 * Get fields from prospect custom group.
 *
 * @return array
 */
function _wmf_civicrm_get_benefactor_fields(): array {
  return [
    'Listed_as_Anonymous' => [
      'name' => 'Listed_as_Anonymous',
      'label' => 'Listed as',
      'data_type' => 'String',
      'html_type' => 'Select',
      'default_value' => 'not_replied',
      'is_searchable' => 1,
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
      'option_values' => [
        'anonymous' => 'Anonymous',
        'not_replied' => 'Not replied',
        'public' => 'Public',
      ],
    ],
    'Listed_on_Benefactor_Page_as' => [
      'name' => 'Listed_on_Benefactor_Page_as',
      'label' => 'Listed on Benefactor Page as',
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_searchable' => 1,
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
    ],
    'Benefactor_order_as' => [
      'name' => 'Benefactor_order_as',
      'label' => 'Benefactor order as',
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_searchable' => 1,
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
    ],
    'Endowment_Site_Listed_as' => [
      'name' => 'Endowment_Site_Listed_as',
      'label' => 'Endowment Site Listed as',
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_searchable' => 1,
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
    ],
    'WLS_Listed_as' => [
      'name' => 'WLS_Listed_as',
      'label' => 'WLS Listed as',
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_searchable' => 1,
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
      'help_pre' => "How donor has chosen to be listed publicly anywhere there is a Legacy listing.",
      'help_post' => "How donor has chosen to be listed publicly anywhere there is a Legacy listing.",
    ],
    'Benefactor_Page_Last_Updated' => [
      'name' => 'Benefactor_Page_Last_Updated',
      'label' => 'Benefactor Page Last Updated',
      'data_type' => 'Date',
      'html_type' => 'Select Date',
      'text_length' => 255,
      'date_format' => 'mm/dd/yy',
    ],
    'WLS_Listing_Last_Updated' => [
      'name' => 'wls_listing_last_updated',
      'column_name' => 'wls_listing_last_updated',
      'label' => 'WLS Listing Last Updated',
      'data_type' => 'Date',
      'html_type' => 'Select Date',
      'text_length' => 255,
      'date_format' => 'mm/dd/yy',
    ],
    'Endowment_Listing_Last_Updated' => [
      'name' => 'endowment_listing_last_updated',
      'column_name' => 'endowment_listing_last_updated',
      'label' => 'Endowment Listing Last Updated',
      'data_type' => 'Date',
      'html_type' => 'Select Date',
      'text_length' => 255,
      'date_format' => 'mm/dd/yy',
    ],
    'Endowment_Level' => [
      'name' => 'Endowment_Level',
      'label' => 'Endowment Level',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => 1,
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
      'option_values' => [
        "1" => "$5m+",
        "2" => "$1m+",
        "3" => "$100k+",
        "4" => "$50k+",
        "5" => "$5k+",
        "6" => "$1k+",
      ],
    ],
    'Benefactor_Level' => [
      'name' => 'Benefactor_Level',
      'label' => 'Benefactor Level',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => 1,
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
      'option_values' => [
        "1" => "Major Benefactor ($50k+)",
        "2" => "Patron Donors ($15k-49,999)",
        "3" => "Leading Donors ($5k-$14,999)",
        "4" => "Sustaining Donor ($1k-$4,999)",
      ],
    ],
  ];
}

function _wmf_civicrm_get_relationship_metadata_fields(): array {
  return [
    'Provided_By_Donor' => [
      'name' => 'provided_by_donor',
      'column_name' => 'provided_by_donor',
      'label' => 'Provided by donor',
      'help_pre' => '"Yes" means the donor provided this information to us (usually on the donation form)',
      'help_post' => 'For employer relationships, "Yes" will trigger automatic matching gifts emails',
      'data_type' => 'Boolean',
      'html_type' => 'Radio',
      'default_value' => 0,
    ],
  ];
}

function _wmf_civicrm_get_assistant_fields(): array {
  return [
    // typo is on prod
    'Assitant_Name' => [
      'name' => 'Assitant_Name',
      'label' => 'Assistant Name & Title',
      'data_type' => 'String',
      'html_type' => 'Text',
      'column_name' => 'assitant_name_70',
      'is_searchable' => TRUE,
    ],
    'Assistant_Contact' => [
      'name' => 'Assistant_Contact',
      'label' => 'Assistant Contact',
      'data_type' => 'String',
      'html_type' => 'Text',
      'text_length' => 255,
      'column_name' => 'email_71',
      'is_searchable' => TRUE,
    ],

    'Assistant_Phone_Number' => [
      'name' => 'Assistant_Phone_Number',
      'label' => 'Assistant Phone Number',
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_searchable' => FALSE,
      'text_length' => 255,
      'column_name' => 'assistant_phone_number_135',
    ],
    'Assistant_Email' => [
      'name' => 'Assistant_Email',
      'label' => 'Assistant Email',
      'html_type' => 'Text',
      'data_type' => 'String',
      'is_searchable' => TRUE,
      'text_length' => 255,
      'column_name' => 'assistant_email_287',
    ],
  ];
}

function _wmf_civicrm_get_mg_year_end_appeal_fields(): array {
  return [
    'Appeal_Ask_Amount' => [
      'name' => 'Appeal_Ask_Amount',
      'label' => 'Appeal Ask Amount',
      'data_type' => 'Money',
      'html_type' => 'Text',
      'is_required' => TRUE,
      'is_searchable' => TRUE,
      'text_length' => 255,
      'is_search_range' => TRUE,
      'weight' => 2,
      'column_name' => 'appeal_ask_amount_303',
    ],
    'Solicitor' => [
      'name' => 'Solicitor',
      'label' => 'Relationship Manager',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => TRUE,
      'weight' => 6,
      'text_length' => 255,
      'column_name' => 'solicitor_305',
      'option_values' => _wmf_civicrm_get_solicitor_values(),
    ],
    'Appeal_Type' => [
      'name' => 'Appeal_Type',
      'label' => 'Appeal Type',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_required' => TRUE,
      'is_searchable' => TRUE,
      'weight' => 9,
      'text_length' => 255,
      'column_name' => 'appeal_type_309',
      'option_values' => [
        '1' => 'Letter',
        '2' => 'Email',
      ],
    ],
  ];
}

function _wmf_civicrm_get_endowment_year_end_appeal_fields(): array {
  return [
    [
      'name' => 'Appeal_Ask_Amount',
      'label' => 'Appeal Ask Amount',
      'data_type' => 'Money',
      'html_type' => 'Text',
      'is_required' => TRUE,
      'is_searchable' => TRUE,
      'is_search_range' => TRUE,
      'weight' => 3,
      'text_length' => 255,
      'column_name' => 'appeal_ask_amount_304',
    ],
    [
      'name' => 'Solicitor',
      'label' => 'Relationship Manager',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => TRUE,
      'weight' => 7,
      'text_length' => 255,
      'column_name' => 'solicitor_306',
      'option_values' => _wmf_civicrm_get_solicitor_values(),
    ],
    [
      'name' => 'Appeal_Type',
      'label' => 'Appeal Type',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_required' => TRUE,
      'is_searchable' => TRUE,
      'weight' => 10,
      'column_name' => 'appeal_type_307',
      'option_values' => [
        '1' => 'Letter',
        '2' => 'Email',
      ],
    ],
  ];
}

function _wmf_civicrm_get_solicitor_values(): array {
  return [
    '1' => 'Sue Gardner',
    '2' => 'Jimmy Wales',
    '3' => 'Lila Tretikov',
    '4' => 'Katherine Maher',
    '5' => 'Maryana Iskander',
    '6' => 'General',
  ];
}

function _wmf_civicrm_get_activity_tracking_fields(): array {
  return [
    'activity_campaign' => [
      'name' => 'activity_campaign',
      'label' => 'Campaign from URL',
      'html_type' => 'Text',
      'data_type' => 'String',
      'is_searchable' => TRUE,
      'text_length' => 255,
      'column_name' => 'campaign',
      'is_view' => 1,
    ],
    'activity_medium' => [
      'name' => 'activity_medium',
      'label' => 'Medium from URL',
      'html_type' => 'Text',
      'data_type' => 'String',
      'is_searchable' => TRUE,
      'text_length' => 255,
      'column_name' => 'medium',
      'is_view' => 1,
    ],
    'activity_source' => [
      'name' => 'activity_source',
      'label' => 'Source from URL',
      'html_type' => 'Text',
      'data_type' => 'String',
      'is_searchable' => TRUE,
      'text_length' => 255,
      'column_name' => 'source',
      'is_view' => 1,
    ],
  ];
}

function _wmf_civicrm_get_address_data_fields(): array {
  return [
    'address_source' => [
      'name' => 'address_source',
      'label' => 'Source',
      'html_type' => 'Select',
      'data_type' => 'String',
      'text_length' => 255,
      'column_name' => 'source',
      'option_values' => [
        'ncoa' => 'NCOA update',
        'staff' => 'Staff Supplied',
        'iwave' => 'iWave',
        'donor' => 'Donor Supplied',
        'paypal' => 'PayPal Account',
        'fundraiseup' => 'Fundraise Up',
      ],
    ],
    'address_update_date' => [
      'name' => 'address_update_date',
      'label' => 'Update date',
      'data_type' => 'Date',
      'html_type' => 'Select Date',
      'text_length' => 255,
      'date_format' => 'yy-mm-dd',
      'note_columns' => 60,
      'note_rows' => 4,
      'column_name' => 'update_date',
    ],
  ];
}

function _wmf_civicrm_get_donor_advised_fields(): array {
  return [
    'owns_donor_advised_for' => [
      'name' => 'owns_donor_advised_for',
      'label' => 'Owns the Donor Advised Fund',
      'html_type' => 'Autocomplete-Select',
      'data_type' => 'EntityReference',
      'text_length' => 255,
      'column_name' => 'owns_donor_advised_for',
      'filter' => 'contact_type=Organization',
      'fk_entity' => 'Contact',
    ],
  ];
}
