<?php

return [
  [
    'name' => 'SavedSearch_ContributionTracking',
    'entity' => 'SavedSearch',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'ContributionTracking',
        'label' => 'ContributionTracking',
        'form_values' => NULL,
        'mapping_id' => NULL,
        'search_custom_id' => NULL,
        'api_entity' => 'ContributionTracking',
        'api_params' => [
          'version' => 4,
          'select' => [
            'id',
            'tracking_date',
            'country',
            'os',
            'os_version',
            'language',
            'amount',
            'currency',
            'payment_method',
            'variant',
            'landing_page',
            'contribution_id',
            'referrer',
            'appeal',
            'gateway',
            'utm_key',
            'utm_campaign',
            'banner',
            'browser',
            'browser_version',
            'screen_width',
            'screen_height'
          ],
          'orderBy' => [],
          'where' => [],
          'groupBy' => [],
          'join' => [],
          'having' => [],
        ],
        'expires_date' => NULL,
        'description' => NULL,
      ],
    ],
  ],
  [
    'name' => 'SavedSearch_ContributionTracking_SearchDisplay_contribution_trackings_table',
    'entity' => 'SearchDisplay',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'contribution_trackings_table',
        'label' => 'contribution-trackings-table',
        'saved_search_id.name' => 'ContributionTracking',
        'type' => 'table',
        'settings' => [
          'description' => NULL,
          'sort' => [
            [
              'id',
              'DESC',
            ],
          ],
          'limit' => 50,
          'pager' => [],
          'placeholder' => 5,
          'columns' => [
            [
              'type' => 'field',
              'key' => 'id',
              'dataType' => 'Integer',
              'label' => 'Tracking ID',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'tracking_date',
              'dataType' => 'Timestamp',
              'label' => 'Tracking Date',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'country',
              'dataType' => 'String',
              'label' => 'Country',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'language',
              'dataType' => 'String',
              'label' => 'Language',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'amount',
              'dataType' => 'Money',
              'label' => 'Amount',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'currency',
              'dataType' => 'String',
              'label' => 'Currency',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'payment_method',
              'dataType' => 'String',
              'label' => 'Payment Method',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'contribution_id',
              'dataType' => 'Integer',
              'label' => 'Contribution ID',
              'sortable' => TRUE,
              'link' => [
                'path' => '',
                'entity' => 'Contribution',
                'action' => 'view',
                'join' => 'contribution_id',
                'target' => 'crm-popup',
              ],
              'title' => 'View Contribution ID',
            ],
            [
              'type' => 'field',
              'key' => 'referrer',
              'dataType' => 'String',
              'label' => 'Referrer',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'gateway',
              'dataType' => 'String',
              'label' => 'Gateway',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'utm_key',
              'dataType' => 'String',
              'label' => 'Utm Key',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'utm_campaign',
              'dataType' => 'String',
              'label' => 'Utm Campaign',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'banner',
              'dataType' => 'String',
              'label' => 'Banner',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'landing_page',
              'dataType' => 'String',
              'label' => 'Landing Page',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'appeal',
              'dataType' => 'String',
              'label' => 'Appeal',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'os',
              'dataType' => 'String',
              'label' => 'OS',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'os_version',
              'dataType' => 'String',
              'label' => 'OS Version',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'browser',
              'dataType' => 'String',
              'label' => 'Browser',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'browser_version',
              'dataType' => 'String',
              'label' => 'Browser Version',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'screen_width',
              'dataType' => 'Integer',
              'label' => 'Screen Width',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'screen_height',
              'dataType' => 'Integer',
              'label' => 'Screen Height',
              'sortable' => TRUE,
            ],
          ],
          'actions' => FALSE,
          'classes' => [
            'table',
            'table-striped',
          ],
          'headerCount' => FALSE,
        ],
        'acl_bypass' => FALSE,
      ],
    ],
  ],
];
