<?php
// See comments in CustomGroups.php - this is now the preferred way to add custom fields.
// Note the apiv4 now allows these to be exported from the apiv4 explorer, using
// the 'CustomGroup.export' action (be sure to choose php next to the copy button
// to avoid reformatting json into php).
return [
  [
    'name' => 'CustomGroup_Matching_Gift_Information',
    'entity' => 'CustomGroup',
    'cleanup' => 'never',
    'update' => 'never',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Matching_Gift_Information',
        'title' => 'Matching Gift Information',
        'extends' => 'Contribution',
        'extends_entity_column_id' => NULL,
        'extends_entity_column_value' => NULL,
        'style' => 'Inline',
        'collapse_display' => FALSE,
        'help_pre' => '',
        'help_post' => '',
        'weight' => 33,
        'is_active' => TRUE,
        'is_multiple' => FALSE,
        'min_multiple' => NULL,
        'max_multiple' => NULL,
        'collapse_adv_display' => TRUE,
        'created_date' => '2022-11-22 16:42:05',
        'is_reserved' => FALSE,
        'is_public' => TRUE,
        'icon' => '',
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Matching_Gift_Information_CustomField_Date_Verified',
    'entity' => 'CustomField',
    'cleanup' => 'never',
    'update' => 'never',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Matching_Gift_Information',
        'name' => 'Date_Verified',
        'label' => 'Date Verified',
        'data_type' => 'Date',
        'html_type' => 'Select Date',
        'default_value' => NULL,
        'is_required' => FALSE,
        'is_searchable' => TRUE,
        'is_search_range' => FALSE,
        'help_pre' => NULL,
        'help_post' => NULL,
        'mask' => NULL,
        'attributes' => NULL,
        'javascript' => NULL,
        'is_active' => TRUE,
        'is_view' => FALSE,
        'options_per_line' => NULL,
        'text_length' => 255,
        'start_date_years' => NULL,
        'end_date_years' => NULL,
        'date_format' => 'mm/dd/yy',
        'time_format' => NULL,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'date_verified_312',
        'option_group_id' => NULL,
        'serialize' => 0,
        'filter' => NULL,
        'in_selector' => FALSE,
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Matching_Gift_Information_CustomField_Match_Amount',
    'entity' => 'CustomField',
    'cleanup' => 'never',
    'update' => 'never',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Matching_Gift_Information',
        'name' => 'Match_Amount',
        'label' => 'Match Amount',
        'data_type' => 'Money',
        'html_type' => 'Text',
        'default_value' => NULL,
        'is_required' => FALSE,
        'is_searchable' => TRUE,
        'is_search_range' => FALSE,
        'help_pre' => NULL,
        'help_post' => NULL,
        'mask' => NULL,
        'attributes' => NULL,
        'javascript' => NULL,
        'is_active' => TRUE,
        'is_view' => FALSE,
        'options_per_line' => NULL,
        'text_length' => 255,
        'start_date_years' => NULL,
        'end_date_years' => NULL,
        'date_format' => NULL,
        'time_format' => NULL,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'match_amount_313',
        'option_group_id' => NULL,
        'serialize' => 0,
        'filter' => NULL,
        'in_selector' => FALSE,
      ],
      'match' => [
        'name',
      ],
    ],
  ],
];
