<?php
// Specify our wmf custom groups.
// Note this is not going through the civicrm_managed system
// ie no mgd in the file prefix
// for historical reasons - ie in the past the managed system did not
// use the move efficient BulkSave. In addition it used to be poor at
// matching existing fields. For new custom fields the CustomGroupMatchingGiftInformation.mgd.php
// is the model to follow.
// The fields in here could be converted but for now follow our old system - which
// keeps the declaration similar as it is conceptually similar.
// ******
// To sync the database with fields defined in this file use:
// drush @wmff cvapi WMFConfig.SyncCustomFields version=4
// ******
use Civi\Api4\OptionValue;
use Civi\WMFHook\CalculatedData;

$calculatedData = new CalculatedData();
// The option value for relationship is also ensured in the relationship
// block extension but we do it here as well in case that is not enabled
// in future for any reason.
CRM_Core_BAO_OptionValue::ensureOptionValueExists([
  'option_group_id' => 'cg_extend_objects',
  'name' => 'civicrm_relationship',
  'label' => ts('Relationship'),
  'value' => 'Relationship',
]);
CRM_Core_BAO_OptionValue::ensureOptionValueExists([
  'option_group_id' => 'cg_extend_objects',
  'name' => 'civicrm_phone',
  'label' => ts('Phone'),
  'value' => 'Phone',
]);
CRM_Core_BAO_OptionValue::ensureOptionValueExists([
  'option_group_id' => 'cg_extend_objects',
  'name' => 'civicrm_batch',
  'label' => ts('Batch'),
  'value' => 'Batch',
]);
// FIXME: Should we do these in an ActivityType.mgd.php?
$mg_year_end_appeal_activity_type = CRM_Core_BAO_OptionValue::ensureOptionValueExists([
  'option_group_id' => 'activity_type',
  'name' => 'Major Gifts Year End Appeal',
  'label' => ts('Major Gifts Year End Appeal'),
]);
$endowment_year_end_appeal_activity_type = CRM_Core_BAO_OptionValue::ensureOptionValueExists([
  'option_group_id' => 'activity_type',
  'name' => 'Endowment Year End Appeal',
  'label' => ts('Endowment Year End Appeal'),
]);
CRM_Core_BAO_OptionValue::ensureOptionValueExists([
  'option_group_id' => 'activity_type',
  'label' => 'Recurring Upgrade',
  'value' => 165,
  'name' => 'Recurring Upgrade',
  'grouping' => NULL,
  'filter' => 1,
  'is_default' => FALSE,
  'description' => 'Donor agreed to increase their recurring donation amount',
  'is_optgroup' => FALSE,
  'is_reserved' => TRUE,
  'is_active' => TRUE,
  'component_id' => NULL,
  'domain_id' => NULL,
  'visibility_id' => NULL,
  'icon' => 'fa-thumbs-o-up',
  'color' => NULL,
]);
CRM_Core_BAO_OptionValue::ensureOptionValueExists([
  'option_group_id' => 'activity_type',
  'label' => 'Recurring Downgrade',
  'value' => 168,
  'name' => 'Recurring Downgrade',
  'grouping' => NULL,
  'filter' => 1,
  'is_default' => FALSE,
  'description' => 'Donor reduced their recurring donation amount',
  'is_optgroup' => FALSE,
  'is_reserved' => TRUE,
  'is_active' => TRUE,
  'component_id' => NULL,
  'domain_id' => NULL,
  'visibility_id' => NULL,
  'icon' => 'fa-arrow-down',
  'color' => NULL,
]);
CRM_Core_BAO_OptionValue::ensureOptionValueExists([
  'option_group_id' => 'activity_type',
  'label' => 'Recurring Upgrade Decline',
  'value' => 166,
  'name' => 'Recurring Upgrade Decline',
  'grouping' => NULL,
  'filter' => 0,
  'is_default' => FALSE,
  'description' => 'Donor declined to increase their recurring donation amount',
  'is_optgroup' => FALSE,
  'is_reserved' => FALSE,
  'is_active' => TRUE,
  'component_id' => NULL,
  'domain_id' => NULL,
  'visibility_id' => NULL,
  'icon' => 'fa-thumbs-o-down',
  'color' => NULL,
]);
CRM_Core_BAO_OptionValue::ensureOptionValueExists([
  'option_group_id' => 'activity_type',
  'label' => 'Direct Mail',
  'name' => 'Direct Mail',
  'icon' => 'fa-envelopes-bulk',
]);

CRM_Core_BAO_OptionValue::ensureOptionValueExists([
  'option_group_id' => 'activity_type',
  'label' => 'Contact referral',
  'value' => 190,
  'name' => 'Contact referral',
  'grouping' => NULL,
  'filter' => 1,
  'is_default' => FALSE,
  'description' => 'Contribution was made by referral from another contact record',
  'is_optgroup' => FALSE,
  'is_reserved' => FALSE,
  'is_active' => TRUE,
  'component_id' => NULL,
  'domain_id' => NULL,
  'visibility_id' => NULL,
  'color' => NULL,
]);

CRM_Core_BAO_OptionValue::ensureOptionValueExists([
  'option_group_id' => 'activity_type',
  'label' => 'Double Opt-In',
  'value' => 220,
  'name' => 'Double Opt-In',
  'grouping' => NULL,
  'filter' => 1,
  'is_default' => FALSE,
  'description' => 'Donor confirmed that they want to receive emails. Opted in email address is in subject.',
  'is_optgroup' => FALSE,
  'is_reserved' => FALSE,
  'is_active' => TRUE,
  'component_id' => NULL,
  'domain_id' => NULL,
  'visibility_id' => NULL,
  'color' => NULL,
]);
CRM_Core_BAO_OptionValue::ensureOptionValueExists([
  'option_group_id' => 'activity_type',
  'label' => 'Recurring Paused',
  'value' => 201,
  'name' => 'Recurring Paused',
  'grouping' => NULL,
  'filter' => 1,
  'weight' => 94,
  'is_default' => FALSE,
  'description' => 'Donor paused recurring',
  'is_optgroup' => FALSE,
  'is_reserved' => FALSE,
  'is_active' => TRUE,
  'component_id' => NULL,
  'domain_id' => NULL,
  'visibility_id' => NULL,
  'icon' => 'fa-pause',
  'color' => NULL,
]);
$recurringCancelActivityId = OptionValue::get(FALSE)
  ->addWhere('name', '=', 'Cancel Recurring Contribution')
  ->execute()
  ->first()['value'];
$recurringModifyActivityId = OptionValue::get(FALSE)
  ->addWhere('name', '=', 'Update Recurring Contribution')
  ->execute()
  ->first()['value'];

return [
  'wmf_donor' => [
    'group' => [
      'extends' => 'Contact',
      'name' => 'wmf_donor',
      'table_name' => 'wmf_donor',
      'title' => ts('WMF Donor'),
      'is_active' => 1,
      'style' => 'inline',
    ],
    'fields' => $calculatedData->getWMFDonorFields(),
  ],
  'External_Identifiers' => [
    'group' => [
      'extends' => 'Contact',
      'name' => 'External_Identifiers',
      'table_name' => 'wmf_external_contact_identifiers',
      'title' => ts('External Identifiers'),
      'is_active' => 1,
      'style' => 'inline',
    ],
    'fields' => _wmf_civicrm_get_external_identifiers_fields(),
  ],
  'contribution_extra' => [
    'group' => [
      'extends' => 'Contribution',
      'name' => 'contribution_extra',
      'table_name' => 'wmf_contribution_extra',
      'title' => ts('Contribution Extra'),
      'is_active' => 1,
    ],
    'fields' => _wmf_civicrm_get_wmf_contribution_extra_fields(),
  ],
  'contribution_settlement' => [
    'group' => [
      'extends' => 'Contribution',
      'name' => 'contribution_settlement',
      'table_name' => 'civicrm_value_contribution_settlement',
      'title' => ts('Contribution Settlement'),
      'is_active' => 1,
    ],
    'fields' => _wmf_civicrm_get_contribution_settlement_fields(),
  ],
  'Communication' => [
    'group' => [
      'name' => 'Communication',
      'extends' => 'Contact',
      'style' => 'Inline',
      'collapse_display' => 0,
      'title' => 'Communication',
      'table_name' => 'civicrm_value_1_communication_4',
    ],
    'fields' => _wmf_civicrm_get_communication_fields(),
  ],
  'Adjustment' => [
    'group' => [
      'name' => 'Adjustment',
      'table_name' => 'civicrm_value_adjustment_31',
      'title' => ts('Adjustment'),
      'extends' => 'Contribution',
      'style' => 'inline',
      'is_active' => 1,
    ],
    'fields' => _wmf_civicrm_get_gift_adjustment_fields(),
  ],
  'Gift_Data' => [
    'group' => [
      'name' => 'Gift_Data',
      'table_name' => 'civicrm_value_1_gift_data_7',
      'title' => ts('Gift Data'),
      'extends' => 'Contribution',
      'style' => 'inline',
      'is_active' => 1,
    ],
    'fields' => _wmf_civicrm_get_gift_data_fields(),
  ],
  'Prospect' => [
    'group' => [
      'name' => 'Prospect',
      'title' => 'Prospect',
      'extends' => 'Contact',
      'style' => 'tab',
      'is_active' => 1,
      'table_name' => 'civicrm_value_1_prospect_5',
    ],
    'fields' => _wmf_civicrm_get_prospect_fields(),
  ],
  'Anonymous' => [
    'group' => [
      'name' => 'Anonymous',
      'title' => 'Benefactor Page Listing',
      'extends' => 'Contact',
      'style' => 'Inline',
      'is_active' => 1,
    ],
    'fields' => _wmf_civicrm_get_benefactor_fields(),
  ],
  'Partner' => [
    'group' => [
      'name' => 'Partner',
      'title' => 'Partner',
      'extends' => 'Contact',
      'style' => 'Inline',
      'is_active' => 1,
      // Setting weight here is a bit hit & miss but one day the api
      // will do the right thing...
      'weight' => 1,
    ],
    'fields' => _wmf_civicrm_get_partner_fields(),
  ],
  'Stock_Information' => [
    'group' => [
      'name' => 'Stock_Information',
      'title' => 'Stock Information',
      'extends' => 'Contribution',
      'style' => 'Inline',
      'is_active' => 1,
      // Setting weight here is a bit hit & miss but one day the api
      // will do the right thing...
      'weight' => 1,
    ],
    'fields' => _wmf_civicrm_get_stock_fields(),
  ],
  'Organization_Contact' => [
    'group' => [
      'name' => 'Organization_Contact',
      'title' => 'Organization Contact',
      'extends' => 'Organization',
      'is_active' => 1,
    ],
    'fields' => _wmf_civicrm_get_organization_contact_fields(),
  ],
  'Relationship_Metadata' => [
    'group' => [
      'name' => 'Relationship_Metadata',
      'title' => 'Relationship Metadata',
      'extends' => 'Relationship',
      'style' => 'Inline',
      'is_active' => 1,
      'table_name' => 'civicrm_value_relationship_metadata',
    ],
    'fields' => _wmf_civicrm_get_relationship_metadata_fields(),
  ],
  'Assistant' => [
    'group' => [
      'name' => 'Assistant',
      'title' => 'Assistant',
      'extends' => 'Individual',
      'style' => 'Inline',
      'is_active' => 1,
      'table_name' => 'civicrm_value_assistant_15',
    ],
    'fields' => _wmf_civicrm_get_assistant_fields(),
  ],
  'Major_Gifts_Year_End_Appeal' => [
    'group' => [
      'name' => 'Major_Gifts_Year_End_Appeal',
      'title' => 'Major Gifts Year End Appeal',
      'extends' => 'Activity',
      'extends_entity_column_value' => $mg_year_end_appeal_activity_type['value'],
      'style' => 'Inline',
      'weight' => 31,
      'is_active' => 1,
      'table_name' => 'civicrm_value_major_gifts_y_27',
    ],
    'fields' => _wmf_civicrm_get_mg_year_end_appeal_fields(),
  ],
  'Endowment_Year_End_Appeal' => [
    'group' => [
      'name' => 'Endowment_Year_End_Appeal',
      'title' => 'Endowment Year End Appeal',
      'extends' => 'Activity',
      'extends_entity_column_value' => $endowment_year_end_appeal_activity_type['value'],
      'style' => 'Inline',
      'weight' => 32,
      'is_active' => TRUE,
      'table_name' => 'civicrm_value_endowment_yea_28',
    ],
    'fields' => _wmf_civicrm_get_endowment_year_end_appeal_fields(),
  ],
  'activity_tracking' => [
    'group' => [
      'name' => 'activity_tracking',
      'title' => 'Activity Tracking',
      'extends' => 'Activity',
      // Values hardcoded above and in ActivityType.mgd.php
      'extends_entity_column_value' => [
        165,
        166,
        168,
        201,
        220,
        $recurringCancelActivityId,
        $recurringModifyActivityId
      ],
      'style' => 'Inline',
      'is_active' => TRUE,
      'table_name' => 'civicrm_activity_tracking',
      'weight' => 3,
    ],
    'fields' => _wmf_civicrm_get_activity_tracking_fields(),
  ],

  'address_data' => [
    'group' => [
      'name' => 'address_data',
      'title' => 'Address Data',
      'extends' => 'Address',
      'style' => 'Inline',
      'is_active' => TRUE,
      'table_name' => 'civicrm_value_address_data',
    ],
    'fields' => _wmf_civicrm_get_address_data_fields(),
  ],
  'phone_data' => [
    'group' => [
      'name' => 'phone_data',
      'title' => 'Phone Data',
      'extends' => 'Phone',
      'style' => 'Inline',
      'is_active' => TRUE,
      'table_name' => 'civicrm_value_phone_data',
    ],
    'fields' => _wmf_civicrm_get_phone_data_fields(),
  ],
  'donor_advised_fund' => [
    'group' => [
      'name' => 'donor_advised_fund',
      'title' => 'Donor Advised Fund',
      'extends' => 'Contribution',
      'style' => 'Inline',
      'is_active' => TRUE,
      'table_name' => 'civicrm_relationship_donor_advised',
    ],
    'fields' => _wmf_civicrm_get_donor_advised_fields(),
  ],
  'direct_mail_data' => [
    'group' => [
      'name' => 'direct_mail_data',
      'title' => 'Direct Mail',
      'table_name' => 'civicrm_value_direct_mail_data',
      'extends' => 'Activity',
      'extends_entity_column_value' => [CRM_Core_PseudoConstant::getKey('CRM_Activity_BAO_Activity', 'activity_type_id', 'direct_mail')],
    ],
    'fields' => _wmf_civicrm_get_direct_mail_fields(),
  ],
  'batch_data' => [
    'group' => [
      'name' => 'batch_data',
      'title' => 'Batch Data',
      'table_name' => 'civicrm_batch_data',
      'extends' => 'Batch',
    ],
    'fields' => _wmf_civicrm_get_batch_data_fields(),
  ],
  'Gift_Information' => [
    'group' => [
      'name' => 'Gift_Information',
      'title' => 'Gift Information',
      'table_name' => 'civicrm_value_1_check_number_9',
      'extends' => 'Contribution',
    ],
    'fields' => _wmf_civicrm_get_gift_information_fields(),
  ],
];

/**
 * Get fields for gift data custom group.
 *
 * @return array
 */
function _wmf_civicrm_get_gift_data_fields(): array {
  return [
    'Fund' => [
      'name' => 'Fund',
      'column_name' => 'fund',
      'label' => ts('Fund'),
      'data_type' => 'String',
      'html_type' => 'Select',
      'default_value' => 'Unrestricted - General',
      'is_active' => 1,
      'is_required' => 1,
      'is_searchable' => 1,
      'option_values' => [
        ['name' => 'Unrestricted__General', 'label' => 'Unrestricted - General', 'value' => 'Unrestricted - General'],
        ['name' => 'endowment', 'label' => 'Endowment Fund', 'value' => 'Endowment Fund'],
        ['name' => 'Restricted__Foundation', 'label' => 'Restricted - Foundation', 'value' => 'Restricted - Foundation'],
        ['name' => 'Major_Gifts_CC104', 'label' => 'Major Gifts - CC104', 'value' => 'Major Gifts - CC104'],
      ],
    ],
    'Campaign' => [
      'name' => 'Campaign',
      'column_name' => 'campaign',
      'label' => ts('Gift Type'),
      'data_type' => 'String',
      'html_type' => 'Select',
      'default_value' => 'Individual Gift',
      'is_active' => 1,
      'is_required' => 1,
      'is_searchable' => 1,
      'option_values' => [
        ['name' => 'Individual_Gift', 'label' => 'Individual Gift', 'value' => 'Individual Gift'],
        ['name' => 'Online_Gift', 'label' => 'Online Gift', 'value' => 'Online Gift'],
        ['name' => 'Alternative_Gifts', 'label' => 'Alternative Gifts', 'value' => 'Alternative Gifts'],
        ['name' => 'Benefactor_Gift', 'label' => 'Benefactor Gift', 'value' => 'Benefactor Gift'],
        ['name' => 'BusDev', 'label' => 'BusDev', 'value' => 'BusDev'],
        ['name' => 'Chapter_Gift', 'label' => 'Chapter Gift', 'value' => 'Chapter Gift'],
        ['name' => 'Combined_Federal_Campaign', 'label' => 'Combined Federal Campaign', 'value' => 'Combined Federal Campaign'],
        ['name' => 'Community_Gift', 'label' => 'Community Gift', 'value' => 'Community Gift'],
        ['name' => 'Corporate_Gift', 'label' => 'Corporate Gift', 'value' => 'Corporate Gift'],
        ['name' => 'Donor_Advised_Fund', 'label' => 'Donor Advised Fund', 'value' => 'Donor Advised Fund'],
        ['name' => 'Endowment_Gift', 'label' => 'Endowment Gift', 'value' => 'Endowment Gift'],
        ['name' => 'Employee_Giving', 'label' => 'Employee Giving', 'value' => 'Employee Giving'],
        ['name' => 'Fund_to_Fund_Transfer', 'label' => 'Fund-to-Fund Transfer', 'value' => 'Fund-to-Fund Transfer'],
        ['name' => 'Foundation_Gift', 'label' => 'Foundation Gift', 'value' => 'Foundation Gift'],
        ['name' => 'Legacy_Gift', 'label' => 'Legacy Gift', 'value' => 'Legacy Gift'],
        ['name' => 'Major_Gift', 'label' => 'Major Gift', 'value' => 'Major Gift'],
        ['name' => 'Matching_Gift', 'label' => 'Matching Gift', 'value' => 'Matching Gift'],
        ['name' => 'Partnerships_Gift', 'label' => 'Partnerships Gift', 'value' => 'Partnerships Gift'],
        ['name' => 'Payroll_Deduction', 'label' => 'Payroll Deduction', 'value' => 'Payroll Deduction'],
        ['name' => 'Realized_Bequest', 'label' => 'Realized Bequest', 'value' => 'Realized Bequest'],
        ['name' => 'Retirement_Fund', 'label' => 'Retirement Fund', 'value' => 'Retirement Fund'],
        ['name' => 'Volunteer_Match', 'label' => 'Volunteer Match', 'value' => 'Volunteer Match'],
      ],
    ],
    'Appeal' => [
      'name' => 'Appeal',
      'column_name' => 'appeal',
      'label' => ts('Direct Mail Appeal'),
      'data_type' => 'String',
      'html_type' => 'Select',
      'default_value' => 'Spontaneous Donation',
      'is_active' => 1,
      'is_required' => 1,
      'is_searchable' => 1,
      'option_values' => [
        ['name' => 'White_Mail', 'label' => 'White Mail', 'value' => 'White Mail'],
        ['name' => 'Spontaneous_Donation', 'label' => 'Spontaneous Donation', 'value' => 'Spontaneous Donation'],
        ['name' => 'Facebook', 'label' => 'Facebook', 'value' => 'Facebook'],
        ['name' => 'Event', 'label' => 'Event', 'value' => 'Event'],
        ['name' => 'Mobile_Giving', 'label' => 'Mobile Giving', 'value' => 'Mobile Giving'],
        ['name' => 'Corp_Matching_Gift', 'label' => 'Corp Matching Gift', 'value' => 'Corp Matching Gift'],
      ],
    ],
    'Donor_Specified' => [
      'name' => 'Donor_Specified',
      'column_name' => 'donor_specified_340',
      'label' => ts('Donor Specified'),
      'data_type' => 'String',
      'html_type' => 'CheckBox',
      'default_value' => NULL,
      'is_required' => FALSE,
      'is_searchable' => TRUE,
      'is_search_range' => FALSE,
      'option_values' => [
        ['name' => 'Endowment_Fund', 'label' => 'Endowment Fund', 'value' => 1],
        ['name' => 'Unrestricted_-_Fund', 'label' => 'Unrestricted - Fund', 'value' => 2],
      ],

    ],
    'Package' => [
      'name' => 'Package',
      'label' => 'Package',
      'column_name' => 'package',
      'html_type' => 'Autocomplete-Select',
      'is_searchable' => TRUE,
      'weight' => 326,
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
      'option_values' => [
        'OCT1B3ES' => 'OCT1B3ES',
        'OCT1B2ES' => 'OCT1B2ES',
      ],
    ],
    'Channel' => [
      'name' => 'Channel',
      'label' => 'Channel',
      'column_name' => 'channel',
      'html_type' => 'Select',
      'is_searchable' => TRUE,
      'weight' => 310,
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
      'option_values' => [
        ['name' => 'Mobile_Banner', 'label' => 'Mobile Banner', 'value' => 'Mobile Banner'],
        ['name' => 'Desktop_Banner', 'label' => 'Desktop Banner', 'value' => 'Desktop Banner'],
        ['name' => 'Portal_Banner', 'label' => 'Portal Banner', 'value' => 'Portal Banner'],
        ['name' => 'Other_Banner', 'label' => 'Other Banner', 'value' => 'Other Banner'],
        ['name' => 'Other_Portal', 'label' => 'Other Portal', 'value' => 'Other Portal'],
        ['name' => 'Wikimedia_Portal', 'label' => 'Wikimedia Portal', 'value' => 'Wikimedia Portal'],
        ['name' => 'Sidebar', 'label' => 'Sidebar', 'value' => 'Sidebar'],
        ['name' => 'Social_Media', 'label' => 'Social Media', 'value' => 'Social Media'],
        ['name' => 'Wikipedia_App', 'label' => 'Wikipedia App', 'value' => 'Wikipedia App'],
        ['name' => 'Email', 'label' => 'Email', 'value' => 'Email'],
        ['name' => 'Direct_Mail', 'label' => 'Direct Mail', 'value' => 'Direct Mail'],
        ['name' => 'Workplace_Giving', 'label' => 'Workplace Giving', 'value' => 'Workplace Giving'],
        ['name' => 'Direct_Solicitation', 'label' => 'Direct Solicitation', 'value' => 'Direct Solicitation'],
        ['name' => 'Planned_Giving', 'label' => 'Planned Giving', 'value' => 'Planned Giving'],
        ['name' => 'Events', 'label' => 'Events', 'value' => 'Events'],
        ['name' => 'SMS', 'label' => 'SMS', 'value' => 'SMS'],
        ['name' => 'Recurring_Gift', 'label' => 'Recurring Gift', 'value' => 'Recurring Gift'],
        ['name' => 'Chapter_Gifts', 'label' => 'Chapter Gifts', 'value' => 'Chapter Gifts'],
        ['name' => 'Other_Offline', 'label' => 'Other Offline', 'value' => 'Other Offline'],
        ['name' => 'Other_Online', 'label' => 'Other Online', 'value' => 'Other Online'],
      ],
    ],
    'is_major_gift' => [
      'name' => 'is_major_gift',
      'label' => 'Is Major Gift',
      'column_name' => 'is_major_gift',
      'description' => 'Has this been solicited through major gift team efforts (or is it over 10k)',
      'data_type' => 'Boolean',
      'html_type' => 'Radio',
      'default_value' => 0,
      'is_searchable' => TRUE,
      'weight' => 312,
    ],
  ];
}

/**
 * Get fields for gift adjustment custom group.
 *
 * @return array
 */
function _wmf_civicrm_get_gift_adjustment_fields(): array {
  return [
    'Date' => [
      'name' => 'Date',
      'column_name' => 'date',
      'label' => ts('Date'),
      'data_type' => 'Date',
      'html_type' => 'Select Date',
      'default_value' => NULL,
      'is_active' => 1,
      'is_required' => 0,
      'is_searchable' => 1,
      'help_pre' => 'Enter the date of the adjustment',
      'date_format' => 'mm/dd/yy',
      'weight' => 4,
      'note_columns' => 60,
      'note_rows' => 4,
    ],
    'Reason' => [
      'name' => 'Reason',
      'column_name' => 'reason',
      'label' => ts('Reason'),
      'data_type' => 'String',
      'html_type' => 'Select',
      'default_value' => NULL,
      'is_active' => 1,
      'is_required' => 0,
      'is_searchable' => 1,
      'weight' => 8,
      'option_values' => [
        ['name' => 'Direct_Mail_Appeal', 'label' => 'Direct Mail Appeal', 'value' => 1],
        ['name' => 'Original_deposit_WMF_move_to_EN', 'label' => 'Original deposit WMF - move to END', 'value' => 4],
        ['name' => 'Original_deposit_END_move_to_WM', 'label' => 'Original deposit END - move to WMF', 'value' => 'Original deposit END - move to WMF'],
      ],
    ],
    'Notes' => [
      'name' => 'Notes',
      'column_name' => 'notes',
      'label' => ts('Notes'),
      'data_type' => 'Memo',
      'html_type' => 'TextArea',
      'default_value' => NULL,
      'is_active' => 1,
      'is_required' => 0,
      'is_searchable' => 1,
      'weight' => 9,
      'help_pre' => 'Record information about the adjustment',
      'attributes' => 'rows=4, cols=60',
      'note_columns' => 60,
      'note_rows' => 4,
    ],
  ];
}

/**
 * Get fields from prospect custom group.
 *
 * @return array
 */
function _wmf_civicrm_get_prospect_fields(): array {
  return [
    'Origin' => [
      'name' => 'Origin',
      'label' => 'Origin',
      'data_type' => 'String',
      'html_type' => 'Select',
      'help_post' => 'How do we know about the prospect?',
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
      //"option_group_id":"65",
    ],
    'Solicitor' => [
      'name' => 'Solicitor',
      'label' => 'Solicitor',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => 1,
      'note_columns' => 60,
      'note_rows' => 4,
      //"option_group_id":"45",
    ],
    'Biography' => [
      'name' => 'Biography',
      'label' => 'Biography',
      "data_type" => 'Memo',
      'html_type' => 'RichTextEditor',
      'is_searchable' => 1,
      'help_post' => 'Who they are, what they do.',
      'attributes' => 'rows=4, cols=60',
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
    ],
    'Estimated_Net_Worth' => [
      'name' => 'Estimated_Net_Worth',
      'label' => '(TS) Estimated Net Worth',
      'column_name' => 'estimated_net_worth_144',
      'data_type' => 'String',
      'html_type' => 'Select',
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
      'option_values' => [
        ['name' => '_20_Million_', 'label' => '$20 Million +', 'value' => '1'],
        ['name' => 'gt_5b', 'label' => '>$5B', 'value' => '7'],
        ['name' => 'gt_1b', 'label' => '>$1B', 'value' => '8'],
        ['name' => 'gt_10b', 'label' => '>$10B', 'value' => '9'],
        ['name' => '_100_Million_plus', 'label' => '$100 Million +', 'value' => '10'],
        ['name' => '_25_000_49_999', 'label' => '$25,000 - $49,999', 'value' => 'B'],
        ['name' => 'Below_25_000', 'label' => 'Below $25,000', 'value' => 'A'],
        ['name' => '_50_000_74_999', 'label' => '$50,000 - $74,999', 'value' => 'C'],
        ['name' => '_75_000_99_999', 'label' => '$75,000 - $99,999', 'value' => 'D'],
        ['name' => '_100_000_149_999', 'label' => '$100,000 - $149,999', 'value' => 'E'],
        ['name' => '_150_000_199_999', 'label' => '$150,000 - $199,999', 'value' => 'F'],
        ['name' => '_200_000_249_999', 'label' => '$200,000 - $249,999', 'value' => 'G'],
        ['name' => '_250_000_499_999', 'label' => '$250,000 - $499,999', 'value' => 'H'],
        ['name' => '_500_000_749_999', 'label' => '$500,000 - $749,999', 'value' => 'I'],
        ['name' => '_750_000_999_999', 'label' => '$750,000 - $999,999', 'value' => 'J'],
        ['name' => '_1_000_000_2_499_999', 'label' => '$1,000,000 - $2,499,999', 'value' => 'K'],
        ['name' => '_2_500_000_4_999_999', 'label' => '$2,500,000 - $4,999,999', 'value' => 'L'],
        ['name' => '_5_000_000_9_999_999', 'label' => '$5,000,000 - $9,999,999', 'value' => 'M'],
        ['name' => 'Above_10_000_000', 'label' => 'Above $10,000,000', 'value' => 'N'],
      ],
    ],
    'Philanthropic_History' => [
      'name' => 'Philanthropic_History',
      'label' => 'Philanthropic History',
      'data_type' => 'Memo',
      'html_type' => 'RichTextEditor',
      'is_searchable' => 1,
      'attributes' => 'rows=4, cols=60',
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
    ],
    'Philanthropic_Interests' => [
      'name' => 'Philanthropic_Interests',
      'label' => 'Philanthropic Interests',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => 1,
      'note_columns' => 60,
      'note_rows' => 4,
      'option_values' => [
        1 => 'Technology',
        2 => 'Education',
        3 => 'Political Campaign',
        4 => 'Cultural Arts',
        5 => 'Poverty',
        6 => 'Environment',
      ],
    ],
    'Subject_Area_Interest' => [
      'name' => 'Subject_Area_Interest',
      'label' => 'Subject Area Interest',
      'data_type' => 'String',
      'html_type' => 'Multi-Select',
      'is_searchable' => 1,
      'help_post' => 'Subject Area, Interests',
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
      //"option_group_id":"115",
    ],
    'Interests' => [
      'name' => 'Interests',
      'label' => 'Interests',
      'data_type' => 'Memo',
      'html_type' => 'RichTextEditor',
      'is_searchable' => 1,
      'help_post' => 'Pet projects, hobbies, other conversation worthy interests',
      'attributes' => 'rows=4, cols=60',
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
    ],
    'University_Affiliation' => [
      'name' => 'University_Affiliation',
      'label' => 'University Affiliation',
      'data_type' => 'String',
      'html_type' => 'Multi-Select',
      'is_searchable' => 1,
      'help_post' => 'University Attended, Taught At, Employed By',
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
      'option_values' => [
        ['name' => 'Stanford', 'label' => 'Stanford', 'value' => 'Stanford'],
        ['name' => 'CAL__Berkeley', 'label' => 'CAL - Berkeley', 'value' => 'CAL - Berkeley'],
        ['name' => 'MIT', 'label' => 'MIT', 'value' => 'MIT'],
        ['name' => 'CMU', 'label' => 'Carnegie Mellon', 'value' => 'Carnegie Mellon'],
        ['name' => 'Harvard', 'label' => 'Harvard', 'value' => 'Harvard'],
        ['name' => 'University of Chicago', 'label' => 'University of Chicago', 'value' => '1'],
        ['name' => 'Yale', 'label' => 'Yale', 'value' => '2'],
      ],
    ],
    'Board_Affiliations' => [
      'name' => 'Board_Affiliations',
      'label' => 'Board Affiliations',
      'data_type' => 'Memo',
      'html_type' => 'RichTextEditor',
      'is_searchable' => 1,
      'note_columns' => 60,
      'note_rows' => 4,
    ],
    'Notes' => [
      'name' => 'Notes',
      'label' => 'Notes',
      'data_type' => 'Memo',
      'html_type' => 'RichTextEditor',
      'is_searchable' => 1,
      'note_columns' => 60,
      'note_rows' => 4,
    ],
    'Stage' => [
      'name' => 'Stage',
      'label' => 'MG Stage',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => 1,
      'note_columns' => 60,
      'note_rows' => 4,
      // "option_group_id":"32",
    ],
    'On_Hold' => [
      'name' => 'On_Hold',
      'label' => 'On Hold',
      'data_type' => 'Boolean',
      'html_type' => 'Radio',
      'default_value' => 0,
      'is_searchable' => 1,
      'help_post' => 'Prospects archived from being stewarded',
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
    ],
    'Affinity' => [
      'name' => 'Affinity',
      'label' => 'Affinity',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => 1,
      'default_value' => 'Unknown',
      'note_columns' => 60,
      'note_rows' => 4,
      'option_values' => [
        ['name' => 'Unknown', 'label' => 'Unknown', 'value' => 'Unknown'],
        ['name' => 'c4ca4238a0b923820dcc509a6f75849', 'label' => '1', 'value' => '1', 'description' => 'Low'],
        ['name' => 'c81e728d9d4c2f636f067f89cc14862', 'label' => '2', 'value' => '2'],
        ['name' => 'eccbc87e4b5ce2fe28308fd9f2a7baf', 'label' => '3', 'value' => '3'],
        ['name' => 'a87ff679a2f3e71d9181a67b7542122', 'label' => '4', 'value' => '4', 'description' => 'High'],
      ],
    ],

    'Capacity' => [
      'name' => 'Capacity',
      'label' => '(TS) Capacity',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => 1,
      'help_post' => 'Low = <$5k\r\nMedium = $5k to $99,999\r\nHigh = >$100k and over',
      'note_columns' => 60,
      'note_rows' => 4,
      'option_values' => [
        ['name' => '_1_10k', 'label' => '$1-10k', 'value' => '$1-10k'],
        ['name' => '_11_20k', 'label' => '$11-$20k', 'value' => '$11-$20k'],
        ['name' => '_21_30k', 'label' => '$21-$30k', 'value' => '$21-$30k'],
        ['name' => '_31_40k', 'label' => '$31-$40k', 'value' => '$31-$40k'],
        ['name' => '_41_50k', 'label' => '$41-$50k', 'value' => '$41-$50k'],
        ['name' => '_51_75k', 'label' => '$51-$75k', 'value' => '$51-$75k'],
        ['name' => '_76_100k', 'label' => '$76-$100k', 'value' => '$76-$100k'],
        ['name' => '_101_250k', 'label' => '$101-$250k', 'value' => '$101-$250k'],
        ['name' => '_251_500k', 'label' => '$251-$500k', 'value' => '$251-$500k'],
        ['name' => '_501k_1M', 'label' => '$501k - $1M', 'value' => '$501k - $1M'],
        ['name' => '_1_1M_2_5M', 'label' => '$1.1M - $2.5M', 'value' => '$1.1M - $2.5M'],
        ['name' => '_2_6M_5M', 'label' => '$2.6M - $5M', 'value' => '$2.6M - $5M'],
        ['name' => '_5_1M_10M', 'label' => '$5.1M - $10M', 'value' => '$5.1M - $10M'],
        ['name' => '_10M_', 'label' => '$10M+', 'value' => '$10M+'],
        ['name' => 'Unknown', 'label' => 'Unknown', 'value' => '9'],
        ['name' => '250_999', 'label' => '$250-999', 'value' => '10'],
        ['name' => 'Under_250', 'label' => 'Under $250', 'value' => '11'],
      ],
    ],
    'Reviewed' => [
      'name' => 'Reviewed',
      'label' => 'Reviewed',
      'data_type' => 'Date',
      'html_type' => 'Select Date',
      'is_searchable' => 1,
      'is_search_range' => 1,
      'start_date_years' => 10,
      'end_date_years' => 1,
      'date_format' => 'mm/dd/yy',
      'note_columns' => 60,
      'note_rows' => 4,
    ],
    'Income_Range' => [
      'name' => 'Income_Range',
      'label' => '(TS) Income Range',
      'column_name' => 'income_range',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => 1,
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
      'option_values' => [
        'a' => 'Below $30,000',
        'b ' => '$30,000 - $39,999',
        'c' => '$40,000 - $49,999',
        'd' => '$50,000 - $59,999',
        'e' => '$60,000 - $74,999',
        'f' => '$75,000 - $99,999',
        'g' => '$100,000 - $124,999',
        'h' => '$125,000 - $149,999',
        'i' => '$150,000 - $199,999',
        'j' => '$200,000 - $249,999',
        'k' => '$250,000 - $299,999',
        'l' => '$300,000 - $499,999',
        'm' => 'Above $500,000',
      ],
    ],
    'Charitable_Contributions_Decile' => [
      'name' => 'Charitable_Contributions_Decile',
      'column_name' => 'charitable_contributions_decile',
      'label' => '(TS) Charitable Contributions Decile',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => 1,
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
      'option_values' => [
        ['name' => 'c4ca4238a0b923820dcc509a6f75849', 'label' => '1', 'value' => '1'],
        ['name' => 'c81e728d9d4c2f636f067f89cc14862', 'label' => '2', 'value' => '2'],
        ['name' => 'eccbc87e4b5ce2fe28308fd9f2a7baf', 'label' => '3', 'value' => '3'],
        ['name' => 'a87ff679a2f3e71d9181a67b7542122', 'label' => '4', 'value' => '4'],
        ['name' => 'e4da3b7fbbce2345d7772b0674a318d', 'label' => '5', 'value' => '5'],
        ['name' => '1679091c5a880faf6fb5e6087eb1b2d', 'label' => '6', 'value' => '6'],
        ['name' => '8f14e45fceea167a5a36dedd4bea254', 'label' => '7', 'value' => '7'],
        ['name' => 'c9f0f895fb98ab9159f51fd0297e236', 'label' => '8', 'value' => '8'],
        ['name' => '45c48cce2e2d7fbdea1afc51c7c6ad2', 'label' => '9', 'value' => '9'],
        ['name' => '10', 'label' => '10', 'value' => '10'],
        ['name' => '11', 'label' => '11', 'value' => '11'],
      ],
    ],
    'Disc_Income_Decile' => [
      'name' => 'Disc_Income_Decile',
      'label' => '(TS) Disc Income Decile',
      'column_name' => 'disc_income_decile',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => 1,
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
      'option_values' => [
        ['name' => 'c4ca4238a0b923820dcc509a6f75849', 'label' => '1', 'value' => '1'],
        ['name' => 'c81e728d9d4c2f636f067f89cc14862', 'label' => '2', 'value' => '2'],
        ['name' => 'eccbc87e4b5ce2fe28308fd9f2a7baf', 'label' => '3', 'value' => '3'],
        ['name' => 'a87ff679a2f3e71d9181a67b7542122', 'label' => '4', 'value' => '4'],
        ['name' => 'e4da3b7fbbce2345d7772b0674a318d', 'label' => '5', 'value' => '5'],
        ['name' => '1679091c5a880faf6fb5e6087eb1b2d', 'label' => '6', 'value' => '6'],
        ['name' => '8f14e45fceea167a5a36dedd4bea254', 'label' => '7', 'value' => '7'],
        ['name' => 'c9f0f895fb98ab9159f51fd0297e236', 'label' => '8', 'value' => '8'],
        ['name' => '45c48cce2e2d7fbdea1afc51c7c6ad2', 'label' => '9', 'value' => '9'],
        ['name' => '10', 'label' => '10', 'value' => '10'],
        ['name' => '11', 'label' => '11', 'value' => '11'],
      ],
    ],
    'ask_amount' => [
      'name' => 'ask_amount',
      'label' => 'Ask Amount',
      'data_type' => 'Money',
      'html_type' => 'Text',
      'is_searchable' => 1,
      'is_search_range' => 1,
    ],
    'expected_amount' => [
      'name' => 'expected_amount',
      'label' => 'Expected Amount',
      'data_type' => 'Money',
      'html_type' => 'Text',
      'is_searchable' => 1,
      'is_search_range' => 1,
    ],
    'likelihood' => [
      'name' => 'likelihood',
      'label' => 'Likelihood (%)',
      'data_type' => 'Int',
      'html_type' => 'Text',
      'is_searchable' => 1,
      'is_search_range' => 1,
    ],
    'expected_close_date' => [
      'name' => 'expected_close_date',
      'label' => 'Expected Close Date',
      'data_type' => 'Date',
      'html_type' => 'Select Date',
      'is_searchable' => 1,
      'is_search_range' => 1,
    ],
    'close_date' => [
      'name' => 'close_date',
      'label' => 'Close Date',
      'data_type' => 'Date',
      'html_type' => 'Select Date',
      'is_searchable' => 1,
      'is_search_range' => 1,
    ],
    'next_step' => [
      'name' => 'next_step',
      'label' => 'Next Step',
      'data_type' => 'Memo',
      'html_type' => 'RichTextEditor',
      'note_columns' => 60,
      'note_rows' => 4,
    ],
    'PG_Stage' => [
      'name' => 'PG_Stage',
      'label' => 'PG Stage',
      'data_type' => 'String',
      'html_type' => 'Select',
      'note_columns' => 60,
      'note_rows' => 4,
      'is_searchable' => 1,
      'option_values' => [
        '1' => 'Cultivation',
        '2' => "Cont'd Cultivation",
      ],
    ],
    'Survey_Responses' => [
      'name' => 'Survey_Responses',
      'label' => 'Survey Responses',
      'data_type' => 'String',
      'html_type' => 'Text',
      'note_columns' => 60,
      'note_rows' => 4,
      'help_pre' => 'Data field to store any MGF survey related data for future reference.  Please date appropriately and do not overwrite previous responses.',
    ],
    'Family_Composition' => [
      'name' => 'Family_Composition',
      'label' => '(TS) Family Composition',
      'data_type' => 'String',
      'html_type' => 'Select',
      'column_name' => 'family_composition_173',
      'is_searchable' => 1,
      'option_values' => [
        1 => 'Single',
        2 => 'Single with Children',
        3 => 'Couple',
        4 => 'Couple with children',
        5 => 'Multiple Generations',
        6 => 'Multiple Surnames (3+)',
        7 => 'Other',
      ],
    ],
    'Occupation' => [
      'name' => 'Occupation',
      'label' => '(TS) Occupation',
      'column_name' => 'occupation_175',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => 1,
      'option_values' => [
        1 => 'Professional/Technical',
        2 => 'Upper Management/Executive',
        3 => 'Sales/Service',
        4 => 'Office/Clerical',
        5 => 'Skilled Trade',
        6 => 'Retired',
        7 => 'Administrative/Management',
        8 => 'Self Employed',
        9 => 'Military',
        10 => 'Farming/Agriculture',
        11 => 'Medical/Health Services',
        12 => 'Financial Services',
        13 => 'Teacher/Educator',
        14 => 'Legal Services',
        15 => 'Religious',
      ],
    ],
    'IRA_and_401K_Decile' => [
      'label' => '(TS) IRA and 401K Decile',
      'name' => 'IRA_and_401K_Decile',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => 1,
      'option_values' => [
        ['name' => 'c4ca4238a0b923820dcc509a6f75849', 'label' => '1', 'value' => '1'],
        ['name' => 'c81e728d9d4c2f636f067f89cc14862', 'label' => '2', 'value' => '2'],
        ['name' => 'eccbc87e4b5ce2fe28308fd9f2a7baf', 'label' => '3', 'value' => '3'],
        ['name' => 'a87ff679a2f3e71d9181a67b7542122', 'label' => '4', 'value' => '4'],
        ['name' => 'e4da3b7fbbce2345d7772b0674a318d', 'label' => '5', 'value' => '5'],
        ['name' => '1679091c5a880faf6fb5e6087eb1b2d', 'label' => '6', 'value' => '6'],
        ['name' => '8f14e45fceea167a5a36dedd4bea254', 'label' => '7', 'value' => '7'],
        ['name' => 'c9f0f895fb98ab9159f51fd0297e236', 'label' => '8', 'value' => '8'],
        ['name' => '45c48cce2e2d7fbdea1afc51c7c6ad2', 'label' => '9', 'value' => '9'],
        ['name' => '10', 'label' => '10', 'value' => '10'],
      ],
    ],
    'Prospect_Insight' => [
      'name' => 'Prospect_Insight',
      'label' => 'Prospect Insight',
      'data_type' => 'String',
      'html_type' => 'Select',
      'help_pre' => 'iWave determined prospect insight',
      'column_name' => 'prospect_insight_280',
      'option_values' => [
        ['name' => 'Hidden_Gem', 'label' => 'Hidden Gem', 'value' => '1'],
        ['name' => 'Your_Champion', 'label' => 'Your Champion', 'value' => '2'],
        ['name' => 'Distinguished_Philanthropist', 'label' => 'Distinguished Philanthropist', 'value' => 'Distinguished Philanthropist'],
        ['name' => 'Not_Now_Prospect', 'label' => 'Not Now Prospect', 'value' => 'Not Now Prospect'],
      ],
    ],
    'Estimated_Capacity' => [
      'name' => 'Estimated_Capacity',
      'label' => '(TS) Estimated Capacity',
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_searchable' => TRUE,
      'is_search_range' => FALSE,
      'weight' => 295,
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
      'column_name' => 'estimated_capacity_281',
    ],
    'Planned_Giving_Score' => [
      'name' => 'Planned_Giving_Score',
      'label' => 'Planned Giving Score',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => TRUE,
      'is_search_range' => FALSE,
      'weight' => 312,
      'is_active' => TRUE,
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
      'column_name' => 'planned_giving_score_282',
      'option_values' => [
        ['name' => 'c4ca4238a0b923820dcc509a6f75849', 'label' => '1', 'value' => '1'],
        ['name' => 'c81e728d9d4c2f636f067f89cc14862', 'label' => '2', 'value' => '2'],
        ['name' => 'eccbc87e4b5ce2fe28308fd9f2a7baf', 'label' => '3', 'value' => '3'],
        ['name' => 'a87ff679a2f3e71d9181a67b7542122', 'label' => '4', 'value' => '4'],
      ],
    ],
    'Planned_Giving_Segment' => [
      'name' => 'Planned_Giving_Segment',
      'label' => 'Planned Giving Segment',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => TRUE,
      'is_search_range' => FALSE,
      'weight' => 313,
      'is_active' => TRUE,
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
      'column_name' => 'planned_giving_segment_283',
      'option_values' => [
        ['name' => 'Potential_Planned_Giver', 'label' => 'Potential Planned Giver', 'value' => '1'],
        ['name' => 'Ideal_Planned_Giver', 'label' => 'Ideal Planned Giver', 'value' => '2'],
        ['name' => 'Not_a_Planned_Giver', 'label' => 'Not a Planned Giver', 'value' => 'Not a Planned Giver'],
        ['name' => 'Strong_Planned_Giving_Prospect', 'label' => 'Strong Planned Giving Prospect', 'value' => 'Strong Planned Giving Prospect'],
      ],
    ],
  ];
}

/**
 * Get fields for partner custom group.
 *
 * @return array
 */
function _wmf_civicrm_get_partner_fields(): array {
  return [
    'Partner' => [
      'name' => 'Partner',
      'label' => 'Partner',
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_searchable' => 1,
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
    ],
  ];
}

/**
 * These are donor identifiers in external systems, like the
 * Fundraise Up Supporter ID. In WmfContact\Save, the external_identifier
 * field will be mapped to a custom field whose name is the gateway name
 * with '_id' appended. So for example if we start storing the PayPal
 * PAYERID we would add a field here called paypal_id.
 *
 * @return array
 */
function _wmf_civicrm_get_external_identifiers_fields(): array {
  return [
    'fundraiseup_id' => [
      'name' => 'fundraiseup_id',
      'column_name' => 'fundraiseup_id',
      'label' => ts('Fundraise Up Supporter ID'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 0,
    ],
    'venmo_user_name' => [
      'name' => 'venmo_user_name',
      'column_name' => 'venmo_user_name',
      'label' => ts('Venmo user name'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 0,
    ],
    'gravy_id' => [
      'name' => 'gravy_id',
      'column_name' => 'gravy_id',
      'label' => ts('Gravy Buyer ID'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 0,
    ],
    'paypal_payer_id' => [
      'name' => 'paypal_payer_id',
      'column_name' => 'paypal_payer_id',
      'label' => ts('Paypal Payer ID'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 0,
    ],
  ];
}

/**
 * Get fields for _wmf_contribution_extra.
 *
 * @return array
 */
function _wmf_civicrm_get_wmf_contribution_extra_fields(): array {
  return [
    'settlement_date' => [
      'name' => 'settlement_date',
      'column_name' => 'settlement_date',
      'label' => ts('Settlement Date'),
      'data_type' => 'Date',
      'html_type' => 'Select Date',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_search_range' => 1,
      'is_view' => 1,
      'date_format' => 'M d, yy',
      'time_format' => 2,
    ],
    'no_thank_you' => [
      'name' => 'no_thank_you',
      'column_name' => 'no_thank_you',
      'label' => ts('No Thank-you Reason'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 0,
    ],
    'total_usd' => [
      'name' => 'total_usd',
      'column_name' => 'total_usd',
      'label' => ts('Total in USD (approx)'),
      'data_type' => 'Money',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_search_range' => 1,
      'is_view' => 1,
    ],
    'gateway_account' => [
      'name' => 'gateway_account',
      'column_name' => 'gateway_account',
      'label' => ts('Gateway Account Name'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'gateway' => [
      'name' => 'gateway',
      'column_name' => 'gateway',
      'label' => ts('Gateway'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'backend_processor' => [
      'name' => 'backend_processor',
      'column_name' => 'backend_processor',
      'label' => ts('Backend Processor'),
      'description' => 'Underlying payment processor, when gateway is a payment orchestrator',
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'gateway_txn_id' => [
      'name' => 'gateway_txn_id',
      'column_name' => 'gateway_txn_id',
      'label' => ts('Gateway Transaction ID'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'backend_processor_txn_id' => [
      'name' => 'backend_processor_txn_id',
      'column_name' => 'backend_processor_txn_id',
      'label' => ts('Backend Processor Transaction ID'),
      'description' => 'ID of transaction at the underlying payment processor, when gateway is a payment orchestrator',
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'payment_orchestrator_reconciliation_id' => [
      'name' => 'payment_orchestrator_reconciliation_id',
      'column_name' => 'payment_orchestrator_reconciliation_id',
      'label' => ts('Payment Orchestrator Reconciliation ID'),
      'description' => 'cross-system reconciliation/shared ID of transaction at the payment orchestrator and underlying payment processor',
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'gateway_status_raw' => [
      'name' => 'gateway_status_raw',
      'column_name' => 'gateway_status_raw',
      'label' => ts('Gateway Status (raw)'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'gateway_date' => [
      'name' => 'gateway_date',
      'column_name' => 'gateway_date',
      'label' => ts('Gateway Last Update Timestamp'),
      'data_type' => 'Date',
      'html_type' => 'Select Date',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_search_range' => 1,
      'is_view' => 1,
      'date_format' => 'M d, yy',
      'time_format' => 2,
    ],
    'original_amount' => [
      'name' => 'original_amount',
      'column_name' => 'original_amount',
      'label' => ts('Original Amount Received (unconverted)'),
      'data_type' => 'Money',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_search_range' => 1,
      'is_view' => 1,
    ],
    'original_currency' => [
      'name' => 'original_currency',
      'column_name' => 'original_currency',
      'label' => ts('Original Currency Received'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'settlement_usd' => [
      'name' => 'settlement_usd',
      'column_name' => 'settlement_usd',
      'label' => ts('Settlement Total (USD)'),
      'data_type' => 'Money',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_search_range' => 1,
      'is_view' => 1,
    ],
    'settlement_currency' => [
      'name' => 'settlement_currency',
      'column_name' => 'settlement_currency',
      'label' => ts('Settlement Currency'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 0,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'settlement_batch_number' => [
      'name' => 'settlement_batch_number',
      'column_name' => 'settlement_batch_number',
      'label' => ts('Settlement Batch Number'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 0,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'deposit_date' => [
      'name' => 'deposit_date',
      'column_name' => 'deposit_date',
      'label' => ts('Deposit Received Date'),
      'data_type' => 'Date',
      'html_type' => 'Select Date',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_search_range' => 1,
      'is_view' => 1,
      'date_format' => 'M d, yy',
      'time_format' => 2,
    ],
    'deposit_usd' => [
      'name' => 'deposit_usd',
      'column_name' => 'deposit_usd',
      'label' => ts('Deposit Total (USD)'),
      'data_type' => 'Money',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_search_range' => 1,
      'is_view' => 1,
    ],
    'deposit_currency' => [
      'name' => 'deposit_currency',
      'column_name' => 'deposit_currency',
      'label' => ts('Deposit Currency'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'parent_contribution_id' => [
      'name' => 'parent_contribution_id',
      'column_name' => 'parent_contribution_id',
      'label' => ts('Parent Contribution ID'),
      'data_type' => 'Int',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'finance_only' => [
      'name' => 'finance_only',
      'column_name' => 'finance_only',
      'label' => ts('Finance Auditing Only'),
      'data_type' => 'Boolean',
      'html_type' => 'Radio',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'markup_fee' => [
      'name' => 'markup_fee',
      'column_name' => 'markup_fee',
      'label' => ts('Markup Fee (in settlement currency)'),
      'data_type' => 'Money',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_view' => 1,
    ],
    'interchange_fee' => [
      'name' => 'interchange_fee',
      'column_name' => 'interchange_fee',
      'label' => ts('Interchange Fee (in settlement currency)'),
      'data_type' => 'Money',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_view' => 1,
    ],
    'scheme_fee' => [
      'name' => 'scheme_fee',
      'column_name' => 'scheme_fee',
      'label' => ts('Scheme Fee (in settlement currency)'),
      'data_type' => 'Money',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_view' => 1,
    ],
    'source_name' => [
      'name' => 'source_name',
      'column_name' => 'source_name',
      'label' => ts('Source Name'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'source_type' => [
      'name' => 'source_type',
      'column_name' => 'source_type',
      'label' => ts('Source Type'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'source_host' => [
      'name' => 'source_host',
      'column_name' => 'source_host',
      'label' => ts('Source Host'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'source_run_id' => [
      'name' => 'source_run_id',
      'column_name' => 'source_run_id',
      'label' => ts('Source Run ID'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'source_version' => [
      'name' => 'source_version',
      'column_name' => 'source_version',
      'label' => ts('Source Version'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
    'source_enqueued_time' => [
      'name' => 'source_enqueued_time',
      'column_name' => 'source_enqueued_time',
      'label' => ts('Enqueued At Timestamp'),
      'data_type' => 'Date',
      'html_type' => 'Select Date',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_search_range' => 1,
      'is_view' => 1,
      'date_format' => 'M d, yy',
      'time_format' => 2,
    ],
    'Postmark_Date' => [
      'name' => 'Postmark_Date',
      'column_name' => 'postmark_date',
      'label' => ts('Postmark Date'),
      'data_type' => 'Date',
      'html_type' => 'Select Date',
      'is_active' => 1,
      'is_searchable' => 0,
      'is_view' => 0,
    ],
  ];
}

/**
 * Get fields for _wmf_contribution_extra.
 *
 * @return array
 */
function _wmf_civicrm_get_contribution_settlement_fields(): array {
  return [
    'settlement_date' => [
      'name' => 'settlement_date',
      'column_name' => 'settlement_date',
      'label' => ts('Settlement Date'),
      'data_type' => 'Date',
      'html_type' => 'Select Date',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_search_range' => 1,
      'is_view' => 1,
      'date_format' => 'M d, yy',
      'time_format' => 2,
      'weight' => 1,
    ],
    'settlement_currency' => [
      'name' => 'settlement_currency',
      'column_name' => 'settlement_currency',
      'label' => ts('Settlement Currency'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
      'weight' => 2,
    ],
    'settlement_batch_reference' => [
      'name' => 'settlement_batch_reference',
      'column_name' => 'settlement_batch_reference',
      'label' => ts('Settlement Batch Reference'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
      'weight' => 3,
    ],
    'settlement_batch_reversal_reference' => [
      'name' => 'settlement_batch_reversal_reference',
      'column_name' => 'settlement_batch_reversal_reference',
      'label' => ts('Settlement Batch Reference for Reversal transation'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
      'weight' => 4,
    ],
    'settled_donation_amount' => [
      'name' => 'settled_donation_amount',
      'column_name' => 'settled_donation_amount',
      'label' => 'Settled Donation Amount',
      'data_type' => 'Money',
      'html_type' => 'Text',
      'is_active' => 1,
      'weight' => 5,
    ],
    'settled_fee_amount' => [
      'name' => 'settled_fee_amount',
      'column_name' => 'settled_fee_amount',
      'label' => 'Settled Fee Amount',
      'data_type' => 'Money',
      'html_type' => 'Text',
      'is_active' => 1,
      'weight' => 6,
    ],
    'settled_reversal_amount' => [
      'name' => 'settled_reversal_amount',
      'column_name' => 'settled_reversal_amount',
      'label' => 'Settled Reversal Amount',
      'data_type' => 'Money',
      'html_type' => 'Text',
      'is_active' => 1,
      'weight' => 7,
    ],
    'settled_fee_reversal_amount' => [
      'name' => 'settled_fee_reversal_amount',
      'column_name' => 'settled_fee_reversal_amount',
      'label' => 'Settled Fee Reversal Amount',
      'data_type' => 'Money',
      'html_type' => 'Text',
      'is_active' => 1,
      'weight' => 8,
    ],
  ];
}

/**
 * Get fields for communication custom group.
 *
 * @return array
 */
function _wmf_civicrm_get_communication_fields(): array {
  return [
    'opt_in' => [
      'name' => 'opt_in',
      'column_name' => 'opt_in',
      'label' => ts('Opt In'),
      'data_type' => 'Boolean',
      'html_type' => 'Radio',
      'is_active' => 1,
      'is_searchable' => 0,
    ],
    'do_not_solicit' => [
      'name' => 'do_not_solicit',
      'column_name' => 'do_not_solicit',
      'label' => ts('Do not solicit'),
      'data_type' => 'Boolean',
      'html_type' => 'Radio',
      'is_active' => 1,
      'is_required' => 0,
      'is_searchable' => 1,
      'default_value' => 0,
    ],
    'no_direct_mail' => [
      'name' => 'no_direct_mail',
      'column_name' => 'no_direct_mail',
      'label' => ts('Exclude from direct mail'),
      'data_type' => 'Boolean',
      'html_type' => 'Radio',
      'is_active' => 1,
      'is_required' => 0,
      'is_searchable' => 1,
      'default_value' => 0,
    ],
    'no_paper_ty' => [
      'name' => 'no_paper_ty',
      'column_name' => 'no_paper_ty',
      'label' => ts('Exclude from paper receipt'),
      'help_pre' => 'No Paper Thank You',
      'data_type' => 'Boolean',
      'html_type' => 'Radio',
      'is_active' => 1,
      'is_required' => 0,
      'is_searchable' => 1,
      'default_value' => 0,
    ],
    'Employer_Name' => [
      'name' => 'Employer_Name',
      'label' => ts('Employer Name'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
    ],
    'optin_source' => [
      'name' => 'optin_source',
      'label' => ts('Opt-in Source'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
    ],
    'optin_medium' => [
      'name' => 'optin_medium',
      'label' => ts('Opt-in Medium'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
    ],
    'optin_campaign' => [
      'name' => 'optin_campaign',
      'label' => ts('Opt-in Campaign'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
    ],
    'first_name_phonetic' => [
      'name' => 'first_name_phonetic',
      'label' => 'First name phonetic',
      'data_type' => 'String',
      'html_type' => 'Text',
      'help_pre' => 'Phonetic version of first name field',
      'column_name' => 'first_name_phonetic',
      'is_active' => 1,
      'is_searchable' => 1,
    ],
    'last_name_phonetic' => [
      'name' => 'last_name_phonetic',
      'label' => 'Last name phonetic',
      'data_type' => 'String',
      'html_type' => 'Text',
      'help_pre' => 'Phonetic version of last name field',
      'column_name' => 'last_name_phonetic',
      'is_active' => 1,
      'is_searchable' => 1,
    ],
    'last_donor_portal_login' => [
      'name' => 'last_donor_portal_login',
      'label' => 'Last donor portal login',
      'data_type' => 'Date',
      'html_type' => 'Select Date',
      'date_format' => 'M d, yy',
      'time_format' => 2,
      'column_name' => 'last_donor_portal_login',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 1,
    ],
  ];
}

/**
 * Get fields for stock info
 *
 * @return array[]
 */
function _wmf_civicrm_get_stock_fields(): array {
  return [
    'Stock Quantity' => [
      'name' => 'Stock Quantity',
      'column_name' => 'stock_qty',
      'label' => ts('Stock Quantity'),
      'data_type' => 'Int',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 0,
    ],
    'Stock Ticker' => [
      'name' => 'Stock Ticker',
      'column_name' => 'stock_ticker',
      'label' => ts('Stock Ticker'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 0,
    ],
    'Description_of_Stock' => [
      'name' => 'Description_of_Stock',
      'column_name' => 'description_of_stock',
      'label' => ts('Description of Stock'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 0,
    ],
    'Stock Value' => [
      'name' => 'Stock Value',
      'column_name' => 'stock_value',
      'label' => ts('Stock Value'),
      'data_type' => 'Money',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_searchable' => 1,
      'is_view' => 0,
    ],
  ];
}

/**
 * Get fields for organization_contact info
 *
 * @return array[]
 */
function _wmf_civicrm_get_organization_contact_fields(): array {
  return [
    'Name' => [
      'name' => 'Name',
      'label' => ts('Org contact Name'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_required' => 0,
      'is_searchable' => 1,
      'is_view' => 0,
    ],
    'Title' => [
      'name' => 'Title',
      'label' => ts('Org contact Title'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_required' => 0,
      'is_searchable' => 0,
      'is_view' => 0,
    ],
    'Email' => [
      'name' => 'Email',
      'label' => ts('Org contact Email'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_required' => 0,
      'is_searchable' => 1,
      'is_view' => 0,
    ],
    'Phone' => [
      'name' => 'Phone',
      'label' => ts('Org contact Phone'),
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_active' => 1,
      'is_required' => 0,
      'is_searchable' => 0,
      'is_view' => 0,
    ],
  ];
}

/**
 * Get fields from prospect custom group.
 *
 * @return array
 */
function _wmf_civicrm_get_benefactor_fields(): array {
  return [
    'Listed_as_Anonymous' => [
      'name' => 'Listed_as_Anonymous',
      'label' => 'Listed as',
      'data_type' => 'String',
      'html_type' => 'Select',
      'default_value' => 'not_replied',
      'is_searchable' => 1,
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
      'option_values' => [
        ['name' => 'Anonymous', 'label' => 'Anonymous', 'value' => 'anonymous'],
        ['name' => 'Not_replied', 'label' => 'Not replied', 'value' => 'not_replied'],
        ['name' => 'Public', 'label' => 'Public', 'value' => 'public'],
      ],
    ],
    'Listed_on_Benefactor_Page_as' => [
      'name' => 'Listed_on_Benefactor_Page_as',
      'label' => 'Listed on Benefactor Page as',
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_searchable' => 1,
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
    ],
    'Benefactor_order_as' => [
      'name' => 'Benefactor_order_as',
      'label' => 'Benefactor order as',
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_searchable' => 1,
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
    ],
    'Endowment_Site_Listed_as' => [
      'name' => 'Endowment_Site_Listed_as',
      'label' => 'Endowment Site Listed as',
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_searchable' => 1,
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
    ],
    'WLS_Listed_as' => [
      'name' => 'WLS_Listed_as',
      'label' => 'WLS Listed as',
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_searchable' => 1,
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
      'help_pre' => "How donor has chosen to be listed publicly anywhere there is a Legacy listing.",
      'help_post' => "How donor has chosen to be listed publicly anywhere there is a Legacy listing.",
    ],
    'Benefactor_Page_Last_Updated' => [
      'name' => 'Benefactor_Page_Last_Updated',
      'label' => 'Benefactor Page Last Updated',
      'data_type' => 'Date',
      'html_type' => 'Select Date',
      'text_length' => 255,
      'date_format' => 'mm/dd/yy',
    ],
    'wls_listing_last_updated' => [
      'name' => 'wls_listing_last_updated',
      'column_name' => 'wls_listing_last_updated',
      'label' => 'WLS Listing Last Updated',
      'data_type' => 'Date',
      'html_type' => 'Select Date',
      'text_length' => 255,
      'date_format' => 'mm/dd/yy',
    ],
    'endowment_listing_last_updated' => [
      'name' => 'endowment_listing_last_updated',
      'column_name' => 'endowment_listing_last_updated',
      'label' => 'Endowment Listing Last Updated',
      'data_type' => 'Date',
      'html_type' => 'Select Date',
      'text_length' => 255,
      'date_format' => 'mm/dd/yy',
    ],
    'Endowment_Level' => [
      'name' => 'Endowment_Level',
      'label' => 'Endowment Level',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => 1,
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
      'option_values' => [
        "1" => "$5m+",
        "2" => "$1m+",
        "3" => "$100k+",
        "4" => "$50k+",
        "5" => "$5k+",
        "6" => "$1k+",
      ],
    ],
    'Benefactor_Level' => [
      'name' => 'Benefactor_Level',
      'label' => 'Benefactor Level',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => 1,
      'text_length' => 255,
      'note_columns' => 60,
      'note_rows' => 4,
      'option_values' => [
        ['name' => 'Major_Benefactor_50k_', 'label' => 'Major Benefactor ($50k+)', 'value' => '1'],
        ['name' => 'Patron_Donors_15k_49_999_', 'label' => 'Patron Donors ($15k-49,999)', 'value' => '2'],
        ['name' => 'Leading_Donors_5k_14_999_', 'label' => 'Leading Donors ($5k-$14,999)', 'value' => '3'],
        ['name' => 'Sustaining_Donor_1k_4_999', 'label' => 'Sustaining Donor ($1k-$4,999)', 'value' => '4'],
      ],
    ],
  ];
}

function _wmf_civicrm_get_relationship_metadata_fields(): array {
  return [
    'provided_by_donor' => [
      'name' => 'provided_by_donor',
      'column_name' => 'provided_by_donor',
      'label' => 'Provided by donor',
      'help_pre' => '"Yes" means the donor provided this information to us (usually on the donation form)',
      'help_post' => 'For employer relationships, "Yes" will trigger automatic matching gifts emails',
      'data_type' => 'Boolean',
      'html_type' => 'Radio',
      'default_value' => 0,
    ],
  ];
}

function _wmf_civicrm_get_assistant_fields(): array {
  return [
    // typo is on prod
    'Assitant_Name' => [
      'name' => 'Assitant_Name',
      'label' => 'Assistant Name & Title',
      'data_type' => 'String',
      'html_type' => 'Text',
      'column_name' => 'assitant_name_70',
      'is_searchable' => TRUE,
    ],
    'Assistant_Contact' => [
      'name' => 'Assistant_Contact',
      'label' => 'Assistant Contact',
      'data_type' => 'String',
      'html_type' => 'Text',
      'text_length' => 255,
      'column_name' => 'email_71',
      'is_searchable' => TRUE,
    ],

    'Assistant_Phone_Number' => [
      'name' => 'Assistant_Phone_Number',
      'label' => 'Assistant Phone Number',
      'data_type' => 'String',
      'html_type' => 'Text',
      'is_searchable' => FALSE,
      'text_length' => 255,
      'column_name' => 'assistant_phone_number_135',
    ],
    'Assistant_Email' => [
      'name' => 'Assistant_Email',
      'label' => 'Assistant Email',
      'html_type' => 'Text',
      'data_type' => 'String',
      'is_searchable' => TRUE,
      'text_length' => 255,
      'column_name' => 'assistant_email_287',
    ],
  ];
}

function _wmf_civicrm_get_mg_year_end_appeal_fields(): array {
  return [
    'Appeal_Ask_Amount' => [
      'name' => 'Appeal_Ask_Amount',
      'label' => 'Appeal Ask Amount',
      'data_type' => 'Money',
      'html_type' => 'Text',
      'is_required' => TRUE,
      'is_searchable' => TRUE,
      'text_length' => 255,
      'is_search_range' => TRUE,
      'weight' => 2,
      'column_name' => 'appeal_ask_amount_303',
    ],
    'Solicitor' => [
      'name' => 'Solicitor',
      'label' => 'Relationship Manager',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => TRUE,
      'weight' => 6,
      'text_length' => 255,
      'column_name' => 'solicitor_305',
      'option_values' => _wmf_civicrm_get_solicitor_values(),
    ],
    'Appeal_Type' => [
      'name' => 'Appeal_Type',
      'label' => 'Appeal Type',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_required' => TRUE,
      'is_searchable' => TRUE,
      'weight' => 9,
      'text_length' => 255,
      'column_name' => 'appeal_type_309',
      'option_values' => [
        '1' => 'Letter',
        '2' => 'Email',
      ],
    ],
  ];
}

function _wmf_civicrm_get_endowment_year_end_appeal_fields(): array {
  return [
    'Appeal_Ask_Amount' => [
      'name' => 'Appeal_Ask_Amount',
      'label' => 'Appeal Ask Amount',
      'data_type' => 'Money',
      'html_type' => 'Text',
      'is_required' => TRUE,
      'is_searchable' => TRUE,
      'is_search_range' => TRUE,
      'weight' => 3,
      'text_length' => 255,
      'column_name' => 'appeal_ask_amount_304',
    ],
    'Solicitor' => [
      'name' => 'Solicitor',
      'label' => 'Relationship Manager',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_searchable' => TRUE,
      'weight' => 7,
      'text_length' => 255,
      'column_name' => 'solicitor_306',
      'option_values' => _wmf_civicrm_get_solicitor_values(),
    ],
    'Appeal_Type' => [
      'name' => 'Appeal_Type',
      'label' => 'Appeal Type',
      'data_type' => 'String',
      'html_type' => 'Select',
      'is_required' => TRUE,
      'is_searchable' => TRUE,
      'weight' => 10,
      'column_name' => 'appeal_type_307',
      'option_values' => [
        '1' => 'Letter',
        '2' => 'Email',
      ],
    ],
  ];
}

function _wmf_civicrm_get_solicitor_values(): array {
  return [
    '1' => 'Sue Gardner',
    '2' => 'Jimmy Wales',
    '3' => 'Lila Tretikov',
    '4' => 'Katherine Maher',
    '5' => 'Maryana Iskander',
    '6' => 'General',
  ];
}

function _wmf_civicrm_get_activity_tracking_fields(): array {
  return [
    'activity_campaign' => [
      'name' => 'activity_campaign',
      'label' => 'Campaign from URL',
      'html_type' => 'Text',
      'data_type' => 'String',
      'is_searchable' => TRUE,
      'text_length' => 255,
      'column_name' => 'campaign',
      'is_view' => 1,
    ],
    'activity_medium' => [
      'name' => 'activity_medium',
      'label' => 'Medium from URL',
      'html_type' => 'Text',
      'data_type' => 'String',
      'is_searchable' => TRUE,
      'text_length' => 255,
      'column_name' => 'medium',
      'is_view' => 1,
    ],
    'activity_source' => [
      'name' => 'activity_source',
      'label' => 'Source from URL',
      'html_type' => 'Text',
      'data_type' => 'String',
      'is_searchable' => TRUE,
      'text_length' => 255,
      'column_name' => 'source',
      'is_view' => 1,
    ],
    'activity_is_from_donor_portal' => [
      'name' => 'activity_is_from_donor_portal',
      'label' => 'Is from Donor Portal',
      'description' => 'True if the activity was initiated by the donor at the donor portal or email preferences page',
      'html_type' => 'Radio',
      'data_type' => 'Boolean',
      'is_searchable' => TRUE,
      'column_name' => 'is_from_donor_portal',
      'default_value' => 0,
      'is_view' => 1,
    ]
  ];
}

function _wmf_civicrm_get_phone_data_fields(): array {
  return [
    'phone_source' => [
      'name' => 'phone_source',
      'label' => 'Source',
      'html_type' => 'Select',
      'data_type' => 'String',
      'text_length' => 255,
      'column_name' => 'source',
      'option_values' => [
        ['name' => 'Acoustic', 'label' => 'Acoustic', 'value' => 'Acoustic'],
        ['name' => 'Staff_Supplied', 'label' => 'Staff Supplied', 'value' => 'Staff'],
        ['name' => 'Donor_Supplied', 'label' => 'Donor Supplied', 'value' => 'Donor'],
        ['name' => 'PayPal_Account', 'label' => 'PayPal Account', 'value' => 'Paypal'],
        ['name' => 'Fundraise_Up', 'label' => 'Fundraise Up', 'value' => 'FundraiseUp'],
        ['name' => 'Venmo', 'label' => 'Venmo', 'value' => 'Venmo'],
      ],
    ],
    'recipient_id' => [
      'name' => 'recipient_id',
      'label' => 'Acoustic recipient ID',
      'data_type' => 'Float',
      'html_type' => 'Text',
      'is_searchable' => TRUE,
      'column_name' => 'recipient_id',
    ],
    'phone_update_date' => [
      'name' => 'phone_update_date',
      'label' => 'Update date',
      'data_type' => 'Date',
      'html_type' => 'Select Date',
      'text_length' => 255,
      'date_format' => 'yy-mm-dd',
      'note_columns' => 60,
      'note_rows' => 4,
      'column_name' => 'update_date',
    ],
  ];
}

function _wmf_civicrm_get_address_data_fields(): array {
  return [
    'address_source' => [
      'name' => 'address_source',
      'label' => 'Source',
      'html_type' => 'Select',
      'data_type' => 'String',
      'text_length' => 255,
      'column_name' => 'source',
      'option_values' => [
        ['name' => 'NCOA_update', 'label' => 'NCOA Update', 'value' => 'ncoa', 'description' => 'National change of address through USPS'],
        ['name' => 'Staff_Supplied', 'label' => 'Staff Supplied', 'value' => 'staff'],
        ['name' => 'iWave', 'label' => 'iWave', 'value' => 'iwave'],
        ['name' => 'Donor_Supplied', 'label' => 'Donor Supplied', 'value' => 'donor'],
        ['name' => 'USPS_returned_mail', 'label' => 'USPS returned mail', 'value' => 'USPS returned mail', 'description' => 'Address information was updated based on information provided on a returned envelope from USPS'],
        ['name' => 'paypal', 'label' => 'PayPal', 'value' => 'paypal'],
        ['name' => 'fundraiseup', 'label' => 'Fundraise Up', 'value' => 'fundraiseup'],
      ],
    ],
    'address_update_date' => [
      'name' => 'address_update_date',
      'label' => 'Update date',
      'data_type' => 'Date',
      'html_type' => 'Select Date',
      'text_length' => 255,
      'date_format' => 'yy-mm-dd',
      'note_columns' => 60,
      'note_rows' => 4,
      'column_name' => 'update_date',
    ],
  ];
}

function _wmf_civicrm_get_donor_advised_fields(): array {
  return [
    'owns_donor_advised_for' => [
      'name' => 'owns_donor_advised_for',
      'label' => 'Owns the Donor Advised Fund',
      'html_type' => 'Autocomplete-Select',
      'data_type' => 'EntityReference',
      'text_length' => 255,
      'column_name' => 'owns_donor_advised_for',
      'filter' => 'contact_type=Organization',
      'fk_entity' => 'Contact',
    ],
  ];
}

function _wmf_civicrm_get_direct_mail_fields(): array {
  return [
    'direct_mail_appeal' => [
      'name' => 'direct_mail_appeal',
      'label' => 'Direct Mail Appeal',
      'html_type' => 'Text',
      'data_type' => 'String',
      'text_length' => 255,
      'column_name' => 'direct_mail_appeal',
    ],
    'direct_mail_package' => [
      'name' => 'direct_mail_package',
      'label' => 'Direct Mail Package',
      'html_type' => 'Text',
      'data_type' => 'String',
      'text_length' => 255,
      'column_name' => 'direct_mail_package',
    ],
  ];
}

function _wmf_civicrm_get_gift_information_fields(): array {
  return [
    'import_batch_number' => [
      'name' => 'import_batch_number',
      'label' => 'Batch Number',
      'html_type' => 'Text',
      'data_type' => 'String',
      'text_length' => 255,
      'column_name' => 'import_batch_number',
      'is_searchable' => TRUE,
    ],
  ];
}

/**
 * Get fields for batch data custom group.
 *
 * @return array
 */
function _wmf_civicrm_get_batch_data_fields(): array {
  return [
    'settlement_date' => [
      'name' => 'settlement_date',
      'column_name' => 'settlement_date',
      'label' => 'Settlement Date',
      'data_type' => 'Date',
      'html_type' => 'Select Date',
      'date_format' => 'yy-mm-dd',
      'is_active' => 1,
      'weight' => 1,
    ],
    'settlement_currency' => [
      'name' => 'settlement_currency',
      'column_name' => 'settlement_currency',
      'label' => 'Settlement Currency',
      'data_type' => 'String',
      'html_type' => 'Text',
      'text_length' => 3,
      'weight' => 2,
    ],
    'settlement_gateway' => [
      'name' => 'settlement_gateway',
      'column_name' => 'settlement_gateway',
      'label' => 'Settlement Gateway',
      'data_type' => 'String',
      'html_type' => 'Text',
      'text_length' => 32,
      'is_active' => 1,
      'weight' => 3,
    ],
    'settled_fee_amount' => [
      'name' => 'settled_fee_amount',
      'column_name' => 'settled_fee_amount',
      'label' => 'Settled Fee Amount',
      'data_type' => 'Money',
      'html_type' => 'Text',
      'is_active' => 1,
      'weight' => 4,
    ],
    'settled_reversal_amount' => [
      'name' => 'settled_reversal_amount',
      'column_name' => 'settled_reversal_amount',
      'label' => 'Settled Reversal Amount',
      'data_type' => 'Money',
      'html_type' => 'Text',
      'is_active' => 1,
      'weight' => 5,
    ],
    'settled_net_amount' => [
      'name' => 'settled_net_amount',
      'column_name' => 'settled_net_amount',
      'label' => 'Settled Net Amount',
      'data_type' => 'Money',
      'html_type' => 'Text',
      'is_active' => 1,
      'weight' => 6,
    ],
    'settled_donation_amount' => [
      'name' => 'settled_donation_amount',
      'column_name' => 'settled_donation_amount',
      'label' => 'Settled Donation Amount',
      'data_type' => 'Money',
      'html_type' => 'Text',
      'is_active' => 1,
      'weight' => 7,
    ],
    'issue_tracker_reference' => [
      'name' => 'issue_tracker_reference',
      'column_name' => 'issue_tracker_reference',
      'label' => 'Phab',
      'data_type' => 'String',
      'html_type' => 'Text',
      'text_length' => 32,
      'weight' => 8,
    ],
    'issue_category' => [
      'name' => 'issue_category',
      'column_name' => 'issue_category',
      'label' => 'Issue Category',
      'data_type' => 'String',
      'html_type' => 'Select',
      'weight' => 9,
      'option_values' => [
        'every.org' => 'Every.org',
        'paypal_grants' => 'PayPal Grants',
      ],
    ],
    'issue_notes' => [
      'name' => 'issue_notes',
      'column_name' => 'issue_notes',
      'label' => 'Issue Notes',
      'data_type' => 'Memo',
      'html_type' => 'TextArea',
      'weight' => 10,
    ],
    'last_successful_validation_date' => [
      'name' => 'last_successful_validation_date',
      'column_name' => 'last_successful_validation_date',
      'label' => 'Last successfully validated at',
      'data_type' => 'Date',
      'html_type' => 'Select Date',
      'weight' => 11,
    ],
  ];
}
