<?php

use CRM_Wmf_ExtensionUtil as E;

$navigation = [
  [
    'name' => 'Navigation_WMF-admin',
    'entity' => 'Navigation',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('WMF Administration'),
        'name' => 'WMF-admin',
        'url' => '',
        'icon' => NULL,
        'permission' => 'administer CiviCRM',
        'permission_operator' => 'AND',
        'parent_id.name' => 'Administer',
        'is_active' => TRUE,
        'weight' => 1,
        'has_separator' => NULL,
        'domain_id' => 'current_domain',
      ],
    ],
  ],
  [
    'name' => 'Navigation_WMF_Navigation_Donor_Segments',
    'entity' => 'Navigation',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Donor segments & statuses'),
        'name' => 'donor_segments',
        'url' => 'civicrm/wmf-segment',
        'icon' => NULL,
        'permission' => 'access CiviCRM',
        'permission_operator' => 'AND',
        'parent_id.name' => 'Reports',
        'is_active' => TRUE,
        'weight' => 1,
        'has_separator' => NULL,
        'domain_id' => 'current_domain',
      ],
    ],
  ],
  [
    'name' => 'Navigation_WMF_Configuration',
    'entity' => 'Navigation',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('WMF configuration'),
        'name' => 'wmf_configuration',
        'url' => 'civicrm/admin/setting/wmf-civicrm',
        'icon' => NULL,
        'permission' => 'administer CiviCRM',
        'permission_operator' => 'AND',
        'parent_id.name' => 'WMF-admin',
        'is_active' => TRUE,
        'weight' => 1,
        'has_separator' => NULL,
        'domain_id' => 'current_domain',
      ],
    ],
  ],
  [
    'name' => 'Navigation_WMF_Queue_Configuration',
    'entity' => 'Navigation',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('WMF Queue configuration'),
        'name' => 'wmf_queue_configuration',
        'url' => 'civicrm/admin/setting/wmf-queue',
        'icon' => NULL,
        'permission' => 'administer queues',
        'permission_operator' => 'AND',
        'parent_id.name' => 'WMF-admin',
        'is_active' => TRUE,
        'weight' => 2,
        'has_separator' => NULL,
        'domain_id' => 'current_domain',
      ],
    ],
  ],
  [
    'name' => 'Navigation_WMF_Audit_Configuration',
    'entity' => 'Navigation',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('WMF Audit configuration'),
        'name' => 'wmf_audit_configuration',
        'url' => 'civicrm/admin/setting/wmf-audit',
        'icon' => NULL,
        'permission' => 'administer queues',
        'permission_operator' => 'AND',
        'parent_id.name' => 'WMF-admin',
        'is_active' => TRUE,
        'weight' => 2,
        'has_separator' => NULL,
        'domain_id' => 'current_domain',
      ],
    ],
  ],
  [
    'name' => 'Navigation_WMF_Zendesk_Configuration',
    'entity' => 'Navigation',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('WMF Zendesk configuration'),
        'name' => 'wmf_zendesk_configuration',
        'url' => 'civicrm/admin/setting/zendesk',
        'icon' => NULL,
        'permission' => 'administer CiviCRM system',
        'permission_operator' => 'AND',
        'parent_id.name' => 'WMF-admin',
        'is_active' => TRUE,
        'weight' => 2,
        'has_separator' => NULL,
        'domain_id' => 'current_domain',
      ],
    ],
  ],
  // The below entries are duplicate menu items
  // where the extension has already created them
  // in a generic place but we ALSO add to our super special
  // menu.
  [
    'name' => 'Navigation_WMF_SmashPig_Configuration',
    'entity' => 'Navigation',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('SmashPig Settings'),
        'name' => 'wmf_smash_pig_configuration',
        'url' => 'civicrm/settings/smashpig',
        'icon' => NULL,
        'permission' => 'administer queues',
        'permission_operator' => 'AND',
        'parent_id.name' => 'WMF-admin',
        'is_active' => TRUE,
        'weight' => 3,
        'has_separator' => NULL,
        'domain_id' => 'current_domain',
      ],
    ],
  ],
  [
    'name' => 'Navigation_WMF_Damaged',
    'entity' => 'Navigation',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Damaged Messages'),
        'name' => 'wmf_damaged',
        'url' => 'civicrm/damaged',
        'icon' => NULL,
        'permission' => 'administer queues',
        'permission_operator' => 'AND',
        'parent_id.name' => 'WMF-admin',
        'is_active' => TRUE,
        'weight' => 10,
        'has_separator' => NULL,
        'domain_id' => 'current_domain',
      ],
    ],
  ],
  [
    'name' => 'Navigation_WMF_Deduper_Configuration',
    'entity' => 'Navigation',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Deduper Settings'),
        'name' => 'wmf_deduper_configuration',
        'url' => 'civicrm/admin/setting/deduper',
        'icon' => NULL,
        'permission' => 'administer CiviCRM',
        'permission_operator' => 'AND',
        'parent_id.name' => 'WMF-admin',
        'is_active' => TRUE,
        'weight' => 20,
        'has_separator' => NULL,
        'domain_id' => 'current_domain',
      ],
    ],
  ],
  [
    'name' => 'Navigation_WMF_Deduper',
    'entity' => 'Navigation',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Deduper'),
        'name' => 'wmf_deduper',
        'url' => 'civicrm/a/#/dupefinder/Contact',
        'icon' => NULL,
        'permission' => 'administer CiviCRM',
        'permission_operator' => 'AND',
        'parent_id.name' => 'WMF-admin',
        'is_active' => TRUE,
        'weight' => 30,
        'has_separator' => NULL,
        'domain_id' => 'current_domain',
      ],
    ],
  ],
  [
    'name' => 'Navigation_WMF_Search_Kit',
    'entity' => 'Navigation',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Search Kit'),
        'name' => 'wmf_search_kit',
        'url' => 'civicrm/admin/search#/list',
        'icon' => NULL,
        'permission' => 'administer CiviCRM',
        'permission_operator' => 'AND',
        'parent_id.name' => 'WMF-admin',
        'is_active' => TRUE,
        'weight' => 40,
        'has_separator' => NULL,
        'domain_id' => 'current_domain',
      ],
    ],
  ],
  [
    'name' => 'Navigation_WMF_Import_Templates',
    'entity' => 'Navigation',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Import Templates'),
        'name' => 'wmf_import_templates',
        'url' => 'civicrm/imports/templates',
        'icon' => NULL,
        'permission' => 'administer CiviCRM',
        'permission_operator' => 'AND',
        'parent_id.name' => 'WMF-admin',
        'is_active' => TRUE,
        'weight' => 50,
        'has_separator' => NULL,
        'domain_id' => 'current_domain',
      ],
    ],
  ],
  [
    'name' => 'Navigation_WMF_Imports',
    'entity' => 'Navigation',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Imports'),
        'name' => 'wmf_imports',
        'url' => 'civicrm/imports/templates',
        'icon' => NULL,
        'permission' => 'administer queues',
        'permission_operator' => 'AND',
        'parent_id.name' => 'WMF-admin',
        'is_active' => TRUE,
        'weight' => 60,
        'has_separator' => NULL,
        'domain_id' => 'current_domain',
      ],
    ],
  ],
  [
    'name' => 'Navigation_WMF_Legacy_Import',
    'entity' => 'Navigation',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Legacy Imports'),
        'name' => 'wmf_legacy_import',
        'url' => 'admin/import_checks',
        'icon' => NULL,
        'permission' => 'administer CiviCRM',
        'permission_operator' => 'AND',
        'parent_id.name' => 'WMF-admin',
        'is_active' => TRUE,
        'weight' => 65,
        'has_separator' => NULL,
        'domain_id' => 'current_domain',
      ],
    ],
  ],
  [
    'name' => 'Navigation_WMF_Segments',
    'entity' => 'Navigation',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Donor Segments and Statuses'),
        'name' => 'wmf_donor_status',
        'url' => 'civicrm/wmf-segment',
        'icon' => NULL,
        'permission' => 'administer CiviCRM',
        'permission_operator' => 'AND',
        'parent_id.name' => 'WMF-admin',
        'is_active' => TRUE,
        'weight' => 70,
        'has_separator' => NULL,
        'domain_id' => 'current_domain',
      ],
    ],
  ],
  [
    'name' => 'Navigation_WMF_API',
    'entity' => 'Navigation',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('API Explorer (v4)'),
        'name' => 'wmf_api',
        'url' => 'civicrm/api4#explorer',
        'icon' => NULL,
        'permission' => 'administer CiviCRM',
        'permission_operator' => 'AND',
        'parent_id.name' => 'WMF-admin',
        'is_active' => TRUE,
        'weight' => 80,
        'has_separator' => NULL,
        'domain_id' => 'current_domain',
      ],
    ],
  ],
  [
    'name' => 'Navigation_WMF_Caches',
    'entity' => 'Navigation',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Flush Caches'),
        'name' => 'wmf_cache',
        'url' => 'civicrm/admin/setting/updateConfigBackend?reset=1',
        'icon' => NULL,
        'permission' => 'administer CiviCRM',
        'permission_operator' => 'AND',
        'parent_id.name' => 'WMF-admin',
        'is_active' => TRUE,
        'weight' => 100,
        'has_separator' => NULL,
        'domain_id' => 'current_domain',
      ],
    ],
  ],
  [
    'name' => 'Navigation_WMF_Debug',
    'entity' => 'Navigation',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Debug Settings'),
        'name' => 'wmf_debug',
        'url' => 'civicrm/admin/setting/debug?reset=1',
        'icon' => NULL,
        'permission' => 'administer CiviCRM',
        'permission_operator' => 'AND',
        'parent_id.name' => 'WMF-admin',
        'is_active' => TRUE,
        'weight' => 110,
        'has_separator' => NULL,
        'domain_id' => 'current_domain',
      ],
    ],
  ],
  [
    'name' => 'Navigation_WMF_Documentation_CiviCRM_Developer',
    'entity' => 'Navigation',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Developer Docs (CiviCRM)'),
        'name' => 'wmf_documentation_civicrm',
        'url' => 'https://docs.civicrm.org/dev/en/latest/?src=iam',
        'icon' => NULL,
        'permission' => 'administer queues',
        'permission_operator' => 'AND',
        'parent_id.name' => 'WMF-admin',
        'is_active' => TRUE,
        'weight' => 150,
        'has_separator' => NULL,
        'domain_id' => 'current_domain',
      ],
    ],
  ],
  [
    'name' => 'Navigation_WMF_Documentation_CiviCRM_FR_Tech',
    'entity' => 'Navigation',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('FR-Tech Docs'),
        'name' => 'wmf_documentation_fr_tech',
        'url' => 'https://wikitech.wikimedia.org/wiki/Fundraising/Internal-facing/CiviCRM',
        'icon' => NULL,
        'permission' => 'administer queues',
        'permission_operator' => 'AND',
        'parent_id.name' => 'WMF-admin',
        'is_active' => TRUE,
        'weight' => 160,
        'has_separator' => NULL,
        'domain_id' => 'current_domain',
      ],
    ],
  ],
];

if (Civi::settings()->get('environment') === 'Development') {
  $navigation[] = [
    'name' => 'Navigation_Mail catcher',
    'entity' => 'Navigation',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Mail catcher'),
        'name' => 'wmf_dev_mail_catcher',
        'url' => 'http://wmff.localhost:1080/',
        'icon' => NULL,
        'permission' => 'administer CiviCRM',
        'permission_operator' => 'AND',
        'parent_id.name' => 'Administer',
        'is_active' => TRUE,
        'weight' => 1,
        'has_separator' => NULL,
        'domain_id' => 'current_domain',
      ],
    ],
  ];
}
return $navigation;
