<?php
use CRM_Wmf_ExtensionUtil as E;
return [
  [
    'name' => 'SavedSearch_WMFMessageFields',
    'entity' => 'SavedSearch',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'WMFMessageFields',
        'label' => E::ts('WMFMessageFields'),
        'api_entity' => 'WMFMessageField',
        'api_params' => [
          'version' => 4,
          'select' => [
            'name',
            'title',
            'description',
            'api_entity',
            'api_field',
            'mapped_to',
            'comment',
            'data_type',
            'used_for',
            'notes',
          ],
          'orderBy' => [],
          'where' => [],
        ],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'SavedSearch_WMFMessageFields_SearchDisplay_WMFMessageFields',
    'entity' => 'SearchDisplay',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'WMFMessageFields',
        'label' => E::ts('WMFMessageFields'),
        'saved_search_id.name' => 'WMFMessageFields',
        'type' => 'table',
        'settings' => [
          'description' => E::ts(NULL),
          'sort' => [],
          'limit' => 50,
          'pager' => [],
          'placeholder' => 5,
          'columns' => [
            [
              'type' => 'field',
              'key' => 'name',
              'dataType' => 'String',
              'label' => E::ts('Name'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'title',
              'dataType' => 'String',
              'label' => E::ts('Title'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'description',
              'dataType' => 'String',
              'label' => E::ts('Description'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'api_entity',
              'dataType' => 'String',
              'label' => E::ts('Api Entity'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'api_field',
              'dataType' => 'String',
              'label' => E::ts('Api Field'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'mapped_to',
              'dataType' => 'String',
              'label' => E::ts('Mapped To'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'comment',
              'dataType' => 'String',
              'label' => E::ts('Comment'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'data_type',
              'dataType' => 'String',
              'label' => E::ts('Data Type'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'used_for',
              'dataType' => 'String',
              'label' => E::ts('Used For'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'notes',
              'dataType' => 'String',
              'label' => E::ts('Notes'),
              'sortable' => TRUE,
            ],
          ],
          'actions' => TRUE,
          'classes' => ['table', 'table-striped'],
          'actions_display_mode' => 'menu',
        ],
      ],
      'match' => [
        'saved_search_id',
        'name',
      ],
    ],
  ],
];
