<?php
use CRM_Wmf_ExtensionUtil as E;
return [
  [
    'name' => 'SavedSearch_Batch_entry_General_',
    'entity' => 'SavedSearch',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Batch_entry_General_',
        'label' => E::ts('Batch entry (General)'),
        'api_entity' => 'Contribution',
        'api_params' => [
          'version' => 4,
          'select' => [
            'contact_id',
            'contribution_status_id:label',
            'financial_type_id:label',
            'total_amount',
            'source',
            'receive_date',
            'payment_instrument_id:label',
            'Gift_Data.Fund:label',
            'Gift_Data.Donor_Specified:label',
            'Gift_Data.Channel:label',
            'Gift_Data.Campaign:label',
            'Gift_Data.Appeal:label',
            'contribution_extra.gateway',
            'contribution_extra.gateway_account',
            'contribution_extra.no_thank_you',
            'contribution_settlement.settlement_batch_reference',
            'Gift_Information.import_batch_number',
            'Adjustment.Date',
            'Adjustment.Notes',
            'Adjustment.Reason:label',
            'Contribution_ContributionSoft_contribution_id_01.contact_id',
            'Contribution_ContributionSoft_contribution_id_01.soft_credit_type_id:label',
          ],
          'orderBy' => [],
          'where' => [],
          'groupBy' => [],
          'join' => [
            [
              'ContributionSoft AS Contribution_ContributionSoft_contribution_id_01',
              'LEFT',
              [
                'id',
                '=',
                'Contribution_ContributionSoft_contribution_id_01.contribution_id',
              ],
            ],
          ],
          'having' => [],
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'SavedSearch_Batch_entry_General_SearchDisplay_Batch_entry_General_',
    'entity' => 'SearchDisplay',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Batch_entry_General_',
        'label' => E::ts('Batch entry (General)'),
        'saved_search_id.name' => 'Batch_entry_General_',
        'type' => 'batch',
        'settings' => [
          'classes' => [
            'table',
            'table-striped',
            'table-bordered',
            'crm-sticky-header',
          ],
          'pager' => [
            'show_count' => FALSE,
            'expose_limit' => TRUE,
            'hide_single' => TRUE,
          ],
          'columns' => [
            [
              'type' => 'field',
              'key' => 'contact_id',
              'label' => 'Contact ID',
              'spec' => [
                'name' => 'contact_id',
                'data_type' => 'Integer',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'contact_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'EntityRef',
                'entity_reference' => [
                  'entity' => 'Contact',
                  'key' => 'id',
                  'on_delete' => 'CASCADE',
                ],
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => NULL,
              ],
              'required' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'contribution_status_id:label',
              'label' => 'Contribution Status',
              'default' => 1,
              'spec' => [
                'name' => 'contribution_status_id',
                'data_type' => 'Integer',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'contribution_status_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => 1,
              ],
            ],
            [
              'type' => 'field',
              'key' => 'contribution_settlement.settlement_batch_reference',
              'label' => 'Finance Batch',
              'spec' => [
                'name' => 'contribution_settlement.settlement_batch_reference',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'contribution_settlement.settlement_batch_reference',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
              ],
            ],
            [
              'type' => 'field',
              'key' => 'Gift_Information.import_batch_number',
              'label' => 'Batch Number',
              'spec' => [
                'name' => 'Gift_Information_import_batch_number',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'Gift_Information.import_batch_number',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
              ],
            ],
            [
              'type' => 'field',
              'key' => 'financial_type_id:label',
              'label' => 'Financial Type',
              'spec' => [
                'name' => 'financial_type_id',
                'data_type' => 'Integer',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'financial_type_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => [
                  'entity' => 'FinancialType',
                  'key' => 'id',
                ],
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => 9,
              ],
              'required' => TRUE,
              'default' => 9,
            ],
            [
              'type' => 'field',
              'key' => 'total_amount',
              'label' => 'Total Amount',
              'tally' => [
                'fn' => 'SUM',
                'target' => TRUE,
                'label' => 'Total Amount',
              ],
              'spec' => [
                'name' => 'total_amount',
                'data_type' => 'Money',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'total_amount',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'entity_reference' => NULL,
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => NULL,
              ],
              'required' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'source',
              'label' => 'Contribution Source',
              'spec' => [
                'name' => 'source',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'source',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
              ],
            ],
            [
              'type' => 'field',
              'key' => 'receive_date',
              'label' => 'Contribution Date',
              'spec' => [
                'name' => 'receive_date',
                'data_type' => 'Timestamp',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'receive_date',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select Date',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
              ],
              'format' => 'dateformatFull',
            ],
            [
              'type' => 'field',
              'key' => 'payment_instrument_id:label',
              'label' => 'Payment Method',
              'required' => TRUE,
              'spec' => [
                'name' => 'payment_instrument_id',
                'data_type' => 'Integer',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'payment_instrument_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => NULL,
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => NULL,
              ],
            ],
            [
              'type' => 'field',
              'key' => 'Contribution_ContributionSoft_contribution_id_01.contact_id',
              'label' => 'Contribution Contribution Soft Credits: Contact ID',
              'spec' => [
                'name' => 'Contribution_ContributionSoft_contribution2fcfe8c2b6254fe7',
                'data_type' => 'Integer',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'contact_id',
                'original_field_entity' => 'ContributionSoft',
                'input_type' => 'EntityRef',
                'entity_reference' => [
                  'entity' => 'Contact',
                  'key' => 'id',
                  'on_delete' => 'CASCADE',
                ],
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
              ],
            ],
            [
              'type' => 'field',
              'key' => 'Contribution_ContributionSoft_contribution_id_01.soft_credit_type_id:label',
              'label' => 'Contribution Contribution Soft Credits: Soft Credit Type',
              'spec' => [
                'name' => 'Contribution_ContributionSoft_contribution16b3265579af7863',
                'data_type' => 'Integer',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'soft_credit_type_id',
                'original_field_entity' => 'ContributionSoft',
                'input_type' => 'Select',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
              ],
            ],
            [
              'type' => 'field',
              'key' => 'Gift_Data.Fund:label',
              'label' => 'Gift Data: Fund',
              'spec' => [
                'name' => 'Gift_Data_Fund',
                'data_type' => 'String',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'Gift_Data.Fund',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => NULL,
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => 'Major Gifts - CC104',
              ],
              'required' => TRUE,
              'default' => 'Major Gifts - CC104',
            ],
            [
              'type' => 'field',
              'key' => 'Gift_Data.Channel:label',
              'label' => 'Gift Data: Channel',
              'spec' => [
                'name' => 'Gift_Data_Channel',
                'data_type' => 'String',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'Gift_Data.Channel',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => NULL,
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => 'Other Offline',
              ],
              'required' => TRUE,
              'default' => 'Other Offline',
            ],
            [
              'type' => 'field',
              'key' => 'Gift_Data.Campaign:label',
              'label' => 'Gift Type',
              'spec' => [
                'name' => 'Gift_Data_Campaign',
                'data_type' => 'String',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'Gift_Data.Campaign',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => NULL,
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => NULL,
              ],
              'required' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'Gift_Data.Appeal:label',
              'label' => 'Gift Data: Appeal',
              'spec' => [
                'name' => 'Gift_Data_Appeal',
                'data_type' => 'String',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'Gift_Data.Appeal',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => NULL,
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => 'White Mail',
              ],
              'required' => TRUE,
              'default' => 'White Mail',
            ],
            [
              'type' => 'field',
              'key' => 'contribution_extra.gateway',
              'label' => 'Gateway',
              'spec' => [
                'name' => 'contribution_extra_gateway',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'contribution_extra.gateway',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
              ],
            ],
            [
              'type' => 'field',
              'key' => 'contribution_extra.gateway_account',
              'label' => 'Gateway Account',
              'spec' => [
                'name' => 'contribution_extra_gateway_account',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'contribution_extra.gateway_account',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
              ],
            ],
            [
              'type' => 'field',
              'key' => 'contribution_extra.no_thank_you',
              'label' => 'No Thank-you Reason',
              'spec' => [
                'name' => 'contribution_extra_no_thank_you',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'contribution_extra.no_thank_you',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
              ],
            ],
            [
              'type' => 'field',
              'key' => 'Adjustment.Date',
              'label' => 'Adjustment: Date',
              'spec' => [
                'name' => 'Adjustment_Date',
                'data_type' => 'Date',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'Adjustment.Date',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select Date',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
              ],
            ],
            [
              'type' => 'field',
              'key' => 'Adjustment.Notes',
              'label' => 'Adjustment: Notes',
              'spec' => [
                'name' => 'Adjustment_Notes',
                'data_type' => 'Text',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'Adjustment.Notes',
                'original_field_entity' => 'Contribution',
                'input_type' => 'TextArea',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
              ],
            ],
            [
              'type' => 'field',
              'key' => 'Adjustment.Reason:label',
              'label' => 'Adjustment: Reason',
              'spec' => [
                'name' => 'Adjustment_Reason',
                'data_type' => 'String',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'Adjustment.Reason',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
              ],
            ],
          ],
          'tally' => [],
          'limit' => 100,
        ],
      ],
      'match' => [
        'saved_search_id',
        'name',
      ],
    ],
  ],
  [
    'name' => 'SavedSearch_Batch_entry_General_SearchDisplay_Batch_entry_General_UserJob_1',
    'entity' => 'UserJob',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('August International 1K+'),
        'end_date' => '2026-09-09 17:52:53',
        'expires_date' => '2026-09-16 17:52:53',
        'status_id' => 1,
        'job_type' => 'search_batch_import',
        'search_display_id.name' => 'Batch_entry_General_',
        'metadata' => [
          'DataSource' => [
            'table_name' => 'civicrm_tmp_d_searchbatch_fcdf43c6fe46733941fcccca8fd95a12',
            'column_headers' => [
              'Contact ID',
              'Contribution Status',
              'Batch Number',
              'Financial Type',
              'Total Amount',
              'Contribution Source',
              'Contribution Date',
              'Payment Method',
              'Contribution Contribution Soft Credits: Contact ID',
              'Contribution Contribution Soft Credits: Soft Credit Type',
              'Gift Data: Fund',
              'Gift Data: Channel',
              'Gift Type',
              'Gift Data: Appeal',
              'Gateway',
              'No Thank-you Reason',
              'Adjustment: Date',
              'Adjustment: Notes',
              'Adjustment: Reason',
            ],
            'column_specs' => [
              'contact_id' => [
                'name' => 'contact_id',
                'data_type' => 'Integer',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'contact_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'EntityRef',
                'entity_reference' => [
                  'entity' => 'Contact',
                  'key' => 'id',
                  'on_delete' => 'CASCADE',
                ],
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => NULL,
                'label' => E::ts('Contact ID'),
              ],
              'contribution_status_id' => [
                'name' => 'contribution_status_id',
                'data_type' => 'Integer',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'contribution_status_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => 1,
                'label' => E::ts('Contribution Status'),
              ],
              'Gift_Information_import_batch_number' => [
                'name' => 'Gift_Information_import_batch_number',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'Gift_Information.import_batch_number',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
                'label' => E::ts('Batch Number'),
              ],
              'financial_type_id' => [
                'name' => 'financial_type_id',
                'data_type' => 'Integer',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'financial_type_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => [
                  'entity' => 'FinancialType',
                  'key' => 'id',
                ],
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => 9,
                'label' => E::ts('Financial Type'),
              ],
              'total_amount' => [
                'name' => 'total_amount',
                'data_type' => 'Money',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'total_amount',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'entity_reference' => NULL,
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => NULL,
                'label' => E::ts('Total Amount'),
              ],
              'source' => [
                'name' => 'source',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'source',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
                'label' => E::ts('Contribution Source'),
              ],
              'receive_date' => [
                'name' => 'receive_date',
                'data_type' => 'Timestamp',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'receive_date',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select Date',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
                'label' => E::ts('Contribution Date'),
              ],
              'payment_instrument_id' => [
                'name' => 'payment_instrument_id',
                'data_type' => 'Integer',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'payment_instrument_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => NULL,
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => NULL,
                'label' => E::ts('Payment Method'),
              ],
              'Contribution_ContributionSoft_contribution2fcfe8c2b6254fe7' => [
                'name' => 'Contribution_ContributionSoft_contribution2fcfe8c2b6254fe7',
                'data_type' => 'Integer',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'contact_id',
                'original_field_entity' => 'ContributionSoft',
                'input_type' => 'EntityRef',
                'entity_reference' => [
                  'entity' => 'Contact',
                  'key' => 'id',
                  'on_delete' => 'CASCADE',
                ],
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
                'label' => E::ts('Contribution Contribution Soft Credits: Contact ID'),
              ],
              'Contribution_ContributionSoft_contribution16b3265579af7863' => [
                'name' => 'Contribution_ContributionSoft_contribution16b3265579af7863',
                'data_type' => 'Integer',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'soft_credit_type_id',
                'original_field_entity' => 'ContributionSoft',
                'input_type' => 'Select',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
                'label' => E::ts('Contribution Contribution Soft Credits: Soft Credit Type'),
              ],
              'Gift_Data_Fund' => [
                'name' => 'Gift_Data_Fund',
                'data_type' => 'String',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'Gift_Data.Fund',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => NULL,
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => 'Major Gifts - CC104',
                'label' => E::ts('Gift Data: Fund'),
              ],
              'Gift_Data_Channel' => [
                'name' => 'Gift_Data_Channel',
                'data_type' => 'String',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'Gift_Data.Channel',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => NULL,
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => 'Other Offline',
                'label' => E::ts('Gift Data: Channel'),
              ],
              'Gift_Data_Campaign' => [
                'name' => 'Gift_Data_Campaign',
                'data_type' => 'String',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'Gift_Data.Campaign',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => NULL,
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => NULL,
                'label' => E::ts('Gift Type'),
              ],
              'Gift_Data_Appeal' => [
                'name' => 'Gift_Data_Appeal',
                'data_type' => 'String',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'Gift_Data.Appeal',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => NULL,
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => 'White Mail',
                'label' => E::ts('Gift Data: Appeal'),
              ],
              'contribution_extra_gateway' => [
                'name' => 'contribution_extra_gateway',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'contribution_extra.gateway',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
                'label' => E::ts('Gateway'),
              ],
              'contribution_extra_no_thank_you' => [
                'name' => 'contribution_extra_no_thank_you',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'contribution_extra.no_thank_you',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
                'label' => E::ts('No Thank-you Reason'),
              ],
              'Adjustment_Date' => [
                'name' => 'Adjustment_Date',
                'data_type' => 'Date',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'Adjustment.Date',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select Date',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
                'label' => E::ts('Adjustment: Date'),
              ],
              'Adjustment_Notes' => [
                'name' => 'Adjustment_Notes',
                'data_type' => 'Text',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'Adjustment.Notes',
                'original_field_entity' => 'Contribution',
                'input_type' => 'TextArea',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
                'label' => E::ts('Adjustment: Notes'),
              ],
              'Adjustment_Reason' => [
                'name' => 'Adjustment_Reason',
                'data_type' => 'String',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'Adjustment.Reason',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
                'label' => E::ts('Adjustment: Reason'),
              ],
            ],
            'targets' => [
              'total_amount' => 2100,
            ],
          ],
          'runner' => [
            'title' => E::ts('Queue Runner'),
            'onEndUrl' => '/civicrm/import/contact/summary?user_job_id=5312&reset=1',
          ],
          'import_options' => [
            'date_format' => 1,
          ],
          'summary_info' => [],
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'SavedSearch_Batch_entry_General_SearchDisplay_Batch_entry_General_UserJob_2',
    'entity' => 'UserJob',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Batch 51298 Ind.'),
        'expires_date' => '2026-10-10 14:00:54',
        'status_id' => 2,
        'job_type' => 'search_batch_import',
        'search_display_id.name' => 'Batch_entry_General_',
        'metadata' => [
          'DataSource' => [
            'table_name' => 'civicrm_tmp_d_searchbatch_f54343a74c3dd94c8c2f1fb08ac59d1f',
            'column_headers' => [
              'Contact ID',
              'Contribution Status',
              'Batch Number',
              'Financial Type',
              'Total Amount',
              'Contribution Source',
              'Contribution Date',
              'Payment Method',
              'Contribution Contribution Soft Credits: Contact ID',
              'Contribution Contribution Soft Credits: Soft Credit Type',
              'Gift Data: Fund',
              'Gift Data: Channel',
              'Gift Type',
              'Gift Data: Appeal',
              'Gateway',
              'No Thank-you Reason',
              'Adjustment: Date',
              'Adjustment: Notes',
              'Adjustment: Reason',
            ],
            'column_specs' => [
              'contact_id' => [
                'name' => 'contact_id',
                'data_type' => 'Integer',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'contact_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'EntityRef',
                'entity_reference' => [
                  'entity' => 'Contact',
                  'key' => 'id',
                  'on_delete' => 'CASCADE',
                ],
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => NULL,
                'label' => E::ts('Contact ID'),
              ],
              'contribution_status_id' => [
                'name' => 'contribution_status_id',
                'data_type' => 'Integer',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'contribution_status_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => 1,
                'label' => E::ts('Contribution Status'),
              ],
              'Gift_Information_import_batch_number' => [
                'name' => 'Gift_Information_import_batch_number',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'Gift_Information.import_batch_number',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
                'label' => E::ts('Batch Number'),
              ],
              'financial_type_id' => [
                'name' => 'financial_type_id',
                'data_type' => 'Integer',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'financial_type_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => [
                  'entity' => 'FinancialType',
                  'key' => 'id',
                ],
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => 9,
                'label' => E::ts('Financial Type'),
              ],
              'total_amount' => [
                'name' => 'total_amount',
                'data_type' => 'Money',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'total_amount',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'entity_reference' => NULL,
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => NULL,
                'label' => E::ts('Total Amount'),
              ],
              'source' => [
                'name' => 'source',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'source',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
                'label' => E::ts('Contribution Source'),
              ],
              'receive_date' => [
                'name' => 'receive_date',
                'data_type' => 'Timestamp',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'receive_date',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select Date',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
                'label' => E::ts('Contribution Date'),
              ],
              'payment_instrument_id' => [
                'name' => 'payment_instrument_id',
                'data_type' => 'Integer',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'payment_instrument_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => NULL,
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => NULL,
                'label' => E::ts('Payment Method'),
              ],
              'Contribution_ContributionSoft_contribution2fcfe8c2b6254fe7' => [
                'name' => 'Contribution_ContributionSoft_contribution2fcfe8c2b6254fe7',
                'data_type' => 'Integer',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'contact_id',
                'original_field_entity' => 'ContributionSoft',
                'input_type' => 'EntityRef',
                'entity_reference' => [
                  'entity' => 'Contact',
                  'key' => 'id',
                  'on_delete' => 'CASCADE',
                ],
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
                'label' => E::ts('Contribution Contribution Soft Credits: Contact ID'),
              ],
              'Contribution_ContributionSoft_contribution16b3265579af7863' => [
                'name' => 'Contribution_ContributionSoft_contribution16b3265579af7863',
                'data_type' => 'Integer',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'soft_credit_type_id',
                'original_field_entity' => 'ContributionSoft',
                'input_type' => 'Select',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
                'label' => E::ts('Contribution Contribution Soft Credits: Soft Credit Type'),
              ],
              'Gift_Data_Fund' => [
                'name' => 'Gift_Data_Fund',
                'data_type' => 'String',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'Gift_Data.Fund',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => NULL,
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => 'Major Gifts - CC104',
                'label' => E::ts('Gift Data: Fund'),
              ],
              'Gift_Data_Channel' => [
                'name' => 'Gift_Data_Channel',
                'data_type' => 'String',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'Gift_Data.Channel',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => NULL,
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => 'Other Offline',
                'label' => E::ts('Gift Data: Channel'),
              ],
              'Gift_Data_Campaign' => [
                'name' => 'Gift_Data_Campaign',
                'data_type' => 'String',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'Gift_Data.Campaign',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => NULL,
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => NULL,
                'label' => E::ts('Gift Type'),
              ],
              'Gift_Data_Appeal' => [
                'name' => 'Gift_Data_Appeal',
                'data_type' => 'String',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'Gift_Data.Appeal',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => NULL,
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => 'White Mail',
                'label' => E::ts('Gift Data: Appeal'),
              ],
              'contribution_extra_gateway' => [
                'name' => 'contribution_extra_gateway',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'contribution_extra.gateway',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
                'label' => E::ts('Gateway'),
              ],
              'contribution_extra_no_thank_you' => [
                'name' => 'contribution_extra_no_thank_you',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'contribution_extra.no_thank_you',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
                'label' => E::ts('No Thank-you Reason'),
              ],
              'Adjustment_Date' => [
                'name' => 'Adjustment_Date',
                'data_type' => 'Date',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'Adjustment.Date',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select Date',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
                'label' => E::ts('Adjustment: Date'),
              ],
              'Adjustment_Notes' => [
                'name' => 'Adjustment_Notes',
                'data_type' => 'Text',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'Adjustment.Notes',
                'original_field_entity' => 'Contribution',
                'input_type' => 'TextArea',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
                'label' => E::ts('Adjustment: Notes'),
              ],
              'Adjustment_Reason' => [
                'name' => 'Adjustment_Reason',
                'data_type' => 'String',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'Adjustment.Reason',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
                'label' => E::ts('Adjustment: Reason'),
              ],
            ],
            'targets' => [
              'total_amount' => 100,
            ],
          ],
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'SavedSearch_Batch_entry_General_SearchDisplay_Batch_entry_General_UserJob_3',
    'entity' => 'UserJob',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Batch 081626'),
        'end_date' => '2026-09-16 13:36:49',
        'expires_date' => '2026-09-23 13:36:49',
        'status_id' => 1,
        'job_type' => 'search_batch_import',
        'search_display_id.name' => 'Batch_entry_General_',
        'metadata' => [
          'DataSource' => [
            'table_name' => 'civicrm_tmp_d_searchbatch_a69f18c2fdba9ebc1f1fdd0917e7663b',
            'column_headers' => [
              'Contact ID',
              'Contribution Status',
              'Batch Number',
              'Financial Type',
              'Total Amount',
              'Contribution Source',
              'Contribution Date',
              'Payment Method',
              'Contribution Contribution Soft Credits: Contact ID',
              'Contribution Contribution Soft Credits: Soft Credit Type',
              'Gift Data: Fund',
              'Gift Data: Channel',
              'Gift Type',
              'Gift Data: Appeal',
              'Gateway',
              'No Thank-you Reason',
              'Adjustment: Date',
              'Adjustment: Notes',
              'Adjustment: Reason',
            ],
            'column_specs' => [
              'contact_id' => [
                'name' => 'contact_id',
                'data_type' => 'Integer',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'contact_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'EntityRef',
                'entity_reference' => [
                  'entity' => 'Contact',
                  'key' => 'id',
                  'on_delete' => 'CASCADE',
                ],
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => NULL,
                'label' => E::ts('Contact ID'),
              ],
              'contribution_status_id' => [
                'name' => 'contribution_status_id',
                'data_type' => 'Integer',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'contribution_status_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => 1,
                'label' => E::ts('Contribution Status'),
              ],
              'Gift_Information_import_batch_number' => [
                'name' => 'Gift_Information_import_batch_number',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'Gift_Information.import_batch_number',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
                'label' => E::ts('Batch Number'),
              ],
              'financial_type_id' => [
                'name' => 'financial_type_id',
                'data_type' => 'Integer',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'financial_type_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => [
                  'entity' => 'FinancialType',
                  'key' => 'id',
                ],
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => 9,
                'label' => E::ts('Financial Type'),
              ],
              'total_amount' => [
                'name' => 'total_amount',
                'data_type' => 'Money',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'total_amount',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'entity_reference' => NULL,
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => NULL,
                'label' => E::ts('Total Amount'),
              ],
              'source' => [
                'name' => 'source',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'source',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
                'label' => E::ts('Contribution Source'),
              ],
              'receive_date' => [
                'name' => 'receive_date',
                'data_type' => 'Timestamp',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'receive_date',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select Date',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
                'label' => E::ts('Contribution Date'),
              ],
              'payment_instrument_id' => [
                'name' => 'payment_instrument_id',
                'data_type' => 'Integer',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'payment_instrument_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => NULL,
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => NULL,
                'label' => E::ts('Payment Method'),
              ],
              'Contribution_ContributionSoft_contribution2fcfe8c2b6254fe7' => [
                'name' => 'Contribution_ContributionSoft_contribution2fcfe8c2b6254fe7',
                'data_type' => 'Integer',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'contact_id',
                'original_field_entity' => 'ContributionSoft',
                'input_type' => 'EntityRef',
                'entity_reference' => [
                  'entity' => 'Contact',
                  'key' => 'id',
                  'on_delete' => 'CASCADE',
                ],
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
                'label' => E::ts('Contribution Contribution Soft Credits: Contact ID'),
              ],
              'Contribution_ContributionSoft_contribution16b3265579af7863' => [
                'name' => 'Contribution_ContributionSoft_contribution16b3265579af7863',
                'data_type' => 'Integer',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'soft_credit_type_id',
                'original_field_entity' => 'ContributionSoft',
                'input_type' => 'Select',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
                'label' => E::ts('Contribution Contribution Soft Credits: Soft Credit Type'),
              ],
              'Gift_Data_Fund' => [
                'name' => 'Gift_Data_Fund',
                'data_type' => 'String',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'Gift_Data.Fund',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => NULL,
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => 'Major Gifts - CC104',
                'label' => E::ts('Gift Data: Fund'),
              ],
              'Gift_Data_Channel' => [
                'name' => 'Gift_Data_Channel',
                'data_type' => 'String',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'Gift_Data.Channel',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => NULL,
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => 'Other Offline',
                'label' => E::ts('Gift Data: Channel'),
              ],
              'Gift_Data_Campaign' => [
                'name' => 'Gift_Data_Campaign',
                'data_type' => 'String',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'Gift_Data.Campaign',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => NULL,
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => NULL,
                'label' => E::ts('Gift Type'),
              ],
              'Gift_Data_Appeal' => [
                'name' => 'Gift_Data_Appeal',
                'data_type' => 'String',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'Gift_Data.Appeal',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => NULL,
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => 'White Mail',
                'label' => E::ts('Gift Data: Appeal'),
              ],
              'contribution_extra_gateway' => [
                'name' => 'contribution_extra_gateway',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'contribution_extra.gateway',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
                'label' => E::ts('Gateway'),
              ],
              'contribution_extra_no_thank_you' => [
                'name' => 'contribution_extra_no_thank_you',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'contribution_extra.no_thank_you',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
                'label' => E::ts('No Thank-you Reason'),
              ],
              'Adjustment_Date' => [
                'name' => 'Adjustment_Date',
                'data_type' => 'Date',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'Adjustment.Date',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select Date',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
                'label' => E::ts('Adjustment: Date'),
              ],
              'Adjustment_Notes' => [
                'name' => 'Adjustment_Notes',
                'data_type' => 'Text',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'Adjustment.Notes',
                'original_field_entity' => 'Contribution',
                'input_type' => 'TextArea',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
                'label' => E::ts('Adjustment: Notes'),
              ],
              'Adjustment_Reason' => [
                'name' => 'Adjustment_Reason',
                'data_type' => 'String',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'Adjustment.Reason',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
                'label' => E::ts('Adjustment: Reason'),
              ],
            ],
            'targets' => [
              'total_amount' => 1091,
            ],
          ],
          'runner' => [
            'title' => E::ts('Queue Runner'),
            'onEndUrl' => '/civicrm/import/contact/summary?user_job_id=5333&reset=1',
          ],
          'import_options' => [
            'date_format' => 1,
          ],
          'summary_info' => [],
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'SavedSearch_Batch_entry_General_SearchDisplay_Batch_entry_General_UserJob_4',
    'entity' => 'UserJob',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('081626'),
        'end_date' => '2026-09-16 17:09:30',
        'expires_date' => '2026-09-23 17:09:30',
        'status_id' => 1,
        'job_type' => 'search_batch_import',
        'search_display_id.name' => 'Batch_entry_General_',
        'metadata' => [
          'DataSource' => [
            'table_name' => 'civicrm_tmp_d_searchbatch_e4ebc9098e06a702662d0d68d8f3a380',
            'column_headers' => [
              'Contact ID',
              'Contribution Status',
              'Batch Number',
              'Financial Type',
              'Total Amount',
              'Contribution Source',
              'Contribution Date',
              'Payment Method',
              'Contribution Contribution Soft Credits: Contact ID',
              'Contribution Contribution Soft Credits: Soft Credit Type',
              'Gift Data: Fund',
              'Gift Data: Channel',
              'Gift Type',
              'Gift Data: Appeal',
              'Gateway',
              'No Thank-you Reason',
              'Adjustment: Date',
              'Adjustment: Notes',
              'Adjustment: Reason',
            ],
            'column_specs' => [
              'contact_id' => [
                'name' => 'contact_id',
                'data_type' => 'Integer',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'contact_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'EntityRef',
                'entity_reference' => [
                  'entity' => 'Contact',
                  'key' => 'id',
                  'on_delete' => 'CASCADE',
                ],
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => NULL,
                'label' => E::ts('Contact ID'),
              ],
              'contribution_status_id' => [
                'name' => 'contribution_status_id',
                'data_type' => 'Integer',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'contribution_status_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => 1,
                'label' => E::ts('Contribution Status'),
              ],
              'Gift_Information_import_batch_number' => [
                'name' => 'Gift_Information_import_batch_number',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'Gift_Information.import_batch_number',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
                'label' => E::ts('Batch Number'),
              ],
              'financial_type_id' => [
                'name' => 'financial_type_id',
                'data_type' => 'Integer',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'financial_type_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => [
                  'entity' => 'FinancialType',
                  'key' => 'id',
                ],
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => 9,
                'label' => E::ts('Financial Type'),
              ],
              'total_amount' => [
                'name' => 'total_amount',
                'data_type' => 'Money',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'total_amount',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'entity_reference' => NULL,
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => NULL,
                'label' => E::ts('Total Amount'),
              ],
              'source' => [
                'name' => 'source',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'source',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
                'label' => E::ts('Contribution Source'),
              ],
              'receive_date' => [
                'name' => 'receive_date',
                'data_type' => 'Timestamp',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'receive_date',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select Date',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
                'label' => E::ts('Contribution Date'),
              ],
              'payment_instrument_id' => [
                'name' => 'payment_instrument_id',
                'data_type' => 'Integer',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'payment_instrument_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => NULL,
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => NULL,
                'label' => E::ts('Payment Method'),
              ],
              'Contribution_ContributionSoft_contribution2fcfe8c2b6254fe7' => [
                'name' => 'Contribution_ContributionSoft_contribution2fcfe8c2b6254fe7',
                'data_type' => 'Integer',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'contact_id',
                'original_field_entity' => 'ContributionSoft',
                'input_type' => 'EntityRef',
                'entity_reference' => [
                  'entity' => 'Contact',
                  'key' => 'id',
                  'on_delete' => 'CASCADE',
                ],
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
                'label' => E::ts('Contribution Contribution Soft Credits: Contact ID'),
              ],
              'Contribution_ContributionSoft_contribution16b3265579af7863' => [
                'name' => 'Contribution_ContributionSoft_contribution16b3265579af7863',
                'data_type' => 'Integer',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'soft_credit_type_id',
                'original_field_entity' => 'ContributionSoft',
                'input_type' => 'Select',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
                'label' => E::ts('Contribution Contribution Soft Credits: Soft Credit Type'),
              ],
              'Gift_Data_Fund' => [
                'name' => 'Gift_Data_Fund',
                'data_type' => 'String',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'Gift_Data.Fund',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => NULL,
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => 'Major Gifts - CC104',
                'label' => E::ts('Gift Data: Fund'),
              ],
              'Gift_Data_Channel' => [
                'name' => 'Gift_Data_Channel',
                'data_type' => 'String',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'Gift_Data.Channel',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => NULL,
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => 'Other Offline',
                'label' => E::ts('Gift Data: Channel'),
              ],
              'Gift_Data_Campaign' => [
                'name' => 'Gift_Data_Campaign',
                'data_type' => 'String',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'Gift_Data.Campaign',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => NULL,
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => NULL,
                'label' => E::ts('Gift Type'),
              ],
              'Gift_Data_Appeal' => [
                'name' => 'Gift_Data_Appeal',
                'data_type' => 'String',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'Gift_Data.Appeal',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => NULL,
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => 'White Mail',
                'label' => E::ts('Gift Data: Appeal'),
              ],
              'contribution_extra_gateway' => [
                'name' => 'contribution_extra_gateway',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'contribution_extra.gateway',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
                'label' => E::ts('Gateway'),
              ],
              'contribution_extra_no_thank_you' => [
                'name' => 'contribution_extra_no_thank_you',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'contribution_extra.no_thank_you',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
                'label' => E::ts('No Thank-you Reason'),
              ],
              'Adjustment_Date' => [
                'name' => 'Adjustment_Date',
                'data_type' => 'Date',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'Adjustment.Date',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select Date',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
                'label' => E::ts('Adjustment: Date'),
              ],
              'Adjustment_Notes' => [
                'name' => 'Adjustment_Notes',
                'data_type' => 'Text',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'Adjustment.Notes',
                'original_field_entity' => 'Contribution',
                'input_type' => 'TextArea',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
                'label' => E::ts('Adjustment: Notes'),
              ],
              'Adjustment_Reason' => [
                'name' => 'Adjustment_Reason',
                'data_type' => 'String',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'Adjustment.Reason',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
                'label' => E::ts('Adjustment: Reason'),
              ],
            ],
            'targets' => [
              'total_amount' => 239.14,
            ],
          ],
          'runner' => [
            'title' => E::ts('Queue Runner'),
            'onEndUrl' => '/civicrm/import/contact/summary?user_job_id=5342&reset=1',
          ],
          'import_options' => [
            'date_format' => 1,
          ],
          'summary_info' => [],
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
];
