<?php
use CRM_Wmf_ExtensionUtil as E;

return [
  [
    'name' => 'SavedSearch_Batch_entry_Stock_',
    'entity' => 'SavedSearch',
    'cleanup' => 'never',
    'update' => 'never',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Batch_entry_Stock_',
        'label' => E::ts('Batch entry (Stock)'),
        'api_entity' => 'Contribution',
        'api_params' => [
          'version' => 4,
          'select' => [
            'contact_id',
            'contribution_status_id:label',
            'financial_type_id:label',
            'total_amount',
            'source',
            'receive_date',
            'payment_instrument_id:label',
            'Gift_Data.Fund:label',
            'Gift_Data.Channel:label',
            'Gift_Data.Campaign:label',
            'Gift_Data.Appeal:label',
            'contribution_extra.gateway',
            'contribution_extra.no_thank_you',
            'Stock_Information.Stock Quantity',
            'Stock_Information.Stock Ticker',
            'Stock_Information.Stock Value',
          ],
          'orderBy' => [],
          'where' => [],
          'groupBy' => [],
          'join' => [],
          'having' => [],
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'SavedSearch_Batch_entry_Stock_SearchDisplay_Data_entry_screen_WMF_DAF_copy_',
    'entity' => 'SearchDisplay',
    'cleanup' => 'never',
    'update' => 'never',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Data_entry_screen_WMF_DAF_copy_',
        'label' => E::ts('Data entry screen (Stock)'),
        'saved_search_id.name' => 'Batch_entry_Stock_',
        'type' => 'batch',
        'settings' => [
          'classes' => [
            'table',
            'table-striped',
            'table-bordered',
            'crm-sticky-header',
          ],
          'pager' => [
            'show_count' => FALSE,
            'expose_limit' => TRUE,
            'hide_single' => TRUE,
          ],
          'columns' => [
            [
              'type' => 'field',
              'key' => 'contact_id',
              'label' => 'Contact ID',
              'spec' => [
                'name' => 'contact_id',
                'data_type' => 'Integer',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'contact_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'EntityRef',
                'entity_reference' => [
                  'entity' => 'Contact',
                  'key' => 'id',
                  'on_delete' => 'CASCADE',
                ],
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => NULL,
              ],
              'required' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'contribution_status_id:label',
              'label' => 'Contribution Status',
              'default' => 1,
              'spec' => [
                'name' => 'contribution_status_id',
                'data_type' => 'Integer',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'contribution_status_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => 1,
              ],
            ],
            [
              'type' => 'field',
              'key' => 'financial_type_id:label',
              'label' => 'Financial Type',
              'spec' => [
                'name' => 'financial_type_id',
                'data_type' => 'Integer',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'financial_type_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => [
                  'entity' => 'FinancialType',
                  'key' => 'id',
                ],
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => 9,
              ],
              'required' => TRUE,
              'default' => 9,
            ],
            [
              'type' => 'field',
              'key' => 'total_amount',
              'label' => 'Total Amount',
              'tally' => [
                'fn' => 'SUM',
                'target' => TRUE,
                'label' => 'Total Amount',
              ],
              'spec' => [
                'name' => 'total_amount',
                'data_type' => 'Money',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'total_amount',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'entity_reference' => NULL,
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => NULL,
              ],
              'required' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'source',
              'label' => 'Contribution Source',
              'spec' => [
                'name' => 'source',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'source',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
              ],
            ],
            [
              'type' => 'field',
              'key' => 'receive_date',
              'label' => 'Contribution Date',
              'spec' => [
                'name' => 'receive_date',
                'data_type' => 'Timestamp',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'receive_date',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select Date',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
              ],
              'format' => 'dateformatFull',
            ],
            [
              'type' => 'field',
              'key' => 'payment_instrument_id:label',
              'label' => 'Payment Method',
              'required' => TRUE,
              'spec' => [
                'name' => 'payment_instrument_id',
                'data_type' => 'Integer',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'payment_instrument_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => NULL,
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => NULL,
              ],
            ],
            [
              'type' => 'field',
              'key' => 'Gift_Data.Fund:label',
              'label' => 'Gift Data: Fund',
              'spec' => [
                'name' => 'Gift_Data_Fund',
                'data_type' => 'String',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'Gift_Data.Fund',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => NULL,
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => 'Major Gifts - CC104',
              ],
              'required' => TRUE,
              'default' => 'Major Gifts - CC104',
            ],
            [
              'type' => 'field',
              'key' => 'Gift_Data.Channel:label',
              'label' => 'Gift Data: Channel',
              'spec' => [
                'name' => 'Gift_Data_Channel',
                'data_type' => 'String',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'Gift_Data.Channel',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => NULL,
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => 'Other Offline',
              ],
              'required' => TRUE,
              'default' => 'Other Offline',
            ],
            [
              'type' => 'field',
              'key' => 'Gift_Data.Campaign:label',
              'label' => 'Gift Type',
              'spec' => [
                'name' => 'Gift_Data_Campaign',
                'data_type' => 'String',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'Gift_Data.Campaign',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => NULL,
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => NULL,
              ],
              'required' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'Gift_Data.Appeal:label',
              'label' => 'Gift Data: Appeal',
              'spec' => [
                'name' => 'Gift_Data_Appeal',
                'data_type' => 'String',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'Gift_Data.Appeal',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'entity_reference' => NULL,
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => 'White Mail',
              ],
              'required' => TRUE,
              'default' => 'White Mail',
            ],
            [
              'type' => 'field',
              'key' => 'contribution_extra.gateway',
              'label' => 'Gateway',
              'spec' => [
                'name' => 'contribution_extra_gateway',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'contribution_extra.gateway',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
              ],
            ],
            [
              'type' => 'field',
              'key' => 'contribution_extra.no_thank_you',
              'label' => 'No Thank-you Reason',
              'spec' => [
                'name' => 'contribution_extra_no_thank_you',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'contribution_extra.no_thank_you',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'entity_reference' => NULL,
                'required' => FALSE,
                'nullable' => TRUE,
                'api_default' => NULL,
              ],
            ],
            [
              'type' => 'field',
              'key' => 'Stock_Information.Stock Quantity',
              'label' => 'Stock Quantity',
              'required' => TRUE,
              'spec' => [
                'name' => 'Stock_Information_Stock_Quantity',
                'data_type' => 'Float',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'Stock_Information.Stock Quantity',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Number',
                'entity_reference' => NULL,
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => NULL,
              ],
            ],
            [
              'type' => 'field',
              'key' => 'Stock_Information.Stock Ticker',
              'label' => 'Stock Ticker',
              'required' => TRUE,
              'spec' => [
                'name' => 'Stock_Information_Stock_Ticker',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'Stock_Information.Stock Ticker',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'entity_reference' => NULL,
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => NULL,
              ],
            ],
            [
              'type' => 'field',
              'key' => 'Stock_Information.Stock Value',
              'label' => 'Stock Value',
              'required' => TRUE,
              'spec' => [
                'name' => 'Stock_Information_Stock_Value',
                'data_type' => 'Money',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'Stock_Information.Stock Value',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'entity_reference' => NULL,
                'required' => TRUE,
                'nullable' => FALSE,
                'api_default' => NULL,
              ],
            ],
          ],
          'tally' => [],
          'limit' => 100,
        ],
      ],
      'match' => [
        'saved_search_id',
        'name',
      ],
    ],
  ],
];
