<?php
use CRM_Wmf_ExtensionUtil as E;

return [
  [
    'name' => 'SavedSearch_Accounting_System_Batches',
    'entity' => 'SavedSearch',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Accounting_System_Batches',
        'label' => E::ts('Accounting System Batches'),
        'api_entity' => 'Batch',
        'api_params' => [
          'version' => 4,
          'select' => [
            'id',
            'title',
            'batch_data.settled_net_amount',
            'created_date',
            'batch_data.settlement_date',
            'batch_data.settlement_currency',
            'batch_data.settled_donation_amount',
            'batch_data.settled_fee_amount',
            'batch_data.settled_reversal_amount',
            'item_count',
            'status_id:label',
            'name',
            'batch_data.issue_tracker_reference',
            'batch_data.last_successful_validation_date',
          ],
          'orderBy' => [],
          'where' => [
            [
              'mode_id:name',
              '=',
              'Automatic Batch',
            ],
          ],
          'groupBy' => [],
          'join' => [],
          'having' => [],
        ],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'SavedSearch_Accounting_System_Batches_SearchDisplay_Accounting_System_Batches',
    'entity' => 'SearchDisplay',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Accounting_System_Batches',
        'label' => E::ts('Accounting System Batches'),
        'saved_search_id.name' => 'Accounting_System_Batches',
        'type' => 'table',
        'settings' => [
          'description' => E::ts('Batches for export to Intact'),
          'sort' => [
            [
              'batch_data.settlement_date',
              'DESC',
            ],
          ],
          'limit' => 50,
          'pager' => [],
          'placeholder' => 5,
          'columns' => [
            [
              'type' => 'field',
              'key' => 'id',
              'label' => E::ts('Batch ID'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'title',
              'label' => E::ts('Batch Title'),
              'sortable' => TRUE,
              'link' => [
                'path' => 'civicrm/contribution/settled#?finance_batch=[name]',
                'entity' => '',
                'action' => '',
                'join' => '',
                'target' => '',
                'task' => '',
              ],
              'title' => E::ts('Delete Batches'),
            ],
            [
              'type' => 'field',
              'key' => 'batch_data.settled_net_amount',
              'label' => E::ts('Settled Net Amount'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'created_date',
              'label' => E::ts('Created Date'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'batch_data.settlement_date',
              'label' => E::ts('Settlement Date'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'batch_data.settlement_currency',
              'label' => E::ts('Settlement Currency'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'batch_data.settled_donation_amount',
              'label' => E::ts('Settled Donation Amount'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'batch_data.settled_fee_amount',
              'label' => E::ts('Batch Data: Settled Fee Amount'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'batch_data.settled_reversal_amount',
              'label' => E::ts('Batch Data: Settled Reversal Amount'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'item_count',
              'label' => E::ts('Batch Number of Items'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'status_id:label',
              'label' => E::ts('Batch Status'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'batch_data.issue_tracker_reference',
              'label' => E::ts('Phab'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'batch_data.last_successful_validation_date',
              'label' => E::ts('Last successfully validated'),
              'sortable' => TRUE,
            ],
            [
              'size' => 'btn-xs',
              'links' => [
                [
                  'path' => 'civicrm/batch/download?type=details&batch=[name]',
                  'icon' => 'fa-external-link',
                  'text' => E::ts('Download Journals'),
                  'style' => 'default',
                  'conditions' => [
                    [
                      'status_id:name',
                      'IN',
                      ['total_verified', 'validated'],
                    ],
                  ],
                  'task' => '',
                  'entity' => '',
                  'action' => '',
                  'join' => '',
                  'target' => '',
                ],
                [
                  'path' => 'civicrm/batch/download?type=journals&batch=[name]',
                  'icon' => 'fa-external-link',
                  'text' => E::ts('Download Transations'),
                  'style' => 'default',
                  'conditions' => [
                    [
                      'status_id:name',
                      'IN',
                      ['Closed', 'Exported', 'total_verified', 'validated'],
                    ],
                  ],
                  'task' => '',
                  'entity' => '',
                  'action' => '',
                  'join' => '',
                  'target' => '',
                ],
                [
                  'path' => 'civicrm/contribution/settled#?finance_batch=[name]',
                  'icon' => 'fa-external-link',
                  'text' => E::ts('Search Transactions'),
                  'style' => 'default',
                  'conditions' => [],
                  'task' => '',
                  'entity' => '',
                  'action' => '',
                  'join' => '',
                  'target' => '_blank',
                ],
              ],
              'type' => 'buttons',
              'alignment' => 'text-right',
              'label' => E::ts('Download Transactions'),
            ],
          ],
          'actions' => TRUE,
          'classes' => [
            'table',
            'table-striped',
          ],
          'actions_display_mode' => 'menu',
          'columnMode' => 'custom',
          'cssRules' => [
            [
              'bg-warning',
              'status_id:name',
              '=',
              'needs_attention',
            ],
            [
              'bg-success',
              'status_id:name',
              'IN',
              [
                'total_verified',
                'validated',
              ],
            ],
            [
              'bg-info',
              'status_id:name',
              'IN',
              [
                'Open',
              ],
            ],
            [
              'disabled',
              'status_id:name',
              'IN',
              [
                'Closed',
                'Exported',
              ],
            ],
          ],
        ],
      ],
      'match' => [
        'saved_search_id',
        'name',
      ],
    ],
  ],
];
