<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from wmf-thankyou/xml/schema/CRM/WmfThankyou/EOYEmailJob.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:de000c8b8a60befd0ee19b2df1f5916f)
 */
use CRM_WmfThankyou_ExtensionUtil as E;

/**
 * Database access object for the EOYEmailJob entity.
 */
class CRM_WmfThankyou_DAO_EOYEmailJob extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'wmf_eoy_receipt_donor';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * EOY email job ID
   *
   * @var int
   */
  public $id;

  /**
   * Email address
   *
   * @var string
   */
  public $email;

  /**
   * queued|failed|sent
   *
   * @var string
   */
  public $status;

  /**
   * @var int
   */
  public $year;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'wmf_eoy_receipt_donor';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('EOYEmail Jobs') : E::ts('EOYEmail Job');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('EOY email job ID'),
          'description' => E::ts('EOY email job ID'),
          'required' => TRUE,
          'where' => 'wmf_eoy_receipt_donor.id',
          'table_name' => 'wmf_eoy_receipt_donor',
          'entity' => 'EOYEmailJob',
          'bao' => 'CRM_WmfThankyou_DAO_EOYEmailJob',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'email' => [
          'name' => 'email',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Email'),
          'description' => E::ts('Email address'),
          'maxlength' => 254,
          'size' => 30,
          'where' => 'wmf_eoy_receipt_donor.email',
          'rule' => 'email',
          'table_name' => 'wmf_eoy_receipt_donor',
          'entity' => 'EOYEmailJob',
          'bao' => 'CRM_WmfThankyou_DAO_EOYEmailJob',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'status' => [
          'name' => 'status',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Processing status'),
          'description' => E::ts('queued|failed|sent'),
          'maxlength' => 254,
          'size' => 20,
          'where' => 'wmf_eoy_receipt_donor.status',
          'table_name' => 'wmf_eoy_receipt_donor',
          'entity' => 'EOYEmailJob',
          'bao' => 'CRM_WmfThankyou_DAO_EOYEmailJob',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'pseudoconstant' => [
            'callback' => 'CRM_WmfThankyou_BAO_EOYEmailJob::getStatuses',
          ],
          'add' => NULL,
        ],
        'year' => [
          'name' => 'year',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Send year'),
          'where' => 'wmf_eoy_receipt_donor.year',
          'table_name' => 'wmf_eoy_receipt_donor',
          'entity' => 'EOYEmailJob',
          'bao' => 'CRM_WmfThankyou_DAO_EOYEmailJob',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'receipt_donor', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'receipt_donor', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'email_year' => [
        'name' => 'email_year',
        'field' => [
          0 => 'email',
          1 => 'year',
        ],
        'localizable' => FALSE,
        'sig' => 'wmf_eoy_receipt_donor::0::email::year',
      ],
      'status' => [
        'name' => 'status',
        'field' => [
          0 => 'status',
        ],
        'localizable' => FALSE,
        'sig' => 'wmf_eoy_receipt_donor::0::status',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
