<div class="help">
<p>This page shows the segments & donor statuses currently being generated by WMF code.</p>
<p>The current statuses and segments were described in this <a target="_blank" href="https://docs.google.com/spreadsheets/d/17Pc1tIvqol6XJhuu97RlOfwy_Avbb9MEaRwhy2F529I/edit?usp=sharing">spreadsheet</a>.
For the older version, the phab was <a target="_blank" href="https://phabricator.wikimedia.org/T336305">donor segments</a>
and the segments were initially described in this <a target="_blank" href="https://docs.google.com/spreadsheets/d/1qM36MeKWyOENl-iR5umuLph5HLHG6W_6c46xJUdE3QY/edit#gid=1786541006"> Google doc</a>.
</p>
<p>A contact will be assigned to the first segment / status that they match (from the top / lowest value), except om the old segments where if they are in the Major Donor or Mid Tier segments, in which case they will not be assigned to a recurring status even if they do have a recurring donation.</p>
</div>

<h3 style="margin: 0px 0px 10px 0px;">Segments</h3>
<table class="row-highlight">
  <tr>
    <th>Label</th>
    <th>Description</th>
    <th>Value</th>
  </tr>
  {foreach from=$segments item='segment'}
    <tr>
      <td>{$segment.label}</td>
      <td>{$segment.description|nl2br}</td>
      <td>{$segment.value}</td>
    </tr>
  {/foreach}
</table>

<h3 style="margin: 10px 0px;">Statuses</h3>
{foreach from=$statuses key='title' item='statusGroup'}
  <h4 style="margin: 10px 0px;">{$title}</h4>
  <table class="row-highlight">
    <tr>
      <th>Label</th>
      <th>Description</th>
      <th>Value</th>
    </tr>
    {foreach from=$statusGroup item='status'}
      <tr>
        <td>{$status.label}</td>
        <td>{$status.description|nl2br}</td>
        <td>{$status.value}</td>
      </tr>
    {/foreach}
  </table>
{/foreach}

<h3 style="margin: 0px 0px 10px 0px;">Old segments</h3>
<table class="row-highlight">
      <tr>
        <th>Label</th>
        <th>Description</th>
        <th>Value</th>
      </tr>
  {foreach from=$oldSegments item='oldSegment'}
      <tr>
        <td>{$oldSegment.label}</td>
        <td>{$oldSegment.description|nl2br}</td>
        <td>{$oldSegment.value}</td>
      </tr>
  {/foreach}
</table>

<h3 style="margin: 10px 0px;">Old statuses</h3>
<table class="row-highlight">
      <tr>
        <th>Label</th>
        <th>Description</th>
        <th>Value</th>
      </tr>
    {foreach from=$oldStatuses item='oldStatus'}
      <tr>
        <td>{$oldStatus.label}</td>
        <td>{$oldStatus.description|nl2br}</td>
        <td>{$oldStatus.value}</td>
      </tr>
    {/foreach}
</table>
