<?php

return [
  'smashpig_recurring_use_queue' => [
    'group_name' => 'SmashPig Preferences',
    'group' => 'smashpig',
    'name' => 'smashpig_recurring_use_queue',
    'quick_form_type' => 'Element',
    'html_type' => 'checkbox',
    'type' => 'Boolean',
    'default' => 0,
    'title' => 'Use queue for recurring',
    'is_domain' => '1',
    'is_contact' => 0,
    'description' => 'When true, SmashPig Recurring Charge job pushes donations to donations queue instead of creating directly',
    'help_text' => 'Queue connection settings are part of system-wide SmashPig settings managed via SmashPig\'s yaml files',
    'settings_pages' => ['smashpig' => ['weight' => 1]],
  ],
  'smashpig_recurring_retry_cadence' => [
    'group_name' => 'SmashPig Preferences',
    'group' => 'smashpig',
    'name' => 'smashpig_recurring_retry_cadence',
    'type' => 'String',
    'quick_form_type' => 'Element',
    'html_type' => 'text',
    'html_attributes' => [
      'size' => 15,
      'maxlength' => 15,
    ],
    'default' => '1,2',
    'title' => 'Failed payment retry cadence',
    'is_domain' => '1',
    'is_contact' => 0,
    'description' => 'Sequence of days after failure on which to retry payments. E.g "3,7,14" means to re-attempt 3, 7, and 14 days after the initial failure.',
    'settings_pages' => ['smashpig' => ['weight' => 2]],
  ],
  'smashpig_recurring_send_failure_email' => [
    'group_name' => 'SmashPig Preferences',
    'group' => 'smashpig',
    'name' => 'smashpig_recurring_send_failure_email',
    'type' => 'Boolean',
    'quick_form_type' => 'Element',
    'html_type' => 'checkbox',
    'default' => 0,
    'title' => 'Send email when canceling recurring contributions',
    'is_domain' => '1',
    'is_contact' => 0,
    'description' => 'Once the job has hit the limit of failed payments above, send an email to the donor about cancellation.',
    'settings_pages' => ['smashpig' => ['weight' => 4]],
  ],
  'smashpig_recurring_catch_up_days' => [
    'group_name' => 'SmashPig Preferences',
    'group' => 'smashpig',
    'name' => 'smashpig_recurring_catch_up_days',
    'type' => 'Integer',
    'quick_form_type' => 'Element',
    'html_type' => 'text',
    'html_attributes' => [
      'size' => 3,
      'maxlength' => 3,
    ],
    'default' => 15,
    'title' => 'Days in the past to look for recurring contributions due to charge',
    'is_domain' => '1',
    'is_contact' => 0,
    'description' => 'The job will attempt to charge recurring contributions whose next_sched_contribution date is between now and this many days in the past.',
    'settings_pages' => ['smashpig' => ['weight' => 5]],
  ],
  'smashpig_recurring_batch_size' => [
    'group_name' => 'SmashPig Preferences',
    'group' => 'smashpig',
    'name' => 'smashpig_recurring_batch_size',
    'type' => 'Integer',
    'quick_form_type' => 'Element',
    'html_type' => 'text',
    'html_attributes' => [
      'size' => 4,
      'maxlength' => 4,
    ],
    'default' => 100,
    'title' => 'Number of payments to charge each run',
    'is_domain' => '1',
    'is_contact' => 0,
    'description' => 'The job will attempt to charge up to this many recurring contributions each run before stopping.',
    'settings_pages' => ['smashpig' => ['weight' => 6]],
  ],
  'smashpig_recurring_time_limit_in_seconds' => [
    'group_name' => 'SmashPig Preferences',
    'group' => 'smashpig',
    'name' => 'smashpig_recurring_time_limit_in_seconds',
    'type' => 'Integer',
    'quick_form_type' => 'Element',
    'html_type' => 'text',
    'html_attributes' => [
      'size' => 4,
      'maxlength' => 4,
    ],
    'default' => 0,
    'title' => 'Maximum number of seconds to spend processing (0 for no limit)',
    'is_domain' => '1',
    'is_contact' => 0,
    'description' => 'The job will stop charging recurring contributions after this many seconds.',
    'settings_pages' => ['smashpig' => ['weight' => 7]],
  ],
  'smashpig_recurring_charge_descriptor' => [
    'group name' => 'SmashPig Preferences',
    'group' => 'smashpig',
    'name' => 'smashpig_recurring_charge_descriptor',
    'type' => 'Text',
    'quick_form_type' => 'Element',
    'html_type' => 'text',
    'html_attributes' => array(
      'size' => 40,
    ),
    'default' => 'Donation',
    'is_domain' => '1',
    'is_contact' => 0,
    'title' => 'Monthly charge soft descriptor',
    'description' => 'The first 22 or so characters of this string show up on credit card statements.',
    'settings_pages' => ['smashpig' => ['weight' => 8]],
  ],
  'smashpig_recurring_min_days_between_charges' => [
    'group name' => 'SmashPig Preferences',
    'group' => 'smashpig',
    'name' => 'smashpig_recurring_min_days_between_charges',
    'type' => 'Integer',
    'quick_form_type' => 'Element',
    'html_type' => 'text',
    'html_attributes' => [
      'size' => 4,
      'maxlength' => 4,
    ],
    'default' => 23,
    'title' => 'Minimum time to wait between one charge and the next for a given recurring contribution',
    'is_domain' => '1',
    'is_contact' => 0,
    'description' => 'Needs to account for the longest possible retry delay in the "cadence" setting.',
    'settings_pages' => ['smashpig' => ['weight' => 9]],
  ],
  'smashpig_suppressed_error_messages' => [
    'group_name' => 'SmashPig Preferences',
    'group' => 'smashpig',
    'name' => 'smashpig_suppressed_error_messages',
    'type' => 'String',
    'quick_form_type' => 'Element',
    'html_type' => 'text',
    'html_attributes' => [
      'size' => 256,
      'maxlength' => 256,
    ],
    'default' => 'authorization_failed:requires_buyer_authentication',
    'title' => 'Suppressed error messages',
    'is_domain' => '1',
    'is_contact' => 0,
    'description' => 'Comma separated list of payment error messages which will never trigger an alert',
    'settings_pages' => ['smashpig' => ['weight' => 10]],
  ]
];
