<?php

/*
 * TODO:
 * - undo STUPID boilerplate
 * - stream data (unbuffered query using a new db connection)
 */

function wmf_eoy_receipt_run($options = []) {
  require_once 'EoySummary.php';
  civicrm_initialize();
  $donors = new wmf_eoy_receipt\EoySummary($options);

  $donors->calculate_year_totals();
  $donors->send_letters();
}

function wmf_eoy_receipt_calculate_summaries($options = []) {
  require_once 'EoySummary.php';
  civicrm_initialize();
  $donors = new wmf_eoy_receipt\EoySummary($options);

  $donors->calculate_year_totals();
}

function wmf_eoy_receipt_send_letters($options = []) {
  require_once 'EoySummary.php';
  civicrm_initialize();
  $donors = new wmf_eoy_receipt\EoySummary($options);

  $donors->send_letters();
}

function wmf_eoy_receipt_menu() {
  $items = [];

  $items['admin/config/wmf_eoy_receipt'] = [
    'title' => 'End-of-year Receipt',
    'description' => t('Configure.'),
    'access arguments' => ['access CiviContribute'],
    'page callback' => 'drupal_get_form',
    'page arguments' => ['wmf_eoy_receipt_settings'],
  ];

  return $items;
}

function wmf_eoy_receipt_enable() {
  variable_set('wmf_eoy_target_year',
    variable_get('wmf_eoy_target_year', intval(date('Y')) - 1));
  /*
      variable_set('wmf_eoy_threshold',
          variable_get('wmf_eoy_threshold', 1000));
  */

  variable_set('wmf_eoy_test',
    variable_get('wmf_eoy_test', TRUE));
}

function wmf_eoy_receipt_settings() {
  $form = [
    'wmf_eoy_target_year' => [
      '#title' => t('Year to process'),
      '#type' => 'textfield',
      '#size' => 10,
      '#default_value' => variable_get('wmf_eoy_target_year', NULL),
    ],
    /*
            'wmf_eoy_threshold' => array(
                '#title' => t('Threshold total donations (USD)'),
                '#type' => 'textfield',
                '#size' => 10,
                '#default_value' => variable_get('wmf_eoy_threshold', null),
                '#description' => t('Minimum amount given this year which will trigger a letter'),
            ),
    */
    'wmf_eoy_batch_max' => [
      '#title' => t('Email batch size'),
      '#type' => 'textfield',
      '#size' => 10,
      '#default_value' => variable_get('wmf_eoy_batch_max', 100),
      '#description' => t('Maximum emails sent per batch run'),
    ],
    'wmf_eoy_test_email' => [
      '#title' => t('Test email destination'),
      '#type' => 'textfield',
      '#size' => 30,
      '#default_value' => variable_get('wmf_eoy_test_email', NULL),
    ],
    'wmf_eoy_test' => [
      '#title' => t('Test mode'),
      '#type' => 'checkbox',
      '#default_value' => variable_get('wmf_eoy_test', NULL),
    ],
  ];
  return system_settings_form($form);
}
