<?php

use queue2civicrm\unsubscribe\UnsubscribeQueueConsumer;
use SmashPig\Core\Configuration;
use SmashPig\Core\Context;

/**
 * Implements hook_menu
 */
function wmf_unsubscribe_qc_menu() {
  $items[ 'admin/config/queue2civicrm/unsubscribe_qc' ] = array(
    'title'            => 'Unsubscribe',
    'description'      => t('Configure unsubscribe queue'),
    'access arguments' => array( 'administer queue2civicrm' ),
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array( 'unsubscribe_qc_settings' ),
  );
  return $items;
}

/**
 * Constructs the settings page for this module.
 *
 * @return array Of form components.
 */
function unsubscribe_qc_settings() {
  $form = array();

  $form['unsubscribe_qc_disable'] = array(
    '#type' => 'checkbox',
    '#title' => t('Disable job'),
    '#description' => t('If checked, no message processing will be performed.'),
    '#default_value' => variable_get('unsubscribe_qc_disable', false),
  );

  $form['description'] = array(
    '#type'        => 'markup',
    '#description' => t('<p>Contacts in the unsubscribe queue are processed by marking them as opt-out in the CRM.</p>'),
  );

  $form['unsubscribe_batch'] = array(
    '#type'          => 'select',
    '#title'         => t('Cron batch size'),
    '#description'   => t('Maximum number of items processed by an unsubscribe job'),
    '#default_value' => variable_get('unsubscribe_batch', 0),
    '#options'       => array(
      0   => 'Unlimited',
      1   => 1,
      5   => 5,
      10  => 10,
      50  => 50,
      75  => 75,
      100 => 100,
      150 => 150,
      300 => 300,
      500 => 500,
      750 => 750,
      1000 => 1000
    ),
  );

  $form['unsubscribe_batch_time'] = array(
    '#type' => 'textfield',
    '#title' => t('Job time limit (in seconds)'),
    '#description' => t('Maximum elapsed duration of an unsubscribe job, after which we will abort from the loop.  This can be used to set a reliable duty cycle for the job.  Either a time limit or batch size limit is required.'),
    '#required' => TRUE,
    '#default_value' => variable_get('unsubscribe_batch_time', 90),
  );

  return system_settings_form($form);
}

/**
 * Callback from Drush that actually executes the loop for processing messages in the queue.
 * @ref unsubscribe_process_message
 * @ref drush_unsubscribe_queue_consume
 */
function unsubscribe_batch_process() {
  wmf_common_create_smashpig_context('unsubscribe');
  watchdog('unsubscribe', 'Executing: unsubscribe_batch_process');

  civicrm_initialize();

  $consumer = new UnsubscribeQueueConsumer(
     'unsubscribe',
     variable_get('refund_batch_time', 0),
     variable_get('refund_batch', 0)
  );

  $processed = $consumer->dequeueMessages();


  if ($processed > 0) {
    watchdog('unsubscribe', 'Successfully processed ' . $processed . ' unsubscribe(s).');
  }
  else {
    watchdog('unsubscribe', 'No unsubscribes processed.');
  }
}
