<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from wmf-civicrm/xml/schema/CRM/Wmf/ContributionTracking.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:ad1cc5f0cacffe7fcf0634ad5c23fc44)
 */
use CRM_Wmf_ExtensionUtil as E;

/**
 * Database access object for the ContributionTracking entity.
 */
class CRM_Wmf_DAO_ContributionTracking extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '5.61';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_contribution_tracking';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = FALSE;

  /**
   * Unique Contribution Tracking ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * FK to Contribution
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $contribution_id;

  /**
   * Amount
   *
   * @var float|string|null
   *   (SQL type: decimal(20,3))
   *   Note that values will be retrieved from the database as a string.
   */
  public $amount;

  /**
   * Currency ISO Code
   *
   * @var string|null
   *   (SQL type: varchar(3))
   *   Note that values will be retrieved from the database as a string.
   */
  public $currency;

  /**
   * USD Amount
   *
   * @var float|string|null
   *   (SQL type: decimal(20,2))
   *   Note that values will be retrieved from the database as a string.
   */
  public $usd_amount;

  /**
   * @var bool|string|null
   *   (SQL type: tinyint)
   *   Note that values will be retrieved from the database as a string.
   */
  public $is_recurring;

  /**
   * Referrer
   *
   * @var string|null
   *   (SQL type: varchar(4096))
   *   Note that values will be retrieved from the database as a string.
   */
  public $referrer;

  /**
   * UTM Medium
   *
   * @var string|null
   *   (SQL type: varchar(128))
   *   Note that values will be retrieved from the database as a string.
   */
  public $utm_medium;

  /**
   * UTM Campaign
   *
   * @var string|null
   *   (SQL type: varchar(128))
   *   Note that values will be retrieved from the database as a string.
   */
  public $utm_campaign;

  /**
   * UTM Key
   *
   * @var string|null
   *   (SQL type: varchar(128))
   *   Note that values will be retrieved from the database as a string.
   */
  public $utm_key;

  /**
   * Gateway, e.g paypal_ec,adyen
   *
   * @var string|null
   *   (SQL type: varchar(32))
   *   Note that values will be retrieved from the database as a string.
   */
  public $gateway;

  /**
   * e.g JimmyQuote - the appeal is the text to the left of the input boxes (on desktop-size screens)
   *
   * @var string|null
   *   (SQL type: varchar(64))
   *   Note that values will be retrieved from the database as a string.
   */
  public $appeal;

  /**
   *  a 'variant' generally changes something about the input boxes or their labels
   *
   * @var string|null
   *   (SQL type: varchar(64))
   *   Note that values will be retrieved from the database as a string.
   */
  public $payments_form_variant;

  /**
   * Banner
   *
   * @var string|null
   *   (SQL type: varchar(128))
   *   Note that values will be retrieved from the database as a string.
   */
  public $banner;

  /**
   * Landing Page
   *
   * @var string|null
   *   (SQL type: varchar(128))
   *   Note that values will be retrieved from the database as a string.
   */
  public $landing_page;

  /**
   * @var int|string|null
   *   (SQL type: int)
   *   Note that values will be retrieved from the database as a string.
   */
  public $payment_method_id;

  /**
   * @var int|string|null
   *   (SQL type: int)
   *   Note that values will be retrieved from the database as a string.
   */
  public $payment_submethod_id;

  /**
   * Language
   *
   * @var string|null
   *   (SQL type: varchar(8))
   *   Note that values will be retrieved from the database as a string.
   */
  public $language;

  /**
   * Country
   *
   * @var string|null
   *   (SQL type: varchar(2))
   *   Note that values will be retrieved from the database as a string.
   */
  public $country;

  /**
   * Tracking Date
   *
   * @var string|null
   *   (SQL type: datetime)
   *   Note that values will be retrieved from the database as a string.
   */
  public $tracking_date;

  /**
   * Operating System
   *
   * @var string|null
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $os;

  /**
   * Operating System - Major Version
   *
   * @var string|null
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $os_version;

  /**
   * Browser
   *
   * @var string|null
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $browser;

  /**
   * Browser Version
   *
   * @var string|null
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $browser_version;

  /**
   * Denotes whether a recurring donation was the result of upsell or an organic recurring transaction
   *
   * @var int|string|null
   *   (SQL type: int)
   *   Note that values will be retrieved from the database as a string.
   */
  public $recurring_choice_id;

  /**
   * The device the banner was served to (e.g Desktop or Mobile)
   *
   * @var int|string|null
   *   (SQL type: int)
   *   Note that values will be retrieved from the database as a string.
   */
  public $device_type_id;

  /**
   * Large or small banner
   *
   * @var int|string|null
   *   (SQL type: int)
   *   Note that values will be retrieved from the database as a string.
   */
  public $banner_size_id;

  /**
   * Test, rather than a control group
   *
   * @var bool|string|null
   *   (SQL type: tinyint)
   *   Note that values will be retrieved from the database as a string.
   */
  public $is_test_variant;

  /**
   * The name of the tested variant (if not control)
   *
   * @var string|null
   *   (SQL type: varchar(128))
   *   Note that values will be retrieved from the database as a string.
   */
  public $banner_variant;

  /**
   * Did the user select to pay the processing fee
   *
   * @var bool|string|null
   *   (SQL type: tinyint)
   *   Note that values will be retrieved from the database as a string.
   */
  public $is_pay_fee;

  /**
   * External mailing identifier
   *
   * @var string|null
   *   (SQL type: varchar(32))
   *   Note that values will be retrieved from the database as a string.
   */
  public $mailing_identifier;

  /**
   * UTM Source. This is the original text but is separately broken out into banner etc. We aspire to drop this field but per T354708 Peter Coombe is still reliant on it
   *
   * @var string|null
   *   (SQL type: varchar(128))
   *   Note that values will be retrieved from the database as a string.
   */
  public $utm_source;

  /**
   * Temporary banner history log ID to associate banner history EventLogging events.
   *
   * @var string|null
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $banner_history_log_id;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_contribution_tracking';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Contribution Trackings') : E::ts('Contribution Tracking');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique Contribution Tracking ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.id',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'contribution_id' => [
          'name' => 'contribution_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Contribution ID'),
          'description' => E::ts('FK to Contribution'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.contribution_id',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contribute_DAO_Contribution',
          'FKColumnName' => 'id',
          'html' => [
            'type' => 'Number',
          ],
          'add' => NULL,
        ],
        'amount' => [
          'name' => 'amount',
          'type' => CRM_Utils_Type::T_MONEY,
          'title' => E::ts('Amount'),
          'description' => E::ts('Amount'),
          'precision' => [
            20,
            3,
          ],
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.amount',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'html' => [
            'type' => 'Decimal',
          ],
          'add' => NULL,
        ],
        'currency' => [
          'name' => 'currency',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Currency'),
          'description' => E::ts('Currency ISO Code'),
          'maxlength' => 3,
          'size' => CRM_Utils_Type::FOUR,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.currency',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'html' => [
            'type' => 'text',
          ],
          'add' => NULL,
        ],
        'usd_amount' => [
          'name' => 'usd_amount',
          'type' => CRM_Utils_Type::T_MONEY,
          'title' => E::ts('Usd Amount'),
          'description' => E::ts('USD Amount'),
          'precision' => [
            20,
            2,
          ],
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.usd_amount',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'html' => [
            'type' => 'Decimal',
          ],
          'add' => NULL,
        ],
        'is_recurring' => [
          'name' => 'is_recurring',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Is Recurring?'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.is_recurring',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'html' => [
            'type' => 'Boolean',
          ],
          'add' => NULL,
        ],
        'referrer' => [
          'name' => 'referrer',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Referrer'),
          'description' => E::ts('Referrer'),
          'maxlength' => 4096,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.referrer',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'utm_medium' => [
          'name' => 'utm_medium',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Utm Medium'),
          'description' => E::ts('UTM Medium'),
          'maxlength' => 128,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.utm_medium',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'utm_campaign' => [
          'name' => 'utm_campaign',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Utm Campaign'),
          'description' => E::ts('UTM Campaign'),
          'maxlength' => 128,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.utm_campaign',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'utm_key' => [
          'name' => 'utm_key',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Utm Key'),
          'description' => E::ts('UTM Key'),
          'maxlength' => 128,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.utm_key',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'gateway' => [
          'name' => 'gateway',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Gateway'),
          'description' => E::ts('Gateway, e.g paypal_ec,adyen'),
          'maxlength' => 32,
          'size' => CRM_Utils_Type::MEDIUM,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.gateway',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'appeal' => [
          'name' => 'appeal',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Appeal'),
          'description' => E::ts('e.g JimmyQuote - the appeal is the text to the left of the input boxes (on desktop-size screens)'),
          'maxlength' => 64,
          'size' => CRM_Utils_Type::BIG,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.appeal',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'payments_form_variant' => [
          'name' => 'payments_form_variant',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Payments Form Variant'),
          'description' => E::ts(' a \'variant\' generally changes something about the input boxes or their labels'),
          'maxlength' => 64,
          'size' => CRM_Utils_Type::BIG,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.payments_form_variant',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'banner' => [
          'name' => 'banner',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Banner'),
          'description' => E::ts('Banner'),
          'maxlength' => 128,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.banner',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'landing_page' => [
          'name' => 'landing_page',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Landing Page'),
          'description' => E::ts('Landing Page'),
          'maxlength' => 128,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.landing_page',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'payment_method_id' => [
          'name' => 'payment_method_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Payment Method Family'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.payment_method_id',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
          ],
          'pseudoconstant' => [
            'optionGroupName' => 'payment_method',
            'optionEditPath' => 'civicrm/admin/options/payment_method',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'payment_submethod_id' => [
          'name' => 'payment_submethod_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Specific Payment Method'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.payment_submethod_id',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
          ],
          'pseudoconstant' => [
            'optionGroupName' => 'payment_instrument',
            'optionEditPath' => 'civicrm/admin/options/payment_instrument',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'language' => [
          'name' => 'language',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Language'),
          'description' => E::ts('Language'),
          'maxlength' => 8,
          'size' => CRM_Utils_Type::EIGHT,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.language',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'country' => [
          'name' => 'country',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Country'),
          'description' => E::ts('Country'),
          'maxlength' => 2,
          'size' => CRM_Utils_Type::TWO,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.country',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'tracking_date' => [
          'name' => 'tracking_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => E::ts('Tracking Date'),
          'description' => E::ts('Tracking Date'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.tracking_date',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'add' => NULL,
        ],
        'os' => [
          'name' => 'os',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Os'),
          'description' => E::ts('Operating System'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.os',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'os_version' => [
          'name' => 'os_version',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Os Version'),
          'description' => E::ts('Operating System - Major Version'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.os_version',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'browser' => [
          'name' => 'browser',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Browser'),
          'description' => E::ts('Browser'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.browser',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'browser_version' => [
          'name' => 'browser_version',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Browser Version'),
          'description' => E::ts('Browser Version'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.browser_version',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'recurring_choice_id' => [
          'name' => 'recurring_choice_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Recurring Choice'),
          'description' => E::ts('Denotes whether a recurring donation was the result of upsell or an organic recurring transaction'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.recurring_choice_id',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
          ],
          'pseudoconstant' => [
            'optionGroupName' => 'recurring_choice',
            'optionEditPath' => 'civicrm/admin/options/recurring_choice',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'device_type_id' => [
          'name' => 'device_type_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Device Type'),
          'description' => E::ts('The device the banner was served to (e.g Desktop or Mobile)'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.device_type_id',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
          ],
          'pseudoconstant' => [
            'optionGroupName' => 'device_type',
            'optionEditPath' => 'civicrm/admin/options/device_type',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'banner_size_id' => [
          'name' => 'banner_size_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Banner Size'),
          'description' => E::ts('Large or small banner'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.banner_size_id',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
          ],
          'pseudoconstant' => [
            'optionGroupName' => 'banner_size',
            'optionEditPath' => 'civicrm/admin/options/banner_size',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'is_test_variant' => [
          'name' => 'is_test_variant',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Is a test variant'),
          'description' => E::ts('Test, rather than a control group'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.is_test_variant',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'add' => NULL,
        ],
        'banner_variant' => [
          'name' => 'banner_variant',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Banner Variant'),
          'description' => E::ts('The name of the tested variant (if not control)'),
          'maxlength' => 128,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.banner_variant',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'is_pay_fee' => [
          'name' => 'is_pay_fee',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('User opted to pay fee (PTF)'),
          'description' => E::ts('Did the user select to pay the processing fee'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.is_pay_fee',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'add' => NULL,
        ],
        'mailing_identifier' => [
          'name' => 'mailing_identifier',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Mailing Identifier'),
          'description' => E::ts('External mailing identifier'),
          'maxlength' => 32,
          'size' => CRM_Utils_Type::MEDIUM,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.mailing_identifier',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'utm_source' => [
          'name' => 'utm_source',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('UTM Source'),
          'description' => E::ts('UTM Source. This is the original text but is separately broken out into banner etc. We aspire to drop this field but per T354708 Peter Coombe is still reliant on it'),
          'maxlength' => 128,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.utm_source',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'banner_history_log_id' => [
          'name' => 'banner_history_log_id',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Banner History Log ID'),
          'description' => E::ts('Temporary banner history log ID to associate banner history EventLogging events.'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.banner_history_log_id',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'contribution_tracking', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'contribution_tracking', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'currency' => [
        'name' => 'currency',
        'field' => [
          0 => 'currency',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_contribution_tracking::0::currency',
      ],
      'utm_medium_id' => [
        'name' => 'utm_medium_id',
        'field' => [
          0 => 'utm_medium',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_contribution_tracking::0::utm_medium',
      ],
      'utm_campaign_id' => [
        'name' => 'utm_campaign_id',
        'field' => [
          0 => 'utm_campaign',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_contribution_tracking::0::utm_campaign',
      ],
      'banner' => [
        'name' => 'banner',
        'field' => [
          0 => 'banner',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_contribution_tracking::0::banner',
      ],
      'landing_page' => [
        'name' => 'landing_page',
        'field' => [
          0 => 'landing_page',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_contribution_tracking::0::landing_page',
      ],
      'payment_method_id' => [
        'name' => 'payment_method_id',
        'field' => [
          0 => 'payment_method_id',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_contribution_tracking::0::payment_method_id',
      ],
      'language' => [
        'name' => 'language',
        'field' => [
          0 => 'language',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_contribution_tracking::0::language',
      ],
      'country' => [
        'name' => 'country',
        'field' => [
          0 => 'country',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_contribution_tracking::0::country',
      ],
      'tracking_date' => [
        'name' => 'tracking_date',
        'field' => [
          0 => 'tracking_date',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_contribution_tracking::0::tracking_date',
      ],
      'index_mailing_identifier' => [
        'name' => 'index_mailing_identifier',
        'field' => [
          0 => 'mailing_identifier',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_contribution_tracking::0::mailing_identifier',
      ],
      'banner_history_log_id' => [
        'name' => 'banner_history_log_id',
        'field' => [
          0 => 'mailing_identifier',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_contribution_tracking::0::banner_history_log_id',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
