<?php
/*
+--------------------------------------------------------------------+
| CiviCRM version 4.7                                                |
+--------------------------------------------------------------------+
| Copyright CiviCRM LLC (c) 2004-2017                                |
+--------------------------------------------------------------------+
| This file is a part of CiviCRM.                                    |
|                                                                    |
| CiviCRM is free software; you can copy, modify, and distribute it  |
| under the terms of the GNU Affero General Public License           |
| Version 3, 19 November 2007 and the CiviCRM Licensing Exception.   |
|                                                                    |
| CiviCRM is distributed in the hope that it will be useful, but     |
| WITHOUT ANY WARRANTY; without even the implied warranty of         |
| MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               |
| See the GNU Affero General Public License for more details.        |
|                                                                    |
| You should have received a copy of the GNU Affero General Public   |
| License and the CiviCRM Licensing Exception along                  |
| with this program; if not, contact CiviCRM LLC                     |
| at info[AT]civicrm[DOT]org. If you have questions about the        |
| GNU Affero General Public License or the licensing of CiviCRM,     |
| see the CiviCRM license FAQ at http://civicrm.org/licensing        |
+--------------------------------------------------------------------+
*/
/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2017
 *
 * Generated from xml/schema/CRM/Dedupetools/MergeConflict.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:fc4048ac266452c77403f4d2c3a168dc)
 */
require_once 'CRM/Core/DAO.php';
require_once 'CRM/Utils/Type.php';
/**
 * CRM_Dedupetools_DAO_MergeConflict constructor.
 */
class CRM_Dedupetools_DAO_MergeConflict extends CRM_Core_DAO {
  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  static $_tableName = 'civicrm_mergeconflict';
  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var boolean
   */
  static $_log = false;
  /**
   * Unique MergeConflict ID
   *
   * @var int unsigned
   */
  public $id;
  /**
   * FK to Contact
   *
   * @var int unsigned
   */
  public $contact_id;
  /**
   * Class constructor.
   */
  function __construct() {
    $this->__table = 'civicrm_merge_conflict';
    parent::__construct();
  }
  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = array(
        'id' => array(
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'Unique MergeConflict ID',
          'required' => true,
          'table_name' => 'civicrm_mergeconflict',
          'entity' => 'MergeConflict',
          'bao' => 'CRM_Dedupetools_DAO_MergeConflict',
          'localizable' => 0,
        ),
        'contact_1' => array(
          'name' => 'contact_1',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'FK to Contact',
          'table_name' => 'civicrm_merge_conflict',
          'entity' => 'MergeConflict',
          'bao' => 'CRM_Dedupetools_DAO_MergeConflict',
          'localizable' => 0,
        ),
        'contact_2' => array(
          'name' => 'contact_2',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'FK to Contact',
          'table_name' => 'civicrm_merge_conflict',
          'entity' => 'MergeConflict',
          'bao' => 'CRM_Dedupetools_DAO_MergeConflict',
          'localizable' => 0,
        ),
        'group_id' => array(
          'name' => 'group_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'FK to Group',
          'table_name' => 'civicrm_merge_conflict',
          'entity' => 'MergeConflict',
          'bao' => 'CRM_Dedupetools_DAO_MergeConflict',
          'localizable' => 0,
        ),
        'conflicted_field' => array(
          'name' => 'conflicted_field',
          'type' => CRM_Utils_Type::T_STRING,
          'table_name' => 'civicrm_merge_conflict',
          'entity' => 'MergeConflict',
          'bao' => 'CRM_Dedupetools_DAO_MergeConflict',
          'localizable' => 0,
        ),
        'value1' => array(
          'name' => 'value1',
          'type' => CRM_Utils_Type::T_STRING,
          'table_name' => 'civicrm_merge_conflict',
          'entity' => 'MergeConflict',
          'bao' => 'CRM_Dedupetools_DAO_MergeConflict',
          'localizable' => 0,
        ),
        'value2' => array(
          'name' => 'value2',
          'type' => CRM_Utils_Type::T_STRING,
          'table_name' => 'civicrm_merge_conflict',
          'entity' => 'MergeConflict',
          'bao' => 'CRM_Dedupetools_DAO_MergeConflict',
          'localizable' => 0,
        ),
        'analysis' => array(
          'name' => 'analysis',
          'type' => CRM_Utils_Type::T_STRING,
          'table_name' => 'civicrm_merge_conflict',
          'entity' => 'MergeConflict',
          'bao' => 'CRM_Dedupetools_DAO_MergeConflict',
          'localizable' => 0,
        ),
      );
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }
  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }
  /**
   * Returns the names of this table
   *
   * @return string
   */
  static function getTableName() {
    return self::$_tableName;
  }
  /**
   * Returns if this table needs to be logged
   *
   * @return boolean
   */
  function getLog() {
    return self::$_log;
  }
  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  static function &import($prefix = false) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'mergeconflict', $prefix, array());
    return $r;
  }
  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  static function &export($prefix = false) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'mergeconflict', $prefix, array());
    return $r;
  }
  /**
   * Returns the list of indices
   */
  public static function indices($localize = TRUE) {
    $indices = array();
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }
}
