<?php

use wmf_communication\Mailer;
use wmf_communication\Templating;

/**
 * Implementation of hook_menu().
 */
function large_donation_menu() {

  $items = array();

  $items['admin/config/large_donation'] = array(
    'title' => 'Large Donation Processor',
    'access arguments' => array('administer large_donation'),
    'page callback' => 'system_admin_menu_block_page',
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  $items['admin/config/large_donation/configure'] = array(
    'title' => 'Configure',
    'description' => 'Configure large donation settings.',
    'access arguments' => array('administer large_donation'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('large_donation_settings'),
  );

  return $items;
}

/**
 * Implementation of hook_permission().
 */
function large_donation_permission() {
  return array(
    'administer large_donation' => array(
      'title' => t('Administer Large Donations'),
    ),
  );
}

/**
 * Callback for menu path "admin/config/large_donation".
 */
function large_donation_settings( $formId, $formState ) {
  $form = array();

  // Should we display a blank new entry for adding a threshold level?
  $plus_new_level = isset( $formState['clicked_button'] )
      && $formState['clicked_button']['#attributes']['id'] === 'add_threshold';

  // Are we deleting something?
  $is_deleting = isset( $formState['clicked_button'] )
      && $formState['clicked_button']['#attributes']['class'] === array( 'delete' );

  if ( $is_deleting ) {
      preg_match( '/^delete_(\d+|NEW)$/', $formState['clicked_button']['#attributes']['id'], $matches );
      $id = $matches[1];
      if ( $id !== 'NEW' ) {
          db_delete( 'large_donation_notification' )
            ->condition( 'id', $id, '=' )
            ->execute();

          drupal_set_message( "Deleted notification threshold with id={$id}.", 'warning' );
      }
  }

  $result = db_select( 'large_donation_notification' )
      ->fields( 'large_donation_notification' )
      ->condition( 'enabled', true, '=' )
      ->orderBy( 'threshold', 'ASC' )
      ->execute();

  $levels = $result->fetchAllAssoc( 'id', PDO::FETCH_ASSOC );

  if ( $plus_new_level ) {
      $levels[] = array(
          'id' => 'NEW',
          'threshold' => '',
          'addressee' => '',
      );
  }

  $uiIndex = 1;
  foreach ( $levels as $row ) {
      $form["group_{$row['id']}"] = array(
          '#type' => 'fieldset',
      );

      $form["group_{$row['id']}"]["delete_{$row['id']}"] = array(
          '#type' => 'button',
          '#value' => t( 'Delete notification !index', array( '!index' => $uiIndex ) ),
          '#attributes' => array(
              'id' => "delete_{$row['id']}",
              'class' => array( 'delete' ),
          ),
      );

      $form["group_{$row['id']}"]["threshold_{$row['id']}"] = array(
          '#type' => 'textfield',
          '#title' => t( 'Large donation value !index', array( '!index' => $uiIndex ) ),
          '#required' => TRUE,
          '#default_value' => $row['threshold'],
          '#description' => t( 'Donations over this amount (USD) will trigger an email.' ),
      );

      $form["group_{$row['id']}"]["addressee_{$row['id']}"] = array(
          '#type' => 'textarea',
          '#title' => t( 'Email Notification Addresses !index', array( '!index' => $uiIndex ) ),
          '#required' => FALSE,
          '#default_value' => $row['addressee'],
          '#description' => t( 'Addresses, separated by commas or newlines, to be notified on large contributions.' ),
      );

      $uiIndex++;
  }

  $form['add_threshold'] = array(
      '#type' => 'button',
      '#value' => t( 'Add threshold level' ),
      '#attributes' => array(
          'id' => 'add_threshold',
      ),
  );

  $form['submit'] = array(
      '#type' => 'submit',
      '#value' => t( 'Save configuration' ),
  );

  return $form;
}

function large_donation_settings_submit( $form, $formState ) {
    foreach ( $formState['values'] as $field => $value ) {
        if ( preg_match( '/^threshold_(\d+|NEW)$/', $field, $matches ) ) {
            $id = $matches[1];
            $addressee = $formState['values']["addressee_{$id}"];

            if ( $id === 'NEW' ) {
                drupal_set_message( "Added a new threshold level." );
                $id = null;
            }
            db_merge( 'large_donation_notification' )
                ->key( array( 'id' => $id ) )
                ->fields( array(
                    'threshold' => $value,
                    'addressee' => $addressee,
                ) )
                ->execute();
        }
    }

    drupal_set_message( "Saved the configuration." );
}

/**
 * Implements hook_civicrm_post
 */
function large_donation_civicrm_post( $action, $type, $id, &$contribution ) {
    switch ( $action ) {
    case 'create':
        if ( $type === 'Contribution' ) {
            $dbs = wmf_civicrm_get_dbs();
            $dbs->push( 'default' );

            $result = db_select( 'large_donation_notification' )
                ->fields( 'large_donation_notification' )
                ->condition( 'threshold', (float) $contribution->total_amount, '<=' )
                ->condition( 'enabled', true, '=' )
                ->execute();

            $count = 0;
            while ( $notification = $result->fetch() ) {
                $count++;
                watchdog( 'large_donation', "Notifying of large donation, contribution: {$contribution->id} above threshold {$notification->threshold}" );

                large_donation_notification_send( $contribution, $notification );
            }
            
            if ( !$count ) {
                watchdog( 'large_donation', "Donation amount {$contribution->total_amount} was not above the lowest notification threshold." );
            }
        }
        break;
    default:
    }
}

/**
 * large_donation_notification
 *
 * The email should include the total amount, source amount, contact and
 * contribution ids, and a link to the contact/contribution.
 *
 * No personally identifiable information should be included.
 *
 * @param CRM_Contribute_BAO_Contribution $contribution
 * @param stdClass $notification
 */
function large_donation_notification_send( $contribution, $notification ) {
    $contact_link = CRM_Utils_System::url(
        'civicrm/contact/view',
        array(
            'selectedChild' => 'contribute',
            'cid' => $contribution->contact_id,
            'reset' => 1,
        ),
        true,
        'Contributions'
    );

    $contribution_link = CRM_Utils_System::url(
        'civicrm/contact/view/contribution',
        array(
            'action' => 'view',
            'id' => $contribution->id,
            'reset' => 1,
        ),
        true
    );

    $to = $notification->addressee;

    $params = array(
        'threshold' => floatval( $notification->threshold ),
        'contribution' => $contribution,
        'contact_link' => $contact_link,
        'contribution_link' => $contribution_link,
    );

    if ( !$to ) {
        watchdog( 'large_donation', 'Notification recipient address is not set up!', NULL, WATCHDOG_ERROR );
        return;
    }

    $mailer = Mailer::getDefault();

    $template = new Templating( __DIR__ . '/templates', 'notification', 'en', $params, 'html' );
    $message = $template->render();

    try {
        $email = array(
            'to' => $to,
            'from_address' => 'fr-tech+large_donation@wikimedia.org',
            'from_name' => 'Large Donation Bot',
            'subject' => "WMF - large donation: \${$contribution->total_amount}",
            'html' => $message,
        );
        $mailer->send( $email );
		watchdog('large_donation', 'A large donation notification was sent to: ' . print_r( $to, true ) );
    } catch ( Exception $e ) {
        watchdog('large_donation', 'Sending large donation message failed for contribution: ' . $contribution->id . '<pre>' . check_plain(print_r($contribution, TRUE)) . "\n\n" . $e->getMessage() . '</pre>', array(), WATCHDOG_ERROR);
    }
}
