<?php

/**
 * Implements hook_menu
 */
function wmf_refund_qc_menu() {
  $items[ 'admin/config/queue2civicrm/refund_qc' ] = array(
    'title'            => 'Refund',
    'description'      => 'Configure refund queue settings',
    'access arguments' => array( 'administer queue2civicrm' ),
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array( 'refund_qc_settings' ),
  );
  return $items;
}

/**
 * Constructs the settings page for this module.
 *
 * @return array Of form components.
 */
function refund_qc_settings() {
  $form = array();

  $form[ 'refund_qc' ][ 'description' ] = array(
    '#type'        => 'fieldset',
    '#title'       => t('Refund queue'),
    '#description' => t('This queue contains refund notifications, usually sent by the gateway to our IPN listener, or a nightly audit manifest.  We honor these notifications by refunding the associated contributions in our CRM.'),
    '#collapsible' => FALSE,
    '#collapsed'   => FALSE,
  );

  $form[ 'refund_qc' ][ 'refund_queue' ] = array(
    '#type'          => 'textfield',
    '#title'         => t('Subscription path'),
    '#required'      => TRUE,
    '#default_value' => variable_get('refund_queue', '/queue/refund-notifications_test'),
    '#description'   => t('Queue for refund notifications'),
  );

  $form[ 'refund_qc' ][ 'refund_batch' ] = array(
    '#type'          => 'select',
    '#title'         => t('Cron batch size'),
    '#description'   => t('Maximum number of donations processed by a refund job'),
    '#required'      => TRUE,
    '#default_value' => variable_get('refund_batch', 0),
    '#options'       => array(
      0   => '0 (Disable)',
      1   => 1,
      5   => 5,
      10  => 10,
      25  => 25,
      50  => 50,
      75  => 75,
      100 => 100,
      125 => 125,
      150 => 150,
      200 => 200,
      250 => 250,
      300 => 300,
      500 => 500,
      750 => 750,
      1000 => 1000
    ),
  );

  return system_settings_form($form);
}

/**
 * Callback from Drush that actually executes the loop for processing messages in the queue.
 * @ref refund_process_message
 * @ref drush_refund_queue_consume
 */
function refund_batch_process() {
  civicrm_api_classapi(); # hah

  watchdog('refund', 'Executing: refund_batch_process');

  $q = queue2civicrm_stomp();
  $processed = $q->dequeue_loop(
    variable_get('refund_queue', '/queue/refund-notifications_test'),
    variable_get('refund_batch', 0),
    'refund_import'
  );

  if ($processed > 0) {
    watchdog('refund', 'Successfully processed ' . $processed . ' refund(s).');
  }
  else {
    watchdog('refund', 'No refunds processed.');
  }
}

/**
 * @param $msg A STOMP message class.
 */
function refund_import($msg) {
  $txnid = $msg->headers['correlation-id'];
  watchdog('refund', "Beginning processing of message $txnid: " . json_encode($msg), array(), WATCHDOG_INFO);

  // Sanity checking :)
  $required_fields = array( "gateway_refund_id", "gateway_parent_id", "gross_currency", "gross", "date", "gateway",
    "type",
  );
  $body = json_decode($msg->body, TRUE);
  foreach( $required_fields as $field_name ) {
    if ( !array_key_exists( $field_name, $body ) ) {
      $error = "$txnid: Required field '$field_name' not present! Dropping message on floor.";
      throw new WmfException( 'CIVI_REQ_FIELD', $error );
    }
  }

  $gateway = strtoupper($body['gateway']);
  $parentTxn = $body['gateway_parent_id'];
  $refundTxn = $body['gateway_refund_id'];

  if ( $body['gross'] < 0 ) {
    $body['gross'] = abs( $body['gross'] );
  }

  // FIXME: these WATCHDOG_ERROR's are not exceptions?
  if ( $contributions = wmf_civicrm_get_contributions_from_gateway_id( $gateway, $parentTxn ) ) {
    // Perform the refund!
    try {
      wmf_civicrm_mark_refund( $contributions[0]['id'], $body['type'], true, $body['date'],
        $refundTxn,
        $body['gross_currency'],
        $body['gross']
      );

      watchdog('refund', "$txnid: Successfully marked as refunded", WATCHDOG_INFO);
    } catch (Exception $ex) {
      watchdog('refund', "$txnid: Could not refund due to internal error: " . $ex->getMessage(), WATCHDOG_ERROR);
      throw $ex;
    }
  } else {
    watchdog( 'refund', "$txnid: Contribution not found for this transaction!", WATCHDOG_ERROR );
    throw new WmfException( 'MISSING_PREDECESSOR', "Parent not found: $parentTxn" );
  }
}
