<?php
return [
  [
    'name' => 'SavedSearch_Damaged_Table',
    'entity' => 'SavedSearch',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Damaged_Table',
        'label' => 'Damaged Table',
        'form_values' => NULL,
        'mapping_id' => NULL,
        'search_custom_id' => NULL,
        'api_entity' => 'Damaged',
        'api_params' => [
          'version' => 4,
          'select' => [
            'id',
            'original_date',
            'damaged_date',
            'original_queue',
            'gateway',
            'order_id',
            'gateway_txn_id',
            'error',
          ],
          'orderBy' => [],
          'where' => [],
          'groupBy' => [],
          'join' => [],
          'having' => [],
        ],
        'expires_date' => NULL,
        'description' => NULL,
      ],
    ],
  ],
  [
    'name' => 'SavedSearch_Damaged_Table_SearchDisplay_Damageds_Table_1',
    'entity' => 'SearchDisplay',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Damageds_Table_1',
        'label' => 'Damaged Table 1',
        'saved_search_id.name' => 'Damaged_Table',
        'type' => 'table',
        'settings' => [
          'actions' => TRUE,
          'limit' => 50,
          'classes' => [
            'table',
            'table-striped',
          ],
          'pager' => [],
          'placeholder' => 5,
          'sort' => [
            [
              'original_date',
              'DESC',
            ],
          ],
          'columns' => [
            [
              'type' => 'field',
              'key' => 'id',
              'dataType' => 'Integer',
              'label' => 'id',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'original_date',
              'dataType' => 'Timestamp',
              'label' => 'Original Date',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'damaged_date',
              'dataType' => 'Timestamp',
              'label' => 'Damaged Date',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'original_queue',
              'dataType' => 'String',
              'label' => 'Original Queue',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'gateway',
              'dataType' => 'String',
              'label' => 'Gateway',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'order_id',
              'dataType' => 'String',
              'label' => 'order_id',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'gateway_txn_id',
              'dataType' => 'String',
              'label' => 'gateway_txn_id',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'error',
              'dataType' => 'Text',
              'label' => 'Error',
              'sortable' => TRUE,
              'rewrite' => '{"[error]"|truncate:100:"..."}',
              'link' => [
                'path' => '',
                'entity' => 'Damaged',
                'action' => 'update',
                'join' => '',
                'target' => 'crm-popup',
              ],
              'title' => 'Edit Damaged',
            ],
            [
              'size' => 'btn-xs',
              'links' => [
                [
                  'entity' => 'Damaged',
                  'action' => 'delete',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-trash',
                  'text' => 'Delete',
                  'style' => 'danger',
                  'path' => '',
                  'condition' => [],
                ],
              ],
              'type' => 'buttons',
              'alignment' => 'text-right',
            ],
          ],
        ],
        'acl_bypass' => FALSE,
      ],
    ],
  ],
];
