<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from deduper/xml/schema/CRM/Deduper/ContactNamePairFamily.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:470f4478c9554216d9ebd818bd650a5c)
 */
use CRM_Deduper_ExtensionUtil as E;

/**
 * Database access object for the ContactNamePairFamily entity.
 */
class CRM_Deduper_DAO_ContactNamePairFamily extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_contact_name_pair_family';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique ContactNamePair ID
   *
   * @var int
   */
  public $id;

  /**
   * Family name (generally the anglicised options)
   *
   * @var string
   */
  public $name_a;

  /**
   * Alternate name
   *
   * @var string
   */
  public $name_b;

  /**
   * Is this the most common way to write this name?
   *
   * @var bool
   */
  public $is_most_common_form;

  /**
   * Is this variant active?
   *
   * @var bool
   */
  public $is_active;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_contact_name_pair_family';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Contact Name Pair Families') : E::ts('Contact Name Pair Family');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('Unique ContactNamePair ID'),
          'required' => TRUE,
          'where' => 'civicrm_contact_name_pair_family.id',
          'table_name' => 'civicrm_contact_name_pair_family',
          'entity' => 'ContactNamePairFamily',
          'bao' => 'CRM_Deduper_DAO_ContactNamePairFamily',
          'localizable' => 0,
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'name_a' => [
          'name' => 'name_a',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Name A'),
          'description' => E::ts('Family name (generally the anglicised options)'),
          'maxlength' => 64,
          'size' => 30,
          'where' => 'civicrm_contact_name_pair_family.name_a',
          'table_name' => 'civicrm_contact_name_pair_family',
          'entity' => 'ContactNamePairFamily',
          'bao' => 'CRM_Deduper_DAO_ContactNamePairFamily',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'name_b' => [
          'name' => 'name_b',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Name B'),
          'description' => E::ts('Alternate name'),
          'maxlength' => 64,
          'size' => 30,
          'where' => 'civicrm_contact_name_pair_family.name_b',
          'table_name' => 'civicrm_contact_name_pair_family',
          'entity' => 'ContactNamePairFamily',
          'bao' => 'CRM_Deduper_DAO_ContactNamePairFamily',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'is_most_common_form' => [
          'name' => 'is_most_common_form',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Most common form?'),
          'description' => E::ts('Is this the most common way to write this name?'),
          'where' => 'civicrm_contact_name_pair_family.is_most_common_form',
          'default' => '0',
          'table_name' => 'civicrm_contact_name_pair_family',
          'entity' => 'ContactNamePairFamily',
          'bao' => 'CRM_Deduper_DAO_ContactNamePairFamily',
          'localizable' => 0,
          'html' => [
            'type' => 'CheckBox',
          ],
          'add' => NULL,
        ],
        'is_active' => [
          'name' => 'is_active',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Is active?'),
          'description' => E::ts('Is this variant active?'),
          'where' => 'civicrm_contact_name_pair_family.is_active',
          'default' => '1',
          'table_name' => 'civicrm_contact_name_pair_family',
          'entity' => 'ContactNamePairFamily',
          'bao' => 'CRM_Deduper_DAO_ContactNamePairFamily',
          'localizable' => 0,
          'html' => [
            'type' => 'CheckBox',
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'contact_name_pair_family', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'contact_name_pair_family', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'name_a' => [
        'name' => 'name_a',
        'field' => [
          0 => 'name_a',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_contact_name_pair_family::0::name_a',
      ],
      'name_b' => [
        'name' => 'name_b',
        'field' => [
          0 => 'name_b',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_contact_name_pair_family::0::name_b',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
