<?php

/**
 * Implementation of hook_menu()
 */
function fundraiseup_audit_menu() {
  $items = [];

  $items['admin/config/wmf_audit/fundraiseup_audit'] = [
    'title' => 'fundraiseup Audit',
    'description' => t('Configure fundraiseup audit settings.'),
    'access arguments' => ['administer wmf_audit'],
    'page callback' => 'drupal_get_form',
    'page arguments' => ['fundraiseup_audit_settings'],
  ];

  return $items;
}

/**
 * Callback for menu
 */
function fundraiseup_audit_settings() {
  $form['fundraiseup_audit_recon_files_dir'] = [
    '#type' => 'textfield',
    '#title' => t('Directory containing incoming reconciliation files'),
    '#required' => TRUE,
    '#default_value' => variable_get('fundraiseup_audit_recon_files_dir'),
  ];
  $form['fundraiseup_audit_recon_completed_dir'] = [
    '#type' => 'textfield',
    '#title' => t('Directory for completed reconciliation files'),
    '#required' => TRUE,
    '#default_value' => variable_get('fundraiseup_audit_recon_completed_dir'),
  ];
  $form['fundraiseup_audit_test_mode'] = [
    '#type' => 'checkbox',
    '#title' => t('When this box is checked, no queue messages will be sent.'),
    '#required' => FALSE,
    '#default_value' => variable_get('fundraiseup_audit_test_mode'),
  ];
  return system_settings_form($form);
}

function fundraiseup_audit_create_processor($options) {
  return new FundraiseupAuditProcessor($options);
}
