<div class="help">
<p>This page shows the segments & donor statuses currently being generated by WMF code</p>
<p>The phab was <a target="_blank" href="https://phabricator.wikimedia.org/T336305">donor segments</a>
and the segments were initially described in this <a target="_blank" href="https://docs.google.com/spreadsheets/d/1qM36MeKWyOENl-iR5umuLph5HLHG6W_6c46xJUdE3QY/edit#gid=1786541006"> google doc</a>
</p>
<p>A contact will be assigned to the first segment / status they match (from the top/ lowest)</p>
</div>

<h3 style="margin: 0px 0px 10px 0px;">Segments</h3>
<table class="row-highlight">
      <tr>
        <th>Label</th>
        <th>Description</th>
        <th>Value</th>
      </tr>
  {foreach from=$segments item='segment'}
      <tr>
        <td>{$segment.label}</td>
        <td>{$segment.description|nl2br}</td>
        <td>{$segment.value}</td>
      </tr>
  {/foreach}
</table>

<h3 style="margin: 10px 0px;">Statuses</h3>
<table class="row-highlight">
      <tr>
        <th>Label</th>
        <th>Description</th>
        <th>Value</th>
      </tr>
    {foreach from=$statuses item='status'}
      <tr>
        <td>{$status.label}</td>
        <td>{$status.description|nl2br}</td>
        <td>{$status.value}</td>
      </tr>
    {/foreach}
</table>
