<?php

/**
 * Implementation of hook_menu()
 */
function dlocal_audit_menu() {
  $items = [];

  $items['admin/config/wmf_audit/dlocal_audit'] = [
    'title' => 'Dlocal Audit',
    'description' => t('Configure WMF audit settings.'),
    'access arguments' => ['administer wmf_audit'],
    'page callback' => 'drupal_get_form',
    'page arguments' => ['dlocal_audit_settings'],
  ];

  return $items;
}

/**
 * Callback for menu
 */
function dlocal_audit_settings() {
  $form['dlocal_audit_log_search_past_days'] = [
    '#type' => 'textfield',
    '#title' => t('Plus or minus log search (in days)'),
    '#required' => TRUE,
    '#default_value' => variable_get('dlocal_audit_log_search_past_days'),
  ];
  return system_settings_form($form);
}

function dlocal_audit_create_processor($options) {
  return new DlocalAuditProcessor($options);
}
