<?php

function amazon_audit_create_processor($options) {
  /**
   * To override default audit parser settings, edit the SmashPig
   * processor configuration amazon/main.yaml:
   *
   * audit:
   *     file-types:
   *         - SmashPig\PaymentProviders\Amazon\Audit\RefundReport
   *         - SmashPig\PaymentProviders\Amazon\Audit\SettlementReport
   *
   */
  return new AmazonAuditProcessor($options);
}
