<?php

/**
 * Implementation of hook_menu()
 */
function amazon_audit_menu() {
  $items = [];

  $items['admin/config/wmf_audit/amazon_audit'] = [
    'title' => 'Amazon Audit',
    'description' => t('Configure WMF audit settings.'),
    'access arguments' => ['administer wmf_audit'],
    'page callback' => 'drupal_get_form',
    'page arguments' => ['amazon_audit_settings'],
  ];

  return $items;
}

/**
 * Callback for menu
 */
function amazon_audit_settings() {
  $form['amazon_audit_log_search_past_days'] = [
    '#type' => 'textfield',
    '#title' => t('Plus or minus log search (in days)'),
    '#required' => TRUE,
    '#default_value' => variable_get('amazon_audit_log_search_past_days'),
  ];
  return system_settings_form($form);
}

function amazon_audit_create_processor($options) {
  /**
   * To override default audit parser settings, edit the SmashPig
   * processor configuration amazon/main.yaml:
   *
   * audit:
   *     file-types:
   *         - SmashPig\PaymentProviders\Amazon\Audit\RefundReport
   *         - SmashPig\PaymentProviders\Amazon\Audit\SettlementReport
   *
   */
  return new AmazonAuditProcessor($options);
}
