<?php

use \SmashPig\Core\UtcDate;

function orphan_slayer_process_orphans($gateway, $age, $batch, $timeLimit) {
  $startTime = time();
  $slain = 0;
  $secondsElapsed = 0;
  $slayer = new OrphanSlayer($gateway);
  $orphan = $slayer->get_oldest();
  while (
    $orphan && ($orphan['date'] < UtcDate::getUtcTimestamp("-$age minutes")) &&
    ($batch === 0 || $slain < $batch) &&
    ($timeLimit === 0 || $secondsElapsed < $timeLimit)
  ) {
    if ($orphan['contribution_tracking_id']) {
      $result = $slayer->rectify($orphan);
      \Civi::log('wmf')->info('orphan slayer: orphan {contribution_tracking_id}: was rectified and the result is {result}', [
        'contribution_tracking_id' => $orphan['contribution_tracking_id'],
        'result' =>  print_r($result, TRUE),
      ]);
    }
    else {
      $slayer->cancel($orphan);
    }
    $slain++;
    $secondsElapsed = time() - $startTime;
    $orphan = $slayer->get_oldest();
  }
  if ($batch > 0 && $slain >= $batch) {
    \Civi::log('wmf')->info('orphan slayer: Reached batch limit of {batch} orphans', ['batch' => $batch]);
  }
  if ($timeLimit > 0 && $secondsElapsed >= $timeLimit) {
    \Civi::log('wmf')->info('orphan slayer: Reached time limit of {time_limit} seconds', ['time_limit' => $timeLimit]);
  }
  \Civi::log('wmf')->info('orphan slayer: Slayed $slain orphans in {seconds_elapsed} seconds', ['seconds_elapsed' => $secondsElapsed]);
}
