<?php

/*
 +--------------------------------------------------------------------+
 | Copyright CiviCRM LLC. All rights reserved.                        |
 |                                                                    |
 | This work is published under the GNU AGPLv3 license with some      |
 | permitted exceptions and without any warranty. For full license    |
 | and copyright information, see https://civicrm.org/licensing       |
 +--------------------------------------------------------------------+
 */

namespace Civi\Api4\Action\ExampleData;

use Civi\Api4\Generic\BasicGetAction;
use Civi\Api4\Generic\Result;
use Civi\Test\ExampleDataLoader;

/**
 * Get a list of example data-sets.
 *
 * Examples are generated by scanning `ExampleDataInterface` files. The scanner caches
 * metadata fields (`name`, `title`, `tags`, `file`) to avoid extraneous scanning, but
 * substantive fields (`data`) are computed as-needed.
 *
 * @method string getLanguage()
 * @method $this setLanguage(string $language)
 *
 * FIXME: When we have an update for dev-docs, include a `@link` here.
 */
class Get extends BasicGetAction {

  /**
   * Specify the language to use if this is a multi-lingual environment.
   *
   * E.g. "en_US" or "fr_CA"
   *
   * @var string
   */
  protected $language;

  public function _run(Result $result) {
    if ($this->getLanguage()) {
      // On destruct the language swaps back again.
      $swapLocale = \CRM_Utils_AutoClean::swapLocale($this->getLanguage());
    }

    if ($this->select !== [] && !in_array('name', $this->select)) {
      $this->select[] = 'name';
    }
    parent::_run($result);
  }

  protected function getRecords() {
    return \Civi\Test::examples()->getMetas();
  }

  protected function selectArray($values) {
    $result = parent::selectArray($values);

    $heavyFields = array_intersect(
      explode(',', ExampleDataLoader::HEAVY_FIELDS),
      $this->select ?: []
    );
    if (!empty($heavyFields)) {
      foreach ($result as &$item) {
        $heavy = \Civi\Test::examples()->getFull($item['name']);
        $item = array_merge($item, \CRM_Utils_Array::subset($heavy, $heavyFields));
      }
    }

    return $result;
  }

}
