-- +--------------------------------------------------------------------+
-- | CiviCRM version 5       |
-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC (c) 2004-2020                                |
-- +--------------------------------------------------------------------+
-- | This file is a part of CiviCRM.                                    |
-- |                         |
-- | CiviCRM is free software; you can copy, modify, and distribute it  |
-- | under the terms of the GNU Affero General Public License           |
-- | Version 3, 19 November 2007 and the CiviCRM Licensing Exception.   |
-- |                         |
-- | CiviCRM is distributed in the hope that it will be useful, but     |
-- | WITHOUT ANY WARRANTY; without even the implied warranty of         |
-- | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               |
-- | See the GNU Affero General Public License for more details.        |
-- |                         |
-- | You should have received a copy of the GNU Affero General Public   |
-- | License and the CiviCRM Licensing Exception along                  |
-- | with this program; if not, contact CiviCRM LLC                     |
-- | at info[AT]civicrm[DOT]org. If you have questions about the        |
-- | GNU Affero General Public License or the licensing of CiviCRM,     |
-- | see the CiviCRM license FAQ at http://civicrm.org/licensing        |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--


-- +--------------------------------------------------------------------+
-- | CiviCRM version 5       |
-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC (c) 2004-2020                                |
-- +--------------------------------------------------------------------+
-- | This file is a part of CiviCRM.                                    |
-- |                         |
-- | CiviCRM is free software; you can copy, modify, and distribute it  |
-- | under the terms of the GNU Affero General Public License           |
-- | Version 3, 19 November 2007 and the CiviCRM Licensing Exception.   |
-- |                         |
-- | CiviCRM is distributed in the hope that it will be useful, but     |
-- | WITHOUT ANY WARRANTY; without even the implied warranty of         |
-- | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               |
-- | See the GNU Affero General Public License for more details.        |
-- |                         |
-- | You should have received a copy of the GNU Affero General Public   |
-- | License and the CiviCRM Licensing Exception along                  |
-- | with this program; if not, contact CiviCRM LLC                     |
-- | at info[AT]civicrm[DOT]org. If you have questions about the        |
-- | GNU Affero General Public License or the licensing of CiviCRM,     |
-- | see the CiviCRM license FAQ at http://civicrm.org/licensing        |
-- +--------------------------------------------------------------------+
--
-- Generated from drop.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the exisiting tables
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_mergeconflict`;
DROP TABLE IF EXISTS `civicrm_contact_name_pair`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_contact_name_pair
-- *
-- * Pairs of names which are equivalent
-- *
-- *******************************************************/
CREATE TABLE `civicrm_contact_name_pair` (

     `id` int unsigned NOT NULL AUTO_INCREMENT  COMMENT 'Unique ContactNamePair ID',
     `name_a` varchar(64)    COMMENT 'First name (this is the master, if that matters)',
     `name_b` varchar(64)    COMMENT 'Second name (if one name is a nickname or a mis-spelling it will be this one)',
     `is_name_b_nickname` tinyint   DEFAULT 0 ,
     `is_name_b_inferior` tinyint   DEFAULT 0,
  PRIMARY KEY (`id`),
     INDEX `name_a`(name_a),
     INDEX `name_b`(name_b),
     INDEX `is_name_b_nickname`(is_name_b_nickname),
     INDEX `is_name_b_inferior`(is_name_b_inferior)
  );

-- /*******************************************************
-- *
-- * civicrm_mergeconflict
-- *
-- * Table for tracking and viewing merge conflicts.
-- *
-- *******************************************************/
CREATE TABLE `civicrm_mergeconflict` (

     `id` int unsigned NOT NULL AUTO_INCREMENT  COMMENT 'Unique MergeConflict ID',
     `contact_1` int unsigned    COMMENT 'FK to Contact',
     `contact_2` int unsigned    COMMENT 'FK to Contact',
     `group_id` int unsigned    COMMENT 'FK to Group',
     `conflicted_field` varchar(0),
     `value_1` varchar(0),
     `value_2` varchar(0),
     `analysis` varchar(0),
     PRIMARY KEY (`id`)
     );


