<?php 

/**
 * Implementation of hook_permission().
 */
function contribution_audit_permission() {
  return array(
    'administer contribution_audit' => array(
      'title' => t('Administer Contribution Auditing'),
    ),
  );
}

/**
 * Implementation of hook_menu()
 */
function contribution_audit_menu() {
  $items = array();
  
  $items['admin/config/contribution_audit'] = array(
    'title' => 'Contribution Auditing',
    'page callback' => 'system_admin_menu_block_page',
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
    'access arguments' => array('administer contribution_audit'),
  );

  /*
  TODO: there are no knobs yet.
  $items['admin/config/contribution_audit/configure'] = array(
    'title' => 'Configure',
    'description' => 'Configure contribution audit settings.',
    'access arguments' => array('administer contribution_audit'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array( 'contribution_audit_settings' ),
  );
  */
  
  return $items;
}

/**
 * Callback for menu
 */
function contribution_audit_settings() {
  $form[ 'contribution_audit_fieldset' ] = array(
    '#type' => 'fieldset',
    '#title' => t('Contribution audit settings'),
    '#description' => t( 'A placeholder form for Contribution Audit settings.' ),
    ); 
  return system_settings_form( $form );
}

function contribution_audit_allocate_unallocated_contribs( $start_date, $end_date ) {
  watchdog( 'contribution_audit', 'Running contribution_audit_allocate_unallocated_contribs for time period from @start_date until @end_date', array( '@start_date' => $start_date, '@end_date' => $end_date ), WATCHDOG_DEBUG );
  $allocated = array(); // country => $
  // find the info from missing trxns
  $missing_trxns = contribution_audit_find_missing_trxns( $start_date, $end_date );
  watchdog( 'contribution_audit', 'Total missing transactions: @num', array('@num' => count( $missing_trxns )), WATCHDOG_DEBUG );
  foreach ( $missing_trxns as $missing_trxn ) {
    // what happens if we still dont have country data?
    if ( !strlen($missing_trxn[ 'country' ])) {
      $missing_trxn[ 'country' ] = 'unknown';
      // try secondary searches
      $missing_trxn = module_invoke( 'log_audit', 'contribution_audit_secondary_trxn_search', $missing_trxn );
    }
    _contribution_audit_aggregate_country_amounts( $allocated, $missing_trxn );
  }
  return $allocated;
}  

/**
 * @TODO some of this might be better off in normalization functions, but just trying to get this done for deadline
 * @param unknown_type $allocated
 * @param unknown_type $trxn
 */
function _contribution_audit_aggregate_country_amounts( &$allocated, $trxn ) {
  // handle currency conversion, etc
  foreach ( array( 'fee','net', 'gross' ) as $amount_key ) { // ensure that valuse are set for fee/net/gross
    if ( !isset( $trxn[ $amount_key ] )) $trxn[ $amount_key ] = 0;
  }
  foreach ( array( 'date', 'original_currency', 'country'  ) as $amount_key ) { // ensure that values are set for date, original currency, country
    if ( !isset( $trxn[ $amount_key ] )) $trxn[ $amount_key ] = '';
  }
  $trxn = wmf_civicrm_normalize_contribution_amounts( $trxn );
  if ( !in_array( $trxn[ 'country' ], array_keys( $allocated ))) {
    $allocated[ $trxn[ 'country' ]][ 'amnt' ] = $trxn[ 'gross' ];
    $allocated[ $trxn[ 'country' ]][ 'count' ] = 1;
  } else {
    $allocated[ $trxn[ 'country' ]][ 'amnt' ] += $trxn[ 'gross' ];
    $allocated[ $trxn[ 'country' ]][ 'count' ] += 1;
  }
}

/**
 * Hook to find missing transactions
 * @return array containing the missing transactions
 */
function contribution_audit_find_missing_trxns( $start_date, $end_date ) {
  $missing_trxns = module_invoke_all( 'contribution_audit_find_missing_trxns', $start_date, $end_date );
  return $missing_trxns;
}

/**
 * Hook to find transactions missing country info
 * @return array contaning transactions missing country info
 */
function contribution_audit_find_trxns_missing_country_info() {
  $trxns_missing_country_info = array();
  module_invoke_all( 'contribution_audit_find_missing_trxns', $trxns_missing_country_info );
  return $trxns_missing_country_info;
}
