<?php
use CRM_ExchangeRates_ExtensionUtil as E;

return [
  'exchange_rates_quote_oanda' => [
    'group_name' => 'Exchange Rates Settings',
    'group' => 'exchange_rates',
    'name' => 'exchange_rates_quote_oanda',
    'type' => 'string',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => E::ts('Which data point to request from OANDA for each currency'),
    'default' => 'bid',
    'title' => E::ts('OANDA data request'),
    'help_text' => '',
    'html_type' => 'select',
    'html_attributes' => [
      'class' => 'crm-select2',
    ],
    'settings_pages' => ['exchange_rates' => ['weight' => 10]],
    'options' => [
      'bid' => 'Average bid',
      'low_bid' => 'Low bid',
      'high_bid' => 'High bid',
      'midpoint' => 'Midpoint between average bid and average ask',
    ],
  ],
  'exchange_rates_key_oanda' => [
    'group_name' => 'Exchange Rates Settings',
    'group' => 'exchange_rates',
    'name' => 'exchange_rates_key_oanda',
    'type' => 'string',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => E::ts('Key for OANDA API calls (found on OANDA account settings page)'),
    'default' => '',
    'title' => E::ts('OANDA API Key'),
    'help_text' => '',
    'html_type' => 'password',
    'settings_pages' => ['exchange_rates' => ['weight' => 20]],
  ],
  'exchange_rates_last_update_timestamp' => [
    'group_name' => 'Exchange Rates Settings',
    'group' => 'exchange_rates',
    'name' => 'exchange_rates_last_update_timestamp',
    'type' => 'int',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('Timestamp of latest exchange rate update from the banks'),
    'default' => '',
    'title' => ts('Latest rate update'),
    'help_text' => 'Set automatically after each update',
    'html_type' => 'text',
    'settings_pages' => ['exchange_rates' => ['weight' => 30]],
  ],
  'exchange_rates_remaining_quotes' => [
    'group_name' => 'Exchange Rates Settings',
    'group' => 'exchange_rates',
    'name' => 'exchange_rates_remaining_quotes',
    'type' => 'int',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => E::ts('Number of exchange rate quotes left to retrieve in our account'),
    'default' => '',
    'title' => E::ts('Remaining quotes'),
    'help_text' => 'Set automatically after each update',
    'html_type' => 'text',
    'settings_pages' => ['exchange_rates' => ['weight' => 40]],
  ],
  'exchange_rates_cache_granularity' => [
    'group_name' => 'Exchange Rates Settings',
    'group' => 'exchange_rates',
    'name' => 'exchange_rates_cache_granularity',
    'type' => 'string',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => E::ts('Granularity of the cache for a given exchange rate. More granular means more DB lookups but potentially more accurate rates.'),
    'default' => 'day',
    'title' => E::ts('Cache granularity'),
    'help_text' => 'Should match the frequency at which you fetch new exchange rates (e.g. via the updateAll API call)',
    'html_type' => 'select',
    'html_attributes' => [
      'class' => 'crm-select2',
    ],
    'settings_pages' => ['exchange_rates' => ['weight' => 50]],
    'options' => [
      'hour' => 'Hour',
      'day' => 'Day',
      'month' => 'Month',
    ],
  ],
];
