<?php

require_once 'offline2civicrm.common.inc';

use wmf_communication\Templating;

/**
 * Implementation of hook_menu().
 */
function offline2civicrm_menu() {
  $items = array();
  
  $items['admin/config/offline2civicrm'] = array(
    'title' => 'Offline to CiviCRM',
    'access arguments' => array('administer offline2civicrm'),
    'page callback' => 'system_admin_menu_block_page',
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  /*
  TODO
  $items['admin/config/offline2civicrm/settings'] = array(
    'title' => 'Offline to CiviCRM',
    'description' => t('Configure offline import interface.'),
    'access arguments' => array('administer offline2civicrm'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('offline2civicrm_settings'),
  );
  */

  $items['admin/import_checks'] = array(
    'title' => 'Import Checks',
    'access arguments' => array('offline2civicrm bulk import'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('offline2civicrm_import_checks_form'),
  );

  return $items;
}

/**
 * Implementation of hook_permission().
 */
function offline2civicrm_permission() {
  return array(
    'administer offline2civicrm' => array(
      'title' => t("Administer offline2civicrm"),
    ),
    'offline2civicrm bulk import' => array(
      'title' => t("Import batch files with offline2civicrm"),
    ),
  );
}

/**
 * Callback for menu path "admin/config/offline2civicrm".
 */
function offline2civicrm_settings() {
  $form = array();
  
  return system_settings_form($form);
}

function offline2civicrm_import_checks_form() {
  $dir = drupal_get_path( 'module', 'offline2civicrm' );
  drupal_add_js( $dir . '/upload_form.js' );

  $log_events = ChecksImportLog::recentEvents();
  $headers = array( 'Time', 'Who', 'Done' );
  $rows = array();
  foreach ( $log_events as $event ) {
    $rows[] = array(
      $event->time,
      $event->who,
      $event->done,
    );
  }
  $log_html = theme_table( array(
    'header' => $headers,
    'rows' => $rows,
    'empty' => "No events yet.",
    'attributes' => array(),
    'caption' => t( 'Latest import events' ),
    'colgroups' => array(),
    'sticky' => true,
  ) ).theme('pager');

  $form['import_upload_file'] = array(
    '#title' => t( 'Upload checks file' ),
    '#type' => 'file',
  );
  $form['import_upload_submit'] = array(
    '#type' => 'submit',
    '#value' => t( 'Upload' ),
  );
  $form['import_upload_format'] = array(
    '#title' => t( 'File format' ),
    '#type' => 'radios',
    '#default_value' => 'azl',
    '#options' => array(
        'azl' => t( 'AZ Lockbox' ),
        'coinbase' => t( 'Coinbase Merchant Orders' ),
        'jpmorgan' => t( 'JP Morgan' ),
        'paypal' => t( 'PayPal EFT' ),
    ),
  );
  $form['log'] = array(
    '#markup' => $log_html,
  );

  $form['#attributes'] = array( 'enctype' => "multipart/form-data" );

  return $form;
}

function offline2civicrm_import_checks_form_submit( $form, $form_state ) {
  if ( !empty( $form_state['values']['import_upload_submit'] ) ) {
    try {
      $validators = array(
        'file_validate_extensions' => array('csv'),
      );
      $file = file_save_upload( 'import_upload_file', $validators );
      if ( !$file ) {
        throw new Exception( t( "Form upload failed!" ) );
      }

      // This workaround... does not always work.  Will be deprecated in Civi 4.3
      civicrm_initialize();
      $smellyTmp = CRM_Core_TemporaryErrorScope::useException();

      switch ( $form_state['values']['import_upload_format'] ) {
      case 'azl':
        $importer = new AzlChecksFile( $file->uri );
        break;
      case 'coinbase':
        $importer = new CoinbaseFile( $file->uri );
        break;
      case 'paypal':
        $importer = new PayPalChecksFile( $file->uri );
        break;
      case 'jpmorgan':
        $importer = new JpMorganFile( $file->uri );
        break;
      default:
        throw new Exception( 'Bad file format selection' );
      }
      $importer->import();
      drupal_set_message( "Successful import!" );
    }
    catch ( WmfException $ex ) {
      $message = t( "Import error: !err", array( '!err' => $ex->getMessage() ) );
      form_set_error( 'import_upload_file', $message );
      ChecksImportLog::record( $message );
    }
    catch ( Exception $ex ) {
      $message = t( "Unknown import error: !err", array( '!err' => $ex->getMessage() ) );
      form_set_error( 'import_upload_file', $message );
      ChecksImportLog::record( $message );
    }
    if ( $file ) {
      file_delete( $file, true );
    }
  }
}
