<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from wmf-civicrm/xml/schema/CRM/Wmf/ContributionTracking.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:bf67621a5a990e7755b05779155320da)
 */
use CRM_Wmf_ExtensionUtil as E;

/**
 * Database access object for the ContributionTracking entity.
 */
class CRM_Wmf_DAO_ContributionTracking extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '5.61';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_contribution_tracking';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = FALSE;

  /**
   * Unique Contribution Tracking ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * FK to Contribution
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $contribution_id;

  /**
   * Amount
   *
   * @var float|string|null
   *   (SQL type: decimal(20,3))
   *   Note that values will be retrieved from the database as a string.
   */
  public $amount;

  /**
   * Currency ISO Code
   *
   * @var string|null
   *   (SQL type: varchar(3))
   *   Note that values will be retrieved from the database as a string.
   */
  public $currency;

  /**
   * USD Amount
   *
   * @var float|string|null
   *   (SQL type: decimal(20,2))
   *   Note that values will be retrieved from the database as a string.
   */
  public $usd_amount;

  /**
   * Referrer
   *
   * @var string|null
   *   (SQL type: varchar(4096))
   *   Note that values will be retrieved from the database as a string.
   */
  public $referrer;

  /**
   * UTM Medium
   *
   * @var string|null
   *   (SQL type: varchar(128))
   *   Note that values will be retrieved from the database as a string.
   */
  public $utm_medium;

  /**
   * UTM Campaign
   *
   * @var string|null
   *   (SQL type: varchar(128))
   *   Note that values will be retrieved from the database as a string.
   */
  public $utm_campaign;

  /**
   * UTM Key
   *
   * @var string|null
   *   (SQL type: varchar(128))
   *   Note that values will be retrieved from the database as a string.
   */
  public $utm_key;

  /**
   * Banner
   *
   * @var string|null
   *   (SQL type: varchar(128))
   *   Note that values will be retrieved from the database as a string.
   */
  public $banner;

  /**
   * Landing Page
   *
   * @var string|null
   *   (SQL type: varchar(128))
   *   Note that values will be retrieved from the database as a string.
   */
  public $landing_page;

  /**
   * Payment Method
   *
   * @var string|null
   *   (SQL type: varchar(128))
   *   Note that values will be retrieved from the database as a string.
   */
  public $payment_method;

  /**
   * Language
   *
   * @var string|null
   *   (SQL type: varchar(8))
   *   Note that values will be retrieved from the database as a string.
   */
  public $language;

  /**
   * Country
   *
   * @var string|null
   *   (SQL type: varchar(2))
   *   Note that values will be retrieved from the database as a string.
   */
  public $country;

  /**
   * Tracking Date
   *
   * @var string|null
   *   (SQL type: datetime)
   *   Note that values will be retrieved from the database as a string.
   */
  public $tracking_date;

  /**
   * Operating System
   *
   * @var string|null
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $os;

  /**
   * Operating System - Major Version
   *
   * @var string|null
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $os_version;

  /**
   * Browser
   *
   * @var string|null
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $browser;

  /**
   * Browser Version
   *
   * @var string|null
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $browser_version;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_contribution_tracking';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Contribution Trackings') : E::ts('Contribution Tracking');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'contribution_id', 'civicrm_contribution', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique Contribution Tracking ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.id',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'contribution_id' => [
          'name' => 'contribution_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Contribution ID'),
          'description' => E::ts('FK to Contribution'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.contribution_id',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contribute_DAO_Contribution',
          'add' => NULL,
        ],
        'amount' => [
          'name' => 'amount',
          'type' => CRM_Utils_Type::T_MONEY,
          'title' => E::ts('Amount'),
          'description' => E::ts('Amount'),
          'precision' => [
            20,
            3,
          ],
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.amount',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'add' => NULL,
        ],
        'currency' => [
          'name' => 'currency',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Currency'),
          'description' => E::ts('Currency ISO Code'),
          'maxlength' => 3,
          'size' => CRM_Utils_Type::FOUR,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.currency',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'add' => NULL,
        ],
        'usd_amount' => [
          'name' => 'usd_amount',
          'type' => CRM_Utils_Type::T_MONEY,
          'title' => E::ts('Usd Amount'),
          'description' => E::ts('USD Amount'),
          'precision' => [
            20,
            2,
          ],
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.usd_amount',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'add' => NULL,
        ],
        'referrer' => [
          'name' => 'referrer',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Referrer'),
          'description' => E::ts('Referrer'),
          'maxlength' => 4096,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.referrer',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'add' => NULL,
        ],
        'utm_medium' => [
          'name' => 'utm_medium',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Utm Medium'),
          'description' => E::ts('UTM Medium'),
          'maxlength' => 128,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.utm_medium',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'add' => NULL,
        ],
        'utm_campaign' => [
          'name' => 'utm_campaign',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Utm Campaign'),
          'description' => E::ts('UTM Campaign'),
          'maxlength' => 128,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.utm_campaign',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'add' => NULL,
        ],
        'utm_key' => [
          'name' => 'utm_key',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Utm Key'),
          'description' => E::ts('UTM Key'),
          'maxlength' => 128,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.utm_key',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'add' => NULL,
        ],
        'banner' => [
          'name' => 'banner',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Banner'),
          'description' => E::ts('Banner'),
          'maxlength' => 128,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.banner',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'add' => NULL,
        ],
        'landing_page' => [
          'name' => 'landing_page',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Landing Page'),
          'description' => E::ts('Landing Page'),
          'maxlength' => 128,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.landing_page',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'add' => NULL,
        ],
        'payment_method' => [
          'name' => 'payment_method',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Payment Method'),
          'description' => E::ts('Payment Method'),
          'maxlength' => 128,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.payment_method',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'add' => NULL,
        ],
        'language' => [
          'name' => 'language',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Language'),
          'description' => E::ts('Language'),
          'maxlength' => 8,
          'size' => CRM_Utils_Type::EIGHT,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.language',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'add' => NULL,
        ],
        'country' => [
          'name' => 'country',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Country'),
          'description' => E::ts('Country'),
          'maxlength' => 2,
          'size' => CRM_Utils_Type::TWO,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.country',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'add' => NULL,
        ],
        'tracking_date' => [
          'name' => 'tracking_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => E::ts('Tracking Date'),
          'description' => E::ts('Tracking Date'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.tracking_date',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'add' => NULL,
        ],
        'os' => [
          'name' => 'os',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Os'),
          'description' => E::ts('Operating System'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.os',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'add' => NULL,
        ],
        'os_version' => [
          'name' => 'os_version',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Os Version'),
          'description' => E::ts('Operating System - Major Version'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.os_version',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'add' => NULL,
        ],
        'browser' => [
          'name' => 'browser',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Browser'),
          'description' => E::ts('Browser'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.browser',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'add' => NULL,
        ],
        'browser_version' => [
          'name' => 'browser_version',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Browser Version'),
          'description' => E::ts('Browser Version'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_contribution_tracking.browser_version',
          'table_name' => 'civicrm_contribution_tracking',
          'entity' => 'ContributionTracking',
          'bao' => 'CRM_Wmf_DAO_ContributionTracking',
          'localizable' => 0,
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'contribution_tracking', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'contribution_tracking', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'currency' => [
        'name' => 'currency',
        'field' => [
          0 => 'currency',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_contribution_tracking::0::currency',
      ],
      'utm_medium_id' => [
        'name' => 'utm_medium_id',
        'field' => [
          0 => 'utm_medium',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_contribution_tracking::0::utm_medium',
      ],
      'utm_campaign_id' => [
        'name' => 'utm_campaign_id',
        'field' => [
          0 => 'utm_campaign',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_contribution_tracking::0::utm_campaign',
      ],
      'banner' => [
        'name' => 'banner',
        'field' => [
          0 => 'banner',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_contribution_tracking::0::banner',
      ],
      'landing_page' => [
        'name' => 'landing_page',
        'field' => [
          0 => 'landing_page',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_contribution_tracking::0::landing_page',
      ],
      'payment_method' => [
        'name' => 'payment_method',
        'field' => [
          0 => 'payment_method',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_contribution_tracking::0::payment_method',
      ],
      'language' => [
        'name' => 'language',
        'field' => [
          0 => 'language',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_contribution_tracking::0::language',
      ],
      'country' => [
        'name' => 'country',
        'field' => [
          0 => 'country',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_contribution_tracking::0::country',
      ],
      'tracking_date' => [
        'name' => 'tracking_date',
        'field' => [
          0 => 'tracking_date',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_contribution_tracking::0::tracking_date',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
