<?php

use Civi\WMFQueue\UnsubscribeQueueConsumer;

/**
 * Implements hook_menu
 */
function wmf_unsubscribe_qc_menu() {
  $items['admin/config/queue2civicrm/unsubscribe_qc'] = [
    'title' => 'Unsubscribe',
    'description' => t('Configure unsubscribe queue'),
    'access arguments' => ['administer queue2civicrm'],
    'page callback' => 'drupal_get_form',
    'page arguments' => ['unsubscribe_qc_settings'],
  ];
  return $items;
}

/**
 * Constructs the settings page for this module.
 *
 * @return array Of form components.
 */
function unsubscribe_qc_settings() {
  $form = [];

  $form['unsubscribe_qc_disable'] = [
    '#type' => 'checkbox',
    '#title' => t('Disable job'),
    '#description' => t('If checked, no message processing will be performed.'),
    '#default_value' => variable_get('unsubscribe_qc_disable', FALSE),
  ];

  $form['description'] = [
    '#type' => 'markup',
    '#description' => t('<p>Contacts in the unsubscribe queue are processed by '
      . 'marking them as opt-out in the CRM.</p><p>Those in the opt_in queue '
      . 'are processed by marking them as opt-in.</p>'),
  ];

  $form['unsubscribe_batch'] = [
    '#type' => 'select',
    '#title' => t('Cron batch size'),
    '#description' => t('Maximum number of items processed by an unsubscribe job'),
    '#default_value' => variable_get('unsubscribe_batch', 0),
    '#options' => [
      0 => 'Unlimited',
      1 => 1,
      5 => 5,
      10 => 10,
      50 => 50,
      75 => 75,
      100 => 100,
      150 => 150,
      300 => 300,
      500 => 500,
      750 => 750,
      1000 => 1000,
    ],
  ];

  $form['unsubscribe_batch_time'] = [
    '#type' => 'textfield',
    '#title' => t('Job time limit (in seconds)'),
    '#description' => t('Maximum elapsed duration of an unsubscribe job, after which we will abort from the loop.  This can be used to set a reliable duty cycle for the job.  Either a time limit or batch size limit is required.'),
    '#required' => TRUE,
    '#default_value' => variable_get('unsubscribe_batch_time', 90),
  ];

  return system_settings_form($form);
}

/**
 * Callback from Drush that actually executes the loop for processing messages in the queues.
 *
 * @ref unsubscribe_process_message
 * @ref drush_unsubscribe_queue_consume
 */
function unsubscribe_batch_process() {
  civicrm_initialize();
  if (variable_get("unsubscribe_qc_disable", FALSE)) {
    \Civi::log('wmf')->info('unsubscribe_qc: unsubscribe_qc is disabled. No messages processed.');
    return 0;
  }

  wmf_common_create_smashpig_context('unsubscribe');
  \Civi::log('wmf')->info('Executing: unsubscribe_batch_process');

  $consumer = new UnsubscribeQueueConsumer(
    'unsubscribe',
    variable_get('unsubscribe_batch_time', 0),
    variable_get('unsubscribe_batch', 0)
  );

  $processed = $consumer->dequeueMessages();

  if ($processed > 0) {
    \Civi::log('wmf')->info('Successfully processed {processed} unsubscribe(s).', ['processed' => $processed]);
  }
  else {
    \Civi::log('wmf')->info('No unsubscribes processed.');
  }
}
