-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_exchange_rate`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_exchange_rate
-- *
-- * Historical exchange rates
-- *
-- *******************************************************/
CREATE TABLE `civicrm_exchange_rate` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique ExchangeRate ID',
  `currency` char(3) COMMENT 'ISO currency code',
  `value_in_usd` double COMMENT 'USD value of a single unit of the currency',
  `local_update` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT 'Timestamp of the last update on the local side',
  `bank_update` timestamp NOT NULL COMMENT 'Timestamp of the last update on the bank side',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ExchangeRate_Currency_BankUpdate`(currency, bank_update)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
