<?php

function _wmf_civicrm_update_7523_insert_currency_symbols(){
	civicrm_initialize();
	CRM_CORE_DAO::executeQuery('SET NAMES utf8');//just in case db not expecting ut8
	CRM_CORE_DAO::executeQuery(
		'INSERT INTO civicrm_currency (name, symbol, numeric_code, full_name) VALUES
		(   "AUD",  "$", "036", "Australian Dollar"),
		(   "CAD",  "$", "124", "Canadian Dollar"),
		(   "EUR",  "€", "978", "Euro"),
		(   "GBP",  "£", "826", "Pound Sterling"),
		(   "ILS",  "₪", "826", "New Israeli Shekel"),
		(   "INR",  "₨", "356", "Indian Rupee"),
		(   "JPY",  "¥", "392", "Japanese Yen"),
		(   "KRW",  "₩", "410", "South Korean Won"),
		(   "LAK",  "₭", "418", "Lao Kip"),
		(  "MNT",  "₮", "496", "Mongolian Tugrik"),
		(  "NGN",  "₦", "566", "Nigerian Naira"),
		(  "PLN", "zł", "985", "Polish Złoty"),
		(  "THB",  "฿", "764", "Thai Baht"),
		(  "USD",  "$", "840", "US Dollar"),
		(  "VND",  "₫", "704", "Viet Nam Dong"),
		(  "ZAR",  "R", "710", "South African Rand"),
		(  "AED", NULL, "784", "UAE Dirham"),
		(  "AFN",  "؋", "971", "Afghani"),
		(  "ALL","Lek", "008", "Albanian Lek"),
		(  "AMD", NULL, "051", "Armenian Dram"),
		(  "ANG",  "ƒ", "532", "Netherlands Antillian Guilder"),
		(  "AOA", NULL, "973", "Angola Kwanza"),
		(  "ARS",  "$", "032", "Argentine Peso"),
		(  "AWG",  "ƒ", "533", "Aruban Guilder"),
		(  "AZN","ман", "944", "Azerbaijanian Manat"),
		(  "BAM", "KM", "977", "Convertible Marks"),
		(  "BBD",  "$", "052", "Barbados Dollar"),
		(  "BDT", NULL, "050", "Bangladeshi Taka"),
		(  "BGN", "лв", "975", "Bulgarian Lev"),
		(  "BHD", NULL, "048", "Bahraini Dinar"),
		(  "BIF", NULL, "108", "Burundi Franc"),
		(  "BMD",  "$", "060", "Bermudian Dollar"),
		(  "BND",  "$", "096", "Brunei Dollar"),
		(  "BOB", "$b", "068", "Boliviano"),
		(  "BOV", NULL, "984", "Bolivian Mvdol"),
		(  "BRL", "R$", "986", "Brazilian Real"),
		(  "BSD",  "$", "044", "Bahamian Dollar"),
		(  "BTN", NULL, "064", "Bhutan Ngultrum"),
		(  "BWP",  "P", "072", "Botswana Pula"),
		(  "BYR", "p.", "974", "Belarussian Rouble"),
		(  "BZD","BZ$", "084", "Belize Dollar"),
		(  "CDF", NULL, "976", "Franc Congolais"),
		(  "CHE", NULL, "947", "WIR Euro"),
		(  "CHF","CHF", "756", "Swiss Franc"),
		(  "CHW", NULL, "948", "WIR Franc"),
		(  "CLF", NULL, "990", "Unidades de fomento"),
		(  "CLP",  "$", "152", "Chilean Peso"),
		(  "CNY", "元", "156", "Chinese Yuan Renminbi"),
		(  "COP",  "$", "170", "Colombian Peso"),
		(  "COU", NULL, "970", "Unidad de Valor Real"),
		(  "CRC",  "₡", "188", "Costa Rican Colon"),
		(  "RSD", "Дин.","941", "Serbian Dinar"),
		(  "CUP",  "₱", "192", "Cuban Peso"),
		(  "CVE", NULL, "132", "Cape Verde Escudo"),
		(  "CYP",  "£", "196", "Cyprus Pound"),
		(  "CZK", "Kč", "203", "Czech Koruna"),
		(  "DJF", NULL, "262", "Djibouti Franc"),
		(  "DKK", "kr", "208", "Danish Krone"),
		(  "DOP","RD$", "214", "Dominican Peso"),
		(  "DZD", NULL, "012", "Algerian Dinar"),
		(  "EGP",  "£", "818", "Egyptian Pound"),
		(  "ERN", NULL, "232", "Eritrean Nakfa"),
		(  "ETB", NULL, "230", "Ethiopian Birr"),
		(  "FJD",  "$", "242", "Fiji Dollar"),
		(  "FKP",  "£", "238", "Falkland Islands Pound"),
		(  "GEL", NULL, "981", "Georgian Lari"),
		(  "GHC",  "¢", "288", "Ghanaian Cedi"),
		(  "GIP",  "£", "292", "Gibraltar Pound"),
		(  "GMD", NULL, "270", "Gambian Dalasi"),
		(  "GNF", NULL, "324", "Guinea Franc"),
		(  "GTQ",  "Q", "320", "Guatemalan Quetzal"),
		(  "GWP", NULL, "624", "Guinea-Bissau Peso"),
		(  "GYD",  "$", "328", "Guyana Dollar"),
		(  "HKD","HK$", "344", "Hong Kong Dollar"),
		(  "HNL",  "L", "340", "Honduran Lempira"),
		(  "HRK", "kn", "191", "Croatian Kuna"),
		(  "HTG", NULL, "332", "Haitian Gourde"),
		(  "HUF", "Ft", "348", "Hungarian Forint"),
		(  "IDR", "Rp", "360", "Indonesian Rupiah"),
		(  "IQD", NULL, "368", "Iraqi Dinar"),
		(  "IRR",  "﷼", "364", "Iranian Rial"),
		(  "ISK", "kr", "352", "Iceland Krona"),
		(  "JMD", "J$", "388", "Jamaican Dollar"),
		(  "JOD", NULL, "400", "Jordanian Dinar"),
		(  "KES", NULL, "404", "Kenyan Shilling"),
		(  "KGS", "лв", "417", "Kyrgyzstan Som"),
		(  "KHR",  "៛", "116", "Cambodian Riel"),
		(  "KMF", NULL, "174", "Comoro Franc"),
		(  "KPW",  "₩", "408", "North Korean Won"),
		(  "KWD", NULL, "414", "Kuwaiti Dinar"),
		(  "KYD",  "$", "136", "Cayman Islands Dollar"),
		(  "KZT", "лв", "398", "Kazakhstan Tenge"),
		(  "LBP",  "£", "422", "Lebanese Pound"),
		(  "LKR",  "₨", "144", "Sri Lanka Rupee"),
		(  "LRD",  "$", "430", "Liberian Dollar"),
		(  "LSL", NULL, "426", "Lesotho Loti"),
		(  "LTL", "Lt", "440", "Lithuanian Litas"),
		(  "LVL", "Ls", "428", "Latvian Lats"),
		( "LYD", NULL, "434", "Libyan Dinar"),
		( "MAD", NULL, "504", "Moroccan Dirham"),
		( "MDL", NULL, "498", "Moldovan Leu"),
		( "MGA", NULL, "969", "Malagascy Ariary"),
		( "MKD","ден", "807", "Macedonian Denar"),
		( "MMK", NULL, "104", "Myanmar Kyat"),
		( "MOP", NULL, "446", "Macao Pataca"),
		( "MRO", NULL, "478", "Mauritanian Ouguiya"),
		( "MTL", "Lm", "470", "Maltese Lira"),
		( "MUR",  "₨", "480", "Mauritius Rupee"),
		( "MVR", NULL, "462", "Maldive Rufiyaa"),
		( "MWK", NULL, "454", "Malawi Kwacha"),
		( "MXN",  "$", "484", "Mexican Peso"),
		( "MXV", NULL, "979", "Mexican Unidad de Inversion (UID)"),
		( "MYR", "RM", "458", "Malaysian Ringgit"),
		( "MZN", "MT", "943", "Mozambique Metical"),
		( "NAD", "N$", "516", "Namibian Dollar"),
		( "NIO", "C$", "558", "Nicaraguan Cordoba Oro"),
		( "NOK", "kr", "578", "Norwegian Krone"),
		( "NPR",  "₨", "524", "Nepalese Rupee"),
		( "NZD",  "$", "554", "New Zealand Dollar"),
		( "OMR",  "﷼", "512", "Rial Omani"),
		( "PAB","B/.", "590", "Panamanian Balboa"),
		( "PEN","S/.", "604", "Peruvian Nuevo Sol"),
		( "PGK", NULL, "598", "Papua New Guinea Kina"),
		( "PHP","Php", "608", "Philippine Peso"),
		( "PKR",  "₨", "586", "Pakistan Rupee"),
		( "PYG", "Gs", "600", "Paraguay Guarani"),
		( "QAR",  "﷼", "634", "Qatari Rial"),
		( "ROL", NULL, "642", "Romanian Old Leu"),
		( "RON","lei", "946", "Romanian New Leu"),
		( "RUB","руб", "643", "Russian Rouble"),
		( "RWF", NULL, "646", "Rwanda Franc"),
		( "SAR",  "﷼", "682", "Saudi Riyal"),
		( "SBD",  "$", "090", "Solomon Islands Dollar"),
		( "SCR",  "₨", "690", "Seychelles Rupee"),
		( "SDD", NULL, "736", "Sudanese Dinar"),
		( "SEK", "kr", "752", "Swedish Krona"),
		( "SGD",  "$", "702", "Singapore Dollar"),
		( "SHP",  "£", "654", "Saint Helena Pound"),
		( "SIT", NULL, "705", "Slovenian Tolar"),
		( "SKK","SIT", "703", "Slovak Koruna"),
		( "SLL", NULL, "694", "Leone"),
		( "SOS",  "S", "706", "Somali Shilling"),
		( "SRD",  "$", "968", "Surinam Dollar"),
		( "STD", NULL, "678", "São Tome and Principe Dobra"),
		( "SVC",  "$", "222", "El Salvador Colon"),
		( "SYP",  "£", "760", "Syrian Pound"),
		( "SZL", NULL, "748", "Swaziland Lilangeni"),
		( "TJS", NULL, "972", "Tajik Somoni"),
		( "TMM", NULL, "795", "Turkmenistan Manat"),
		( "TND", NULL, "788", "Tunisian Dinar"),
		( "TOP", NULL, "776", "Tongan Pa\'anga"),
		( "TRY","YTL", "949", "New Turkish Lira"),
		( "TTD","TT$", "780", "Trinidad and Tobago Dollar"),
		( "TWD","NT$", "901", "New Taiwan Dollar"),
		( "TZS", NULL, "834", "Tanzanian Shilling"),
		( "UAH",  "₴", "980", "Ukrainian Hryvnia"),
		( "UGX", NULL, "800", "Ugandan Shilling"),
		( "USN", NULL, "997", "US Dollar (Next day)"),
		( "USS", NULL, "998", "US Dollar (Same day)"),
		( "UYU", "$U", "858", "Peso Uruguayo"),
		( "UZS", "лв", "860", "Uzbekistan Sum"),
		( "VEF", "Bs", "937", "Venezuela Bolivar"),
		( "VUV", NULL, "548", "Vanuatu Vatu"),
		( "WST", NULL, "882", "Samoan Tala"),
		( "XAF", NULL, "950", "CFA Franc BEAC"),
		( "XAG", NULL, "961", "Silver"),
		( "XAU", NULL, "959", "Gold"),
		( "XBA", NULL, "955", "Bond Markets Units European Composite Unit (EURCO)"),
		( "XBB", NULL, "956", "European Monetary Unit (E.M.U.-6)"),
		( "XBC", NULL, "957", "European Unit of Account 9 (E.U.A.-9)"),
		( "XBD", NULL, "958", "European Unit of Account 17 (E.U.A.-17)"),
		( "XCD",  "$", "951", "East Caribbean Dollar"),
		( "XDR", NULL, "960", "Special Drawing Right"),
		( "XFO", NULL,  NULL, "Gold-Franc"),
		( "XFU", NULL,  NULL, "UIC-Franc"),
		( "XOF", NULL, "952", "CFA Franc BCEAO"),
		( "XPD", NULL, "964", "Palladium"),
		( "XPF", NULL, "953", "CFP Franc"),
		( "XPT", NULL, "962", "Platinum"),
		( "XTS", NULL, "963", "Code for testing purposes"),
		( "XXX", NULL, "999", "No currency involved"),
		( "YER",  "﷼", "886", "Yemeni Rial"),
		( "ZMK", NULL, "894", "Zambian Kwacha"),
		( "ZWD", "Z$", "716", "Zimbabwe Dollar") ON DUPLICATE KEY UPDATE symbol=VALUES(symbol);'
	);
}

