<?php

return [
  'smashpig_recurring_use_queue' => [
    'group_name' => 'SmashPig Preferences',
    'group' => 'smashpig',
    'name' => 'smashpig_recurring_use_queue',
    'quick_form_type' => 'YesNo',
    'html_type' => 'radio',
    'type' => 'Boolean',
    'default' => 0,
    'title' => 'Use queue for recurring',
    'is_domain' => '1',
    'is_contact' => 0,
    'description' => 'When true, SmashPig Recurring Charge job pushes donations to donations queue instead of creating directly',
    'help_text' => 'Queue connection settings are part of system-wide SmashPig settings managed via SmashPig\'s yaml files',
  ],
  'smashpig_recurring_retry_delay_days' => [
    'group_name' => 'SmashPig Preferences',
    'group' => 'smashpig',
    'name' => 'smashpig_recurring_retry_delay_days',
    'type' => 'Integer',
    'quick_form_type' => 'Element',
    'html_type' => 'text',
    'html_attributes' => [
      'size' => 3,
      'maxlength' => 3,
    ],
    'default' => 1,
    'title' => 'Days to wait till retrying a failed payment',
    'is_domain' => '1',
    'is_contact' => 0,
    'description' => 'If a payment fails during a recurring charge job, schedule the payment for retry this many days later.',
  ],
  'smashpig_recurring_max_failures' => [
    'group_name' => 'SmashPig Preferences',
    'group' => 'smashpig',
    'name' => 'smashpig_recurring_max_failures',
    'type' => 'Integer',
    'quick_form_type' => 'Element',
    'html_type' => 'text',
    'html_attributes' => [
      'size' => 3,
      'maxlength' => 3,
    ],
    'default' => 3,
    'title' => 'Number of failed payments at which we cancel a recurring contribution',
    'is_domain' => '1',
    'is_contact' => 0,
    'description' => 'If a payment attempt fails this many times, the associated recurring contribution will be canceled.',
  ],
  'smashpig_recurring_catch_up_days' => [
    'group_name' => 'SmashPig Preferences',
    'group' => 'smashpig',
    'name' => 'smashpig_recurring_catch_up_days',
    'type' => 'Integer',
    'quick_form_type' => 'Element',
    'html_type' => 'text',
    'html_attributes' => [
      'size' => 3,
      'maxlength' => 3,
    ],
    'default' => 15,
    'title' => 'Days in the past to look for recurring contributions due to charge',
    'is_domain' => '1',
    'is_contact' => 0,
    'description' => 'The job will attempt to charge recurring contributions whose next_sched_contribution date is between now and this many days in the past.',
  ],
  'smashpig_recurring_batch_size' => [
    'group_name' => 'SmashPig Preferences',
    'group' => 'smashpig',
    'name' => 'smashpig_recurring_batch_size',
    'type' => 'Integer',
    'quick_form_type' => 'Element',
    'html_type' => 'text',
    'html_attributes' => [
      'size' => 4,
      'maxlength' => 4,
    ],
    'default' => 100,
    'title' => 'Number of payments to charge each run',
    'is_domain' => '1',
    'is_contact' => 0,
    'description' => 'The job will attempt to charge up to this many recurring contributions each run before stopping.',
  ],
];
