<?php

/**
 * Implementation of hook_menu()
 */
function braintree_audit_menu() {
  $items = [];

  $items['admin/config/wmf_audit/braintree_audit'] = [
    'title' => 'Braintree Audit',
    'description' => t('Configure WMF audit settings.'),
    'access arguments' => ['administer wmf_audit'],
    'page callback' => 'drupal_get_form',
    'page arguments' => ['braintree_audit_settings'],
  ];

  return $items;
}

/**
 * Callback for menu
 */
function braintree_audit_settings() {
  $form['braintree_audit_test_mode'] = [
    '#type' => 'checkbox',
    '#title' => t('When this box is checked, no queue messages will be sent.'),
    '#required' => FALSE,
    '#default_value' => variable_get('braintree_audit_test_mode'),
  ];
  $form['braintree_audit_log_search_past_days'] = [
    '#type' => 'textfield',
    '#title' => t('Plus or minus log search (in days)'),
    '#required' => TRUE,
    '#default_value' => variable_get('braintree_audit_log_search_past_days'),
  ];
  return system_settings_form($form);
}

function braintree_audit_create_processor($options) {
  return new BraintreeAuditProcessor($options);
}
