-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_contribution_tracking`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_contribution_tracking
-- *
-- * CiviCRM Contribution Tracking table
-- *
-- *******************************************************/
CREATE TABLE `civicrm_contribution_tracking` (
  `id` int unsigned NOT NULL COMMENT 'Unique Contribution Tracking ID',
  `contribution_id` int unsigned COMMENT 'FK to Contribution',
  `amount` decimal(20,3) COMMENT 'Amount',
  `currency` varchar(3) COMMENT 'Currency ISO Code',
  `usd_amount` decimal(20,2) COMMENT 'USD Amount',
  `referrer` varchar(4096) COMMENT 'Referrer',
  `utm_medium` varchar(128) COMMENT 'UTM Medium',
  `utm_campaign` varchar(128) COMMENT 'UTM Campaign',
  `utm_key` varchar(128) COMMENT 'UTM Key',
  `gateway` varchar(32) COMMENT 'Gateway, e.g paypal_ec,adyen',
  `appeal` varchar(64) COMMENT 'e.g JimmyQuote - the appeal is the text to the left of the input boxes (on desktop-size screens)',
  `variant` varchar(64) COMMENT ' a \'variant\' generally changes something about the input boxes or their labels',
  `banner` varchar(128) COMMENT 'Banner',
  `landing_page` varchar(128) COMMENT 'Landing Page',
  `payment_method` varchar(128) COMMENT 'Payment Method',
  `language` varchar(8) COMMENT 'Language',
  `country` varchar(2) COMMENT 'Country',
  `tracking_date` datetime COMMENT 'Tracking Date',
  `os` varchar(255) COMMENT 'Operating System',
  `os_version` varchar(255) COMMENT 'Operating System - Major Version',
  `browser` varchar(255) COMMENT 'Browser',
  `browser_version` varchar(255) COMMENT 'Browser Version',
  PRIMARY KEY (`id`),
  INDEX `currency`(currency),
  INDEX `utm_medium_id`(utm_medium),
  INDEX `utm_campaign_id`(utm_campaign),
  INDEX `banner`(banner),
  INDEX `landing_page`(landing_page),
  INDEX `payment_method`(payment_method),
  INDEX `language`(language),
  INDEX `country`(country),
  INDEX `tracking_date`(tracking_date),
  CONSTRAINT FK_civicrm_contribution_tracking_contribution_id FOREIGN KEY (`contribution_id`) REFERENCES `civicrm_contribution`(`id`) ON DELETE SET NULL
)
ENGINE=InnoDB;
