<?php

use queue2civicrm\opt_in\OptInQueueConsumer;

/**
 * Implements hook_menu
 */
function wmf_optin_qc_menu() {
  $items[ 'admin/config/queue2civicrm/optin_qc' ] = array(
    'title'            => 'Opt In',
    'description'      => t('Configure Opt In queue'),
    'access arguments' => array( 'administer optin' ),
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array( 'optin_qc_settings' ),
  );
  return $items;
}

/**
 * Constructs the settings page for this module.
 *
 * @return array Of form components.
 */
function optin_qc_settings() {
  $form = array();

  $form['optin_qc_disable'] = array(
    '#type' => 'checkbox',
    '#title' => t('Disable job'),
    '#description' => t('If checked, no message processing will be performed.'),
    '#default_value' => variable_get('optin_qc_disable', false),
  );

  $form['optin_batch'] = array(
    '#type'          => 'select',
    '#title'         => t('Cron batch size'),
    '#description'   => t('Maximum number of items processed by an optin job'),
    '#default_value' => variable_get('optin_batch', 0),
    '#options'       => array(
      0   => 'Unlimited',
      1   => 1,
      5   => 5,
      10  => 10,
      50  => 50,
      75  => 75,
      100 => 100,
      150 => 150,
      300 => 300,
      500 => 500,
      750 => 750,
      1000 => 1000
    ),
  );

  $form['optin_batch_time'] = array(
    '#type' => 'textfield',
    '#title' => t('Job time limit (in seconds)'),
    '#description' => t('Maximum elapsed duration of an optin job, after which we will abort from the loop.  This can be used to set a reliable duty cycle for the job.  Either a time limit or batch size limit is required.'),
    '#required' => TRUE,
    '#default_value' => variable_get('optin_batch_time', 90),
  );

  return system_settings_form($form);
}

/**
 * Callback from Drush that actually executes the loop for processing messages in the queues.
 * @ref optin_process_message
 * @ref drush_optin_queue_consume
 */
function optin_batch_process() {
  if (variable_get( "optin_qc_disable", false )){
    watchdog('optin_qc_disable', 'optin_qc is disabled. No messages processed.');
    return 0;
  }

  wmf_common_create_smashpig_context('optin');
  watchdog('optin', 'Executing: optin_batch_process');

  civicrm_initialize();

  $optInConsumer = new OptInQueueConsumer(
    'opt-in',
    variable_get('optin_batch_time', 0),
    variable_get('optin_batch', 0)
  );

  $processed = $optInConsumer->dequeueMessages();

  if ($processed > 0) {
    watchdog('opt_in', 'Successfully processed ' . $processed . ' opt-in(s).');
  }
  else {
    watchdog('opt_in', 'No opt-ins processed.');
  }
}
