<?php

/*
 * TODO:
 * - undo STUPID boilerplate
 * - stream data (unbuffered query using a new db connection)
 */

function wmf_eoy_receipt_run($options = []) {
  civicrm_initialize();
  $donors = new Civi\EoySummary($options);

  $donors->calculate_year_totals();
  $donors->send_letters();
}

function wmf_eoy_receipt_calculate_summaries($options = []) {
  civicrm_initialize();
  $donors = new Civi\EoySummary($options);

  return $donors->calculate_year_totals();
}

function wmf_eoy_receipt_send_letters($options = []) {
  civicrm_initialize();
  $donors = new Civi\EoySummary($options);

  $donors->send_letters();
}

function wmf_eoy_receipt_menu() {
  $items = [];

  $items['admin/config/wmf_eoy_receipt'] = [
    'title' => 'End-of-year Receipt',
    'description' => t('Configure.'),
    'access arguments' => ['access CiviContribute'],
    'page callback' => 'drupal_get_form',
    'page arguments' => ['wmf_eoy_receipt_settings'],
  ];

  return $items;
}

function wmf_eoy_receipt_enable() {
  variable_set('wmf_eoy_target_year',
    variable_get('wmf_eoy_target_year', intval(date('Y')) - 1));
}

function wmf_eoy_receipt_settings() {
  $form = [
    'wmf_eoy_target_year' => [
      '#title' => t('Year to process'),
      '#type' => 'textfield',
      '#size' => 10,
      '#default_value' => variable_get('wmf_eoy_target_year', NULL),
    ],
    'wmf_eoy_batch' => [
      '#title' => t('Email batch size'),
      '#type' => 'textfield',
      '#size' => 10,
      '#default_value' => variable_get('wmf_eoy_batch', 100),
      '#description' => t('Maximum emails sent per batch run'),
    ],
  ];
  return system_settings_form($form);
}
