<?php
header('Content-type: application/xml');
$IPADDRESS = isset($_GET['IPADDRESS']) ? $_GET['IPADDRESS'] : '';
$ORDERID = isset($_GET['ORDERID']) ? $_GET['ORDERID'] : '';
$EFFORTID = isset($_GET['EFFORTID']) ? $_GET['EFFORTID'] : '';
?>
<XML>
	<REQUEST>
		<ACTION>DO_PAYMENT</ACTION>
		<META>
			<IPADDRESS>123.123.123.123</IPADDRESS>
			<MERCHANTID>1</MERCHANTID>
			<VERSION>1.0</VERSION>
			<REQUESTIPADDRESS><?php echo $IPADDRESS ?></REQUESTIPADDRESS>
		</META>
		<PARAMS>
			<PAYMENT>
				<PAYMENTPRODUCTID>11</PAYMENTPRODUCTID>
				<AMOUNT>29990</AMOUNT>
				<CURRENCYCODE>EUR</CURRENCYCODE>
				<COUNTRYCODE>NL</COUNTRYCODE>
				<STREETNUMBER>14</STREETNUMBER>
				<CITY>Barcelona</CITY>
				<INVOICENUMBER>31245</INVOICENUMBER>
				<FIRSTNAME>Jan</FIRSTNAME>
				<PREFIXSURNAME>van</PREFIXSURNAME>
				<SURNAME>Driel</SURNAME>
				<LANGUAGECODE>nl</LANGUAGECODE>
			</PAYMENT>
		</PARAMS>
		<RESPONSE>
			<RESULT>OK</RESULT>
			<META>
				<RESPONSEDATETIME>20040718114145</RESPONSEDATETIME>
				<REQUESTID>231</REQUESTID>
			</META>
			<ROW>
				<EFFORTID><?php echo $EFFORTID ?></EFFORTID>
				<ATTEMPTID>1</ATTEMPTID>
				<ACCOUNTHOLDER>GlobalCollect BV</ACCOUNTHOLDER>
				<SWIFTCODE>ABNA NL 2A</SWIFTCODE>
				<CITY>Amsterdam</CITY>
				<BANKACCOUNTNUMBER>440339464</BANKACCOUNTNUMBER>
				<BANKNAME>ABN AMRO Bank</BANKNAME>
				<ADDITIONALREFERENCE>19998990005</ADDITIONALREFERENCE>
				<STATUSDATE>20030829153248</STATUSDATE>
				<PAYMENTREFERENCE>186200004710</PAYMENTREFERENCE>
				<ORDERID><?php echo $ORDERID ?></ORDERID>
				<STATUSID>800</STATUSID>
				<MERCHANTID>1</MERCHANTID>
				<COUNTRYDESCRIPTION>Nederland</COUNTRYDESCRIPTION>
			</ROW>
		</RESPONSE>
	</REQUEST>
</XML>
