<?php
/*
+--------------------------------------------------------------------+
| CiviCRM version 4.7                                                |
+--------------------------------------------------------------------+
| Copyright CiviCRM LLC (c) 2004-2017                                |
+--------------------------------------------------------------------+
| This file is a part of CiviCRM.                                    |
|                                                                    |
| CiviCRM is free software; you can copy, modify, and distribute it  |
| under the terms of the GNU Affero General Public License           |
| Version 3, 19 November 2007 and the CiviCRM Licensing Exception.   |
|                                                                    |
| CiviCRM is distributed in the hope that it will be useful, but     |
| WITHOUT ANY WARRANTY; without even the implied warranty of         |
| MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               |
| See the GNU Affero General Public License for more details.        |
|                                                                    |
| You should have received a copy of the GNU Affero General Public   |
| License and the CiviCRM Licensing Exception along                  |
| with this program; if not, contact CiviCRM LLC                     |
| at info[AT]civicrm[DOT]org. If you have questions about the        |
| GNU Affero General Public License or the licensing of CiviCRM,     |
| see the CiviCRM license FAQ at http://civicrm.org/licensing        |
+--------------------------------------------------------------------+
*/
/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2017
 *
 * Generated from xml/schema/CRM/ExtendedMailingStats/MailingStats.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:91cf6cadf39e7afbadcc98c306dcaa90)
 */
require_once 'CRM/Core/DAO.php';
require_once 'CRM/Utils/Type.php';
/**
 * CRM_ExtendedMailingStats_DAO_MailingStats constructor.
 */
class CRM_ExtendedMailingStats_DAO_MailingStats extends CRM_Core_DAO {
  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  static $_tableName = 'civicrm_mailing_stats';
  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var boolean
   */
  static $_log = true;

  /**
   * Unique ID
   *
   * @var int unsigned
   */
  public $id;

  /**
   * Mailing ID
   *
   * @var int unsigned
   */
  public $mailing_id;
  /**
   * Title of mailing
   *
   * @var string
   */
  public $mailing_name;
  /**
   *
   * @var boolean
   */
  public $is_completed;
  /**
   *
   * @var timestamp
   */
  public $created_date;
  /**
   *
   * @var timestamp
   */
  public $start;
  /**
   *
   * @var timestamp
   */
  public $finish;
  /**
   *
   * @var int unsigned
   */
  public $recipients;
  /**
   *
   * @var int unsigned
   */
  public $delivered;
  /**
   *
   * @var float
   */
  public $send_rate;
  /**
   *
   * @var int unsigned
   */
  public $bounced;

  /**
   *
   * @var int unsigned
   */
  public $blocked;
  /**
   *
   * @var int unsigned
   */
  public $opened_total;

  /**
   *
   * @var int unsigned
   */
  public $opened_unique;
  /**
   *
   * @var int unsigned
   */
  public $unsubscribed;
  /**
   *
   * @var int unsigned
   */
  public $forwarded;
  /**
   *
   * @var int unsigned
   */
  public $clicked_total;
  /**
   *
   * @var int unsigned
   */
  public $trackable_urls;
  /**
   *
   * @var int unsigned
   */
  public $clicked_contribution_page;
  /**
   *
   * @var int unsigned
   */
  public $contribution_count;
  /**
   *
   * @var float
   */
  public $contribution_total;
  /**
   * Class constructor.
   */
  function __construct() {
    $this->__table = 'civicrm_mailing_stats';
    parent::__construct();
  }
  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = array(
        'id' => array(
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'Unique ID',
          'required' => true,
          'table_name' => 'civicrm_mailing_stats',
          'entity' => 'MailingStats',
          'bao' => 'CRM_ExtendedMailingStats_DAO_MailingStats',
          'localizable' => 0,
        ),
        'mailing_id' => array(
          'name' => 'mailing_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'Mailing ID',
          'required' => true,
          'table_name' => 'civicrm_mailing_stats',
          'entity' => 'MailingStats',
          'bao' => 'CRM_ExtendedMailingStats_DAO_MailingStats',
          'localizable' => 0,
        ),
        'mailing_name' => array(
          'name' => 'mailing_name',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Mailing Name') ,
          'description' => 'Title of mailing',
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'table_name' => 'civicrm_mailing_stats',
          'entity' => 'MailingStats',
          'bao' => 'CRM_ExtendedMailingStats_DAO_MailingStats',
          'localizable' => 0,
          'html' => array(
            'type' => 'Text',
          ) ,
        ) ,
        'is_completed' => array(
          'name' => 'is_completed',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => ts('Is completed') ,
          'import' => true,
          'where' => 'civicrm_mailing_stats.is_completed',
          'headerPattern' => '',
          'dataPattern' => '',
          'export' => true,
          'table_name' => 'civicrm_mailing_stats',
          'entity' => 'MailingStats',
          'bao' => 'CRM_ExtendedMailingStats_DAO_MailingStats',
          'localizable' => 0,
          'html' => array(
            'type' => 'CheckBox',
          ) ,
        ) ,
        'created_date' => array(
          'name' => 'created_date',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => ts('Created Date') ,
          'required' => false,
          'default' => 'NULL',
          'table_name' => 'civicrm_mailing_stats',
          'entity' => 'MailingStats',
          'bao' => 'CRM_ExtendedMailingStats_DAO_MailingStats',
          'localizable' => 0,
          'html' => array(
            'type' => 'Select Date',
            'formatType' => 'activityDateTime',
          ) ,
        ) ,
        'start' => array(
          'name' => 'start',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => ts('Start') ,
          'required' => false,
          'default' => 'NULL',
          'table_name' => 'civicrm_mailing_stats',
          'entity' => 'MailingStats',
          'bao' => 'CRM_ExtendedMailingStats_DAO_MailingStats',
          'localizable' => 0,
          'html' => array(
            'type' => 'Select Date',
            'formatType' => 'activityDateTime',
          ) ,
        ) ,
        'finish' => array(
          'name' => 'finish',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => ts('Finish') ,
          'required' => false,
          'default' => 'NULL',
          'table_name' => 'civicrm_mailing_stats',
          'entity' => 'MailingStats',
          'bao' => 'CRM_ExtendedMailingStats_DAO_MailingStats',
          'localizable' => 0,
          'html' => array(
            'type' => 'Select Date',
            'formatType' => 'activityDateTime',
          ) ,
        ) ,
        'recipients' => array(
          'name' => 'recipients',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Number of Recipients') ,
          'required' => false,
          'default' => 'NULL',
          'table_name' => 'civicrm_mailing_stats',
          'entity' => 'MailingStats',
          'bao' => 'CRM_ExtendedMailingStats_DAO_MailingStats',
          'localizable' => 0,
          'html' => array(
            'type' => 'Text',
          ) ,
        ) ,
        'delivered' => array(
          'name' => 'delivered',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Number of Successful Deliveries') ,
          'required' => false,
          'default' => 'NULL',
          'table_name' => 'civicrm_mailing_stats',
          'entity' => 'MailingStats',
          'bao' => 'CRM_ExtendedMailingStats_DAO_MailingStats',
          'localizable' => 0,
          'html' => array(
            'type' => 'Text',
          ) ,
        ) ,
        'send_rate' => array(
          'name' => 'send_rate',
          'type' => CRM_Utils_Type::T_FLOAT,
          'title' => ts('Send Rate') ,
          'required' => false,
          'default' => 'NULL',
          'table_name' => 'civicrm_mailing_stats',
          'entity' => 'MailingStats',
          'bao' => 'CRM_ExtendedMailingStats_DAO_MailingStats',
          'localizable' => 0,
          'html' => array(
            'type' => 'Text',
          ) ,
        ) ,
        'bounced' => array(
          'name' => 'bounced',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Number of Bounces') ,
          'required' => false,
          'default' => 'NULL',
          'table_name' => 'civicrm_mailing_stats',
          'entity' => 'MailingStats',
          'bao' => 'CRM_ExtendedMailingStats_DAO_MailingStats',
          'localizable' => 0,
          'html' => array(
            'type' => 'Text',
          ) ,
        ) ,
        'blocked' => array(
          'name' => 'blocked',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Number of Blocks'),
          'description' => ts('Blocks represent administrative blocks such as blacklisting or lack of whitelisting by the email provider'),
          'required' => false,
          'default' => 'NULL',
          'table_name' => 'civicrm_mailing_stats',
          'entity' => 'MailingStats',
          'bao' => 'CRM_ExtendedMailingStats_DAO_MailingStats',
          'localizable' => 0,
          'html' => array(
            'type' => 'Text',
          ),
        ),
        'suppressed' => array(
          'name' => 'suppressed',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Number of Blocks'),
          'description' => ts('Blocks represent administrative blocks such as blacklisting or lack of whitelisting by the email provider'),
          'required' => false,
          'default' => 'NULL',
          'table_name' => 'civicrm_mailing_stats',
          'entity' => 'MailingStats',
          'bao' => 'CRM_ExtendedMailingStats_DAO_MailingStats',
          'localizable' => 0,
          'html' => array(
            'type' => 'Text',
          ),
        ),
        'abuse_complaints' => array(
          'name' => 'abuse_complaints',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Number of abuse or spam complaints from email'),
          'description' => ts('If using an external provider they may receive abuse complaints (e.g people marking mail as spam)'),
          'required' => false,
          'default' => 'NULL',
          'table_name' => 'civicrm_mailing_stats',
          'entity' => 'MailingStats',
          'bao' => 'CRM_ExtendedMailingStats_DAO_MailingStats',
          'localizable' => 0,
          'html' => array(
            'type' => 'Text',
          ),
        ),
        'opened_total' => array(
          'name' => 'opened_total',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Number Opened') ,
          'required' => false,
          'default' => 'NULL',
          'table_name' => 'civicrm_mailing_stats',
          'entity' => 'MailingStats',
          'bao' => 'CRM_ExtendedMailingStats_DAO_MailingStats',
          'localizable' => 0,
          'html' => array(
            'type' => 'Text',
          ),
        ),
        'opened_unique' => array(
          'name' => 'opened_unique',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Unique Opens') ,
          'required' => false,
          'default' => 'NULL',
          'table_name' => 'civicrm_mailing_stats',
          'entity' => 'MailingStats',
          'bao' => 'CRM_ExtendedMailingStats_DAO_MailingStats',
          'localizable' => 0,
          'html' => array(
            'type' => 'Text',
          ),
        ),
        'unsubscribed' => array(
          'name' => 'unsubscribed',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Number Unsubscribed') ,
          'required' => false,
          'default' => 'NULL',
          'table_name' => 'civicrm_mailing_stats',
          'entity' => 'MailingStats',
          'bao' => 'CRM_ExtendedMailingStats_DAO_MailingStats',
          'localizable' => 0,
          'html' => array(
            'type' => 'Text',
          ),
        ),
        'forwarded' => array(
          'name' => 'forwarded',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Number Forwarded') ,
          'required' => false,
          'default' => 'NULL',
          'table_name' => 'civicrm_mailing_stats',
          'entity' => 'MailingStats',
          'bao' => 'CRM_ExtendedMailingStats_DAO_MailingStats',
          'localizable' => 0,
          'html' => array(
            'type' => 'Text',
          ) ,
        ),
        'clicked_unique' => array(
          'name' => 'clicked_unique',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Unique clicks') ,
          'required' => false,
          'default' => 'NULL',
          'table_name' => 'civicrm_mailing_stats',
          'entity' => 'MailingStats',
          'bao' => 'CRM_ExtendedMailingStats_DAO_MailingStats',
          'localizable' => 0,
          'html' => array(
            'type' => 'Text',
          ),
        ),
        'clicked_total' => array(
          'name' => 'clicked_total',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Total clicks') ,
          'required' => false,
          'default' => 'NULL',
          'table_name' => 'civicrm_mailing_stats',
          'entity' => 'MailingStats',
          'bao' => 'CRM_ExtendedMailingStats_DAO_MailingStats',
          'localizable' => 0,
          'html' => array(
            'type' => 'Text',
          ) ,
        ),
        'trackable_urls' => array(
          'name' => 'trackable_urls',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Trackable urls') ,
          'required' => false,
          'default' => 'NULL',
          'table_name' => 'civicrm_mailing_stats',
          'entity' => 'MailingStats',
          'bao' => 'CRM_ExtendedMailingStats_DAO_MailingStats',
          'localizable' => 0,
          'html' => array(
            'type' => 'Text',
          ) ,
        ) ,
        'clicked_contribution_page' => array(
          'name' => 'clicked_contribution_page',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Number of clicks on Contribute Page') ,
          'required' => false,
          'default' => 'NULL',
          'table_name' => 'civicrm_mailing_stats',
          'entity' => 'MailingStats',
          'bao' => 'CRM_ExtendedMailingStats_DAO_MailingStats',
          'localizable' => 0,
          'html' => array(
            'type' => 'Text',
          ) ,
        ) ,
        'contribution_count' => array(
          'name' => 'contribution_count',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Number Of Related Contributions') ,
          'required' => false,
          'default' => 'NULL',
          'table_name' => 'civicrm_mailing_stats',
          'entity' => 'MailingStats',
          'bao' => 'CRM_ExtendedMailingStats_DAO_MailingStats',
          'localizable' => 0,
          'html' => array(
            'type' => 'Text',
          ) ,
        ) ,
        'contribution_total' => array(
          'name' => 'contribution_total',
          'type' => CRM_Utils_Type::T_FLOAT,
          'title' => ts('Total Amount Contributed') ,
          'required' => false,
          'default' => 'NULL',
          'table_name' => 'civicrm_mailing_stats',
          'entity' => 'MailingStats',
          'bao' => 'CRM_ExtendedMailingStats_DAO_MailingStats',
          'localizable' => 0,
          'html' => array(
            'type' => 'Text',
          ) ,
        ) ,
      );
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }
  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }
  /**
   * Returns the names of this table
   *
   * @return string
   */
  static function getTableName() {
    return self::$_tableName;
  }
  /**
   * Returns if this table needs to be logged
   *
   * @return boolean
   */
  function getLog() {
    return self::$_log;
  }
  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  static function &import($prefix = false) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'mailing_stats', $prefix, array());
    return $r;
  }
  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  static function &export($prefix = false) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'mailing_stats', $prefix, array());
    return $r;
  }
  /**
   * Returns the list of indices
   */
  public static function indices($localize = TRUE) {
    $indices = array(
      'index_start' => array(
        'name' => 'index_start',
        'field' => array(
          0 => 'start',
        ) ,
        'localizable' => false,
        'sig' => 'civicrm_mailing_stats::0::start',
      ) ,
      'index_finish' => array(
        'name' => 'index_finish',
        'field' => array(
          0 => 'finish',
        ) ,
        'localizable' => false,
        'sig' => 'civicrm_mailing_stats::0::finish',
      ) ,
    );
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }
}
