-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--


-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from drop.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the exisiting tables
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_strings`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_strings
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_strings` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique Strings ID',
  `entity_table` varchar(64) NOT NULL COMMENT 'Table where referenced item is stored',
  `entity_field` varchar(64) NOT NULL COMMENT 'Field where referenced item is stored',
  `entity_id` int(11) NOT NULL COMMENT 'ID of the relevant entity.',
  -- We can make string utf8mb4 (supports emojis, kanji) because we know it is never used
  -- to join on another table (that might not be the same collation).
  `string` longtext COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Translated string',
  `language` varchar(16) NOT NULL COMMENT 'Language',
  `is_active` tinyint(4) DEFAULT NULL COMMENT 'Is this string active?',
  `is_default` tinyint(4) DEFAULT NULL COMMENT 'Is this the default string for the given locale?',
 PRIMARY KEY (`id`)
) ENGINE=InnoDB


