<?php

function mod_install_refresher_perm() {
	return array( 'administer wmf test settings' );
}

function mod_install_refresher_menu() {
  $items = array();
  
  $items['admin/settings/mod_install_refresher'] = array(
    'title' => t('Module Install Refresher'),
    'description' => t('Uninstalls and re-installs the selected module'),
    'access arguments' => array('administer wmf test settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mod_install_refresher_form'),
  );
  
  return $items;
}

function mod_install_refresher_form() {
  $form = array();
  
  $form['mod_install_refresher_module'] = array(
    '#type' => 'select',
    '#title' => t('Module'),
	'#options' => module_list(),
    '#default_value' => variable_get('mod_install_refresher_module', ''),
    '#required' => FALSE,
  );
  $form['submit1'] = array(
    '#value' => 'Refresh Module Installation!',
    '#type' => 'submit'
  );

  return $form;
}

/**
 * Implementation of hook_form_submit
 *
 */
function mod_install_refresher_form_submit($form, &$form_state) {
	$module = $form_state['values']['mod_install_refresher_module'];
	include_once './includes/install.inc';
	if (module_exists($module)){
		drupal_uninstall_module($module);
	}
	drupal_install_modules(array($module));
	$content = "Refreshed install on module $module";
	watchdog('mod_install_refresher', $content);
	drupal_set_message($content);
}