-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_contribution_tracking`;

SET FOREIGN_KEY_CHECKS=1;

-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_contribution_tracking
-- *
-- * CiviCRM Contribution Tracking table
-- *
-- *******************************************************/
CREATE TABLE `civicrm_contribution_tracking` (
  `id` int unsigned NOT NULL COMMENT 'Unique Contribution Tracking ID',
  `contribution_id` int unsigned COMMENT 'FK to Contribution',
  `amount` decimal(20,3) COMMENT 'Amount',
  `currency` varchar(3) COMMENT 'Currency ISO Code',
  `usd_amount` decimal(20,2) COMMENT 'USD Amount',
  `is_recurring` tinyint,
  `referrer` varchar(4096) COMMENT 'Referrer',
  `utm_medium` varchar(128) COMMENT 'UTM Medium',
  `utm_campaign` varchar(128) COMMENT 'UTM Campaign',
  `utm_key` varchar(128) COMMENT 'UTM Key',
  `gateway` varchar(32) COMMENT 'Gateway, e.g paypal_ec,adyen',
  `appeal` varchar(64) COMMENT 'e.g JimmyQuote - the appeal is the text to the left of the input boxes (on desktop-size screens)',
  `payments_form_variant` varchar(64) COMMENT ' a \'variant\' generally changes something about the input boxes or their labels',
  `banner` varchar(128) COMMENT 'Banner',
  `landing_page` varchar(128) COMMENT 'Landing Page',
  `payment_method_id` int,
  `payment_submethod_id` int,
  `language` varchar(8) COMMENT 'Language',
  `country` varchar(2) COMMENT 'Country',
  `tracking_date` datetime COMMENT 'Tracking Date',
  `os` varchar(255) COMMENT 'Operating System',
  `os_version` varchar(255) COMMENT 'Operating System - Major Version',
  `browser` varchar(255) COMMENT 'Browser',
  `browser_version` varchar(255) COMMENT 'Browser Version',
  `recurring_choice_id` int COMMENT 'Denotes whether a recurring donation was the result of upsell or an organic recurring transaction',
  `device_type_id` int COMMENT 'The device the banner was served to (e.g Desktop or Mobile)',
  `banner_size_id` int COMMENT 'Large or small banner',
  `is_test_variant` tinyint COMMENT 'Test, rather than a control group',
  `banner_variant` varchar(128) COMMENT 'The name of the tested variant (if not control)',
  `is_pay_fee` tinyint COMMENT 'Did the user select to pay the processing fee',
  `mailing_identifier` varchar(32) COMMENT 'External mailing identifier',
  `utm_source` varchar(128) COMMENT 'UTM Source. This is the original text but is separately broken out into banner etc. We aspire to drop this field but per T354708 Peter Coombe is still reliant on it',
  `banner_history_log_id` varchar(255) COMMENT 'Temporary banner history log ID to associate banner history EventLogging events.',
  PRIMARY KEY (`id`),
  INDEX `currency`(currency),
  INDEX `utm_medium_id`(utm_medium),
  INDEX `utm_campaign_id`(utm_campaign),
  INDEX `banner`(banner),
  INDEX `landing_page`(landing_page),
  INDEX `payment_method_id`(payment_method_id),
  INDEX `language`(language),
  INDEX `country`(country),
  INDEX `tracking_date`(tracking_date),
  INDEX `index_mailing_identifier`(mailing_identifier),
  INDEX `banner_history_log_id`(mailing_identifier),
  CONSTRAINT FK_civicrm_contribution_tracking_contribution_id FOREIGN KEY (`contribution_id`) REFERENCES `civicrm_contribution`(`id`) ON DELETE SET NULL)
ENGINE=InnoDB;
