<?php
/*
+--------------------------------------------------------------------+
| CiviCRM version 4.7                                                |
+--------------------------------------------------------------------+
| Copyright CiviCRM LLC (c) 2004-2017                                |
+--------------------------------------------------------------------+
| This file is a part of CiviCRM.                                    |
|                                                                    |
| CiviCRM is free software; you can copy, modify, and distribute it  |
| under the terms of the GNU Affero General Public License           |
| Version 3, 19 November 2007 and the CiviCRM Licensing Exception.   |
|                                                                    |
| CiviCRM is distributed in the hope that it will be useful, but     |
| WITHOUT ANY WARRANTY; without even the implied warranty of         |
| MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               |
| See the GNU Affero General Public License for more details.        |
|                                                                    |
| You should have received a copy of the GNU Affero General Public   |
| License and the CiviCRM Licensing Exception along                  |
| with this program; if not, contact CiviCRM LLC                     |
| at info[AT]civicrm[DOT]org. If you have questions about the        |
| GNU Affero General Public License or the licensing of CiviCRM,     |
| see the CiviCRM license FAQ at http://civicrm.org/licensing        |
+--------------------------------------------------------------------+
*/
/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2017
 *
 * Generated from xml/schema/CRM/Omnimail/OmnimailJobProgress.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:9b5f9397769a4b1c942fcf3181cb8b17)
 */
require_once 'CRM/Core/DAO.php';
require_once 'CRM/Utils/Type.php';
/**
 * CRM_Omnimail_DAO_OmnimailJobProgress constructor.
 */
class CRM_Omnimail_DAO_OmnimailJobProgress extends CRM_Core_DAO {
  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  static $_tableName = 'civicrm_omnimail_job_progress';
  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var boolean
   */
  static $_log = false;
  /**
   * Unique OmnimailJobProgress ID
   *
   * @var int unsigned
   */
  public $id;
  /**
   * Mailing provider name
   *
   * @var string
   */
  public $mailing_provider;
  /**
   * job name
   *
   * @var string
   */
  public $job;
  /**
   * optional suffix to disambiguate the job
   *
   * @var string
   */
  public $job_identifier;
  /**
   * Mailing provider name
   *
   * @var timestamp
   */
  public $last_timestamp;
  /**
   * End timestamp of current retrieval
   *
   * @var timestamp
   */
  public $progress_end_timestamp;
  /**
   * json copy of any paramters that need to be passed to the provider.
   *
   * @var string
   */
  public $retrieval_parameters;
  /**
   * How many lines have been processed
   *
   * @var int unsigned
   */
  public $offset;
  /**
   * Class constructor.
   */
  function __construct() {
    $this->__table = 'civicrm_omnimail_job_progress';
    parent::__construct();
  }
  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = array(
        'id' => array(
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'Unique OmnimailJobProgress ID',
          'required' => true,
          'table_name' => 'civicrm_omnimail_job_progress',
          'entity' => 'OmnimailJobProgress',
          'bao' => '_OmnimailJobProgress',
          'localizable' => 0,
        ) ,
        'mailing_provider' => array(
          'name' => 'mailing_provider',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Mailing Provider') ,
          'description' => 'Mailing provider name',
          'maxlength' => 32,
          'size' => CRM_Utils_Type::MEDIUM,
          'table_name' => 'civicrm_omnimail_job_progress',
          'entity' => 'OmnimailJobProgress',
          'bao' => '_OmnimailJobProgress',
          'localizable' => 0,
        ) ,
        'job' => array(
          'name' => 'job',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Job') ,
          'description' => 'job name',
          'maxlength' => 32,
          'size' => CRM_Utils_Type::MEDIUM,
          'table_name' => 'civicrm_omnimail_job_progress',
          'entity' => 'OmnimailJobProgress',
          'bao' => '_OmnimailJobProgress',
          'localizable' => 0,
        ) ,
        'job_identifier' => array(
          'name' => 'job_identifier',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Job Identifier') ,
          'description' => 'optional suffix to disambiguate the job',
          'maxlength' => 512,
          'size' => CRM_Utils_Type::T_LONGTEXT,
          'table_name' => 'civicrm_omnimail_job_progress',
          'entity' => 'OmnimailJobProgress',
          'bao' => '_OmnimailJobProgress',
          'localizable' => 0,
        ) ,
        'last_timestamp' => array(
          'name' => 'last_timestamp',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => ts('Last Timestamp') ,
          'description' => 'Mailing provider name',
          'table_name' => 'civicrm_omnimail_job_progress',
          'entity' => 'OmnimailJobProgress',
          'bao' => '_OmnimailJobProgress',
          'localizable' => 0,
        ) ,
        'progress_end_timestamp' => array(
          'name' => 'progress_end_timestamp',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => ts('Progress End Timestamp') ,
          'description' => 'End timestamp of current retrieval',
          'table_name' => 'civicrm_omnimail_job_progress',
          'entity' => 'OmnimailJobProgress',
          'bao' => '_OmnimailJobProgress',
          'localizable' => 0,
        ) ,
        'retrieval_parameters' => array(
          'name' => 'retrieval_parameters',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Retrieval Parameters') ,
          'description' => 'json copy of any paramters that need to be passed to the provider.',
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'table_name' => 'civicrm_omnimail_job_progress',
          'entity' => 'OmnimailJobProgress',
          'bao' => '_OmnimailJobProgress',
          'localizable' => 0,
        ) ,
        'offset' => array(
          'name' => 'offset',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Offset') ,
          'description' => 'How many lines have been processed',
          'table_name' => 'civicrm_omnimail_job_progress',
          'entity' => 'OmnimailJobProgress',
          'bao' => '_OmnimailJobProgress',
          'localizable' => 0,
        ) ,
      );
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }
  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }
  /**
   * Returns the names of this table
   *
   * @return string
   */
  static function getTableName() {
    return self::$_tableName;
  }
  /**
   * Returns if this table needs to be logged
   *
   * @return boolean
   */
  function getLog() {
    return self::$_log;
  }
  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  static function &import($prefix = false) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'omnimail_job_progress', $prefix, array());
    return $r;
  }
  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  static function &export($prefix = false) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'omnimail_job_progress', $prefix, array());
    return $r;
  }
  /**
   * Returns the list of indices
   */
  public static function indices($localize = TRUE) {
    $indices = array();
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }
}
