<?php
use CRM_Wmf_ExtensionUtil as E;

return [
  'wmf_unsubscribe_url' => [
    'group_name' => 'wmf Settings',
    'group' => 'wmf',
    'name' => 'wmf_unsubscribe_url',
    'default' => 'https://payments.wikimedia.org/index.php/Special:FundraiserUnsubscribe',
    'type' => 'String',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts('Unsubscribe base url'),
    'help_text' => '',
    'html_type' => 'text',
    'html_attributes' => [
      'size' => 80,
    ],
    'settings_pages' => ['wmf-civicrm' => ['weight' => 20]],
  ],
  'wmf_email_preferences_url' => [
    'group_name' => 'wmf Settings',
    'group' => 'wmf',
    'name' => 'wmf_email_preferences_url',
    'default' => 'https://donorpreferences.wikimedia.org/wiki/index.php?title=Special:EmailPreferences/emailPreferences',
    'type' => 'String',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts('Email preferences base url'),
    'help_text' => '',
    'html_type' => 'text',
    'html_attributes' => [
      'size' => 100,
    ],
    'settings_pages' => ['wmf-civicrm' => ['weight' => 30]],
  ],
  'wmf_recurring_upgrade_url' => [
    'group_name' => 'wmf Settings',
    'group' => 'wmf',
    'name' => 'wmf_recurring_upgrade_url',
    'default' => 'https://donorpreferences.wikimedia.org/index.php?title=Special:RecurUpgrade/recurUpgrade',
    'type' => 'String',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts('Recurring Upgrade base url'),
    'help_text' => '',
    'html_type' => 'text',
    'html_attributes' => [
      'size' => 100,
    ],
    'settings_pages' => ['wmf-civicrm' => ['weight' => 35]],
  ],
  'wmf_donor_portal_url' => [
    'group_name' => 'wmf Settings',
    'group' => 'wmf',
    'name' => 'wmf_donor_portal_url',
    'default' => 'https://donorpreferences.wikimedia.org/index.php?title=Special:DonorPortal',
    'type' => 'String',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts('Donor Portal base url'),
    'help_text' => '',
    'html_type' => 'text',
    'html_attributes' => [
      'size' => 100,
    ],
    'settings_pages' => ['wmf-civicrm' => ['weight' => 36]],
  ],
  'wmf_last_delete_deleted_contact_modified_date' => [
    'group_name' => 'wmf Settings',
    'group' => 'wmf',
    'name' => 'wmf_last_delete_deleted_contact_modified_date',
    'default' => null,
    'type' => 'Date',
    'quick_form_type' => 'DateTime',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts('Last delete deleted contact\'s modified date'),
    'help_text' => '',
    'html_type' => 'text',
    'html_attributes' => [
      'size' => 20,
    ],
    'settings_pages' => ['wmf-civicrm' => ['weight' => 40]],
  ],
  'wmf_save_process_greetings_on_create' => [
    'group_name' => 'wmf Settings',
    'group' => 'wmf',
    'name' => 'wmf_save_process_greetings_on_create',
    'default' => 1,
    'type' => 'Boolean',
    'quick_form_type' => 'YesNo',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts('Should greeting processing be done during create'),
    'help_text' => '',
    'html_type' => 'radio',
    'settings_pages' => ['wmf-civicrm' => ['weight' => 50]],
  ],
  //
  'wmf_refund_alert_factor' => [
    'group_name' => 'wmf Settings',
    'group' => 'wmf',
    'name' => 'wmf_refund_alert_factor',
    'default' => 0.02,
    'type' => 'Float',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts('Refund discrepancy alert factor'),
    'help_text' => E::ts(
      'Send a failmail when a refund differs from the original contribution by more than this factor'
    ),
    'html_type' => 'number',
    'html_attributes' => [
      'size' => '5',
    ],
    // FixCivi: these would make a lot more sense under 'html_attributes' but you'd have to take that up
    // with SettingsTrait::addFieldsDefinedInSettingsMetadata which passes the 'options' to the same
    // class's add function as its $attributes argument.
    'options' => [
      'step' => '0.01',
      'min' => '0',
      'max' => '1',
    ],
    'settings_pages' => ['wmf-civicrm' => ['weight' => 60]],
   ],
  'wmf_resolved_charge_descriptor' => [
    'group name' => 'wmf Settings',
    'group' => 'wmf',
    'name' => 'wmf_resolved_charge_descriptor',
    'type' => 'Text',
    'quick_form_type' => 'Element',
    'html_type' => 'text',
    'html_attributes' => array(
      'size' => 40,
    ),
    'default' => 'Donation',
    'is_domain' => '1',
    'is_contact' => 0,
    'title' => 'Soft descriptor for resolved pending transactions',
    'description' => 'The first 22 or so characters of this string show up on credit card statements.',
    'settings_pages' => ['wmf-civicrm' => ['weight' => 70]],
  ],
  'zendesk_api_user' => [
    'group_name' => 'Zendesk settings',
    'group' => 'zendesk_settings',
    'name' => 'zendesk_api_user',
    'type' => 'string',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => \CRM_Wmf_ExtensionUtil::ts('API User for Zendesk API calls (found on Zendesk API settings page)'),
    'default' => 'zendesk_api_user',
    'title' => E::ts('Zendesk API User'),
    'help_text' => '',
    'html_type' => 'text',
    'settings_pages' => ['zendesk' => ['weight' => 20]],
  ],
  'zendesk_api_password' => [
    'group_name' => 'Zendesk settings',
    'group' => 'zendesk_settings',
    'name' => 'zendesk_api_password',
    'type' => 'string',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => \CRM_Wmf_ExtensionUtil::ts('API password for Zendesk API calls (found on Zendesk API settings page)'),
    'default' => 'zendesk_api_password',
    'title' => E::ts('Zendesk API password'),
    'help_text' => '',
    'html_type' => 'password',
    'settings_pages' => ['zendesk' => ['weight' => 20]],
  ],
  'zendesk_url' => [
    'group_name' => 'Zendesk settings',
    'group' => 'zendesk_settings',
    'name' => 'zendesk_url',
    'type' => 'string',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => \CRM_Wmf_ExtensionUtil::ts('URL of the WMF Zendesk instance'),
    'default' => 'https://wikimedia.zendesk.com',
    'title' => E::ts('Zendesk URL'),
    'help_text' => '',
    'html_type' => 'text',
    'settings_pages' => ['zendesk' => ['weight' => 20]],
  ],
];
