<?php

define( 'WP_AUDIT_RECON_PARSER_DIR', '/usr/local/src/WP_Parser_Lib/' );
define( 'WP_AUDIT_RECON_FILES_DIR', '/usr/local/src/recon_files/' );
define('WP_AUDIT_RECON_COMPLETED_DIR', '/usr/local/src/recon_files-completed/');
define('WP_AUDIT_WORKING_LOG_DIR', '/usr/local/src/log_files-working/');
define('WP_AUDIT_LOG_SEARCH_PAST_DAYS', 7);
define( 'WP_AUDIT_TEST_MODE', true );

/**
 * Implementation of hook_menu()
 */
function worldpay_audit_menu() {
  $items = array();

  $items['admin/config/wmf_audit/worldpay_audit'] = array(
    'title' => 'WorldPay Audit',
    'description' => t('Configure WMF audit settings.'),
    'access arguments' => array('administer wmf_audit'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array( 'worldpay_audit_settings' ),
  );

  return $items;
}

/**
 * Callback for menu
 */
function worldpay_audit_settings() {
  $form['worldpay_audit_recon_files_dir']  = array(
    '#type' => 'textfield',
    '#title' => t( 'Directory containing incoming reconciliation files' ),
    '#required' => TRUE,
    '#default_value' => variable_get( 'worldpay_audit_recon_files_dir', WP_AUDIT_RECON_FILES_DIR ),
  );
  $form['worldpay_audit_recon_completed_dir']  = array(
    '#type' => 'textfield',
    '#title' => t( 'Directory for completed reconciliation files' ),
    '#required' => TRUE,
    '#default_value' => variable_get( 'worldpay_audit_recon_completed_dir', WP_AUDIT_RECON_COMPLETED_DIR ),
  );
  $form['worldpay_audit_working_log_dir'] = array(
    '#type' => 'textfield',
    '#title' => t('Working directory for payments logs (Not the source - that is defined at the wmf_audit level)'),
    '#required' => TRUE,
    '#default_value' => variable_get('worldpay_audit_working_log_dir', WP_AUDIT_WORKING_LOG_DIR),
  );
  $form['worldpay_audit_test_mode']  = array(
    '#type' => 'checkbox',
    '#title' => t( 'When this box is checked, no stomp messages will be sent.' ),
    '#required' => FALSE,
    '#default_value' => variable_get( 'worldpay_audit_test_mode', WP_AUDIT_TEST_MODE ),
  );
  $form['worldpay_audit_log_search_past_days'] = array(
    '#type' => 'textfield',
    '#title' => t( 'Plus or minus log search (in days)' ),
    '#required' => TRUE,
    '#default_value' => variable_get('worldpay_audit_log_search_past_days', WP_AUDIT_LOG_SEARCH_PAST_DAYS),
  );
  return system_settings_form( $form );
}
