<?php

require_once 'db_switcher.inc';
require_once 'recurring.inc';
require_once 'tracking.inc';

/**
 * return a map of option value (id) => option name
 */
function civicrm_api_option_group($group_name, $key = null)
{
	static $cached_group = array();
	if (!array_key_exists($group_name, $cached_group))
	{
		$api = civicrm_api_classapi();
		$api->OptionValue->Get(array(
			'option_group_name' => $group_name,
		));
		$cached_group[$group_name] = array();
		$option_values = $api->values();
		foreach ($option_values as $row)
		{
			$cached_group[$group_name][$row->value] = $row->name;
		}
	}
	if ($key)
	{
		// In this case, just lookup name and return the option value
		$forwards = array_flip($cached_group[$group_name]);
		return $forwards[$key];
	}
	return $cached_group[$group_name];
}

function civicrm_option_group_id( $group_name ) {
    $api = civicrm_api_classapi();
    $success = $api->OptionGroup->Get(array(
        'name' => $group_name,
    ));
    if ( $success && $api->values ) {
        return $api->values[0]->id;
    }
}

function civicrm_api_contribution_status($key = null)
{
	return civicrm_api_option_group('contribution_status', $key);
}

function civicrm_api_classapi()
{
	civicrm_initialize();
	if (module_load_include('php', 'civicrm', '../api/class.api') === FALSE)
	{
		watchdog('civicrm_api', t('Failed to load civicrm api classes'), array(), WATCHDOG_ERROR);
	}
	else
	{
		return new civicrm_api3();
	}
}

/**
 * Determines the settlement currency for a given donation.
 * Argument is a queue message or a civicrm contribution array.
 */
function wmf_civicrm_get_settlement_currency($transaction)
{
	return 'USD';
}

/**
 * Given the date a payment was settled (in unix seconds), recalculate the
 * amount in USD using the exchange rate at that moment.  Put this amount in a
 * custom field.
 * Then, set the civi amounts and currencies to reflect the real settlement
 * currency and amount.
 *
 * Return the contribution array with these extra fields merged in.
 */
function wmf_civicrm_settle( $contribution, $settled_timestamp = null )
{
    if ( $settled_timestamp === null ) {
        // Get the stored date
        // FIXME wmf_civicrm_contribution_get_custom_values('settlement_date');
        $field = wmf_civicrm_get_custom_field_name( 'settlement_date' );
        $params = array(
            'entityID' => $contribution['id'],
            $field => 1
        );
        require_once 'CRM/Core/BAO/CustomValueTable.php';
        $result = CRM_Core_BAO_CustomValueTable::getValues( $params );
        $settlement_db_date = $result[$field];
        $settled_timestamp = strtotime( $settlement_db_date );
        $settlement_db_date = date( 'YmdHis', $settled_timestamp );
    } else {
        $settlement_db_date = date( 'YmdHis', $settled_timestamp );
    }

    list($original_currency, $original_amount) = explode(" ", $contribution['source']);
    $total_usd = round(exchange_rate_convert($original_currency, $original_amount, $settled_timestamp), 2);

    $custom_values = array(
        'total_usd' => $total_usd,
        'settlement_date' => $settlement_db_date,
    );
    wmf_civicrm_set_custom_field_values($contribution['id'], $custom_values);

    $settled_currency = wmf_civicrm_get_settlement_currency( $contribution );
    if ( $contribution['currency'] != $settled_currency ) {
        $settlement_convert =
            exchange_rate_convert( $settled_currency, 1, $settled_timestamp );
        $contribution['total_amount'] = round( $contribution['total_amount'] * $settlement_convert, 2 );
        $contribution['fee_amount'] = round( $contribution['fee_amount'] * $settlement_convert, 2 );
        $contribution['net_amount'] = round( $contribution['net_amount'] * $settlement_convert, 2 );

        $contribution['currency'] = $settled_currency;

        $contribution['version'] = 3; //WTF

        $contribution_result = civicrm_api( "Contribution", "Create", $contribution );
        if ( array_key_exists( 'is_error', $contribution_result ) && $contribution_result['is_error'] != 0 ) {
            throw new Exception( "Couldn't update contribution with new settlement info. txn_id: {$contribution['trxn_id']}" );
        }
    }

    return array_merge( $contribution, $custom_values );
}

// FIXME all of these custom field helpers share flaws: they do not consider entity type, or custom group name
function wmf_civicrm_contribution_get_custom_values( $contribution_id, $names )
{
    $names = (array)$names;
    $params[ 'entityID' ] = $contribution_id;
    foreach ( $names as $name ) {
        $field = wmf_civicrm_get_custom_field_name( $name );
        $params[ $field ] = 1;
        $field_map[ $field ] = $name;
    }
    require_once 'CRM/Core/BAO/CustomValueTable.php';
    $result = CRM_Core_BAO_CustomValueTable::getValues( $params );
    foreach ( $result as $field => $value ) {
        if ( array_key_exists( $field, $field_map ) ) {
            $ret[ $field_map[ $field ] ] = $value;
        }
    }
    return $ret;
}

// FIXME: contribution_set_custom_values
function wmf_civicrm_set_custom_field_values($entity_id, $map)
{
    require_once 'CRM/Core/BAO/CustomValueTable.php';

    $params = array(
        'entityID' => $entity_id,
    );
    $custom_fields = wmf_civicrm_get_custom_field_map(array_keys($map));
    foreach ($map as $field_name => $value)
    {
        $params[$custom_fields[$field_name]] = $value;
    }
    $result = CRM_Core_BAO_CustomValueTable::setValues($params);
    if (!empty($result['is_error']))
    {
        throw new WmfException( 'CIVI_CONFIG',
            t( 'Failed to set custom values: id !id, error: !err', array( '!id' => $entity_id, '!err' => $result['error_message'] ) )
        );
    }
}

function wmf_civicrm_get_custom_field_map( $field_names, $group_name = null )
{
    require_once 'CRM/Core/BAO/CustomField.php';

    static $custom_fields = array();
    foreach ($field_names as $name)
    {
        if (empty($custom_fields[$name]))
        {
            $id = CRM_Core_BAO_CustomField::getCustomFieldID( $name, $group_name );
            $custom_fields[$name] = "custom_{$id}";
        }
    }

    return $custom_fields;
}

function wmf_civicrm_get_custom_field_name( $field_name ) {
    $custom_fields = wmf_civicrm_get_custom_field_map( array( $field_name ) );
    return $custom_fields[ $field_name ];
}

/**
 * Try to import a transaction message into CiviCRM, otherwise
 * throw an exception.
 */
function wmf_civicrm_contribution_message_import( &$msg ) {
    $msg = wmf_civicrm_verify_message_and_stage($msg);

    //XXX should be debug level, or does this have a magic purpose?
    watchdog('queue2civicrm', 'Contribution:<pre>' . check_plain(print_r($msg, TRUE)) . '</pre>');

    // insert the contact information
    $contact = wmf_civicrm_message_contact_insert( $msg );

    // Insert the location record
    $location = wmf_civicrm_message_location_insert( $msg, $contact );

    // Insert the contribution record.
    $contribution = wmf_civicrm_message_contribution_insert( $msg, $contact );

    if ( isset( $msg[ 'recurring' ] ) && $msg[ 'recurring' ] == 1 ) {
        watchdog( 'queue2civicrm_import', 'Attempting to insert recurring record.'); //BLAH
        wmf_civicrm_message_contribution_recur_insert( $msg, $contact['id'], $contribution );
    }

    // Tag contact for review
    try {
        $tag = wmf_civicrm_tag_contact_for_review( $contact );
    } catch (WmfException $ex) {
        // XXX copying old logic, continues without a review tag
    }

    // Map the tracking record to the CiviCRM contribution
    // @FIXME what do we do if this returns false?  nothing at the moment...
    wmf_civicrm_message_update_contribution_tracking( $msg, $contribution );

    return $contribution;
}

/**
 * Insert the contribution record
 * 
 * Serves as a standard way for message processors to handle contribution
 * insertion.
 * 
 * @param array $msg
 * @param array $contact
 * @param integer $recur_id   See `civicrm_contribution`.`contribution_recur_id`
 * @param integer $effort_id  The effort id - the number of successful payments for recurring payments
 * @return array
 */
function wmf_civicrm_message_contribution_insert( $msg, $contact, $recur_id=NULL, $effort_id=NULL )
{
    civicrm_initialize();

    try {
        $transaction = WmfTransaction::from_message( $msg );
        $transaction->recur_sequence = $effort_id;
        $trxn_id = $transaction->get_unique_id();
    } catch ( Exception $ex ) {
        throw new WmfException("INVALID_MESSAGE", "Could not add contribution: " . $ex->getMessage(), $msg );
    }

    $msg['contribution_type'] = wmf_civicrm_get_message_contribution_type($msg);
    $contribution_type_id = wmf_civicrm_get_civi_id( 'contribution_type_id', $msg['contribution_type'] );

    //XXX always redundant?
    if ( !array_key_exists( "payment_instrument", $msg ) ){
        $msg['payment_instrument'] = wmf_civicrm_get_message_payment_instrument( $msg );
    }
    $payment_instrument_id = wmf_civicrm_get_civi_id( 'payment_instrument_id', $msg['payment_instrument'] );
    if ( !$payment_instrument_id )
    {
        throw new WmfException("INVALID_MESSAGE", "No payment type found for message.", $msg);
    }

    if ( !array_key_exists( 'check_number', $msg ) ){
        $msg['check_number'] = NULL;
    }
    if ( !array_key_exists( 'letter_code', $msg ) ){
        $msg['letter_code'] = NULL;
    }

    $contribution = array(
        'contact_id' => $contact[ 'id' ],
        'total_amount' => $msg['gross'],
        'contribution_type_id' => $contribution_type_id,
        'payment_instrument_id' => $payment_instrument_id,
        'fee_amount' => $msg['fee'],
        'net_amount' => $msg['net'],
        'trxn_id' => $trxn_id,
        'receive_date' => date( 'Y-m-d H:i:s', $msg['date'] ),
        'currency' => $msg['currency'],
        'source' => $msg['original_currency'] . ' ' . $msg['original_gross'],
        'contribution_recur_id' => $recur_id,
        'check_number' => $msg['check_number'],
        'letter_code' => $msg['letter_code'],

        // API required fields
        'version' => '3'
    );

    watchdog( 'wmf_civicrm', 'Contribution array for civicrm_contribution_add(): ' . print_r($contribution, TRUE), NULL, WATCHDOG_DEBUG);

    $contribution_result = civicrm_api( "Contribution", "Create", $contribution );
    
    watchdog( 'wmf_civicrm', 'Contribution result from civicrm_contribution_add(): ' . print_r($contribution_result, TRUE), NULL, WATCHDOG_DEBUG);
    
    if ( array_key_exists( 'is_error', $contribution_result ) && $contribution_result['is_error'] != 0 ) {
        throw new WmfException( 'INVALID_MESSAGE',
            t( 'Cannot create contribution: !error.', array( '!error' => $contribution_result['error_message'] ) ),
            array( 'contribution' => $contribution, 'source' => $msg )
        );
    }
  
    /**
    *  Apply custom field defaults.
    *
    *  Hopefully the Civi API will eventually handle custom fields in the
    *  above "Create" call.
    *
    * At the moment, all custom fields get default values for online contribution EXCEPT for 'Donor Comment'.
    *
    * NOTE: the custom field for "Gift_Information" indicates that check number is stored here.  It is not.
    */
    $comment = ( isset( $msg[ 'comment' ] ) ) ? $msg[ 'comment'] : '';
    $lettercode = ( $msg[ 'letter_code' ] ) ? $msg[ 'letter_code'] : NULL;
    $gateway_account = array_key_exists( 'gateway_account', $msg ) ? $msg[ 'gateway_account' ] : '';

    $custom_vars = array(
        'Contribution_Comments' => $comment,
        'Gift_Data' => $lettercode,
        'gateway_account' => $gateway_account,
    );
    wmf_civicrm_set_custom_field_values( $contribution_result[ 'id' ], $custom_vars );

    return $contribution_result[ 'values' ][ $contribution_result[ 'id' ] ];
}

/**
 * @fixme TODO: make the v3 API calls use the wrapper function
 *
 * @param $type
 * @param $name
 * @return bool
 */
function wmf_civicrm_get_civi_id($type, $name)
{
    static $civi_ids = array();
    $params = array('name' => $name);
    $dummy = array();
    
    if(array_key_exists($type, $civi_ids) && array_key_exists($name, $civi_ids[$type])) {
        watchdog('wmf_civicrm', "Already looked up $type - $name. Returning id " . $civi_ids[$type][$name]);
        return $civi_ids[$type][$name];
    }

    switch ($type) {
        case 'contribution_type_id':
            //fixme: This is probably the upside-down way to do it. Really ought to go through the API.
            //
            require_once( drupal_get_path( 'module', 'civicrm' ) . '/../CRM/Contribute/BAO/ContributionType.php' );
            $result = CRM_Contribute_BAO_ContributionType::retrieve($params, $dummy);
            if (!is_null($result)){
                $civi_ids[$type][$name] = $result->id;
                watchdog('wmf_civicrm', "Found id for contribution_type $name: " . $civi_ids[$type][$name]);
            } else {
                //make it. Or, throw an error here. Either way.
                //XXX nonono
                watchdog('wmf_civicrm', "Id for contribution_type $name not found. Creating...");
                $params['description'] = '';
                $params['accounting_code'] = strtoupper($name);
                $params['is_deductible'] = 1;
                $params['is_active'] = 1;
                $result = CRM_Contribute_BAO_ContributionType::add($params, $dummy);
                $civi_ids[$type][$name] = $result->id;
                watchdog('wmf_civicrm', "New id for contribution_type $name :" . $civi_ids[$type][$name]);
            }
            $id = $civi_ids[$type][$name];
            if (empty($id)) {
                throw new WmfException( "CIVI_CONFIG",
                    t( 'Contribution Type "!name" not found!', array( '!name' => $name ) )
                );
            }
            return $id;
        case 'payment_instrument_id':
            require_once 'api/v3/OptionValue.php';
            $group_id = civicrm_api3_option_value_get(
                array('option_group_name' => 'payment_instrument', 'label'=> $name, 'version' => '3'));
            if($group_id['count'] == 1){
                $civi_ids[$type][$name] = $group_id['values'][strval($group_id['id'])]['value'];
                watchdog('wmf_civicrm', "Found value for payment_instrument $name :" . $civi_ids[$type][$name]);
                return $civi_ids[$type][$name];
            } else {
                throw new WmfException("CIVI_CONFIG", t("Payment Instrument '!name' not found!", array("!name" => $name)));
            }
            break;
        case 'tag_id':
            require_once 'api/v3/Tag.php';
            $tag_id = civicrm_api3_tag_get(array('name'=> $name, 'version' => '3'));
            if (is_array($tag_id) && array_key_exists('id', $tag_id)){
                $civi_ids[$type][$name] = $tag_id['id'];
                watchdog('wmf_civicrm', "Found id for Entity Tag $name :" . $civi_ids[$type][$name]);
                return $civi_ids[$type][$name];
            } else {
                throw new WmfException("CIVI_CONFIG", t("Entity Tag '!name' not found!", array("!name" => $name)));
            }
        default:
            throw new WmfException("CIVI_CONFIG", t("Civi lookup for type '!type' not implemented", array("!type" => $type)));
    }
}

function wmf_civicrm_get_message_contribution_type( $msg ) {
    if ($msg['gateway'] == 'merkle') {
        return 'merkle';
    }
    return 'cash';
}

/**
 * Determines which civi-only payment instrument is appropriate for the current 
 * message, and resturns the civi payment instrument's human-readable display 
 * string (if it exists).   
 *
 * TODO lookup table
 */
function wmf_civicrm_get_message_payment_instrument( $msg )
{
    civicrm_initialize();

    $payment_instrument = null;
    
    if ( array_key_exists( 'payment_method', $msg ) && trim( $msg['payment_method'] ) != '' ){
    
        switch( strtolower( $msg[ 'payment_method' ] ) ){
            case 'check':
                $payment_instrument = 'Check';
                break;
            case 'bt':
                $payment_instrument = 'Bank Transfer';
                break;
            case 'cc':
                $payment_instrument = 'Credit Card';	
                switch ( strtolower( $msg['payment_submethod'] ) ){
                    case 'visa':
                        $payment_instrument .= ': Visa';
                        break;
                    case 'mc':
                        $payment_instrument .= ': MasterCard';
                        break;
                    case 'amex':
                        $payment_instrument .= ': American Express';
                        break;
                    case 'maestro':
                        $payment_instrument .= ': Maestro';
                        break;
                    case 'solo':
                        $payment_instrument .= ': Solo';
                        break;
                    case 'laser':
                        $payment_instrument .= ': Laser';
                        break;
                    case 'jcb':
                        $payment_instrument .= ': JCB';
                        break;
                    case 'discover':
                        $payment_instrument .= ': Discover';
                        break;
                    case 'cb':
                        $payment_instrument .= ': Carte Bleue';
                        break;
                }
                break;
            case 'dd':
                $payment_instrument = 'Direct Debit';
                break;
            case 'ew':
                switch( strtolower( $msg['payment_submethod'] ) ){
                    case 'ew_paypal':
                        $payment_instrument = 'Paypal';
                        break;
                    case 'ew_webmoney':
                        $payment_instrument = 'Webmoney';
                        break;
                    case 'ew_moneybookers':
                        $payment_instrument = 'Moneybookers';
                        break;
                    case 'ew_cashu':
                        $payment_instrument = 'Cashu';
                        break;
                    case 'ew_yandex':
                        $payment_instrument = 'Yandex';
                        break;
                }
                break;
            case 'obt':
                if ( strtolower( $msg['payment_submethod'] === 'bpay' ) ){
                    $payment_instrument = 'Bpay';
                }
                break;
            case 'rtbt':
                switch( strtolower( $msg['payment_submethod'] ) ){
                    case 'rtbt_nordea_sweden':
                        $payment_instrument = 'Nordea';
                        break;
                    case 'rtbt_ideal':
                        $payment_instrument = 'iDeal';
                        break;
                    case 'rtbt_enets':
                        $payment_instrument = 'Enets';
                        break;
                    case 'rtbt_sofortuberweisung':
                        $payment_instrument = 'Sofort';
                        break;
                    case 'rtbt_eps':
                        $payment_instrument = 'EPS';
                        break;
                }
                break;
            case 'cash':
                $payment_instrument = 'Cash';
                //'cash_boleto' - Only one right now. I assume there might be more later? 
                switch ( strtolower( $msg['payment_submethod'] ) ){
                    case 'cash_boleto': 
                        $payment_instrument = 'Boleto';
                        break;
                }
                break;	
            case 'payflowpro':
                if ( strtolower( $msg['gateway'] ) === 'payflowpro' ){
                    $payment_instrument = 'Credit Card';
                }
                break;
            case 'amazon':
                $payment_instrument = 'Amazon';
                break;
        }
        
    } else {
        //payment_method is not even in the message. Assume it's legacy... but we can tell some things about these, too...
        if ( array_key_exists( 'gateway', $msg ) && strtolower($msg['gateway']) === 'paypal' ){
            $payment_instrument = 'Paypal';
        }
    }

    //I was going to check to make sure the target gateway was a real thing, but: Hello, overhead. No.
    return $payment_instrument;
}

/**
 * Normalize contribution amounts
 * 
 * Do exchange rate conversions and set appropriate fields for CiviCRM
 * based on information contained in the message.
 * 
 * @param $msg
 * @return array
 */
function wmf_civicrm_normalize_contribution_amounts( $msg ) {
  $settlement_currency = wmf_civicrm_get_settlement_currency($msg);
  try {
      $settlement_convert = exchange_rate_convert($msg['original_currency'], 1, $msg['date']) / exchange_rate_convert($settlement_currency, 1, $msg['date']);
  }
  catch (Exception $ex) {
      wmf_common_failmail( 'wmf_civicrm', "UNKNOWN_CURRENCY: exchange rate will be fudged as '1': " . $ex->getMessage(), $msg );
      $settlement_convert = 1;
  }

  // round the amounts and do exchange rate conversion
  $msg['fee'] = round( $msg['fee'] * $settlement_convert, 2 );
  $msg['gross'] = round( $msg['gross'] * $settlement_convert, 2 );
  $msg['net'] = round( $msg['net'] * $settlement_convert, 2 );
  $msg['currency'] = $settlement_currency;
  
  return $msg;
}

function wmf_civicrm_verify_message_and_stage($msg)
{
    if ( !is_array( $msg ) ) {
        $msg = json_decode($msg->body, true);
    }

    $required = array(
        'email',
        'gross',
        'original_currency',
        'gateway',
        'gateway_txn_id',
    );

    $err = array();
    foreach ($required as $key){
        if (!isset($msg[$key]) || $msg[$key] === ''){
            $err[] = "Required Field '$key' not found in message.";
        }
    }

    if(!array_key_exists('fee', $msg) && !array_key_exists('net', $msg)){
        $msg['fee'] = '0.00';
        $msg['net'] = $msg['gross'];
    } elseif(!array_key_exists('fee', $msg) && array_key_exists('net', $msg)){
        $msg['fee'] = $msg['gross'] - $msg['net'];
    } elseif(array_key_exists('fee', $msg) && !array_key_exists('net', $msg)){
        $msg['net'] = $msg['gross'] - $msg['fee'];
    }

    if (floatval($msg['net']) <= 0 || floatval($msg['gross']) <= 0)
    {
        $err[] = "Positive amount required.";
    }

    if (!empty($err)) {
        throw new WmfException('CIVI_REQ_FIELD', $err, $msg);
    }

    //Now check to make sure this isn't going to be a duplicate message for this gateway.
    if ( wmf_civicrm_get_contributions_from_gateway_id( $msg['gateway'], $msg['gateway_txn_id'] ) ) {
        throw new WmfException('DUPLICATE_CONTRIBUTION', 
        "Contribution already exists. Ignoring message.", 
        $msg);
    }

    $msg['anonymous'] = (array_key_exists('anonymous', $msg) && $msg['anonymous'] == true && strtoupper($msg['anonymous']) != "FALSE") ? 1 : 0;
    $msg['optout'] = (array_key_exists('optout', $msg) && ($msg['optout'] === 0 || $msg['optout'] === '0' || strtoupper($msg['optout']) === "FALSE")) ? 0 : 1;

    //defaults: Keys that aren't actually required, but which will cause some portion of the code to complain
    //if they don't exist (even if they're blank).
    $defaults = array(
        'date' => time(), //defaulting to now. @fixme: if you can think of a better thing to do in the name of historical exchange rates.
        'first_name' => 'Chester',
        'middle_name' => '',
        'last_name' => 'McDefault',
        'street_address' => '',
        'supplemental_address_1' => '',
        'city' => '',
        'country' => '',
        'state_province' => '',
        'postal_code' => '',
        'original_gross' => $msg['gross'],
    );

    $msg = wmf_civicrm_normalize_msg( array_merge($defaults, $msg) );

    // set the correct amount fields/data and do exchange rate conversions.
    $msg = wmf_civicrm_normalize_contribution_amounts( $msg );

    return $msg;
}

/**
 * Insert the contact record
 * 
 * Serves as a standard way for message processors to handle contact
 * insertion.  By passing a contact id, a contact can be updated.
 * 
 * @param array $msg
 * @param int $contact_id
 * @return array
 */
function wmf_civicrm_message_contact_insert( $msg, $contact_id=NULL ) {
    // Set defaults for optional fields in the message
    if ( !array_key_exists( 'contact_type', $msg ) ) {
        $msg['contact_type'] = "Individual";
    } elseif ( $msg['contact_type'] != "Individual" && $msg['contact_type'] != "Organization" ) {
        // looks like an unsupported type was sent, revert to default
        watchdog( 'wmf_civicrm', 'Non-supported contact_type received: %msg', array( '%msg' => print_r( $msg, true )), WATCHDOG_INFO );
        $msg['contact_type'] = "Individual";
    }

    if ( !array_key_exists( 'contact_source', $msg ) ) {
        $msg['contact_source'] = "online donation";
    }

    // Honor the opt-out checkbox, if present, else, set default
    if ( !array_key_exists( 'optout', $msg ) ) {
        $msg['optout'] = 0;
    }
  
    // Create the contact record
    $contact = array(
        'id' => $contact_id,
        'contact_type' => $msg['contact_type'],
        'first_name' => $msg['first_name'],
        'middle_name' => $msg['middle_name'],
        'last_name' => $msg['last_name'],
        'sort_name' => trim( $msg['last_name'] . ', ' . $msg['first_name'], ' ,' ),
        'display_name' => trim( $msg['first_name'] . ' ' . $msg['last_name'] ),
        'do_not_trade' => $msg['anonymous'],
        'is_opt_out' => '0', // $msg['optout'], // we don't offer an option to unsub on contrib, eliminate bugs
        'contact_source' => $msg['contact_source'],
        'preferred_language' => strtolower(substr($msg['language'], 0, 2)) . '_' . strtoupper(substr($msg['country'], 0, 2)),

        // API required fields
        'version' => '3'
    );
    if ( strtolower( $msg['contact_type'] ) == "organization" ){
        unset( $contact['first_name'] );
        unset( $contact['middle_name'] );
        unset( $contact['last_name'] );

        $contact['sort_name'] = $msg['organization_name'];
        $contact['display_name'] = $msg['organization_name'];
    }

    // Attempt to insert the contact
    $contact_result = civicrm_api( "Contact", "Create", $contact );

    if ( $contact_id == NULL ){
        watchdog( 'wmf_civicrm', 'Result for adding contact: %contact', array( '%contact' => print_r( $contact_result, true )), WATCHDOG_DEBUG );
    } else {
        watchdog( 'wmf_civicrm', 'Result for updating contact: %contact', array( '%contact' => print_r( $contact_result, true )), WATCHDOG_DEBUG );
    }

    if ( array_key_exists( 'is_error', $contact_result ) && $contact_result['is_error'] != 0 ){
        throw new WmfException("IMPORT_CONTACT", "Contact could not be added. Aborting import.", $msg);
    }
    return $contact_result;
}

/**
 * Update the contact record
 * 
 * Serves as a standard way for message processors to handle contact
 * updates.
 * 
 * @param array $msg
 * @param int $contact_id
 * @return array
 */
function wmf_civicrm_message_contact_update( $msg, $contact_id )
{
    //FIXME: reverse the way these functions delegate.  Or eliminate -_insert.
    return wmf_civicrm_message_contact_insert( $msg, $contact_id );
}

/**
 * Insert the location record
 * 
 * Serves as a standard way for message processors to handle location
 * insertion.
 * 
 * @param array $msg
 * @param array $contact
 */
function wmf_civicrm_message_location_insert( $msg, $contact ) {
    wmf_civicrm_message_location_update( $msg, $contact );
}

/**
 * Update the location record
 * 
 * Serves as a standard way for message processors to handle location
 * updates.
 * 
 * @param array $msg
 * @param array $contact
 */
function wmf_civicrm_message_location_update( $msg, $contact ) {
    wmf_civicrm_message_email_update( $msg, $contact[ 'id' ] );
    wmf_civicrm_message_address_update( $msg, $contact[ 'id' ] );
}

function wmf_civicrm_message_email_update( $msg, $contact_id ) {
    // unset the email address if the default is used
    // this enables us to properly dedupe contacts later on
    if( $msg[ 'email' ] == 'nobody@wikimedia.org' ){
        return;
    }

    $loc_type_id = wmf_civicrm_get_default_location_type_id();

    $email_params = array(
        'contact_id' => $contact_id,
        'email' => $msg[ 'email' ],
        'is_primary' => 1,
        'is_billing' => 1,
        'location_type_id' => $loc_type_id,
        'version' => 3,
    );

    $result = civicrm_api( "Email", "Create", $email_params );
    if ( array_key_exists( 'is_error', $result ) && $result['is_error'] != 0 ) {
        throw new WmfException( 'IMPORT_CONTACT', "Couldn't store email for the contact.", $result );
    }
}

function wmf_civicrm_message_address_update( $msg, $contact_id ) {
    $loc_type_id = wmf_civicrm_get_default_location_type_id();

    // We can do these lookups a bit more efficiently than Civi
    $country_id = wmf_civicrm_get_country_id( $msg[ 'country' ] );
    $state_province_id = wmf_civicrm_get_state_id( $country_id, $msg['state_province'] );

    $address_params = array(
        'contact_id' => $contact_id,
        'location_type_id' => $loc_type_id,
        'is_primary' => 1,
        'street_address' => $msg['street_address'],
        'supplemental_address_1' => $msg['supplemental_address_1'],
        'city' => $msg['city'],
        'state_province_id' => $state_province_id,
        'state_province' => $msg['state_province'],
        'postal_code' => $msg['postal_code'],
        'country_id' => $country_id,
        'country' => $msg[ 'country' ],
        'is_billing' => 1,
        'version' => 3,
    );

    // FIXME: api does not offer control over fixAddress flag
    //$result = civicrm_api( "Address", "Create", $address_params );
    //if ( array_key_exists( 'is_error', $result ) && $result['is_error'] != 0 ) {

    require_once 'CRM/Core/BAO/Address.php';
    $result = CRM_Core_BAO_Address::add( $address_params, false );
    if ( !$result ) {
        throw new WmfException( 'IMPORT_CONTACT', "Couldn't store address for the contact.", $result );
    }
}

function wmf_civicrm_get_default_location_type_id() {
    require_once 'CRM/Core/BAO/LocationType.php';
    $default_location_type = CRM_Core_BAO_LocationType::getDefault();
    return $default_location_type->id;
}

function wmf_civicrm_get_country_id( $code ) {
    // Outside chance this could be a lang_COUNTRY pair
    $locality = explode( '_', $code );
    if ( count( $locality ) > 1 ) {
        $code = $locality[ 1 ];
    }

    // Assume this is an iso code
    if ( strlen( $code ) == 2 ) {
        $iso_cache = CRM_Core_PseudoConstant::countryIsoCode();
        $id = array_search( strtoupper( $code ), $iso_cache );
        if ( $id !== FALSE ) {
            return $id;
        }
    }
    watchdog( 'wmf_civicrm',
        "Cannot find country: [%code]",
        array( '%code' => $code ),
        WATCHDOG_NOTICE
    );
}

/**
 * Find correct state for insertion
 * 
 * When passing CiviCRM a state abbreviation, odd things can happen - like getting the right abbreviation, but the wrong state
 * So we'll pull back the correct state/province name based off of a user's country/state abbreviation
 */
function wmf_civicrm_get_state( $country, $state )
{
    if ( strlen( $country ) == 2 ) {
        $query = "SELECT s.name AS state_name FROM civicrm_country c, civicrm_state_province s WHERE s.country_id=c.id AND c.iso_code='" . addslashes( $country ) . "' AND s.abbreviation='" . addslashes( $state ) . "'";
    } else {
        $query = "SELECT s.name AS state_name FROM civicrm_country c, civicrm_state_province s WHERE s.country_id=c.id AND c.name='" . addslashes( $country ) . "' AND s.abbreviation='" . addslashes( $state ) . "'";
    }
    $dbs = wmf_civicrm_get_dbs();
    $dbs->push( 'civicrm' );
    $result = db_query( $query );
    if ( $result->num_rows === 1 ){
      $row = db_fetch_object( $result );
      $state = $row->state_name;
    }

    return $state;
}

function wmf_civicrm_get_state_id( $country_id, $state )
{
    $query = <<<EOS
SELECT id
FROM civicrm_state_province s
WHERE
    s.country_id = %d
    AND ( s.abbreviation = '%s' OR s.name = '%s' )
EOS;
    $dbs = wmf_civicrm_get_dbs();
    $dbs->push( 'civicrm' );
    $result = db_query( $query, array( $country_id, $state, $state ) );
    if ( $result->num_rows === 1 ){
        $row = db_fetch_object( $result );
        return $row->id;
    }
    watchdog( 'wmf_civicrm',
        "Cannot find state: [%state] (country %country)",
        array( '%state' => $state, '%country' => $country_id ),
        WATCHDOG_NOTICE
    );
}



/**
 * Normalize the queued message
 * 
 * Decodes the message and updates some of the message fields in ways 
 * that are consistent with how we need to insert data into CiviCRM.
 * This should be useful by other modules processing contribution messages 
 * out of the queue.
 * 
 * @param mixed $msg
 * @return array
 */
function wmf_civicrm_normalize_msg( $msg ) {
    // Decode the message body.
    if ( !is_array( $msg ) ) {
        $msg = json_decode( $msg->body, true );
    }
    
    //handle the payment instrument without altering the original message
    //(just in case any downstream logic needs to switch on the raw data)
    $msg['payment_instrument'] = wmf_civicrm_get_message_payment_instrument( $msg );

    // if we're missing a contrib id, insert new record to the table
    // this can happen if a user somehow makes a trxn from outside the normal workflow
    // checks are ignored as they were completely offline
    if ( !isset( $msg[ 'contribution_tracking_id' ] ) ) {
        if ( array_key_exists( 'payment_method', $msg ) && strtoupper( $msg['payment_method'] ) != "CHECK" ) {

            watchdog( 'wmf_civicrm', 'Contribution missing contribution_tracking_id', array(), WATCHDOG_DEBUG );
            //@fixme: For the regular transactions, this has been moved to the staging function. This needs to happen in recurring also, and then it can be removed here.
            $anonymous = ( array_key_exists( 'anonymous', $msg) && $msg['anonymous'] == true && strtoupper( $msg['anonymous'] ) != "FALSE" ) ? 1 : 0;
            $optout = ( array_key_exists( 'optout', $msg ) && $msg['optout'] == true && strtoupper( $msg['optout'] ) != "FALSE" ) ? 1 : 0;

            $contribution_tracking_id = wmf_civicrm_insert_contribution_tracking( '..' . $msg['payment_method'], 'civicrm', date('YmdHis', (int) $msg[ 'date' ] ), null, $optout, $anonymous ); //ACK! this should not be handled this way! should be dynamic!
            watchdog( 'wmf_civicrm', 'Newly inserted contribution tracking id: @id', array( '@id' => $contribution_tracking_id ), WATCHDOG_DEBUG );
            $msg['contribution_tracking_id'] = $contribution_tracking_id;
        }
    }

    // Convert times to Unix timestamps.
    if ( !is_numeric( $msg['date'] ) ) {
        $msg['date'] = strtotime($msg['date']);
    }
    // if all else fails, fall back to now.
    if ( empty( $msg['date'] ) ) {
        $msg['date'] = time();
    }

    watchdog( 'wmf_civicrm', 'Contribution (pre-conversion):<pre>' . check_plain(print_r($msg, TRUE)) . '</pre>' );

    return $msg;
}

/**
 * Insert the tag record
 * 
 * Serves as a standard way for message processors to handle tag
 * insertion.
 * 
 * @param array $contact
 * @return array
 */
function wmf_civicrm_tag_contact_for_review( $contact )
{
    require_once 'api/v2/EntityTag.php';

    $review_tag_id = wmf_civicrm_get_civi_id('tag_id', 'Review');

    $tag = array(
        'tag_id' => $review_tag_id,
        'contact_id' => $contact[ 'id' ]
    );
    $tag_result = civicrm_entity_tag_add( $tag );
    return $tag_result;
}

/**
 * Pulls all records in the wmf_contribution_extras table that match the gateway
 * and gateway transaction id.
 * @param string $gateway
 * @param string $gateway_txn_id
 * @return mixed array of result rows, or false if none present.
 * @throws WmfException
 */
function wmf_civicrm_get_contributions_from_gateway_id( $gateway, $gateway_txn_id ){
	$gateway = strtolower( $gateway );
	$query = "SELECT cx.*, cc.* FROM wmf_contribution_extra cx LEFT JOIN civicrm_contribution cc 
		ON cc.id = cx.entity_id 
		WHERE gateway LIKE '%s' AND gateway_txn_id LIKE '%s';";

	$row = false;
	$dbs = wmf_civicrm_get_dbs();
	$dbs->push( 'civicrm' );
	$result = db_query( $query, $gateway, $gateway_txn_id );
	$matching = array();
	while ( $row = db_fetch_array( $result ) ) {
		$matching[] = $row;
	}

	if ( count( $matching ) == 0 ) {
        return false;
    }
	return $matching;
}

function wmf_civicrm_get_child_contributions_from_gateway_id( $gateway, $gateway_txn_id ){
	$gateway = strtolower( $gateway );
	$query = "SELECT cx.*, cc.* FROM wmf_contribution_extra cxp 
		LEFT JOIN wmf_contribution_extra cx ON cxp.entity_id = cx.parent_contribution_id 
		LEFT JOIN civicrm_contribution cc ON cc.id = cx.entity_id 
		WHERE cxp.gateway LIKE '%s' AND cxp.gateway_txn_id LIKE '%s';";

	$row = false;
	$dbs = wmf_civicrm_get_dbs();
	$dbs->push( 'civicrm' );
	$result = db_query( $query, $gateway, $gateway_txn_id );
	$matching = array();
	while ( $row = db_fetch_array( $result ) ) {
		$matching[] = $row;
	}

	if ( count( $matching ) == 0 ) {
        return false;
    }
	return $matching;
}


function wmf_civicrm_boost_performance() {
    civicrm_initialize();
    require_once 'CRM/Core/Config.php';
    $config = CRM_Core_Config::singleton();
    $config->doNotResetCache = 1;
}

function wmf_civicrm_set_thankyou_date_to_epoch( $contribution_id ){
	$dbs = wmf_civicrm_get_dbs();
	$dbs->push( 'civicrm' );
	$query = "UPDATE civicrm_contribution SET thankyou_date = \"1970-01-01 00:00:00\" WHERE id=%d";

	$result = db_query( $query, $contribution_id );
	if ( !$result ) {
		watchdog('thank_you', 'Updating TY date to epoch failed ', array(), WATCHDOG_ERROR);
		return false;
	} else {
		watchdog('thank_you', 'TY date set to epoch sucessfully', array(), WATCHDOG_INFO);
		return true;
	}
}

/**
 * Sets the civi records to reflect a contribution refund.
 *
 * The original contribution is set to status "Refunded", and a negative and
 * equal refund contribution is created.  This contribution will be linked
 * to the original through the parent_contribution_id field, and will have
 * status "Pending" unless the $refund_completed argument is true.
 *
 * $refund_type should be 'refund' or 'chargeback', for now we simply dump
 * this string into the "source" field of the negative contribution.
 *
 * If $original_amount and $original_currency are provided, they will be
 * checked against the original contribution and an exception thrown on a
 * mismatch.  If the original amount has been zeroed we reconstruct the
 * contribution using the currency and amount from function parameters.
 *
 * returns the refund contribution id.
 */
function wmf_civicrm_mark_refund(
    $contribution_id,
    $refund_type = 'refund',
    $refund_completed = false,
    $refund_date = null,
    $refund_gateway_txn_id = null,
    $original_currency = null,
    $original_amount = null
) {
    $api = civicrm_api_classapi();

    $success = $api->Contribution->Get(array('id' => $contribution_id));
    if ( !$success || !$api->values ) {
        throw new Exception("No such contribution: $contribution_id, " . $api->errorMsg());
    }
    $result = $api->values;
    $contribution = array_pop($result);

    $dbs = wmf_civicrm_get_dbs();
    $dbs->push( 'civicrm' );

    // Look for existing refunds
    $query = <<<"EOS"
SELECT COUNT(*) FROM wmf_contribution_extra
WHERE
    parent_contribution_id = %d
    OR (entity_id = %d AND COALESCE(parent_contribution_id, 0))
EOS;
    if ( db_result(db_query($query, array($contribution_id, $contribution_id))) ) {
        throw new Exception("Contribution is already linked to a refund, or is itself a refund: $contribution_id");
    }

    // Should we restore?
    if ( (floatval( $contribution->total_amount ) == 0
            or $contribution->contribution_source === "RFD")
        and $original_currency and $original_amount > 0
    ) {
        $dbs->pop();

        //FIXME: call this from the contribution save hook. $round parameter. 
        $contribution->total_amount = round( exchange_rate_convert(
            $original_currency, $original_amount,
            strtotime( $contribution->receive_date )
        ), 2 );

        $dbs->push( 'civicrm' );

        $sql = <<<EOS
UPDATE civicrm_contribution
SET
    source = "%s",
    total_amount = %s
WHERE id = %d
EOS;
        db_query( $sql, array( "$original_currency $original_amount", (string) $contribution->total_amount, $contribution_id ) );
    } else {
        list($actual_currency, $actual_amount) = explode(" ", $contribution->contribution_source);
        if ( ($original_currency && round($original_currency, 2) != round($actual_currency, 2))
            || ($original_amount && round($original_amount, 2) != round($actual_amount, 2)) )
        {
            throw new Exception("Payment amount specified did not match original contribution: $contribution_id");
        }

        $original_currency = $actual_currency;
        $original_amount = $actual_amount;
    }

    $transaction = WmfTransaction::from_unique_id( $contribution->trxn_id );
    if ( $refund_gateway_txn_id ) {
        $transaction->gateway_txn_id = $refund_gateway_txn_id;
    }
    $transaction->is_refund = true;
    $refund_unique_id = $transaction->get_unique_id();

    if ( $refund_date === null ) {
        $refund_date = time();
    }
    $refund_status = ( $refund_completed ? 'Completed' : 'Pending' );
    $refund_params = array(
        'contact_id' => $contribution->contact_id,
        'total_amount' => 0 - $contribution->total_amount,
        'contribution_type_id' => wmf_civicrm_get_civi_id( 'contribution_type_id', $refund_type ),
        'receive_date' => gmdate( 'Y-m-d H:i:s', $refund_date ),
        'contribution_status_id' => civicrm_api_contribution_status( $refund_status ),
        'contribution_source' => "$original_currency -{$original_amount}",
        'thankyou_date' => '1970-01-01 00:00:00',
        'trxn_id' => $refund_unique_id,

        // API required fields
        'version' => '3'
    );
    if ( !$api->Contribution->Create($refund_params) ) {
        throw new Exception("Failed to create refund contribution for: $contribution_id, " . $api->errorMsg());
    }
    $result = $api->values;
    $refund = array_pop($result);

    $account_field_name = wmf_civicrm_get_custom_field_name( 'gateway_account' );

    $custom_values = array(
        'gateway_account' => $contribution->$account_field_name,
        'parent_contribution_id' => $contribution->id,
        'finance_only' => 1,
    );
    wmf_civicrm_set_custom_field_values($refund->id, $custom_values);

    $custom_values = array(
        'finance_only' => 1,
    );
    wmf_civicrm_set_custom_field_values($contribution->id, $custom_values);

    // FIXME: Contribution api cannot do a simple update
    $query = <<<"EOS"
UPDATE civicrm_contribution
SET contribution_status_id = %d
WHERE id = %d
EOS;
    if ( !db_query( $query, array( civicrm_api_contribution_status( 'Refunded' ), $contribution->id ) ) ) {
        throw new Exception("Cannot mark original contribution as refunded: $contribution_id, " . db_error());
    }

    return $refund->id;
}

/**
 * Update civi records to track gateway status change events.
 *
 * If more recent information is in the database, ignore the event
 * unless it is a Refund.
 *
 * For refund events, mark the refund using our helper function.
 *
 * Raw gateway status is stored in a custom field.
 */
function wmf_civicrm_set_gateway_status( int $contribution_id, string $raw_status, string $normalized_status = null, int $timestamp = null )
{
    civicrm_initialize();

    if ( $normalized_status !== null ) {
        require_once 'CRM/Contribute/BAO/Contribution.php';
        $contribution = new CRM_Contribute_BAO_Contribution();
        $contribution->id = $contribution_id;
        if ( !$contribution->find( true ) ) {
            throw new Exception( "Contribution not found: $contribution_id" );
        }

        $status_id = civicrm_api_contribution_status( $normalized_status );
        if ( $status_id === null ) {
            watchdog('wmf_civicrm', "Normalized status does not exist: {$normalized_status}", array(), WATCHDOG_ERROR);
        }
    }

    // this is sort of audit-specific logic
    if ( $normalized_status === 'Refunded' ) {
        // We restore the old status id in case this refund action was less recent
        // than current info in the db.  If the data conditional below succeeds, we
        // set the status to 'refunded' again.
        $old_status_id = $contribution->contribution_status_id;
        try {
            wmf_civicrm_mark_refund( $contribution_id, 'chargeback', true );
        } catch (Exception $e) {
            watchdog('wmf_civicrm', "Cannot create a refund for: {$contribution_id}", array(), WATCHDOG_ERROR);
        }
        $contribution->find( true );
        $contribution->contribution_status_id = $old_status_id;
        $contribution->save();
    }

    if ( $timestamp === null ) {
        $gateway_date = gmdate( 'YmdHis' );
    } else {
        $gateway_date = gmdate( 'YmdHis', $timestamp );
    }

    $original_custom_values = wmf_civicrm_contribution_get_custom_values( $contribution_id, array(
        'gateway_date',
    ) );
    $last_timestamp = strtotime( $original_custom_values['gateway_date'] );
    $last_gateway_date = date( 'YmdHis', $last_timestamp );

    if ( $last_gateway_date >= $gateway_date ) {
        watchdog('wmf_civicrm', "Not updating contribution, because a more recent gateway status change has been recorded: {$contribution_id}", array(), WATCHDOG_INFO);
        return;
    }

    $custom_values['gateway_date'] = $gateway_date;
    $custom_values['gateway_status_raw'] = $raw_status;
    wmf_civicrm_set_custom_field_values($contribution_id, $custom_values);

    if ( $normalized_status !== null ) {
        $contribution->contribution_status_id = $status_id;
    }
    $contribution->save();
}

/**
 * Dedupe helper.
 */
function wmf_civicrm_merge_contacts( $main_contact_id, $other_contact_id ) {
    $api = civicrm_api_classapi();

    require_once "CRM/Dedupe/Merger.php";

    $cidRefs = CRM_Dedupe_Merger::cidRefs();
    $eidRefs = CRM_Dedupe_Merger::eidRefs();
    $moveTables = array_merge( array_keys( $cidRefs ), array_keys( $eidRefs ) );

    CRM_Dedupe_Merger::moveContactBelongings( $main_contact_id, $other_contact_id, $moveTables );

    $api->Contact->delete( array(
        'contact_id' => $other_contact_id,
        'version' => 3
    ) );
}

/**
 * Implementation of hook_civicrm_merge, adds our custom tables.
 */
function wmf_civicrm_civicrm_merge( $type, &$refs ) {
    switch ( $type ) {
    case 'cidRefs':
        require_once 'CRM/Contact/BAO/ContactType.php';
        $contact_types = array( "Contact" );
        $contact_types = array_merge( CRM_Contact_BAO_ContactType::basicTypes(), $contact_types );
        foreach ( $contact_types as &$type ) {
            $type = "'" . $type . "'";
        }
        $contact_types = implode( ", ", $contact_types );

        $sql = <<<EOS
SELECT table_name
FROM civicrm_custom_group
WHERE extends IN ( $contact_types )
EOS;
        $dao = CRM_Core_DAO::executeQuery( $sql );
        while ( $dao->fetch() ) {
            $refs[ $dao->table_name ][] = 'entity_id';
        }
        break;
    }
}

/**
 * Implementation of hook_civicrm_post, used to update contribution_extra fields
 */
function wmf_civicrm_civicrm_post( $op, $type, $id, &$contribution ) {
    switch ( $op ) {
    case 'create':
    case 'edit':
        if ( $type === 'Contribution' ) {
            $extra = array();

            if ( $contribution->trxn_id ) {
                try {
                    $transaction = WmfTransaction::from_unique_id( $contribution->trxn_id );
                    $extra['gateway'] = strtolower( $transaction->gateway );
                    $extra['gateway_txn_id'] = $transaction->gateway_txn_id;
                } catch ( Exception $ex ) {
                    watchdog( 'wmf_civicrm', "Failed to parse trxn_id: {$contribution->trxn_id}, " . $ex->getMessage() );
                }
            }

            if ( $contribution->source ) {
                list( $original_currency, $original_amount ) = explode( " ", $contribution->source );
                $extra['original_currency'] = $original_currency;
                $extra['original_amount'] = $original_amount;
            }

            if ( $extra ) {
                wmf_civicrm_set_custom_field_values( $id, $extra );
            }
        }
        break;
    }
}
