<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from monolog/xml/schema/CRM/Monolog/Monolog.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:49df8c258c5d9a5996849189da52f11e)
 */
use CRM_Monolog_ExtensionUtil as E;

/**
 * Database access object for the Monolog entity.
 */
class CRM_Monolog_DAO_Monolog extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_monolog';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = FALSE;

  /**
   * Unique Monolog ID
   *
   * @var int
   */
  public $id;

  /**
   * @var string
   */
  public $name;

  /**
   * @var string
   */
  public $channel;

  /**
   * @var string
   */
  public $description;

  /**
   * @var string
   */
  public $type;

  /**
   * @var string
   */
  public $minimum_severity;

  /**
   * @var int
   */
  public $weight;

  /**
   * @var bool
   */
  public $is_active;

  /**
   * @var bool
   */
  public $is_final;

  /**
   * @var bool
   */
  public $is_default;

  /**
   * @var text
   */
  public $configuration_options;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_monolog';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Monologs') : E::ts('Monolog');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('Unique Monolog ID'),
          'required' => TRUE,
          'where' => 'civicrm_monolog.id',
          'table_name' => 'civicrm_monolog',
          'entity' => 'Monolog',
          'bao' => 'CRM_Monolog_DAO_Monolog',
          'localizable' => 0,
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'name' => [
          'name' => 'name',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Unique name'),
          'maxlength' => 16,
          'size' => 16,
          'where' => 'civicrm_monolog.name',
          'table_name' => 'civicrm_monolog',
          'entity' => 'Monolog',
          'bao' => 'CRM_Monolog_DAO_Monolog',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'channel' => [
          'name' => 'channel',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Log service channel'),
          'maxlength' => 16,
          'size' => 16,
          'where' => 'civicrm_monolog.channel',
          'table_name' => 'civicrm_monolog',
          'entity' => 'Monolog',
          'bao' => 'CRM_Monolog_DAO_Monolog',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'description' => [
          'name' => 'description',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Description'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_monolog.description',
          'table_name' => 'civicrm_monolog',
          'entity' => 'Monolog',
          'bao' => 'CRM_Monolog_DAO_Monolog',
          'localizable' => 0,
          'html' => [
            'type' => 'TextArea',
          ],
          'add' => NULL,
        ],
        'type' => [
          'name' => 'type',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Type of log service'),
          'maxlength' => 16,
          'size' => CRM_Utils_Type::TWELVE,
          'where' => 'civicrm_monolog.type',
          'table_name' => 'civicrm_monolog',
          'entity' => 'Monolog',
          'bao' => 'CRM_Monolog_DAO_Monolog',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
          ],
          'pseudoconstant' => [
            'callback' => 'CRM_Monolog_BAO_Monolog::getTypes',
          ],
          'add' => '1.0',
        ],
        'minimum_severity' => [
          'name' => 'minimum_severity',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Minimum Severity'),
          'maxlength' => 16,
          'size' => CRM_Utils_Type::TWELVE,
          'where' => 'civicrm_monolog.minimum_severity',
          'table_name' => 'civicrm_monolog',
          'entity' => 'Monolog',
          'bao' => 'CRM_Monolog_DAO_Monolog',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
          ],
          'pseudoconstant' => [
            'callback' => 'CRM_Monolog_BAO_Monolog::getSeverities',
          ],
          'add' => NULL,
        ],
        'weight' => [
          'name' => 'weight',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Weight'),
          'where' => 'civicrm_monolog.weight',
          'table_name' => 'civicrm_monolog',
          'entity' => 'Monolog',
          'bao' => 'CRM_Monolog_DAO_Monolog',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'is_active' => [
          'name' => 'is_active',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Is the handler active'),
          'where' => 'civicrm_monolog.is_active',
          'table_name' => 'civicrm_monolog',
          'entity' => 'Monolog',
          'bao' => 'CRM_Monolog_DAO_Monolog',
          'localizable' => 0,
          'html' => [
            'type' => 'CheckBox',
          ],
          'add' => NULL,
        ],
        'is_final' => [
          'name' => 'is_final',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Is this the final handler to apply'),
          'where' => 'civicrm_monolog.is_final',
          'table_name' => 'civicrm_monolog',
          'entity' => 'Monolog',
          'bao' => 'CRM_Monolog_DAO_Monolog',
          'localizable' => 0,
          'html' => [
            'type' => 'CheckBox',
          ],
          'add' => NULL,
        ],
        'is_default' => [
          'name' => 'is_default',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Is default log service'),
          'where' => 'civicrm_monolog.is_default',
          'table_name' => 'civicrm_monolog',
          'entity' => 'Monolog',
          'bao' => 'CRM_Monolog_DAO_Monolog',
          'localizable' => 0,
          'html' => [
            'type' => 'CheckBox',
          ],
          'add' => NULL,
        ],
        'configuration_options' => [
          'name' => 'configuration_options',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Configuration options'),
          'where' => 'civicrm_monolog.configuration_options',
          'table_name' => 'civicrm_monolog',
          'entity' => 'Monolog',
          'bao' => 'CRM_Monolog_DAO_Monolog',
          'localizable' => 0,
          'serialize' => self::SERIALIZE_JSON,
          'html' => [
            'type' => 'TextArea',
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'monolog', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'monolog', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'UI_name' => [
        'name' => 'UI_name',
        'field' => [
          0 => 'name',
        ],
        'localizable' => FALSE,
        'unique' => TRUE,
        'sig' => 'civicrm_monolog::1::name',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
