<?php


/**
 * Implements hook_menu
 */
function banner_history_menu() {
	$items[ 'admin/config/queue2civicrm/banner_history' ] = array(
		'title' => 'Banner history',
		'description' => t( 'Configure banner history queue' ),
		'access arguments' => array( 'administer queue2civicrm' ),
		'page callback' => 'drupal_get_form',
		'page arguments' => array( 'banner_history_settings_page_args' ),
	);
	return $items;
}

/**
 * Constructs the settings page for this module.
 * @return array Of form components.
 */
function banner_history_settings_page_args() {
	$form = array();

	$form['description'] = array(
		'#type'	=> 'markup',
		'#description' =>
			t( '<p>Banner history log ID associations are consumed from a' .
			' queue and placed in a table.</p>' ),
	);

	$form['banner_history_queue'] = array(
		'#type'	=> 'textfield',
		'#title' => t( 'Subscription path' ),
		'#required' => true,
		'#default_value' => variable_get(
			'banner_history_queue', '/queue/banner-history-test' ),
		'#description'	 => t( 'Queue for banner history log ID associations' ),
	);

	$form['banner_history_batch'] = array(
		'#type' => 'textfield',
		'#title' => t( 'Batch size' ),
		'#description'	 => t(
			'Maximum number of items processed by a banner history job. Use ' .
			'0 for no limit.'
		),
		'#default_value' => variable_get( 'banner_history_batch', 0 ),
	);

	$form['banner_history_batch_time'] = array(
		'#type' => 'textfield',
		'#title' => t( 'Job time limit (in seconds)' ),
		'#description' => t(
			'Maximum elapsed duration of an banner history job, after which ' .
			'we will abort from the loop. This can be used to set a reliable ' .
			'duty cycle for the job. Use 0 for no limit. Either a time limit ' .
			'or batch size limit is required.'
		),
		'#required' => true,
		'#default_value' => variable_get( 'banner_history_batch_time', 0 ),
	);

	return system_settings_form( $form );
}

/**
 * Entry point from banner-history-queue-consume drush command
 */
function banner_history_queue_consume() {
	watchdog( 'banner_history', 'Executing: banner_history_queue_consume' );

	civicrm_initialize();

	$processed = queue2civicrm_stomp()->dequeue_loop(
		variable_get( 'banner_history_queue', '/queue/banner-history-test' ) ,
		variable_get( 'banner_history_batch', 0 ),
		variable_get( 'banner_history_batch_time', 0 ),
		'banner_history_process_message'
	);

	if ( $processed > 0 ) {
		watchdog( 'banner_history',
			"Processed $processed banner_history log ID association(s)." );

	} else {
		watchdog( 'banner_history',
			'No banner history log ID associations processed.' );
	}
}

function banner_history_process_message( $msg ) {

	$body = json_decode( $msg->body, true );

	if ( is_null( $body ) ) {
		throw new WmfException( 'BANNER_HISTORY',
			'Couldn\'t parse banner history message body.' );
	}

	$bannerHistoryId = $body['banner_history_id'];
	$contributionTrackingId = $body['contribution_tracking_id'];

	if ( !$bannerHistoryId || !$contributionTrackingId ) {
		throw new WmfException( 'BANNER_HISTORY',
			'Missing banner history or contribution tracking ID.' );
	}

	if (
		!is_numeric( $contributionTrackingId ) ||
		!preg_match( '/^[0-9a-f]{16,20}$/', $bannerHistoryId )
	) {
		throw new WmfException( 'BANNER_HISTORY',
			'Invalid data in banner history message.' );
	}

	watchdog( 'banner_history', "About to add row for $bannerHistoryId",
		array(), WATCHDOG_INFO);

	db_merge( 'banner_history_contribution_associations' )
		->key( array(
			'banner_history_log_id' => $bannerHistoryId,
			'contribution_tracking_id' => $contributionTrackingId
		) )
		->insertFields( array(
			'banner_history_log_id' => $bannerHistoryId,
			'contribution_tracking_id' => $contributionTrackingId
		) )
		->execute();

	watchdog( 'banner_history', "Processed $bannerHistoryId" );
}
