<?php
use CRM_WmfThankyou_ExtensionUtil as E;

return [
  'wmf_thank_you_from_name' => [
    'group_name' => 'WMF Thank You Settings',
    'group' => 'wmf-thankyou',
    'name' => 'wmf_thank_you_from_name',
    'default' => 'Maryana Iskander',
    'type' => 'String',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts('Annual Fund thank you from name'),
    'help_text' => '',
    'html_type' => 'text',
    'html_attributes' => [
      'size' => 80,
    ],
    'settings_pages' => ['wmf-thankyou' => ['weight' => 1]],
  ],
  'wmf_thank_you_from_address' => [
    'group_name' => 'WMF Thank You Settings',
    'group' => 'wmf-thankyou',
    'name' => 'wmf_thank_you_from_address',
    'default' => 'Maryana@wikipedia.org',
    'type' => 'String',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts('Annual Fund thank you from address'),
    'help_text' => '',
    'html_type' => 'text',
    'html_attributes' => [
      'size' => 80,
    ],
    'settings_pages' => ['wmf-thankyou' => ['weight' => 2]],
  ],
  'wmf_endowment_thank_you_from_name' => [
    'group_name' => 'WMF Thank You Settings',
    'group' => 'wmf-thankyou',
    'name' => 'wmf_endowment_thank_you_from_name',
    'default' => 'Lisa Seitz Gruwell',
    'type' => 'String',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts('Endowment thank you from name'),
    'help_text' => '',
    'html_type' => 'text',
    'html_attributes' => [
      'size' => 80,
    ],
    'settings_pages' => ['wmf-thankyou' => ['weight' => 11]],
  ],
  'wmf_endowment_thank_you_from_address' => [
    'group_name' => 'WMF Thank You Settings',
    'group' => 'wmf-thankyou',
    'name' => 'wmf_endowment_thank_you_from_address',
    'default' => 'endowment@wikimedia.org',
    'type' => 'String',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts('Endowment thank you from address'),
    'help_text' => '',
    'html_type' => 'text',
    'html_attributes' => [
      'size' => 80,
    ],
    'settings_pages' => ['wmf-thankyou' => ['weight' => 12]],
  ],
  'wmf_monthly_convert_thank_you_from_name' => [
    'group_name' => 'WMF Thank You Settings',
    'group' => 'wmf-thankyou',
    'name' => 'wmf_monthly_convert_thank_you_from_name',
    'default' => 'Wikimedia Foundation',
    'type' => 'String',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts('Monthly convert thank you from name'),
    'help_text' => '',
    'html_type' => 'text',
    'html_attributes' => [
      'size' => 80,
    ],
    'settings_pages' => ['wmf-thankyou' => ['weight' => 21]],
  ],
  'wmf_monthly_convert_thank_you_from_address' => [
    'group_name' => 'WMF Thank You Settings',
    'group' => 'wmf-thankyou',
    'name' => 'wmf_monthly_convert_thank_you_from_address',
    'default' => 'donate@wikimedia.org',
    'type' => 'String',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts('Monthly convert thank you from address'),
    'help_text' => '',
    'html_type' => 'text',
    'html_attributes' => [
      'size' => 80,
    ],
    'settings_pages' => ['wmf-thankyou' => ['weight' => 22]],
  ],
  'wmf_eoy_thank_you_from_name' => [
    'group_name' => 'WMF Thank You Settings',
    'group' => 'wmf-thankyou',
    'name' => 'wmf_eoy_thank_you_from_name',
    'default' => 'Wikimedia Foundation',
    'type' => 'String',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts('End of year thank you from name'),
    'help_text' => '',
    'html_type' => 'text',
    'html_attributes' => [
      'size' => 80,
    ],
    'settings_pages' => ['wmf-thankyou' => ['weight' => 31]],
  ],
  'wmf_eoy_thank_you_from_address' => [
    'group_name' => 'WMF Thank You Settings',
    'group' => 'wmf-thankyou',
    'name' => 'wmf_eoy_thank_you_from_address',
    'default' => 'donate@wikimedia.org',
    'type' => 'String',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts('End of year thank you from address'),
    'help_text' => '',
    'html_type' => 'text',
    'html_attributes' => [
      'size' => 80,
    ],
    'settings_pages' => ['wmf-thankyou' => ['weight' => 32]],
  ],

  'thank_you_days' => [
    'name' => 'thank_you_days',
    'title' => E::ts('Days before considering transaction too old to automatically thank'),
    'default' => 14,
    'type' => 'Integer',
    'html_type' => 'text',
    'html_attributes' => [
      'size' => 4,
      'maxlength' => 8,
     ],
    'is_domain' => 1,
    'is_contact' => 0,
    'settings_pages' => ['wmf-thankyou' => ['weight' => 40]],
  ],

  'thank_you_add_civimail_records' => [
    'name' => 'thank_you_add_civimail_records',
    'type' => 'Boolean',
    'quick_form_type' => 'YesNo',
    'title' => E::ts('Track thank you emails to CiviMail'),
    'default' => TRUE,
    'is_domain' => 1,
    'is_contact' => 0,
    'settings_pages' => ['wmf-thankyou' => ['weight' => 45]],
  ],
  'thank_you_civimail_rate' => [
    'name' => 'thank_you_civimail_rate',
    'default' => 1,
    'type' => 'Float',
    'html_type' => 'text',
    'html_attributes' => [
      'size' => 4,
      'maxlength' => 8,
    ],
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts('CiviMail sample rate, from 0 (never) to 1 (always)'),
    'help_text' => '',
    'settings_pages' => ['wmf-thankyou' => ['weight' => 50]],
  ],
  'thank_you_failure_threshold' => [
    'name' => 'thank_you_failure_threshold',
    'default' => 5,
    'type' => 'Integer',
    'html_type' => 'text',
    'html_attributes' => [
      'size' => 4,
      'maxlength' => 8,
    ],
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts('Number of consecutive failures to allow before disabling thank you job'),
    'help_text' => '',
    'settings_pages' => ['wmf-thankyou' => ['weight' => 55]],
  ],

  'thank_you_batch' => [
    'name' => 'thank_you_batch',
    'title' => E::ts('Cron batch size'),
    'default' => 1,
    'type' => 'Integer',
    'html_type' => 'text',
    'html_attributes' => [
      'size' => 4,
      'maxlength' => 8,
    ],
    'is_domain' => 1,
    'is_contact' => 0,
    'help_text' => '',
    'settings_pages' => ['wmf-thankyou' => ['weight' => 55]],
  ],

  'thank_you_batch_time' => [
    'name' => 'thank_you_batch_time',
    'title' => E::ts('Job time limit (in seconds)'),
    'description' => E::ts('Maximum elapsed duration of a thank you job, after which we will abort from the loop.  This can be used to set a reliable duty cycle for the job.  A time limit is required.'),
    'default' => 90,
    'type' => 'Integer',
    'html_type' => 'text',
    'html_attributes' => [
      'size' => 4,
      'maxlength' => 8,
    ],
    'is_domain' => 1,
    'is_contact' => 0,
     'help_text' => '',
    'settings_pages' => ['wmf-thankyou' => ['weight' => 60]],
  ],
];
