<?php
use CRM_Wmf_ExtensionUtil as E;

return [
  'wmf_thank_you_from_name' => [
    'group_name' => 'WMF Thank You Settings',
    'group' => 'wmf-thankyou',
    'name' => 'wmf_thank_you_from_name',
    'default' => 'Maryana Iskander',
    'type' => 'String',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts('Annual Fund thank you from name'),
    'help_text' => '',
    'html_type' => 'text',
    'html_attributes' => [
      'size' => 80,
    ],
    'settings_pages' => ['wmf-thankyou' => ['weight' => 1]],
  ],
  'wmf_thank_you_from_address' => [
    'group_name' => 'WMF Thank You Settings',
    'group' => 'wmf-thankyou',
    'name' => 'wmf_thank_you_from_address',
    'default' => 'Maryana@wikipedia.org',
    'type' => 'String',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts('Annual Fund thank you from address'),
    'help_text' => '',
    'html_type' => 'text',
    'html_attributes' => [
      'size' => 80,
    ],
    'settings_pages' => ['wmf-thankyou' => ['weight' => 2]],
  ],
  'wmf_endowment_thank_you_from_name' => [
    'group_name' => 'WMF Thank You Settings',
    'group' => 'wmf-thankyou',
    'name' => 'wmf_endowment_thank_you_from_name',
    'default' => 'Lisa Seitz Gruwell',
    'type' => 'String',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts('Endowment thank you from name'),
    'help_text' => '',
    'html_type' => 'text',
    'html_attributes' => [
      'size' => 80,
    ],
    'settings_pages' => ['wmf-thankyou' => ['weight' => 11]],
  ],
  'wmf_endowment_thank_you_from_address' => [
    'group_name' => 'WMF Thank You Settings',
    'group' => 'wmf-thankyou',
    'name' => 'wmf_endowment_thank_you_from_address',
    'default' => 'endowment@wikimedia.org',
    'type' => 'String',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts('Endowment thank you from address'),
    'help_text' => '',
    'html_type' => 'text',
    'html_attributes' => [
      'size' => 80,
    ],
    'settings_pages' => ['wmf-thankyou' => ['weight' => 12]],
  ],
  'wmf_monthly_convert_thank_you_from_name' => [
    'group_name' => 'WMF Thank You Settings',
    'group' => 'wmf-thankyou',
    'name' => 'wmf_monthly_convert_thank_you_from_name',
    'default' => 'Wikimedia Foundation',
    'type' => 'String',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts('Monthly convert thank you from name'),
    'help_text' => '',
    'html_type' => 'text',
    'html_attributes' => [
      'size' => 80,
    ],
    'settings_pages' => ['wmf-thankyou' => ['weight' => 21]],
  ],
  'wmf_monthly_convert_thank_you_from_address' => [
    'group_name' => 'WMF Thank You Settings',
    'group' => 'wmf-thankyou',
    'name' => 'wmf_monthly_convert_thank_you_from_address',
    'default' => 'donate@wikimedia.org',
    'type' => 'String',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts('Monthly convert thank you from address'),
    'help_text' => '',
    'html_type' => 'text',
    'html_attributes' => [
      'size' => 80,
    ],
    'settings_pages' => ['wmf-thankyou' => ['weight' => 22]],
  ],
  'wmf_eoy_thank_you_from_name' => [
    'group_name' => 'WMF Thank You Settings',
    'group' => 'wmf-thankyou',
    'name' => 'wmf_eoy_thank_you_from_name',
    'default' => 'Wikimedia Foundation',
    'type' => 'String',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts('End of year thank you from name'),
    'help_text' => '',
    'html_type' => 'text',
    'html_attributes' => [
      'size' => 80,
    ],
    'settings_pages' => ['wmf-thankyou' => ['weight' => 31]],
  ],
  'wmf_eoy_thank_you_from_address' => [
    'group_name' => 'WMF Thank You Settings',
    'group' => 'wmf-thankyou',
    'name' => 'wmf_eoy_thank_you_from_address',
    'default' => 'donate@wikimedia.org',
    'type' => 'String',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts('End of year thank you from address'),
    'help_text' => '',
    'html_type' => 'text',
    'html_attributes' => [
      'size' => 80,
    ],
    'settings_pages' => ['wmf-thankyou' => ['weight' => 32]],
  ],
];
